### PR TITLE
CHE-1264. Don't include CR char in log message when LF char follow

### PR DESCRIPTION
**Pull request by RomanNikitenko**
Fix errors related to inclusion of carriage return char in log message when line feed char follow
@vparfonov please review

Signed-off-by: Roman Nikitenko rnikitenko@codenvy.com

### CODE REVIEW

**Comment by skabashnyuk** [comment]
Test?

**Comment by RomanNikitenko** [comment]
@skabashnyuk  @benoitf  I've added tests, please review

**Comment by skabashnyuk** [comment]
ok

**Comment by vparfonov** [comment]
ok

**Pull request merged**
