### PR TITLE
Correct revert unsaved preference changes

### PR DESCRIPTION
**Pull request by vzhukovs**
### What does this PR do?
This changes proposal fixes the problem when save button might appeared when refresh button called from preferences window.

Signed-off-by: Vladyslav Zhukovskyi <vzhukovs@redhat.com>

### What issues does this PR fix or reference?
#9959 #10019 

#### Release Notes
N/A

#### Docs PR
N/A

### CODE REVIEW

**Comment by vzhukovskii** [comment]
ci-test

**Comment by vzhukovskii** [comment]
ci-build

**Comment by vzhukovskii** [comment]
ci-test

**Comment by vzhukovskii** [comment]
ci-test

**Comment by vzhukovskii** [comment]
ci-build

**Review by vparfonov — APPROVED** [review]

**Comment by vzhukovskii** [comment]
ci-test

**Comment by vzhukovskii** [comment]
ci-build

**Comment by vzhukovskii** [comment]
ci-build

**Comment by vzhukovskii** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test

**Review by vparfonov — APPROVED** [review]

**Comment by vzhukovskii** [comment]
ci-test

**Review by tolusha — APPROVED** [review]

**Review by musienko-maxim — APPROVED** [review]

**Pull request merged**
