### PR TITLE
CHE-4010: Remove deprecation related to texteditor

### PR DESCRIPTION
**Pull request by RomanNikitenko**
### What does this PR do?
Remove deprecation related to org.eclipse.che.ide.api.editor.texteditor:

   org.eclipse.che.ide.api.editor.texteditor.EditorHandle
   org.eclipse.che.ide.api.editor.texteditor.EditorInitCallback
   org.eclipse.che.ide.api.editor.texteditor.EditorModule
   org.eclipse.che.ide.api.editor.texteditor.TextEditorCursorModel
   org.eclipse.che.ide.api.editor.texteditor.TextEditorInit
   org.eclipse.che.ide.api.editor.texteditor.TextEditorPresenter
   org.eclipse.che.ide.api.editor.texteditor.TextEditorPresenterFactory

### What issues does this PR fix or reference?
#4010 

#### Changelog
Removed deprecated classes in the texteditor package.

#### Release Notes
**Advisory**
Removed deprecated classes: We have remove the following deprecated classes from the `texteditor` package:
```
   org.eclipse.che.ide.api.editor.texteditor.EditorHandle
   org.eclipse.che.ide.api.editor.texteditor.EditorInitCallback
   org.eclipse.che.ide.api.editor.texteditor.EditorModule
   org.eclipse.che.ide.api.editor.texteditor.TextEditorCursorModel
   org.eclipse.che.ide.api.editor.texteditor.TextEditorInit
   org.eclipse.che.ide.api.editor.texteditor.TextEditorPresenter
   org.eclipse.che.ide.api.editor.texteditor.TextEditorPresenterFactory
```

### CODE REVIEW

**Review by vparfonov — APPROVED** [review]

**Comment by bmicklea** [comment]
@RomanNikitenko I don't understand - what is being deprecated and what is being removed specifically?

**Comment by RomanNikitenko** [comment]
@bmicklea I have added the list of deprecated entitis

**Comment by bmicklea** [comment]
So these are being deprecated and will be removed later?

**Comment by benoitf** [comment]
@bmicklea analyzing diff it seems it's the removal of deprecated stuff

**Review by bmicklea — APPROVED** [review]

**Pull request merged**
