### PR TITLE
[Selenium] Stabilize selenium tests

### PR DESCRIPTION
**Pull request by SkorikSergey**
### What does this PR do?
Stabilize selenium tests for starting on ci.centos.org.

### CODE REVIEW

**Comment by SkorikSergey** [comment]
[test]

**Comment by SkorikSergey** [comment]
[ci-test]

**Comment by SkorikSergey** [comment]
[ci-build]

**Comment by SkorikSergey** [comment]
[ci-test]

**Comment by SkorikSergey** [comment]
ci-test

**Comment by SkorikSergey** [comment]
[ci-test]

**Comment by SkorikSergey** [comment]
ci-test

**Comment by SkorikSergey** [comment]
[ci-test]

**Comment by SkorikSergey** [comment]
[ci-test]

**Review by artaleks9 — APPROVED** [review]

**Pull request merged**
