### PR TITLE
Restore the dependencies on creating a C# project

### PR DESCRIPTION
**Pull request by azatsarynnyy**
Signed-off-by: Artem Zatsarynnyi <azatsary@redhat.com>

### What does this PR do?
Fixes restoring the dependencies on creating a C# project

### What issues does this PR fix or reference?
#10047

### CODE REVIEW

**Comment by azatsarynnyy** [comment]
ci-test

**Review by vparfonov — APPROVED** [review]

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/468/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/468//Selenium_tests_report)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10405)
docker image: eclipseche/che-server:10405
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Review by dkulieshov — APPROVED** [review]

**Review by dkulieshov — CHANGES_REQUESTED** [review]
`wsPath` that you are using potentially may be not a project path but a project item path. For example project path may be `/projects/p1` and wsPath will be `/projects/p1/pom.xml`

**Comment by dkuleshov** [comment]
I think we should use something like `org.eclipse.che.api.project.server.ProjectManager#getClosest` to get real project and then get its workspace path. What do you think?

**Comment by azatsarynnyy** [comment]
@dkuleshov thank you for pointing this out! I've updated the PR.

**Comment by azatsarynnyy** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/472/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/472//Selenium_tests_report)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10405)
docker image: eclipseche/che-server:10405
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Review by ghost — APPROVED** [review]

**Review by dkulieshov — APPROVED** [review]

**Comment by azatsarynnyy** [comment]
During testing this PR with QA team it's appeared that 30 sec. isn't enough to initialize C# LS including restoring project's dependencies.
@SkorikSergey I've increased the timeout for initializing LS. Could you please check it again?

**Review by vparfonov — APPROVED** [review]

**Comment by SkorikSergey** [comment]
Selenium tests execution on Eclipse Che Multiuser on OCP (https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/472/) doesn't show any regression against this Pull Request.

**Comment by azatsarynnyy** [comment]
Thank you @SkorikSergey for your assistance in checking this PR.

**Pull request merged**
