### PR TITLE
[dockerfiles] [theia] Update to theia 0.3.17

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
update che-theia to latest 0.3.17 theia version

### What issues does this PR fix or reference?
N/A

#### Release Notes
N/A

#### Docs PR
N/A

Change-Id: I711690f465bbf12f760dab65ecceabeb311b8634
Signed-off-by: Florent Benoit <fbenoit@redhat.com>

### CODE REVIEW

**Comment by slemeur** [comment]
cc @slemeur

**Comment by benoitf** [comment]
ci-test

**Comment by benoitf** [comment]
ci-build

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1254/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1254//Selenium_20tests_20report/)
docker image: eclipseche/che-server:12082
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by benoitf** [comment]
ci-test

**Comment by benoitf** [comment]
ci-test

**Comment by benoitf** [comment]
ci-build

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1257/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1257//Selenium_20tests_20report/)
docker image: eclipseche/che-server:12082
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Review by Ohrimenko1988 — APPROVED** [review]

**Review by AndrienkoAleksandr — APPROVED** [review]

**Comment by benoitf** [comment]
@l0rd ok it's tricky. Task menu is now on Terminal menu but as @AndrienkoAleksandr rebind terminal widget then we don't have Terminal/Task 
image

**Pull request merged**
