### PR TITLE
Remove set -o pipefail fron che script

### PR DESCRIPTION
**Pull request by garagatyi**
Use the same style for variable expansion in whole script

In some bash environments `set -o pipefail` is illegal and Che can't start in that case.
@TylerJewell @vparfonov

### CODE REVIEW

**Comment by benoitf** [comment]
it seems description of PR should be updated as it does not only remove pipefail from che.sh script

it removes trailing spaces, add some {}, etc

**Comment by garagatyi** [comment]
Description says about changing style of variable expansion.
I don't think that trailing slashes is important enough to say about it.

**Comment by benoitf** [comment]
image

**Comment by benoitf** [comment]
image

**Comment by garagatyi** [comment]
Description, not title. It is auto generated from commit. I added 2 last lines to description to commit message.

**Comment by skabashnyuk** [comment]
ok. @vparfonov ?

**Comment by TylerJewell** [comment]
LGTM.  Let's merge it.

**Pull request merged**
