### PR TITLE
Add ability to cancel rename operation

### PR DESCRIPTION
**Pull request by RomanNikitenko**
### What does this PR do?
- Increase timeout for rename operation from 10 sec to 30 sec 
- Add ability to cancel rename operation 
- Add loader for 'OK' button to display state when operation is in progress
rename_new

- Fix NPE and provide error message for case when operation is interrupted by timeout:
Current behavior:
rename_current_timeout
The new behavior:
rename_timeout_new

- improve a little process of validation name: 
Current state - we send request per each inputted character
validate_current

The new behavior: while user is typing - we are waiting, when he stopped - we send request to validate new name  
validate_new

### What issues does this PR fix or reference?
#10784 #11754 

Signed-off-by: Roman Nikitenko <rnikiten@redhat.com>

### CODE REVIEW

**Comment by RomanNikitenko** [comment]
ci-test

**Review by dkulieshov — APPROVED** [review]

**Comment by RomanNikitenko** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1157/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1157//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11886
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by RomanNikitenko** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1158/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1158//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11886
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Pull request merged**
