### PR TITLE
CODENVY-651 Save machine config with 'dev' instead of 'isDev' field

### PR DESCRIPTION
**Pull request by mkuznyetsov**
change MachineConfigImpl field 'isDev' to 'dev', as it is done in MachineConfigDto.
It should fix consitensy problems.

Also it needs to make migrations of existing workspaces.

### CODE REVIEW

**Comment by garagatyi** [comment]
LGTM

**Comment by skabashnyuk** [comment]
ok. @evoevodin ?

**Comment by voievodin** [comment]
ok, don't forget to fix [this](https://github.com/eclipse/che/pull/1509/commits/34d34b70717c15fed9e6b34fe0899d4e70b177ae)

**Comment by skabashnyuk** [comment]
ok. do not merge until 4.6

**Comment by riuvshin** [comment]
agree with @skabashnyuk, do not merge this please to until we release 4.5. And do not forget prepare issue with migration script.

**Comment by musienko-maxim** [comment]
After checking all tests we do not have any regressions as compared with nightly4 server.

**Pull request merged**
