### PR TITLE
Fix internal servers URL rewriting on OSX

### PR DESCRIPTION
**Pull request by garagatyi**
### What does this PR do?
Fix internal servers URL rewriting on OSX

### What issues does this PR fix or reference?
Related to #7561

### CODE REVIEW

**Review by sleshchenko — APPROVED** [review]

**Review by skabashnyuk — APPROVED** [review]

**Comment by benoitf** [comment]
question: do we have a way to still get internal url instead of localhost for remote clients ?

**Comment by garagatyi** [comment]
@benoitf you have probably got a bug on OSX. Try to re-pull the repo and build Che again - I've already merged a fix.

**Comment by garagatyi** [comment]
@benoitf Probably I misunderstood you. If you ask whether we have internal vs external URLs then answer is no, we don't.

**Comment by benoitf** [comment]
@garagatyi OK thanks for your answer (and yes my question was about internal vs external)

**Pull request merged**
