### PR TITLE
Fix selenium test groups management

### PR DESCRIPTION
**Pull request by dmytro-ndp**
### What does this PR do?
It fixes selenium test groups management as follow:
- it makes it possible to define the test to be executed on the different infrastructures (not all) at a time, for example, on OpenShift and K8S.
- it moves beanshell script inside test suite xml, which looks hard to understand and to support, to the **SeleniumTestHandler** java class.

### What issues does this PR fix or reference?
#10583

### CODE REVIEW

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/601/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/601//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10791)
docker image: eclipseche/che-server:10791
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/602/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/602//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10791)
docker image: eclipseche/che-server:10791
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/603/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/603//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10791)
docker image: eclipseche/che-server:10791
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/606/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/606//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10791)
docker image: eclipseche/che-server:10791
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by riuvshin** [comment]
ci-test

**Comment by musienko-maxim** [comment]
I think the logic for including/excluding groups is not simple and potentially we may forgot abou this. I think for this one, would be better create unit test for checking correct the logic.

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/608/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/608//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10791)
docker image: eclipseche/che-server:10791
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/611/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/611//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10791)
docker image: eclipseche/che-server:10791
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Review by musienko-maxim — APPROVED** [review]

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/620/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/620//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10791)
docker image: eclipseche/che-server:10791
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/622/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/622//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10791)
docker image: eclipseche/che-server:10791
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by dmytro-ndp** [comment]
ci-test-docker-single

**Pull request merged**
