### PR TITLE
Do not track 'fileWatcherIgnore' file by File Watcher

### PR DESCRIPTION
**Pull request by RomanNikitenko**
### What does this PR do?
Do not track 'fileWatcherIgnore' file by File Watcher

### What issues does this PR fix or reference?
#5883 

Signed-off-by: Roman Nikitenko <rnikiten@redhat.com>

### CODE REVIEW

**Comment by RomanNikitenko** [comment]
ci-test

**Comment by RomanNikitenko** [comment]
ci-test

**Review by vparfonov — APPROVED** [review]

**Comment by RomanNikitenko** [comment]
ci-test

**Comment by RomanNikitenko** [comment]
ci-test

**Review by musienko-maxim — APPROVED** [review]

**Pull request merged**
