### PR TITLE
Add Jenkinsfile for user creation

### PR DESCRIPTION
**Pull request by Katka92**
### What does this PR do?
Add Jenkinsfile for user creation. It will be mainly used for load tests. It uses script that was already present in `che/tests/performance` folder.

### CODE REVIEW

**Comment by Katka92** [comment]
[crw-ci-test]

**Comment by Katka92** [comment]
ci-build

**Comment by Katka92** [comment]
[ci-build]

**Review by dmytro-ndp — APPROVED** [review]

**Comment by Katka92** [comment]
[ci-build]

**Comment by Katka92** [comment]
[crw-ci-test]

**Comment by Katka92** [comment]
[crw-ci-test]

**Comment by Katka92** [comment]
The failing test is not related to the changes made in this PR. Merging.

**Pull request merged**
