### PR TITLE
Project service: Lazy init of Tika

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
Lazy init of Tika.
Instead of initializing when constructor is called, initialize it at first call.

### What issues does this PR fix or reference?
#6169 

#### Changelog
lazily init the tika instance

#### Release Notes
N/A

#### Docs PR
N/A

Change-Id: I06872806f8a4c334614e1e15a12b5c533f5d8c11
Signed-off-by: Florent BENOIT <fbenoit@redhat.com>

### CODE REVIEW

**Comment by skabashnyuk** [comment]
Can we do some sort of provider or so? Or hide initialization logic inside some class instead of doing it in REST service?

**Comment by benoitf** [comment]
@skabashnyuk I fixed the issue, what you're asking is a refactoring on how ProjectService was designed ? AFAIK these changes are handled by maintainers not by contributors.

**Comment by garagatyi** [comment]
@benoitf Can you elaborate on why the kind label is set to bug?

**Comment by benoitf** [comment]
@garagatyi you think it's an enhancement ?
For me it's a bug as creating an instance of an object should be always fast.

**Comment by garagatyi** [comment]
I do believe that marking everything as a bug is not convenient since it tempts ppl to mark everything as a bug to put up the priority and attention of other ppl in the project

**Comment by benoitf** [comment]
I've updated the label to enhancement if it's more convenient for people.

**Comment by garagatyi** [comment]
thanks

**Review by vparfonov — APPROVED** [review]

**Review by skabashnyuk — APPROVED** [review]

**Pull request merged**
