### PR TITLE
Errors in the browser console when importing the eclipse-che project

### PR DESCRIPTION
**Pull request by dkulieshov**
Signed-off-by: Dmytro Kulieshov <dkuliesh@redhat.com>

### What does this PR do?
Fixes multiple error message in dev console in a browser when a user creates a project from sample.

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/8459

### CODE REVIEW

**Comment by dkulieshov** [comment]
ci-build

**Comment by dkulieshov** [comment]
ci-build

**Comment by dkulieshov** [comment]
ci-test

**Comment by dkulieshov** [comment]
ci-test

**Comment by musienko-maxim** [comment]
Selenium tests have not found new regression

**Review by vparfonov — APPROVED** [review]

**Pull request merged**
