### PR TITLE
Make plugins/editors show one entry for each plugin with a drop down for version

### PR DESCRIPTION
**Pull request by JPinkney**
### What does this PR do?
This PR introduces the functionality and styling for having plugins/editors show one entry for each plugin, with a drop down to select the version. Previously, the plugins page and the editors page showed an entry for every version of the plugin.

Video: https://www.youtube.com/watch?v=WkrbTsrjuBk

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/13566

#### Release Notes

Modified plugin and editor dashboard pages to have one entry for each plugin with a drop down to select the version

### CODE REVIEW

**Comment by musienko-maxim** [comment]
Can one of the admins verify this PR?

**Comment by l0rd** [comment]
@JPinkney thanks!

@ashumilova @rhopp can you please have a look. If you consider that it's safe enough I would rather be +1 to merge this PR because it has an important impact on UX (even if it isn't inclued in the endgame).

**Comment by slemeur** [comment]
Nice work @JPinkney ! 

Ping @ashumilova and @rhopp . That is something we would like to integrate in 7.0.0

**Comment by ashumilova** [comment]
Reviewed and like the proposed changes and +1 for merging.
One thing discovered and need to be fixed - when workspace is updated in devfile editor and saved, than the state of plugins and editors pages is not consistent, until user refreshes the page.

**Comment by benoitf** [comment]
I would not merge it, it's an enhancement, linked issue is not event tagged for `7.0.0`

**Review by nickboldt — APPROVED** [review]
So recapping that's a +1 from Anna (with a requested change) and a -1 from Florent. 

I suppose  @rhopp is the tiebreaker here? 

Unclear why I'm being asked to PR review on this one, but here we go:
* code: +0, I'm not an expert
* concept:+1, makes UI cleaner and appears to sync between the plugins and devfile tabs/content.
* QE: -0.5: might break existing UI tests, but not my call.

**Comment by rhopp** [comment]
ci-test

**Comment by vitaliy-guliy** [comment]
I would display the version as a plain text and display the select field only when hovering the row.

**Comment by slemeur** [comment]
I like @JPinkney proposal as it is. If the select box was appearing only on hover, I would not understand that I can change the version. Here it is clear IMO.

+1 to merge for 7.0.0

**Review by benoitf — APPROVED** [review]
target was `7.1.0` but it has been changed to `7.0.0` so I'm fine

**Comment by ashumilova** [comment]
yeah, but need to fix the way how plugins and editors pages are updated on changes in devfile (in editor).

**Comment by ashumilova** [comment]
When we do updates in Yaml editor on "Devfile" page of workspace details, the following method is called:
https://github.com/eclipse/che/blob/d89cf6f0c3b28671cfcef1cfbc4344ca4d110d1d/dashboard/src/app/workspaces/workspace-details/workspace-plugins/workspace-plugins.controller.ts#L71

it has a check, whether plugin is selected (`isPluginEnabled`).
If we had `plugin1/version1` selected, and user changed in editor to 'plugin1/version2', the check works wrong in that case. We need to find plugin id without version and if there are version changes - keep the item selected with the changed version.

**Comment by JPinkney** [comment]
I'll try to fix that as soon as possible but I'm currently working on the last blocker for Che 7 (https://github.com/eclipse/che/issues/13427) so I can't give any accurate timeline on when it will be done

**Comment by akurinnoy** [comment]
@JPinkney seems there is minor fix so I could prepare a commit with fix. You'll only need to test it and merge, wdyt?

**Comment by JPinkney** [comment]
@akurinnoy Yeah that would be great!

**Comment by akurinnoy** [comment]
ci-test

**Comment by akurinnoy** [comment]
@rhopp I've just added commit which fixes bug mentioned [here](https://github.com/eclipse/che/pull/13942#issuecomment-519453164)

It seems happy-path-tests are not happy with that. Is this fail related to my commit? Is there something I could do to fix it?

**Comment by dmytro-ndp** [comment]
@akurinnoy: PR check has been failed because it uses Jenkinsfile now, which has been merged in master tonight. So, you need to take changes from master.

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by JPinkney** [comment]
@akurinnoy I've just tested out your fix and it seems like everything is working!

**Comment by akurinnoy** [comment]
ci-build

**Comment by akurinnoy** [comment]
@rhopp please have a look. Can we merge this PR?

**Comment by rhopp** [comment]
Looking good with one small drawback with the scrolling:
ezgif-4-1a4123601680
I'm using Google Chrome 76.0.3809.87.

**Comment by akurinnoy** [comment]
@rhopp I'm sure issue with scrolling is not related to this changes. Please file an issue for this bug.

**Comment by amisevsk** [comment]
@rhopp @akurinnoy I can confirm that the scrolling issue is present most versions of Che, I've opened issue https://github.com/eclipse/che/issues/14256

**Pull request merged**
