### PR TITLE
CHE-787; Make it possible to change log level when starting Che

### PR DESCRIPTION
**Pull request by mshaposhnik**
**_1 Upvote**_

### CODE REVIEW

**Comment by mshaposhnik** [comment]
@vparfonov @eivantsov @skabashnyuk

**Comment by vparfonov** [comment]
+1

**Comment by TylerJewell** [comment]
1. Do not use two letter short code options - only use a single letter.
2. Rebase against master - the che.sh was heavily rewritten and merged yesterday.
3. What are the full list of log levels that are possible.  Are these Tomcat log levels or che log levels.  If they are tomcat log levels, should they be exposed in che.sh script?

**Comment by mshaposhnik** [comment]
@TylerJewell 
1. Which letter do you propose?
2. Seems changes fits ok
3. It's a logback log levels.

**Comment by TylerJewell** [comment]
1. Just use "-l" if it is available.
2. Make it clear in the log description that it's logback log levels.  Otherwise average person will not know, I think.

**Comment by mshaposhnik** [comment]
-l used for copy-lib. We can change in to -c, and use -l to logs then
-l|--copy-lib
      COPY_LIB=true
    ;;

**Comment by TylerJewell** [comment]
If you make this change, also change the Dockerfile in the root of master.  The ENTRYPOINT passes in the -l option and needs to be updated to use the correct option.

**Comment by mshaposhnik** [comment]
https://github.com/eclipse/che/pull/1242/files

**Pull request merged**
