### PR TITLE
Upgrade dashboard dependencies

### PR DESCRIPTION
**Pull request by evidolob**
### What does this PR do?
Upgrades `jquery` to `3.4.0` and `js-yaml` to `3.13.1` to fix CVE warnings

### CODE REVIEW

**Review by ashumilova — APPROVED** [review]

**Comment by danidoedel** [comment]
@evidolob Is there a reason why you don't use jQuery 3.4.1?

**Comment by evidolob** [comment]
There are no particular reason to have `3.4.0`, I jus use suggested version
@danidoedel Are you suggest to use `3.4.1` ?

**Comment by evidolob** [comment]
ci-test

**Comment by danidoedel** [comment]
@evidolob 3.4.1 is a bug fix release and I think it's always nice to have these bugs fixed in my opinion. It's up to you of course, I was just wondering.

**Comment by evidolob** [comment]
ci-test

**Comment by musienko-maxim** [comment]
ci-test

**Review by musienko-maxim — APPROVED** [review]

**Pull request merged**
