### PR TITLE
Modify URL to fetch user's github account token

### PR DESCRIPTION
**Pull request by sbose78**
part of https://github.com/fabric8-services/fabric8-auth/issues/149
needs to merged along with https://github.com/redhat-developer/rh-che/pull/380

### CODE REVIEW

**Comment by benoitf** [comment]
@sbose78 thanks for the contribution, you will need to sign the Eclipse ECA and amend your commit with the Signed-off-by footer
https://www.eclipse.org/legal/ecafaq.php

**Review by ibuziuk — CHANGES_REQUESTED** [review]
Changing just endpoint url is not enough. There should be also changes done in the way how the token parsing is done

**Comment by ibuziuk** [comment]
@sbose78 if it works for you I can work on migration of rh-che / che / che-starter to the new endpoint

**Comment by sbose78** [comment]
Sure @ibuziuk - feel free to open a new PR :)

**Comment by sbose78** [comment]
Sure @ibuziuk - feel free to open a new PR :) 
Curious, with respect to changes in parsing - are you talking the about the need for using the `Accept : application/json` ?

**Comment by ibuziuk** [comment]
@sbose78 yeah, about changing key value parsing to json one

**Comment by ibuziuk** [comment]
Closing in favor of https://github.com/eclipse/che/pull/6809

**Pull request closed without merging**
