### PR TITLE
Make methods accessible with machine token configurable

### PR DESCRIPTION
**Pull request by mshaposhnik**
### What does this PR do?
Make methods accessible with machine token configurable via multibinder instead of hardcoding.

### What issues does this PR fix or reference?
#11374

#### Release Notes
N/A

#### Docs PR
N/A

### CODE REVIEW

**Comment by mshaposhnik** [comment]
@davidfestal take a look

**Review by sleshchenko — APPROVED** [review]
LGTM

**Comment by skabashnyuk** [comment]
@davidfestal fyi

**Review by skabashnyuk — APPROVED** [review]

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/889/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/889//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11402
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Review by davidfestal — APPROVED** [review]

**Pull request merged**
