### PR TITLE
Remove duplicate keys

### PR DESCRIPTION
**Pull request by tsmaeder**
### What does this PR do?
Fixup for https://github.com/eclipse/che/pull/11898: broke the whole thing working in comments from PR review.

### What issues does this PR fix or reference?
#11490

### CODE REVIEW

**Review by svor — APPROVED** [review]
ok for me, but don't merge until tests will finish.

**Comment by svor** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1175/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1175//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11941
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by svor** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1176/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1176//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11941
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by dmytro-ndp** [comment]
Latest `ci-test` [build](https://github.com/eclipse/che/pull/11941#issuecomment-438825764) failed because it took more that 5 hours. 
You can find server logs [here](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1176/Selenium_20tests_20report/che_server_logs.zip).

**Comment by tsmaeder** [comment]
ci-test

**Pull request merged**
