### PR TITLE
 Move image name from  location to content field in dockerimage recipes

### PR DESCRIPTION
**Pull request by mshaposhnik**
### What does this PR do?
Since field `location` is supposed to contain URL to recipe content, for dockerimage recipes their name moved from `location` field to field `content`.

### What issues does this PR fix or reference?
#6006

#### Release Notes
N/A

#### Docs PR
N/A

### CODE REVIEW

**Comment by garagatyi** [comment]
What about UD? Does UD have any place where it creates workspace config with a dockerimage recipe?

**Comment by mshaposhnik** [comment]
There is some config validations and tests in UD, wil fix them too

**Review by ashumilova — APPROVED** [review]

**Review by ashumilova — APPROVED** [review]

**Review by ashumilova — APPROVED** [review]

**Review by ashumilova — APPROVED** [review]

**Comment by mshaposhnik** [comment]
wtf is going on :) ?

**Comment by ashumilova** [comment]
@mshaposhnik your PR hates me

**Comment by skabashnyuk** [comment]
ci-test

**Review by garagatyi — APPROVED** [review]

**Comment by skabashnyuk** [comment]
ci-test

**Review by skabashnyuk — APPROVED** [review]

**Pull request merged**
