### PR TITLE
[ Selenium ] Get rid of redundant methods in the "SeleniumWebDriverHelper" class

### PR DESCRIPTION
**Pull request by Ohrimenko1988**
### What does this PR do?
Get rid of redundant methods in the "SeleniumWebDriverHelper" class

### What issues does this PR fix or reference?
Issue: https://github.com/eclipse/che/issues/11911

### CODE REVIEW

**Comment by Ohrimenko1988** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1160/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1160//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11913
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1170/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1170//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11913
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by Ohrimenko1988** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1192/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1192//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11913
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Review by SkorikSergey — APPROVED** [review]

**Review by dmytro-ndp — APPROVED** [review]

**Review by artaleks9 — APPROVED** [review]

**Pull request merged**
