### PR TITLE
Explicit dependabot configuration

### PR DESCRIPTION
**Pull request by skabashnyuk**
### What does this PR do?
Add explicit dependabot configuration
 - notifu about `security` updates
 - check java:maven from `/`
- check `Dockerfile` from `/dockerfiles/`

### CODE REVIEW

**Review by mshaposhnik — APPROVED** [review]

**Comment by benoitf** [comment]
what about security alerts we have in https://github.com/eclipse/che/tree/master/tests ?

**Comment by skabashnyuk** [comment]
>what about security alerts we have in https://github.com/eclipse/che/tree/master/tests ?

@rhopp @dmytro-ndp  what about security alerts we have in https://github.com/eclipse/che/tree/master/tests ?

**Comment by dmytro-ndp** [comment]
@skabashnyuk: the alert about improper **minimist** version https://github.com/eclipse/che/network/alert/tests/e2e/package-lock.json/minimist/open 
But it's related to tests, not to product itself. So, it doesn't look as something dangerous for Eclipse Che, IMHO.
@Ohrimenko1988, @Katka92, @rhopp: WDYT about upgrading **minimist** version in our E2E typescript tests /e2e/package-lock.json to 0.2.1 version?

**Comment by benoitf** [comment]
@dmytro-ndp FYI there is already an open PR https://github.com/eclipse/che/pull/17297

**Comment by musienko-maxim** [comment]
[crw-test]

**Comment by musienko-maxim** [comment]
[ci-test]

**Comment by musienko-maxim** [comment]
[ci-test-happy-path]

**Comment by musienko-maxim** [comment]
crw-ci-test

**Comment by musienko-maxim** [comment]
[crw-ci-test]

**Comment by musienko-maxim** [comment]
When i relaunch the happy path test during the maven build project we have error like:
`16:29:08 [Build Che including upstream projects] [INFO] ------------------------------------------------------------------------
16:29:08 [Build Che including upstream projects] [INFO] BUILD FAILURE
16:29:08 [Build Che including upstream projects] [INFO] ------------------------------------------------------------------------
16:29:08 [Build Che including upstream projects] [INFO] Total time:  3.455 s
16:29:08 [Build Che including upstream projects] [INFO] Finished at: 2020-07-07T09:29:07-04:00
16:29:08 [Build Che including upstream projects] [INFO] ------------------------------------------------------------------------
16:29:08 [Build Che including upstream projects] [ERROR] Failed to execute goal com.mycila:license-maven-plugin:3.0:check (check-headers) on project che-docs: Some files do not have the expected license header -> [Help 1]
16:29:08 [Build Che including upstream projects] [ERROR] 
16:29:08 [Build Che including upstream projects] [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
16:29:08 [Build Che including upstream projects] [ERROR] Re-run Maven using the -X switch to enable full debug logging.
16:29:08 [Build Che including upstream projects] [ERROR] 
16:29:08 [Build Che including upstream projects] [ERROR] For more information about the errors and possible solutions, please read the following articles:
16:29:08 [Build Che including upstream projects] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException` 
**Please take a look on this**

**Review by dmytro-ndp — APPROVED** [review]

**Pull request merged**
