### PR TITLE
change predefined host for start tests on the webdriver.sh to localhost

### PR DESCRIPTION
**Pull request by Ohrimenko1988**
### What does this PR do?
- change predefined host for starting selenium tests to "localhost"

### CODE REVIEW

**Review by garagatyi — CHANGES_REQUESTED** [review]
I think we should reimplement function `detectDockerInterfaceIp` instead. And use approach used in Che CLI. 
[Here](https://github.com/garagatyi/che/blob/69d51483859d828aa285bcef324244ca236109ad/dockerfiles/cli/scripts/post_init.sh#L9-L9) is an example: 
`DOCKER_IP=$(docker run --rm --net host eclipse/che-ip:nightly)`

**Comment by riuvshin** [comment]
+1 to what @garagatyi said. `hostname -I | awk '{ print $1 }'` will not work on mac for example

**Review by tolusha — APPROVED** [review]

**Review by akorneta — APPROVED** [review]

**Comment by skabashnyuk** [comment]
```+++```

**Review by riuvshin — CHANGES_REQUESTED** [review]
As @garagatyi said we have to **reimplement** `detectDockerInterfaceIp` function because in that state it does not make any sense

**Review by garagatyi — APPROVED** [review]
Looks good!

**Review by riuvshin — APPROVED** [review]

**Pull request merged**
