### PR TITLE
Add a missing file required to correctly bootstrap Ceylon user projects

### PR DESCRIPTION
**Pull request by davidfestal**
### What does this PR do?

The PR adds a file that had been omitted by mistake and is necessary to bootstrap any new created Ceylon  project, even where Ceylon is not already installed.

### What issues does this PR fix or reference?

https://github.com/eclipse/che/issues/10516

### CODE REVIEW

**Review by benoitf — APPROVED** [review]

**Comment by davidfestal** [comment]
ci-test

**Comment by skabashnyuk** [comment]
what is the content of this file? License?

**Comment by davidfestal** [comment]
@skabashnyuk This file is the Ceylon bootstrapper jar file that is added by the [`ceylon boostrap command`](https://ceylon-lang.org/documentation/1.3/reference/tool/bootstrap/) into user projects in order to enable the user to directly and transparently boostrap Ceylon in his project.

So this is part of the user project template, and according to what @benoitf [commented here](https://github.com/eclipse/che/pull/10096#discussion_r196692460) is not submitted to licensing afaict.

**Comment by skabashnyuk** [comment]
ok. @davidfestal up to your and @benoitf responsibility.

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/532/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/532//Selenium_tests_report)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10517)
docker image: eclipseche/che-server:10517
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Pull request merged**
