### PR TITLE
feat: Add logging with attachments into ReportPortal 

### LINKED ISSUE #22586: Add logging with attachments into ReportPortal
### Is your task related to a problem? Please describe

Logger class should sent data into test steps to reportportal and attach screenshots on test failed.
image

### Describe the solution you'd like

Update Logger class with to send logs using publicReportingAPI.js
Update MochaHooks.ts to create and send attachment on test fail.
https://github.com/reportportal/agent-js-mocha/tree/develop

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nallikaea**
### What does this PR do?
- PR updates Logger class to send logs into report-portal service using external API.
- Added method which will send attachment on test fail

### Screenshot/screencast of this PR

image

### What issues does this PR fix or reference?

#22586 

### How to test this PR?

set SAVE_RP_REPORT_DATA=true, fill relevant reporter constants to set server and user for saving the report. Run some tests.

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix or new feature ](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix-or-new-feature)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by dmytro-ndp** [comment]
@nallikaea : is this PR ready for verification?

**Comment by nallikaea** [comment]
@dmytro-ndp , yes, I rebased it

**Comment by dmytro-ndp** [comment]
@nallikaea : thank you.

Need you help to find attachments after the test execution in ReportPortal.

E.g. "_Check if recommended extensions installed for Java 11 with Lombok PSI online-ocp 4.14 > Check if extensions are installed and enabled_" test failed: 
- here the screenshot is existed in Jenkins build artifacts: https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/Testing/job/e2e/job/basic/job/typescript-tests/13613/artifact/test-repo/tests/e2e/report/Check_if_recommended_extensions_installed_for_Java_11_with_Lombok_PSI_online-ocp_4.14_Check_if_extensions_are_installed_and_enabled/
- here ReportPortal shows no attachment: https://reportportal-crw.apps.ocp-c1.prod.psi.redhat.com/ui/#devspaces/launches/all/145/2901/2912/log?logParams=filter.ex.binaryContent%3Dtrue

**Comment by nallikaea** [comment]
@dmytro-ndp https://reportportal-crw.apps.ocp-c1.prod.psi.redhat.com/ui/#devspaces/launches/all/145/2901/log

**Comment by dmytro-ndp** [comment]
@nallikaea : thank you for the link.

**Review by dmytro-ndp — APPROVED** [review]
looks good to merge

**Pull request merged**
