### PR TITLE
Group all DB migrations related to Che6 into 6.0.0 version;

### PR DESCRIPTION
**Pull request by mshaposhnik**
### What does this PR do?
Moves all DB migrations related to Che6 into 6.0.0 version;
This is needed because Che6 now have migrations in old versions which are not apllied on master Db version. (like 5.8.0)  So when migrating DB to 6 version, it is unable to apply those migrations and conflicts are raised.

### CODE REVIEW

**Comment by mshaposhnik** [comment]
ci-build

**Review by skabashnyuk — APPROVED** [review]

**Comment by sleshchenko** [comment]
I'd make rename `6.0.0/4__remove_old_recipe.sql` to `6.0.0/1__remove_old_recipe.sql` to make it clearer that it linked to `0.1__remove_old_recipe_permissions.sql`

**Comment by mshaposhnik** [comment]
I don't know.. i woluld like to keep original order to avoid accidentally making it incompatible

**Comment by sleshchenko** [comment]
But you didn't keep original order. To do that, you should put `0.1__remove_old_recipe_permissions.sql` just before `6.0.0/4__remove_old_recipe.sql`. I guess to do that you should rename that script to `3.1__remove_old_recipe_permissions.sql`

**Comment by mshaposhnik** [comment]
Thats probably little better for sequence understanding purposes, ok.

**Comment by sleshchenko** [comment]
I think you should change license in `1__add_path_to_serverconf.sql` to RedHat one

**Review by sleshchenko — APPROVED** [review]
Now LGTM

**Pull request merged**
