### PR TITLE
Fix the invalid path conversion. (eclipse#14151)

### LINKED ISSUE #14151: In some case, generated paths to each ssh private key in `/etc/ssh/config` will be mismatch to mount paths.
### Describe the bug

I couldn't `git push` via SSH. I inspected and It is caused by invalid path to SSH key.

### Che version

 - [x] HEAD ~~other: please specify~~

### Steps to reproduce

As currently I'm not sure  how to reproduce, I show my step.

1. Open terminal
2. `ssh -vvv git@ssh.dev.azure.com`
3. Press `Ctrl-C` after SSL auth was failed.
4. `ls /etc/ssh/`

### Expected behavior

The goal is "`git push` is done with no error.".
In the viewpoint of "Steps to reproduce", SSL auth is succeeded.

### Runtime
   - [x] kubernetes (include output of `kubectl version`) 
But It won't depend on runtime.

### Additional context

ssh tryes to find the secret in `/etc/ssh/ssh-dev-azure-com/ssh-privatekey`.

```
debug1: Trying private key: /etc/ssh/ssh-dev-azure-com/ssh-privatekey
debug3: no such identity: /etc/ssh/ssh-dev-azure-com/ssh-privatekey: No such file or directory
debug2: we did not send a packet, disable method
debug3: authmethod_lookup password
debug3: remaining preferred: ,password
debug3: authmethod_is_enabled password
debug1: Next authentication method: password
git@ssh.dev.azure.com's password: 
```

But it mounted on the another path /etc/ssh/ssh.dev.azure.com/ssh-privatekey.

```
$ ls /etc/ssh
github.com  sshd_config        ssh_host_dsa_key.pub    ssh_host_ed25519_key      ssh_host_rsa_key.pub
moduli      ssh.dev.azure.com  ssh_host_ecdsa_key      ssh_host_ed25519_key.pub  ssh_import_id
ssh_config  ssh_host_dsa_key   ssh_host_ecdsa_key.pub  ssh_host_rsa_key
```

### PR DESCRIPTION
**Pull request by monaka**
### What does this PR do?

Fix the invalid path conversion.

### What issues does this PR fix or reference?

fixes #14151

### CODE REVIEW

**Comment by monaka** [comment]
After sent this. I noticed it's better to use hashed value by SHA-256 or something instead of using `keyName` directly.  Because keyName isn't supposed to use as the part of filepath.   I'll add some code and re-push here.

**Comment by vparfonov** [comment]
fixed here https://github.com/eclipse/che/pull/14156 
can be improved in next versions

**Comment by monaka** [comment]
@vparfonov Sorry for late response. I reviewed #14156. I suppose it won't work fine in case `sshPair.name` contains unsuitable chars for the path. As far as I inspect, `sshPair.name` can be set with no character type validation.

**Comment by vparfonov** [comment]
> @vparfonov Sorry for late response. I reviewed #14156. I suppose it won't work fine in case `sshPair.name` contains unsuitable chars for the path. As far as I inspect, `sshPair.name` can be set with no character type validation.

Make sense, thats why i assumed about improved in next steps

**Pull request closed without merging**
