### PR TITLE
CHE-7481 Turn on java debugger integration tests

### PR DESCRIPTION
**Pull request by tolusha**
### What does this PR do?
Turn on java debugger integration tests

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/7481

not required

#### Release Notes

not required

#### Docs PR

not required

### CODE REVIEW

**Comment by tolusha** [comment]
ci-test

**Comment by tolusha** [comment]
ci-build

**Review by dkulieshov — APPROVED** [review]

**Comment by tolusha** [comment]
ci-test

**Comment by tolusha** [comment]
ci-build

**Comment by riuvshin** [comment]
ci-build

**Comment by riuvshin** [comment]
ci-build

**Comment by tolusha** [comment]
ci-build

**Comment by tolusha** [comment]
ci-build

**Pull request merged**
