### PR TITLE
Fix potential security vulnerabilities

### PR DESCRIPTION
**Pull request by akurinnoy**
### What does this PR do?

Upgrade dependencies:

- lodash to 4.17.15
- angularJS and related modules to 1.6.10

### What issues does this PR fix or reference?

https://github.com/eclipse/che/issues/13924

Signed-off-by: Oleksii Kurinnyi <okurinny@redhat.com>

### CODE REVIEW

**Review by benoitf — APPROVED** [review]

**Comment by akurinnoy** [comment]
crw-ci-test

**Comment by akurinnoy** [comment]
ci-test

**Review by mmorhun — APPROVED** [review]

**Comment by SkorikSergey** [comment]
ci-test

**Comment by SkorikSergey** [comment]
crw-ci-test

**Review by SkorikSergey — APPROVED** [review]

**Review by olexii4 — APPROVED** [review]

**Pull request merged**
