### PR TITLE
Remove GWT-related code from Java selenium E2E tests

### PR DESCRIPTION
**Pull request by dmytro-ndp**
### What does this PR do?
Decouple Java selenium E2E tests from GWT-code:
1. Removes dependencies on plugins artifacts:
   * org.eclipse.che.plugin:**che-plugin-github-shared**
   * org.eclipse.che.plugin:**che-plugin-github-server** 
   * org.eclipse.che.core:**che-core-api-debug-shared**

2. Removes tests which aimed to verify GWT-editor functionality:
   * org.eclipse.che.selenium.assistant.*
   * org.eclipse.che.selenium.languageserver.*
   * org.eclipse.che.selenium.debugger.*
   * org.eclipse.che.selenium.editor.*
   * org.eclipse.che.selenium.filewatcher.*
   * org.eclipse.che.selenium.git.*
   * org.eclipse.che.selenium.intelligencecommand.*
   * org.eclipse.che.selenium.mavenplugin.*
   * org.eclipse.che.selenium.miscellaneous.*
   * org.eclipse.che.selenium.opendeclaration.*
   * org.eclipse.che.selenium.plainjava.*
   * org.eclipse.che.selenium.testrunner.*
   * org.eclipse.che.selenium.projectexplorer.*
   * org.eclipse.che.selenium.refactor.*
   * org.eclipse.che.selenium.stack.*
   * org.eclipse.che.selenium.workspaces.CheckStopStartWsTest

3. Moves `GitHubKey` class to test project
4. Works around e2e tests which use che6 workspaces to check functionality which doesn't related to GWT-stuff, and so should be rewritten to use che7 ones:
   * org.eclipse.che.selenium.workspaces.CheckStoppingWsByTimeoutTest
   * org.eclipse.che.selenium.workspaces.CreateWorkspaceOnDashboardTest
   * org.eclipse.che.selenium.workspaces.ProjectStateAfterRefreshTest
   * org.eclipse.che.selenium.workspaces.ProjectStateAfterWorkspaceRestartTest
   * org.eclipse.che.selenium.site.ocpoauth.LoginExistedUserWithOpenShiftOAuthTest
   * org.eclipse.che.selenium.site.ocpoauth.LoginNewUserWithOpenShiftOAuthTest
   * org.eclipse.che.selenium.dashboard.organization.ShareWorkspaceMemberTest
   * org.eclipse.che.selenium.dashboard.workspaces.AddOrImportProjectFormTest
   * org.eclipse.che.selenium.dashboard.ImportProjectFromGitHubTest
   * org.eclipse.che.selenium.swagger.SwaggerTest
   * org.eclipse.che.selenium.hotupdate.*
   * org.eclipse.che.selenium.factory.DirectUrlFactoryWithKeepDirectoryTest
   * org.eclipse.che.selenium.factory.DirectUrlFactoryWithRootFolderTest
   * org.eclipse.che.selenium.factory.DirectUrlFactoryWithSpecificBranchTest

5. Removes classes of tests which had been removed from test suites previously.

### What issues does this PR fix or reference?
#13827, https://github.com/eclipse/che/pull/13788

### CODE REVIEW

**Comment by benoitf** [comment]
it that this PR should go in @skabashnyuk branch ?

**Comment by dmytro-ndp** [comment]
it would be grateful, if it's possible.
I am going to merge further changes from upstream branch **che7cleanup** to make it possible.

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by dmytro-ndp** [comment]
ci-build

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by musienko-maxim** [comment]
Your build is failure

**Comment by dmytro-ndp** [comment]
@skabashnyuk , @vparfonov : Java selenium e2e tests had been fixed to be run against Che 7 without GWT-code.
If you don't mind, I will merge changes from this PR into upstream branch https://github.com/eclipse/che/pull/13788

**Review by skabashnyuk — APPROVED** [review]

**Pull request merged**
