### PR TITLE
UD-1049 : do not change files after build

### PR DESCRIPTION
**Pull request by benoitf**
**_3 Upvotes**_ Change-Id: Ib96b99aa3fecafb9f1a0936a13f06e4f927c0a89
Signed-off-by: Florent BENOIT fbenoit@codenvy.com

### CODE REVIEW

**Comment by vparfonov** [comment]
thanks @benoitf

**Comment by olexii4** [comment]
+1
Can we add in addition coment to https://github.com/codenvy/dashboard/blob/master/src/app/index.module.js#L32
(why we have "DEV = true" in master)

**Comment by benoitf** [comment]
@olexii4 I will create PR on  repository to add comment yes good idea

**Comment by ashumilova** [comment]
+1

**Comment by akurinnoy** [comment]
+1

**Pull request merged**
