### PR TITLE
CHE-6226: Che stylization of Keycloak account pages

### PR DESCRIPTION
**Pull request by mmorhun**
### What does this PR do?
Adds `account` subtheme to Keycloak Che theme.

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/6226

#### Screenshots:
screenshot from 2017-10-03 10-19-48
screenshot from 2017-10-03 10-07-44

### CODE REVIEW

**Review by tolusha — APPROVED** [review]

**Review by riuvshin — APPROVED** [review]

**Review by benoitf — APPROVED** [review]

**Comment by benoitf** [comment]
thanks for the screenshots @mmorhun

**Review by ashumilova — APPROVED** [review]

**Review by skabashnyuk — APPROVED** [review]

**Comment by slemeur** [comment]
@mmorhun : Great work, thanks. 

I suppose that the link "back to che-public" will redirect the user to his dashboard. Is that correct? 
If so, I'd like to make this link more obvious and have a button using our yellow background. The title should be "Back to Dashboard"

**Comment by slemeur** [comment]
Also why the pages are using only a portion of the screen? (horizontally)

**Comment by mmorhun** [comment]
@slemeur 
screenshot from 2017-10-02 15-17-19

**Review by slemeur — APPROVED** [review]

**Pull request merged**
