### PR TITLE
Prevent inconsistency when allowed user namespaces is false and namespace contains random part.

### PR DESCRIPTION
**Pull request by mshaposhnik**
### What does this PR do?

Some namespace naming inconsistency spotted, when `che.infra.kubernetes.namespace.allow_user_defined=false` and when we need to normalize the namespace name. PR fixes this situation.

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/18178

### How to test this PR?
Create a user with invalid symbols in username. Try create/run custom workspaces. Everything should run smooth. namespace name should remain the same.

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Review by sparkoo — COMMENTED** [review]
Do we need now `NamespaceResolutionContext.persistAfterCreate` property? Or do we persist it everytime we call `evalDefaultNamespace`, which is only caller of the property.

**Comment by mshaposhnik** [comment]
Not sure if we won't break something, but let's try :-)

**Review by sparkoo — APPROVED** [review]
tested and works fine 👍🏼 
Do we need to update the docs ?
what about backport to 7.20 ?

**Review by metlos — APPROVED** [review]

**Comment by mshaposhnik** [comment]
[crw-ci-test]

**Pull request merged**
