### PR TITLE
[cli] Simpler networking config explanation & command line overrides

### PR DESCRIPTION
**Pull request by TylerJewell**
### What does this PR do?
Adding improvements on configuring Che for common scenarios. We have seen that users who provide `CHE_HOST` or `CHE_PORT` on the command line want that to override the values of `che.env`.  Today, it is the reverse where values in the environment file would override the command line.  

This set of changes applies an algorithm that will take any values of `CHE_*` or `{CHE_PRODUCT_NAME}_*` that are passed on the command line and insert those parameters into the `config` method, generating an instance-specific `.env` file which will be used by the Che server when it is started.  If this is ARTIK or CODENVY, it will load both the CHE_* and ARTIK_* and CODENVY_* variables, so that anything that we provide as a parameter in a *.env file can now be overridden on the command line.

Matching PRs:
1. Codenvy:  https://github.com/codenvy/codenvy/pull/1764
2. ARTIK: https://github.com/codenvy/artik/pull/337
3. Codenvy SAAS: https://github.com/codenvy/saas/pull/143

#### Changelog
Make command-line `CHE_HOST` or `CHE_PORT` override `che.env` values.

#### Release Notes
Docker command-line environment variables `CHE_HOST` or `CHE_PORT` override `che.env` values.

#### Docs PR
https://github.com/eclipse/che-docs/pull/137

### CODE REVIEW

**Review by benoitf — APPROVED** [review]

**Comment by TylerJewell** [comment]
@eivantsov - you may want to run a quick test.  I did a series of tests to demonstrate that CHE_HOST and CHE_PORT provided on the command line will now override any setting provided in the environment file.

**Review by riuvshin — APPROVED** [review]

**Review by riuvshin — CHANGES_REQUESTED** [review]
this PR does not work for me on Mac

I've build base cli and init images from branch started che, then I tried
`docker run ... restart --skip:nightly --skip:pull -e CHE_PORT=9090` and nothing changed

**Comment by TylerJewell** [comment]
@riuvshin syntax had a mistake - the `-e CHE_PORT=` needs to appear before the image name, not after it.  Once we moved it, then Che started with the custom property.

**Comment by riuvshin** [comment]
tested on mac and ubuntu - works

**Review by riuvshin — APPROVED** [review]

**Comment by riuvshin** [comment]
tesed on digital ocean, it works but we have issue with generation secure random which takes up to 10 minutes on instances with low entroy.
```
2017-02-14 12:10:01,402[ost-startStop-1]  [INFO ] [o.a.c.u.SessionIdGeneratorBase 241]  - Creation of SecureRandom instance for session ID generation using [SHA1PRNG] took [515,672] milliseconds.
```

**Comment by riuvshin** [comment]
I've added `-Djava.security.egd=file:/dev/./urandom` to CHE `JAVA_OPTS` to avoid this

**Pull request merged**
