### PR TITLE
[WIP] Set screen size in the selenium chrome node to 1920x1080

### PR DESCRIPTION
**Pull request by dmytro-ndp**
### What does this PR do?
Sets screen size in the selenium chrome node to 1920x1080

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/7602

### CODE REVIEW

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by skabashnyuk** [comment]
What for?
Maybe 1920x1080?

**Comment by skabashnyuk** [comment]
here https://github.com/eclipse/che/issues/7602 asked about 1920x1020
So what is the decision?

**Comment by dmytro-ndp** [comment]
@skabashnyuk: good catch! It was a typo in description of pull request. It definitely should be 1080 in height.

**Review by tolusha — APPROVED** [review]

**Pull request merged**
