### PR TITLE
Fix Keycloak email template

### PR DESCRIPTION
**Pull request by mkuznyetsov**
Signed-off-by: Mykhailo Kuznietsov <mkuznets@redhat.com>

### What does this PR do?
Fix broken template for Keycloak verification emails 

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/13917

### CODE REVIEW

**Comment by skabashnyuk** [comment]
Can you add preview example?

**Comment by mkuznyetsov** [comment]
Preview on Gmail - the image is not being rendered, as apparently Gmail doesn't support SVG images for that

Screenshot from 2019-07-26 11-58-42

**Comment by skabashnyuk** [comment]
@slemeur we fixed in general problems with styles. however, I would not tell that this email looks amazing. WDYT do we need to invest time making this email templates prettier for GA? I would say - no.

**Comment by slemeur** [comment]
No, it does not have to be fancy for the GA. Can you create an issue to improve style of emails. We could involve UX team on it. (cc @beaumorley)

**Comment by skabashnyuk** [comment]
@rhopp @nickboldt please up vote

**Comment by skabashnyuk** [comment]
@eclipse/eclipse-che-qa can you check if the result of crw-ci-e2e-happy-path-test is fail-positive or not?

**Comment by mkuznyetsov** [comment]
ci-test

**Review by skabashnyuk — APPROVED** [review]

**Comment by artaleks9** [comment]
Selenium tests execution on Eclipse Che Multiuser on OCP (https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1956/) doesn't show any regression against this Pull Request.

**Comment by skabashnyuk** [comment]
@artaleks9 I was talking about crw-ci-e2e-happy-path-test  ?

**Comment by skabashnyuk** [comment]
@rhopp @nickboldt @l0rd  @benoitf  please upvote

**Review by benoitf — APPROVED** [review]

**Pull request merged**
