### PR TITLE
CHE-4307: Keep debug line marked despite file modification

### PR DESCRIPTION
**Pull request by tolusha**
### What does this PR do?
Remove mark before file is modified and add mark on the same line when modification has been done.

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/4307

#### Changelog
Fixed bug that made debug breakpoint markings inaccurate in some cases.

#### Release Notes
not required

#### Docs PR
not required

### CODE REVIEW

**Comment by tolusha** [comment]
```
[TEST]
[TEST] RESULTS ANALYSE:
[TEST]
[TEST] Command line: ./webdriver.sh --suite=Debugger.xml --threads=5
[TEST]
[TEST] CI results https://ci.codenvycorp.com/view/qa/job/che-integration-tests/273/
[TEST] 	- Failed:    27 (unique tests)
[TEST]
[TEST] Local results:
[TEST] 	- Run: 	     10
[TEST] 	- Failed:     0
[TEST]
[TEST] Comparing with https://ci.codenvycorp.com/view/qa/job/che-integration-tests/273/
[TEST] If a test failed then it is NOT marked as regression.
[TEST]
[TEST] NO REGRESSION! NO FAILED TESTS, GREAT JOB!
[TEST]
[TEST]
```

**Comment by dmytro-ndp** [comment]
@tolusha: which tests were included into Debugger.xml ?

**Comment by tolusha** [comment]
```
            <class name="com.codenvy.ide.debugger.ChangeVariableWithEvaluatingTest"/>
            <class name="com.codenvy.ide.debugger.StepIntoStepOverStepReturnWithChangeVariableTest"/>
            <class name="com.codenvy.ide.debugger.CheckBreakPointStateTest"/>
            <class name="com.codenvy.ide.debugger.InnerClassAndLambdaDebuggingTest"/>
            <class name="com.codenvy.ide.debugger.MultimoduleProjectDebuggingTest"/
```

**Comment by dmytro-ndp** [comment]
Thank you.
It would be reasonable to test debugging of other project types as well, that is PHP, NodeJs and C++ (last with privileged mode = true).
Could you, please, check this fixup by using all tests from the package **com.codenvy.ide.debugging.***?

**Review by bmicklea — APPROVED** [review]

**Comment by dmytro-ndp** [comment]
Better, but IMHO is not as good as expected:
out

**Review by dmytro-ndp — APPROVED** [review]

**Comment by tolusha** [comment]
```
[TEST]
[TEST] RESULTS ANALYSE:
[TEST]
[TEST] Command line: ./webdriver.sh --test=com.codenvy.ide.debugger.*
[TEST]
[TEST] CI results https://ci.codenvycorp.com/view/qa/job/che-integration-tests/273/
[TEST] 	- Failed:    27 (unique tests)
[TEST]
[TEST] Local results:
[TEST] 	- Run: 	     16
[TEST] 	- Failed:     2
[TEST] 	com.codenvy.ide.debugger.CppProjectDebuggingTest.shouldDebugCppProject
[TEST] 	com.codenvy.ide.debugger.CppProjectDebuggingTest.shouldRemoveGdbDebugConfig
[TEST]
[TEST] Comparing with https://ci.codenvycorp.com/view/qa/job/che-integration-tests/273/
[TEST] If a test failed then it is NOT marked as regression.
[TEST]
[TEST] REGRESSION (2):
[TEST] 	com.codenvy.ide.debugger.CppProjectDebuggingTest.shouldDebugCppProject
[TEST] 	com.codenvy.ide.debugger.CppProjectDebuggingTest.shouldRemoveGd
```

**Review by mmorhun — APPROVED** [review]

**Comment by dmytro-ndp** [comment]
@tolusha: I have found a regression: breakpoints became inaccessible in editor after refresh of page:
out

**Comment by tolusha** [comment]
@dmytro-ndp 
It seems regression.
```EditorAgent.getActiveEditor```
return null;

**Comment by bmicklea** [comment]
@tolusha this is in 5.12, right?  Can you set the milestone please?

**Comment by tolusha** [comment]
Issue isn't fixed.
New PR is required.

**Pull request closed without merging**
