### PR TITLE
Use che-bot GitHub token when starting minishift to prevent GitHub AP…

### PR DESCRIPTION
**Pull request by rhopp**
…I rate limit errors

Signed-off-by: Radim Hopp <rhopp@redhat.com>

### What does this PR do?
In our testing jobs we are facing with `API rate limit exceeded` when starting minishift.
This PR should solve this (according to this: https://github.com/minishift/minishift/blob/master/docs/source/troubleshooting/troubleshooting-getting-started.adoc#github-api-rate-limit-exceeded)

Before merging this PR it would be great to have job config change merged first (https://gitlab.cee.redhat.com/service/app-interface/merge_requests/3088)

### CODE REVIEW

**Comment by benoitf** [comment]
hello, should we use another github token to let more free slots to che-bot token that is also provides special stuff for che repositories while any github token may work for this case ?

**Comment by rhopp** [comment]
crw-ci-test

**Comment by rhopp** [comment]
@benoitf Do we have any other user that we can use here?

**Comment by benoitf** [comment]
@rhopp I have no idea :-(

**Comment by rhopp** [comment]
[test]

**Comment by rhopp** [comment]
@benoitf I've added a logic to **not use** che-bot token if its current remaining API calls limit is lower then 1000. I hope this solution could be acceptable even when using che-bot token.

**Comment by rhopp** [comment]
[test]

**Review by musienko-maxim — APPROVED** [review]

**Pull request merged**
