### PR TITLE
[WIP] Support PerWorkspacePVCStrategy.

### PR DESCRIPTION
**Pull request by monaka**
### What does this PR do?

Adds new PVC strategy for Kubernetes infrastructure.

### What issues does this PR fix or reference?

#12024

#### Release Notes

Added new PVC strategy named `PerWorkspacePVCStrategy`

#### Docs PR

Not yet. Should be written until this PR is merged.

### CODE REVIEW

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by monaka** [comment]
I checked this code on my workspace (not automated tests).
PV was created as expected. And it was deleted by deleting the workspace.

**Comment by skabashnyuk** [comment]
ci-test

**Review by garagatyi — COMMENTED** [review]
Overall looks good. 
Can you elaborate on what should be done to remove WIP state?
It would be great to have docs about this strategy here https://github.com/eclipse/che/blob/fa2a2dffeb77800aa7c6b0b119c771a0b6d6a37f/assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties#L398-L417
Am I correct that it suppose to work with single pod workspaces only?

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1273/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1273//Selenium_20tests_20report/)
docker image: eclipseche/che-server:12032
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by skabashnyuk** [comment]
@monaka what is your plan for this pr? How we can help you to get it merged?
FYI until it's wip we can't merge it.

**Comment by skabashnyuk** [comment]
ci-build

**Comment by l0rd** [comment]
@skabashnyuk we need to add the documentation for that strategy as suggested https://github.com/eclipse/che/pull/12032#pullrequestreview-181706016

**Comment by sleshchenko** [comment]
Also, It would be nice to add unit tests since other PVC strategies have them.

**Comment by skabashnyuk** [comment]
>@skabashnyuk we need to add the documentation for that strategy as suggested #12032 (review)

If @monaka didn't mind we will do that in separate PR. Just want to make sure we are not duplicating efforts.

**Comment by sleshchenko** [comment]
Work is continued in https://github.com/eclipse/che/pull/12176

**Comment by monaka** [comment]
@sleshchenko Thank you for your improvement!

**Pull request closed without merging**
