### PR TITLE
Pair programming plugin

### PR DESCRIPTION
**Pull request by rnavagamuwa**
### What does this PR do?

This PR adds the pair programming feature for Eclipse che.
### New Behavior

This content may also be included in the release notes.
### Tests written?

No
### To make the demo up and running:
1. Select custom stack **FLUX** from stacks library.
2. Create a project.
3. Run the custom command **flux**
4. Open a file to edit
5. Open a new browser windows to the same workspace, open the same file to edit

**[Documentation](https://docs.google.com/document/d/1hubCWTZ3uS0JVFBvgU5IG6HAlxc2Prap7u7HKcAyGOM/edit?usp=sharing)**

**[Demo](https://www.youtube.com/watch?v=OZNceE-sWto)**

### CODE REVIEW

**Comment by TylerJewell** [comment]
We should start gathering a set of requirements on what will be needed to improve in order for this PR to be accepted and placed into the core project.

My initial thoughts:
1. We need to see the dockerfile that you use as a base for the workspace.
2. Please document all of the non-standard software installed into the workspace that you requrie.
3. We may want to talk a little to @tolusha about packaging up some of the post-ws software into an agent, which is a new concept. Users will be allowed to "add an agent" to a ws, which will be software that can run inside. Maybe "pair-programming" would be the agent here.
4. Any sense of disk and memory requirements for running the system?

**Comment by TylerJewell** [comment]
@rnavagamuwa @sunix - the technical team leads for Che and some of the product managers would like to get a meeting to present a demo, get some screen shots, and to discuss the longer term technology requirements necessary to get these changes committed into the system.  Can we arrange a meeting for 6am pacific one day during an upcoming week?  We will create a google hangout that lets us all share screens together.  Can you propose a couple days that may work for you?

**Comment by rnavagamuwa** [comment]
@TylerJewell I'm fine with any day.Will have to check with @sunix

**Comment by TylerJewell** [comment]
I made a proposal for next Monday.  Here is the google hangout link.  I hope this can work for everyone.
https://plus.google.com/hangouts/_/codenvy.com/tjewell?hceid=dGpld2VsbEBjb2RlbnZ5LmNvbQ.im9k75jimfljt8c2g9tfl2j6bs&authuser=0

**Comment by rnavagamuwa** [comment]
@TylerJewell is it possible for you to have this on next Tuesday? I'm okay with any day except next Monday. Sorry I couldn't mention this earlier. :disappointed:

**Comment by TylerJewell** [comment]
Yes - no problem!

Tyler Jewell | CEO | tyler@​codenvy.​com | 9​78​.8​84​.53​55

**Comment by shadowcodex** [comment]
Does it look like this is going to get merged in any time soon?

**Comment by TylerJewell** [comment]
It's hard to determine the time it takes for merge.  Given the first review of the work, there are about 6 or so improvements that need to be made.

**Comment by TylerJewell** [comment]
@rnavagamuwa - we are doing the merge tomorrow for the new stack / workspace / agent model into the master branch.  It will take us a couple days to settle everything down.  If you can then merge your changes with that branch and work with @tolusha on how to package up your work as an agent, then I think this will be the important step to take forward.

**Comment by rnavagamuwa** [comment]
@TylerJewell sure. I'll merge the new changes and then work with @tolusha on packaging. :+1:

**Comment by shadowcodex** [comment]
@TylerJewell understand completely. I'm just excited to see this coming, I've been waiting for this feature since initial release. Thank you @rnavagamuwa for this pull request.

**Comment by sunix** [comment]
Guys, I'm going to rework this PR
- rebasing all the changesets
- make it work with 5.0.0-M1-SNAPSHOT

@rnavagamuwa could you give me push rights on your forked branch ?
@rnavagamuwa i let you know but i will probably make nasty push force

**Comment by rnavagamuwa** [comment]
@sunix I gave you push rights :smile:  I'm also working on moving code base to CHE 4.5. :+1:

**Comment by bmicklea** [comment]
@sunix @rnavagamuwa is this ready for review?  Or are more changes needed to bring it up to 5.x version?

**Comment by rnavagamuwa** [comment]
@bmicklea yes this is ready for review.

**Comment by bmicklea** [comment]
@skabashnyuk who should review this one?

**Comment by TylerJewell** [comment]
@bmicklea - this is not ready for review or merge. We need to have the pair plugin packaged as a non-default agent.  We have published instructions on that, and asked @sunix for a meeting to discuss path to get that closed + resolved.  We need to help with that migration + conversion.

**Comment by bmicklea** [comment]
Thanks for the clarification, @sunix is there an issue for the packaging work that can be tracked?

**Comment by shadowcodex** [comment]
@TylerJewell is this going to replace the workflow that Sun Tan is going to discuss at checonf2016 using eclipse flux?

**Comment by TylerJewell** [comment]
Sun tan's workflow and this project are the same project.

**Comment by shadowcodex** [comment]
I'm going to be working on adding OT to flux. Will have to modify the orion plugin as well to make it work right. Should we add that to this PR or a separate one later?

#3080

**Comment by TylerJewell** [comment]
I believe that @sunix is planning to productize this PR over the next couple months, including looking at having multiple backbones beyond flux as well.  You guys should connect to discuss strategies - having a true OT engine would be awesome.  I think there was an open source OT engine out there somewhere, but I cannot remember what its name is.

**Comment by shadowcodex** [comment]
@sunix @TylerJewell is this going into the 5.0 release? I didn't see it on the announcement in the forums.

**Comment by TylerJewell** [comment]
No - it will not make it into 5.0 milestone.  There is a lot of performance hardening that needs to be done.  @sunix is targeting it for early part of 2017.

**Comment by bmicklea** [comment]
Hi @sunix - any update on this pull request - it's highly anticipated!  :)

**Comment by TylerJewell** [comment]
Thank you @rnavagamuwa @sunix for the contribution.  We have learned a lot from this submission.  We have refactoring a number of communication systems to use JSON-RPC and we have a new file system watcher that would make notifications and implementation of such a system more efficient.  We are going to close this PR to work on this alternative approach.

**Comment by bs-matil** [comment]
Could the alternative approach be expected as part of che later this year?

**Comment by TylerJewell** [comment]
It is software so it is hard to offer any concrete timeframes.  We keep the list of epics actively being worked on by a community engineer updated in the roadmap located in the project wiki.

Tyler

**Comment by nterray** [comment]
Hello,

I do not see mention of pair programming in the roadmap. Is it labelled differently or do you plan to add the item in the roadmap later on?

**Comment by TylerJewell** [comment]
It is an open source project so we update the roadmap with all epics that have been reserved or committed to by a contributor in the ecosystem.

The maintainers have agreed upon an architecture and approach but it is not added to the roadmap until someone commits to working on it with a pr.  So it is open for anyone to grab right now.

Tyler

**Comment by bs-matil** [comment]
Also I would love to have a look on the architecture. Is it documented somehow=

**Comment by rektide** [comment]
> It is an open source project so we update the roadmap with all epics that have been reserved or committed to by a contributor in the ecosystem.
> 
> The maintainers have agreed upon an architecture and approach but it is not added to the roadmap until someone commits to working on it with a pr.  So it is open for anyone to grab right now.

It'd be super handy to have a Github issue to track for this effort. There's #4474, so that might be a good issue to track.

On another note, I also really like that #4474 doesn't specify a number of users who are collaborating together. Having one person make changes & having those changes show up on someone else's workspace immediately is 96% of what I'm looking forward to, and want for collaboration mechanisms.

**Comment by TylerJewell** [comment]
So, it's possible today to have multiple users in a shared workspace with Che. You can give each user the same URL and they can work within that workspace. It's a last-write wins scenario, but their changes are made to a shared file system and the updates (eventually) appear on each others screen. There is no operational transform, however, and there is not multi-cursor editing where you can see the other person typing as they type. So the UX and behavior is not as you might expect, but there is a form of shared space capability in the product as it is designed today.

I think the engineer / community member that commits to doing the proper implementation will need to write a new specification as an epic replacing #4474. We tend not to have really good detailed specifications on a project until an engineer is full time committed to it.  But the basic approach for the design of this is to make use of a number of server-side file-system watchers that we have built into our workspace agents on the server side to generate efficient events to let us build multi-cursor editing into different browsers sharing a common workspace.

**Comment by rektide** [comment]
> I think the engineer / community member that commits to doing the proper implementation will need to write a new specification as an epic

Perhaps an existing collaborative editing spec or project might work well for Che. Some candidates:

- [TogetherJS](https://togetherjs.com)
- [Gobby's Infinote Protocol](https://github.com/gobby/libinfinity)
- [Atom's Teletype](blog.atom.io/2017/11/15/code-together-in-real-time-with-teletype-for-atom.html) ([very limited](https://github.com/atom/teletype/issues/211) solution atm)
- [Mobwrite](https://code.google.com/archive/p/google-mobwrite/wikis/Protocol.wiki)
- [ShareJS](https://github.com/josephg/ShareJS)
- [ot.js](https://github.com/Operational-Transformation/ot.js/)

**Pull request closed without merging**
