### PR TITLE
Use keyclock token in case MultiUser assembly for SSH Key Uploading

### PR DESCRIPTION
**Pull request by vparfonov**
Signed-off-by: Vitalii Parfonov <vparfonov@redhat.com>

### What does this PR do?
Use keyclock token in case MultiUser assembly for SSH Key Uploading

### What issues does this PR fix or reference?
#11574

### CODE REVIEW

**Comment by vparfonov** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1044/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1044//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11702
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by vparfonov** [comment]
ci-test

**Review by skabashnyuk — APPROVED** [review]

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1047/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1047//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11702
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Review by RomanNikitenko — APPROVED** [review]

**Pull request merged**
