### PR TITLE
Simplify Dashboard build by relying on NPM run-script

### PR DESCRIPTION
**Pull request by akervern**
### What does this PR do?
It simplify NPM dependencies install, and no more require to globally install `typings`, `bower` by relying on run-script env.

### Previous behavior
Required to install several NPM dependencies as global.

### New behavior
Binary location are handled per NPM using local installation; it helps keeping the expected version installed defined in `package.json` file.

### Docs :
https://github.com/codenvy/che-docs/pull/79

### Release Note :
- [x] Added to release note (other enhancement + community PR)

#### Changelog
Simplify Dashboard build by relying on NPM run-script

### CODE REVIEW

**Review by benoitf — APPROVED** [review]

**Comment by benoitf** [comment]
ci-build

**Review by akurinnoy — APPROVED** [review]

**Review by ashumilova — APPROVED** [review]

**Review by olexii4 — APPROVED** [review]

**Comment by slemeur** [comment]
@benoitf thanks a lot for your associated PR for docs. 
Should we update this page: https://github.com/eclipse/che/blob/master/dashboard/README.md too ? 

Added to release note

**Comment by benoitf** [comment]
@slemeur https://github.com/eclipse/che/pull/3829

**Comment by slemeur** [comment]
(smiley_applause) ! 
Excellent! LGTM with milestone 5.2.0

**Review by slemeur — APPROVED** [review]

**Comment by benoitf** [comment]
@akervern thanks, it's now merged

**Comment by akervern** [comment]
✨

**Pull request merged**
