### PR TITLE
CHE-180: Creating and closing OpenShiftClient in every method of Open…

### PR DESCRIPTION
**Pull request by ibuziuk**
### What does this PR do?
Potential fix for https://issues.jboss.org/browse/CHE-180

### What issues does this PR fix or reference?
https://issues.jboss.org/browse/CHE-180

### Docker image
ibuziuk/che-server:closeable - https://hub.docker.com/r/ibuziuk/che-server/tags/

### CODE REVIEW

**Comment by ibuziuk** [comment]
@amisevsk @l0rd please review the code meticulously (formatting was really monotonous task, so I might made some typos)

**Comment by ibuziuk** [comment]
Seems to work fine so far on minishift locally, trying on free-int now

**Review by amisevsk — APPROVED** [review]
LGTM. I've tested the changes and it looks like everything works.

I'm still worried about the overhead of starting so many instances of OpenShiftClient, but this is a lot better than the IOExceptions we were facing before.

**Comment by ibuziuk** [comment]
@amisevsk I believe there is no need to worry about creating many instances of client. OpenShift client should be treated as DB connection IMO - it implements Autocloseabe interface and must be closed once the operation on cluster is finished (the good think that in comparison with DB connection, creating OpenShift client is a "cheap" operation) One thing I notice, if OpenShift connector is created in method and not closed there will be warning - `Resource leak 'openShiftClient' is never closed`

**Review by l0rd — APPROVED** [review]
I confirm that I could not get any "Error while pumping stream". 

And it has no impact on performances: I've started a workspace locally with and without this patch and it takes 1'42'' in both cases :-)

**Comment by ibuziuk** [comment]
@l0rd awesome! shall we merge ?

**Comment by l0rd** [comment]
Unfortunately it does not work on OSO but we figured out that the we couldn't deploy older versions neither. We can exclude that's a regression then and let's merge it!

**Pull request merged**
