### PR TITLE
Added dirigible server to liveness probes list

### PR DESCRIPTION
**Pull request by skabashnyuk**
### What does this PR do?
After pr https://github.com/eclipse/che-plugin-registry/pull/54 introduced new Che Editor.
This pr is adding dirigible to liveness probes checklist. Server configured here https://github.com/dirigiblelabs/dirigible-che-editor-plugin/blob/master/etc/che-plugin.yaml#L9

#### Release Notes
n/a

#### Docs PR
n/a

### CODE REVIEW

**Review by sleshchenko — APPROVED** [review]

**Comment by skabashnyuk** [comment]
ci-test

**Comment by benoitf** [comment]
IMHO it looks odd that we need to update Che binary when a plug-in is added

**Comment by benoitf** [comment]
IMHO, as the editors plug-ins are providing "Editors" it should be automatically added to probes

**Comment by skabashnyuk** [comment]
@benoitf you 100% right and we have an issue for that https://github.com/eclipse/che/issues/10273

**Comment by benoitf** [comment]
@skabashnyuk thx, miss that issue !

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1134/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1134//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11829
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by skabashnyuk** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1137/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1137//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11829
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by skabashnyuk** [comment]
@eclipse/eclipse-che-qa can you take a look?

**Comment by artaleks9** [comment]
Selenium tests execution on Eclipse Che Multiuser on OCP (https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1137) doesn't show any regression against this Pull Request.

**Pull request merged**
