### PR TITLE
Fix e2e dashboard create workspace page objects

### PR DESCRIPTION
**Pull request by olexii4**
Signed-off-by: Oleksii Orel <oorel@redhat.com>

### What does this PR do?
Fix e2e dashboard create workspace page objects.

### What issues does this PR fix or reference?

It is needed for https://github.com/eclipse-che/che-dashboard/pull/252

### CODE REVIEW

**Review by sleshchenko — APPROVED** [review]

**Review by dmytro-ndp — APPROVED** [review]

**Comment by artaleks9** [comment]
@olexii4 
* Unfortunately, it was incorrect fix up. 'Happy-path' E2E test passed, because doesn't use 'CreateWorkspace' page object ('happy-path' test workspace is creating using CLI command).
* So when the 'JavaMaven' devfile E2E test tried to use 'CreateWorkspace' page object, it got error (this is 'che-nightly' job launch):
```
1) Java Maven test
07:31:53         Create Java Maven workspace
07:31:53           Open 'New Workspace' page:
07:31:53       TimeoutError: Exceeded maximum visibility checkings attempts for 'By(xpath, //h1[contains(text(), 'Quick Add')])' element, timeouted after 20000
```
* See the screenshot below.
I guess, or should fix up locator to button 'Quick Add', or should be other title - not 'Create Workspace' :)

quick-add-locator

**Comment by artaleks9** [comment]
* Or should revert it, if the title doesn't change - 'Create Workspace', which is on the right.
dashboard-create-ws

**Comment by sleshchenko** [comment]
@artaleks9 seems e2e used the old dashboard, because now we have the following:
Screenshot_20210531_163722

**Comment by sleshchenko** [comment]
Also note that title will be reverted to Create Workspace and there is a dedicated issue for that https://github.com/eclipse/che/issues/19890

**Comment by artaleks9** [comment]
@sleshchenko 
I see, E2E tests also are passing now.
Thanks for explanation.

So to be clear - now the title is changed depend on the which button is clicked - _Quick Add_ or _Custom Workspace_.
And the goal of the #19890 is to fix the title to _Create Workspace_, what requires changes in two places: 
- dashboard
- e2e tests - locator of page object.
Correctly?

**Pull request merged**
