### PR TITLE
CODENVY-1749: add possibility to set dns resolvers

### PR DESCRIPTION
**Pull request by garagatyi**
### What does this PR do?
Add possibility to set DNS resolving servers.
If Che is set to use custom DNS that is resolvable using custom DNS resolving server admin should set env var: **CHE_DNS_RESOLVERS**
It may contain several values in comma-separated format, e.g. 
```
CHE_DNS_RESOLVERS=10.10.10.10,8.8.8.8
```

### What issues does this PR fix or reference?
Related to codenvy/codenvy#1749

#### Changelog
Add possibility to set custom DNS resolvers for workspace **(master too)** container runtimes.

#### Release Notes
We now let you override the default DNS resolvers used by Che and you workspace runtimes. The default behavior is for Che and workspaces to inherit DNS resolution from the host. You can add `CHE_DNS_RESOLVERS=<ip-list>` to `che.env` to customize how DNS resolution will occur within the Che server and workspace containers. Services such as agents and servers running within Che workspaces will usually require custom DNS resolution when there are internal providers behind a proxy or firewall.

#### Docs PR
https://github.com/eclipse/che-docs/pull/139

### CODE REVIEW

**Comment by garagatyi** [comment]
@bmicklea @eivantsov @JamesDrummond Please review.

**Comment by TylerJewell** [comment]
Let's change it to be CHE_DNS_RESOLVERS inside of che.env.

If you can provide an explanation of what this does (or when an admin would need to configure this) then I can write release notes and identify docs changes that are needed.

Is there a matching codenvy PR?

**Comment by TylerJewell** [comment]
@garagatyi - I will review this - this will not need @bmicklea or @JamesDrummond review.

**Review by riuvshin — APPROVED** [review]
LGTM from configuration point of view

**Comment by JamesDrummond** [comment]
I think this needs docs. I created PR for docs that is in review.

**Comment by TylerJewell** [comment]
@JamesDrummond - the dock PR links to a che PR - it's not a docs PR.

I am not sure this requires docs - we don't document every configuration property in or docs.

**Comment by garagatyi** [comment]
@TylerJewell I updated env variable name. Also I added my comments for docs in bold, please take a look.

**Review by skabashnyuk — APPROVED** [review]

**Comment by garagatyi** [comment]
Also not all the parts of the system inherit DNS resolution rules from host. Nginx container doesn't respect that and use 8.8.8.8 for dns resolution. So user might be surprised if **by default** we inherit from host but WSs don't start because of Nginx.

**Comment by garagatyi** [comment]
@JamesDrummond If you still need docs please use my comments from this PR to change explanation in your PR.

**Review by riuvshin — APPROVED** [review]

**Comment by garagatyi** [comment]
@riuvshin I had to rework PR, so now empty string is used instead of NULL. It is needed because Java code can't interpret NULL as empty array

**Review by TylerJewell — APPROVED** [review]

**Review by riuvshin — APPROVED** [review]

**Comment by garagatyi** [comment]
@TylerJewell please take a look at release notes. I added my comments into it.

**Comment by TylerJewell** [comment]
Ok for you to merge.  I can fix release notes after merge when have time to review.

**Comment by JamesDrummond** [comment]
@TylerJewell I updated the docs PR link. I somehow copied the wrong url. I think documentation on this would be helpful to those evaluating the product features.

@garagatyi What is `master` that you refer to above?

**Comment by garagatyi** [comment]
@JamesDrummond I meant ws-master aka che-server

**Comment by JamesDrummond** [comment]
@garagatyi I rewrote the docs to include che server. https://github.com/eclipse/che-docs/pull/139/files#diff-ba9f2804ca5dc20e010ba41f64ef1cac . Please review.

**Comment by TylerJewell** [comment]
I updated the release notes based upon @garagatyi comments

**Pull request merged**
