### PR TITLE
test: Add workspace readiness function for devworkspace tests

### PR DESCRIPTION
**Pull request by SkorikSergey**
### What does this PR do?
We are using `waitWorkspaceReadiness` function in our tests for checking workspace starting, checking notifications and project importing. This PR adds devworkspace specific `waitWorkspaceReadinessDevworkspace` function. 

Also this function collapses `Open Editor` window(see screenshot). Some test projects has many files and we need to collapse `Open Editor` to make them visible.

Changes were added and checked on `TypescriptPlugin` and `VscodeYamlPlugin` tests.

### Screenshots
screenshot-Open_file (1)

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [ ] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [ ] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [ ] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix or new feature ](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix-or-new-feature)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Review by artaleks9 — APPROVED** [review]

**Comment by dmytro-ndp** [comment]
@SkorikSergey: do we really need to keep `waitWorkspaceReadiness()` in parallel to `waitWorkspaceReadinessDevworkspace()`?

**Comment by SkorikSergey** [comment]
@dmytro-ndp We are still using waitWorkspaceReadiness in `old` tests. It will take too much time to adapt everything. For now I need this fix to stabilize tests.

**Comment by dmytro-ndp** [comment]
@SkorikSergey:  I see.

So that `main` branch is testing Eclipse Che next only, I am curious which old test using `waitWorkspaceReadiness()` is running successfully against Eclipse Che Next?

**Comment by SkorikSergey** [comment]
They are still exits :)

**Review by dmytro-ndp — APPROVED** [review]
LGTM

**Pull request merged**
