### PR TITLE
Allow multiple devfile registries to be specified

### LINKED ISSUE #13961: Allow multiple devfile registries to be added to che
### Is your enhancement related to a problem? Please describe.
At the moment, the dashboard references a single location from where it gets it devfiles from.  In our case, we would like to add additional devfile registries so that we can can deploy che with the blessed set and also our additional set.

### Describe the solution you'd like
In che.properties, the current implementation sets 

```
che.workspace.devfile_registry_url=https://che-devfile-registry.openshift.io/
```
This could be enhanced to take multiple urls which would then be processed in devfile-registry.factory.js when fetching the devfile

### Describe alternatives you've considered
Another option could be having the existing https://che-devfile-registry.openshift.io/ pull in other repositories but this would be clumsy imo and hard to maintain

### PR DESCRIPTION
**Pull request by stalleyj**
### What does this PR do?
This PR allows multiple devfile registries to be specified as a space separated list, for example in values.yml we can have:-
che: 
  workspace: 
    devfileRegistryUrl: "https://che-devfile-registry.openshift.io/ https://raw.githubusercontent.com/kabanero-io/codewind-templates/master/"

The registry location is then stored so that the devfile can be read from the correct location.

### What issues does this PR fix or reference?

Fixes https://github.com/eclipse/che/issues/13961

### CODE REVIEW

**Comment by musienko-maxim** [comment]
Can one of the admins verify this PR?

**Comment by nickboldt** [comment]
@stalleyj Are you able to fill out a contributor agreement?

https://www.eclipse.org/legal/ECA.php

Eclipse projects require this level of bla bla due diligence so we know YOU wrote the code, etc.

**Comment by stalleyj** [comment]
@nickboldt Contributor agreement has been signed https://accounts.eclipse.org/users/jstalley/eca

**Comment by stalleyj** [comment]
Sorry, couldn't amend the commit to be signed successfully so I have raised a new PR here https://github.com/eclipse/che/pull/14059

**Pull request closed without merging**
