### PR TITLE
Fixup SCM URL matching sometimes fails

### PR DESCRIPTION
**Pull request by mshaposhnik**
### What does this PR do?
It is reported that sometimes user secrets containing SCM tokens are ignored. Investigation showed that SCM URL-s in factory and in secrets compared directly, wichi is not good, since them may differ by trailing slash. This PR fixes the situation and 
now URls are compared without the influence of the trailing slash 

PS. During testing, PAT validation bug  for GitLab found. So it is fixes this bug as well.

### How to test this PR?
1) Create new/edit existing secret with the personal access token, containing `scm-url` annotation with trailing slash, as follows:

```
che.eclipse.org/scm-url: 'https://gitlab.apps.cluster-max-fbfa.max-fbfa.example.opentlc.com/'
```
 2) Run the private GitLab project factory from that server. Error in accessing devfile will be shown. 
 3) Deploy che server image `quay.io/skabashn/che-server:che19752`
 4) After the fix, the factory should run without an error.

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by artaleks9** [comment]
[crw-ci-test --rebuild]

**Review by amisevsk — APPROVED** [review]

**Comment by sparkoo** [comment]
Is there a test that verifies that secret with slash matches the url without slash and vice versa? If not, can you please write such test?

**Comment by mshaposhnik** [comment]
I have adapted existing test to take this case in account

**Review by sparkoo — APPROVED** [review]

**Review by skabashnyuk — APPROVED** [review]
Tested with Bitbucket
Знімок екрана 2021-05-13 о 11 50 17
With  slashes in git-secrets
Знімок екрана 2021-05-13 о 11 49 12
with slashes in personal access token
Знімок екрана 2021-05-13 о 11 50 33

**Pull request merged**
