### PR TITLE
Update stacks.json to Refer to Eclipse Dockerhub Repository

### PR DESCRIPTION
**Pull request by JamesDrummond**
### What does this PR do?
Che docker image references to codenvy repository is changed to associated eclipse repository.

### What issues does this PR fix or reference?
Che dockerfiles should be located under the eclipse foundation Docker repository.

### CODE REVIEW

**Comment by JamesDrummond** [comment]
Reference issue https://github.com/eclipse/che/issues/2942

**Comment by skabashnyuk** [comment]
ci-build

**Comment by riuvshin** [comment]
@vparfonov @eivantsov please review

**Comment by AndrienkoAleksandr** [comment]
@JamesDrummond you changed codenvy/mysql to eclipse/mysql but we have not in the dockerHub in the repository eclipse such image...

**Comment by JamesDrummond** [comment]
@AndrienkoAleksandr Please get with @eivantsov to get codenvy/mysql image into eclipse/mysql .

**Comment by AndrienkoAleksandr** [comment]
Ok

**Comment by benoitf** [comment]
@JamesDrummond about custom mysql image I think merging https://github.com/eclipse/che/pull/3049 will allow to get rid of this custom mysql image

**Comment by bmicklea** [comment]
@JamesDrummond and @eivantsov - what's the status of this? Who needs to move this forward?

**Comment by JamesDrummond** [comment]
@bmicklea This issue is blocked until #3049 is fixed.

**Comment by JamesDrummond** [comment]
Refer to new PR https://github.com/eclipse/che/pull/3448

**Pull request closed without merging**
