### PR TITLE
Do not index files from File Index excludes

### PR DESCRIPTION
**Pull request by RomanNikitenko**
### What does this PR do?
- Do not index files from File Index excludes: 
   Current behavior: we do not add to index text field of files from File Index excludes
   New behavior: we do not add to index path, name and text fields of files from File Index excludes
- Do not index hidden files and folders

### What issues does this PR fix or reference?
#6948 

Signed-off-by: Roman Nikitenko <rnikiten@redhat.com>

### CODE REVIEW

**Comment by RomanNikitenko** [comment]
ci-test

**Comment by RomanNikitenko** [comment]
ci-test

**Comment by RomanNikitenko** [comment]
I've updated the PR - filter for hidden files was added

**Comment by RomanNikitenko** [comment]
ci-test

**Comment by RomanNikitenko** [comment]
ci-test

**Comment by RomanNikitenko** [comment]
ci-test

**Review by vparfonov — APPROVED** [review]

**Comment by RomanNikitenko** [comment]
ci-build

**Pull request merged**
