### PR TITLE
Add CentOS based minimal stack with only git to default assembly

### PR DESCRIPTION
**Pull request by dharmit**
### What does this PR do?
Add blank stack based on CentOS to the default assembly

#### Changelog

Add CentOS based minimal stack with git to default assembly

#### Release Notes

Add CentOS based minimal stack with git to default assembly

#### Note
Have rebased this on top of PR #4788 

cc @l0rd

### CODE REVIEW

**Comment by benoitf** [comment]
@dharmit could you rebase this one as well ? thanks

**Review by ghost — APPROVED** [review]

**Comment by dharmit** [comment]
@benoitf done.

**Comment by benoitf** [comment]
ci-build

**Comment by benoitf** [comment]
thx @dharmit

**Comment by benoitf** [comment]
ci-build

**Review by benoitf — APPROVED** [review]

**Review by slemeur — APPROVED** [review]

**Pull request merged**
