### PR TITLE
introduce CODEOWNERS

### PR DESCRIPTION
**Pull request by riuvshin**
### What does this PR do?
Introduce CODEOWNERS for CHE project

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/5593

#### Changelog
Introduce CODEOWNERS

### CODE REVIEW

**Comment by riuvshin** [comment]
Please note that there is some regexes which match multiple modules

**Review by TylerJewell — APPROVED** [review]

**Comment by riuvshin** [comment]
update: as we don't have adm permission in eclipse repos I've requested to enable "review policy" from webmaster

**Review by ashumilova — APPROVED** [review]

**Comment by benoitf** [comment]
BTW maintainers seem not to accurately represent the top contributors on the che project https://github.com/eclipse/che/graphs/contributors

**Comment by riuvshin** [comment]
@benoitf top contributors does not have any sense, because it counts only changed lines and commits count so anyone who will simply move things can become top contributor without any logic added :)

**Comment by garagatyi** [comment]
@benoitf I do think that number of commits of committed lines doesn't matter here

**Comment by benoitf** [comment]
so you are saying that someone that never commit to an open source project is handling the maintenance of this project ?

**Comment by benoitf** [comment]
IMOH it's not applying meritocracy.

**Comment by garagatyi** [comment]
I say that if someone merges 1 commit at a time it doesn't mean that he contributes less than someone who merges something and forgets to squash 100 fixups. If someone merges move of the file that git doesn't recognize as a move and thinks that it was a contribution of 2000 lines it doesn't mean that it was a really big contribution. So, statistics is just statistics

**Comment by benoitf** [comment]
@garagatyi yes but you didn't reply on: someone that almost never commit to an open source project could handle the maintenance of this project ?

**Comment by garagatyi** [comment]
I didn't reply because I didn't say that

**Review by vparfonov — APPROVED** [review]

**Pull request merged**
