### PR TITLE
Set public url for public keycloak endpoints

### PR DESCRIPTION
**Pull request by tolusha**
Signed-off-by: Anatolii Bazko <abazko@redhat.com>

### What does this PR do?
Keycloak of v6.0.1 and v7.0.1 versions behaviors differently.
- `6.0.1` return public urls independently if request to keycloak was done using public [1] or internal [2] urls
- `7.0.1` return internal urls (http://keycloak.eclipse-che.svc:8080/auth/...) if request was done using internal url [2]
This PR make sure that `OIDCInforProvier` stores public keycloak urls.

[1] https://github.com/eclipse/che/blob/9e4c4f1890e7a80dc403730edcbb4a5f6a85c480/multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/OIDCInfoProvider.java#L49
[2] https://github.com/eclipse/che/blob/9e4c4f1890e7a80dc403730edcbb4a5f6a85c480/multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/OIDCInfoProvider.java#L54

### What issues does this PR fix or reference?
https://issues.redhat.com/browse/CRW-1509

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Review by AndrienkoAleksandr — APPROVED** [review]

**Comment by dmytro-ndp** [comment]
@tolusha: about failure: https://github.com/eclipse/che/pull/19096#issuecomment-781348582 :
there is fix of Happy path tests outage in master branch.

**Comment by tolusha** [comment]
[crw-ci-test]

**Comment by tolusha** [comment]
@dmytro-ndp 
I've rebased on master but tests still fail

**Comment by tolusha** [comment]
[crw-ci-test --rebuild]

**Comment by tolusha** [comment]
[crw-ci-test]

**Review by mshaposhnik — APPROVED** [review]

**Review by skabashnyuk — APPROVED** [review]

**Comment by dmytro-ndp** [comment]
@tolusha: FYI: there is [new commit in master branch](https://github.com/eclipse/che/commit/3c7dbbd2edb53ccc8b66de5195964d660894a973), which has to stabilize PR Happy path tests.

**Pull request merged**
