### PR TITLE
[Keycloak] Fix bugs on the docker image.

### PR DESCRIPTION
**Pull request by monaka**
### What does this PR do?

Fix the container image for Keycloak to use Postgres instead of H2.

### CODE REVIEW

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by monaka** [comment]
I've just tested on Helm. I guess there have the similar issue on another runtimes. But I didn't touch them as I'm not familiar with them.

**Comment by monaka** [comment]
I believe this patch itself is sane. But I encountered the another issue around authentication with Che.
I suspect there doesn't have json.erb files required by Che in the Keycloak image.
Which is better, a or b?

(a) I send the additional PR after closed this as they are separated issues.
(b) I push additional patches to his PR because the aim of this PR is to fix deployment failure.

**Comment by skabashnyuk** [comment]
@monaka can you explain how changes you've made related to the topic of this pr? Especially commented lines in kc_realm_user.sh

**Comment by monaka** [comment]
Let me change the title and the aim for this PR. As I tweeted, I managed to run Che on AKS (managed vanilla Kubernetes). I'm going to add some more patches to here.

**Comment by monaka** [comment]
> What do you want to do?

Enable to run Che on vanilla K8s clusters.

> On wich environment? Docker, OpenShift, Kubernetes?

Kubernetes.
(Possibly Docker doesn't. Because it will use `init` container for bootstrapping.) 

> Which version of infrastructure?

Azure AKS 1.11.3.
But the issue will be reproduced all versions of K8s based infrastructure.

> Which version of Che?

master branch, nightly builds.

> What issues do you have with current codebase? Traces, logs?

- I can't see any tables in `keycloak` database on Postgres container.
- I can't see any tables in H2 for the `che` realm.

After fixing above, 

- There is no content for the custom login page.

**Comment by monaka** [comment]
Currently, `/opt/jboss/keycloak/bin/standalone.sh` is called directly on bootstrapping.
But it is required to use `/opt/jboss/docker-entrypoint.sh` if we want to use external DB.

**Comment by eivantsov** [comment]
@monaka thanks for fixing it. However, I do not understand why you copied jsons? it's ok to use them from where they are

**Comment by monaka** [comment]
Indeed it's not good to put same files into different places. But I couldn't resolve how to access JSONs in `init` container from `che-keycloak`. I'm afraid my patches cause side effects to Openshift and Docker deployments, even though it might resolve by some tricky patches to `init`.

**Comment by eivantsov** [comment]
@monaka it is ok to reuse jsons from init.

Just changing start script in the entrypoint should be enough, and you did that already

**Comment by monaka** [comment]
@eivantsov Who setups the realm for Che?

**Comment by eivantsov** [comment]
@monaka it happens in the entrypoint

**Comment by monaka** [comment]
Yes. In addition to patches here, we must add the patch to `depoyment/keycloak` like this.
I'm not sure I'm not familiar with Openshift. But I think this issue will be reproduced on it.

```
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        - name: DB_VENDOR
          value: POSTGRES
```

**Comment by musienko-maxim** [comment]
Can one of the admins verify this PR?

**Comment by monaka** [comment]
I close this as it have not been updated.

**Pull request closed without merging**
