### PR TITLE
fix a default stack

### PR DESCRIPTION
**Pull request by olexii4**
Signed-off-by: Oleksii Orel <oorel@redhat.com>

### What does this PR do?
Fix default stack: dd the default stack command type, because it is a mandatory field to create a factory.

screenshot from 2018-11-26 19-35-02

### CODE REVIEW

**Review by ashumilova — APPROVED** [review]

**Review by akurinnoy — APPROVED** [review]

**Comment by ashumilova** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1243/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1243//Selenium_20tests_20report/)
docker image: eclipseche/che-server:12051
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by slemeur** [comment]
Thanks @olexii4 !

**Review by benoitf — APPROVED** [review]

**Comment by benoitf** [comment]
FYI missing a 'a' in Add in github description

**Comment by olexii4** [comment]
done

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1246/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1246//Selenium_20tests_20report/)
docker image: eclipseche/che-server:12051
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Pull request merged**
