### PR TITLE
Adopt replace stacks script to multi user

### PR DESCRIPTION
**Pull request by riuvshin**
### What does this PR do?
Adopt replace stacks script to multi user

### CODE REVIEW

**Review by davidfestal — COMMENTED** [review]
This will work when the Keycloak dedicated server is deployed. But not when the OSIO Keycloak server is used instead (ie when `DEFAULT_CHE_KEYCLOAK_DISABLED` is `true` in `deploy_che.sh`).
Because I doubt we can connect as `admin/admin` to get the Keycloak token.

**Comment by riuvshin** [comment]
@davidfestal good point! will fix that!

**Comment by riuvshin** [comment]
@davidfestal Im a bit confused now, becuase https://github.com/eclipse/che/blob/che-multiuser/dockerfiles/init/modules/openshift/files/scripts/deploy_che.sh#L100-L101

```
if [ "${CHE_MULTI_USER}" == "true" ]; then
  DEFAULT_CHE_KEYCLOAK_DISABLED="false"
```

so if this is multi user it will always have `  DEFAULT_CHE_KEYCLOAK_DISABLED="false"`

**Comment by davidfestal** [comment]
> if this is multi-user it will always have DEFAULT_CHE_KEYCLOAK_DISABLED="false"

Oh, sorry, I was speaking of `CHE_DEDICATED_KEYCLOAK`.
of the case when you set this variable to `false` on the command line.

**Comment by benoitf** [comment]
on https://www.shellcheck.net/ I have multiple warnings on CHE_MULTIUSER (should be quoted)

**Comment by skabashnyuk** [comment]
PR for Che6?

**Comment by riuvshin** [comment]
as in CHE6 any stack should work on openshift we don't need this anymore.

**Pull request closed without merging**
