### PR TITLE
Regenerate dashboard/yarn.lock

### PR DESCRIPTION
**Pull request by monaka**
### What does this PR do?

Regenerates (update) `yarn.lock`.

### What issues does this PR fix or reference?

#12077 

#### Release Notes

N/A

#### Docs PR

N/A

### CODE REVIEW

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by benoitf** [comment]
ci-build

**Comment by benoitf** [comment]
ci-test

**Comment by benoitf** [comment]
thanks @monaka , now checking with CI jobs

**Comment by monaka** [comment]
Looks the CI build was failed in the unrelated part on this PR...

**Comment by benoitf** [comment]
ci-build

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1253/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1253//Selenium_20tests_20report/)
docker image: eclipseche/che-server:12078
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Review by benoitf — APPROVED** [review]

**Pull request merged**
