### PR TITLE
Update plugin brokers to version 3.1.0

### PR DESCRIPTION
**Pull request by amisevsk**
### What does this PR do?
Update plugin brokers to version 3.1.0. This update includes recently added caching functionality: https://github.com/eclipse/che-plugin-broker/pull/86

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/15470

### CODE REVIEW

**Review by sleshchenko — APPROVED** [review]
LGTM

Just to clarify: do you plan to merge it in 7.8.0 or 7.9.0?

**Comment by amisevsk** [comment]
I think it's safe to merge for 7.8.0 -- I don't think I've missed anything in testing these changes and don't want to leave the PR for a week.

**Comment by amisevsk** [comment]
ci-test

**Comment by amisevsk** [comment]
crw-ci-test

**Comment by amisevsk** [comment]
ci-test

**Pull request merged**
