### PR TITLE
FIX Typo "doesn't exists" -> "doesn't exist"

### PR DESCRIPTION
**Pull request by innovimax**
### What does this PR do?

Fix a typo in code, doc and comments

### What issues does this PR fix or reference?
none

### CODE REVIEW

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by skabashnyuk** [comment]
ci-test

**Comment by skabashnyuk** [comment]
ci-build

**Review by l0rd — APPROVED** [review]

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1283/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1283//Selenium_20tests_20report/)
docker image: eclipseche/che-server:12154
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by skabashnyuk** [comment]
@innovimax  can you squash all your commit to a single one? To pass ip-validation.

**Review by benoitf — APPROVED** [review]

**Comment by benoitf** [comment]
ci-build

**Pull request merged**
