### PR TITLE
[E2E typescript] Fix plugins adding

### PR DESCRIPTION
**Pull request by Katka92**
### What does this PR do?
Add possibility to add version to a plugin that should be added before workspace startup. The version is not mandatory.

### CODE REVIEW

**Comment by musienko-maxim** [comment]
Can one of the admins verify this PR?

**Review by Ohrimenko1988 — APPROVED** [review]

**Comment by Katka92** [comment]
ci-test

**Comment by SkorikSergey** [comment]
ci-test

**Comment by SkorikSergey** [comment]
Selenium tests execution on Eclipse Che Multiuser on OCP (https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1843//Selenium_20tests_20report/) doesn't show any regression against this Pull Request.

**Pull request merged**
