### PR TITLE
Check is thrown exceptions are ConflictException and throw it, to be sure we will get 409 response code in REST API

### PR DESCRIPTION
**Pull request by vparfonov**
Signed-off-by: Vitalii Parfonov <vparfono@redhat.com>

### What does this PR do?
Check is thrown exceptions are ConflictException and throw it, to be sure we will get 409 response code in REST API

### What issues does this PR fix or reference?

https://github.com/eclipse/che/issues/18383

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Review by sparkoo — APPROVED** [review]

**Review by ibuziuk — APPROVED** [review]

**Review by metlos — COMMENTED** [review]
Looks good as such, but I wonder if it didn't make more sense to have this kind of "exception analysis" in the https://github.com/eclipse/che/blob/master/core/che-core-api-core/src/main/java/org/eclipse/che/api/core/rest/ApiExceptionMapper.java#L34 so that we capture this kind of problem in other areas of the codebase as well.

**Comment by vparfonov** [comment]
> Looks good as such, but I wonder if it didn't make more sense to have this kind of "exception analysis" in the https://github.com/eclipse/che/blob/master/core/che-core-api-core/src/main/java/org/eclipse/che/api/core/rest/ApiExceptionMapper.java#L34 so that we capture this kind of problem in other areas of the codebase as well.

Nice idea, i like it

**Comment by ibuziuk** [comment]
[crw-ci-test]

**Comment by ibuziuk** [comment]
[crw-ci-test]

**Comment by ibuziuk** [comment]
[crw-ci-test --rebuild]

**Comment by ibuziuk** [comment]
[crw-ci-test --rebuild]

**Comment by ibuziuk** [comment]
@rhopp @dmytro-ndp we need this fix in 7.22.0, so that it would land in the CRW 2.6 
Can we merge PRs without happy-path success?

**Comment by dmytro-ndp** [comment]
@ibuziuk: PR is 19 days old. It would be nice to take changes from master branch and then run the tests.

**Comment by ibuziuk** [comment]
[crw-ci-test]

**Review by dmytro-ndp — APPROVED** [review]
Happy path tests showed known flakiness https://github.com/eclipse/che/issues/18034 (test results: https://github.com/eclipse/che/pull/18240#issuecomment-728925228)

There was no problem with user management, which this PR was fixing.

**Pull request merged**
