### PR TITLE
Add some new macro for commands 

### PR DESCRIPTION
**Pull request by dkulieshov**
Related issue: https://github.com/eclipse/che/issues/7485

Added a couple of macro for commands:
- `${workspace.namespace}` - is used to refer to current workspace namespace
- `${current.project.eldest.parent.path}` - is used to refer to current project's eldest parent project (e.g. for sub project `/projects/che/core/che-core-api` this will refer to `/projects/che`)

### CODE REVIEW

**Comment by dkulieshov** [comment]
ci-test

**Review by azatsarynnyy — APPROVED** [review]

**Comment by slemeur** [comment]
Docs?

**Comment by dkulieshov** [comment]
ci-test

**Comment by gorkem** [comment]
`current.project.eldest.parent.path` that is almost a sentence 😄 . At least it fits on a tweet

**Review by vparfonov — APPROVED** [review]

**Pull request merged**
