### PR TITLE
CHE-3686: fix docker machines addresses setting

### PR DESCRIPTION
**Pull request by garagatyi**
### What does this PR do?
Set internal machine address by CLI from CHE_IP.
Add and fix docs in che.env.
Change behavior of default machine server address evaluation
to be similar to the previous state.
Code cleanup.

### What issues does this PR fix or reference?
Final addition to fix of #3686 

### Tests written?
Yes

#### Changelog
Fix docker machines addresses setting

### CODE REVIEW

**Comment by garagatyi** [comment]
@amisevsk Please take a look too

**Review by benoitf — APPROVED** [review]
launcher changes are not required as support has been dropped.

**Comment by benoitf** [comment]
thanks

**Comment by garagatyi** [comment]
@benoitf Thanks, I rebased this PR to resolve conflicts

**Comment by TylerJewell** [comment]
This issue has recently come up.  And it should not be the situation where setting this by a user is required.  Does this branch fix this issue?

https://github.com/codenvy/che-docs/issues/75#issuecomment-273801117

**Review by sleshchenko — APPROVED** [review]

**Comment by garagatyi** [comment]
@TylerJewell yes, I think this PR will solve that issue.

**Comment by amisevsk** [comment]
@garagatyi LGTM. Thanks for cleaning up my code.

As long as the launcher/CLI sets `CHE_DOCKER_IP` appropriately, this implementation of `DefaultServerEvaluationStrategy` is simpler, but maybe a little more opaque (since the fact that `CHE_DOCKER_IP` is by a launch script, it's not immediately clear that value will *always* be set at runtime).

**Review by TylerJewell — COMMENTED** [review]
I would like some time to review the modifications to Che.env, verify the networking docs and also have someone verify that they can start a new server on digital ocean by only setting Che host.

**Comment by garagatyi** [comment]
@amisevsk It really depends on how che-server is launched and how CLI works(in case of launching using CLI). There is no guaranty that CLI will always set this property or that other vendor will not embed che-server without usage of CLI.

**Review by TylerJewell — APPROVED** [review]

**Comment by TylerJewell** [comment]
@garagatyi - this is ok to merge.  We hvae had multiple people run into these issues and have had to set CHE_DOCKER_EXTERNAL_* variables temporarily.  Would you advise that we merge this in time for 5.1.2, a bug fix release for Monday?

**Comment by garagatyi** [comment]
Yes, I think we can merge it. Should I merge it now?

**Comment by TylerJewell** [comment]
Yes, please - we should then do some tests on nightly on digital ocean tomorrow to verify that che starts easily with only CHE_HOST.

**Comment by garagatyi** [comment]
ok, I'm merging this PR and dependent in Codenvy. Roman will be able to cherry pick into bug fix branch if needed.

**Pull request merged**
