### PR TITLE
Update Centos-go stack

### PR DESCRIPTION
**Pull request by jarifibrahim**
### What does this PR do?
- Remove Java language server installer
- Add Golang language server installer
- Remove .m2 and javadata volumes
- Add project volume

### What issues does this PR fix or reference?
N/A

### CODE REVIEW

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by sbose78** [comment]
Given the changes I see being done here - Is this stack even in use? :)

**Comment by jarifibrahim** [comment]
> Given the changes I see being done here - Is this stack even in use? :)

Used anywhere? Nopes. Does this stack work with a golang project? Yes.

**Review by ibuziuk — CHANGES_REQUESTED** [review]
volumes updates should not be done. `projects` is mounted by default & `javadata` and `.m2` are required for jdtls cc @tsmaeder

**Comment by tsmaeder** [comment]
@ibuziuk why would jdt.ls be needed on a golang workspace?

**Comment by ibuziuk** [comment]
@tsmaeder this is also what I was wondering some time ago - https://chat.openshift.io/developers/pl/zyc5h8j9di8cfrywmib8oyfhyo

If you think it is not needed, please approve this PR and we could merge

**Comment by musienko-maxim** [comment]
Can one of the admins verify this PR?

**Pull request closed without merging**
