### PR TITLE
CHE-1485 allow special characters in file names and folder names + fix an encoding issue

### PR DESCRIPTION
**Pull request by Leward**
### What does this PR do?

It allows user to create files and folders that contains special (non-ASCII) characters expects the one that are not allowed in Linux or Windows. 
### What issues does this PR fix or reference?

[CHE-1485 Struggling working with Japanese filenames](https://github.com/eclipse/che/issues/1706)
### Previous Behavior

File/Folder names with special characters were marked as invalid
### New Behavior

File/Folder names with special characters are now valid
### Tests written?

Yes
### Docs requirements?

None

image

Note that Japanese names for example makes the terminal to behave a bit weirdly. However by getting into the container it is fine (see screenshot).

### CODE REVIEW

**Comment by Leward** [comment]
By the way I think all the file names passed as a query string parameter to the API should be URL Encoded. 

I supposed because of that, some operation may be broken when executed against files containing special chars in their names. 

This is also my first contribution to Che  :)

**Comment by TylerJewell** [comment]
Thanks for the contribution!  @kuleshov @vparfonov should review and comment.

**Comment by slemeur** [comment]
@vparfonov : could you please have your team reviewing the PR.

**Comment by slemeur** [comment]
@vparfonov : still no review planned on this PR?

**Review by dkulieshov — APPROVED** [review]
Looks nice

**Pull request merged**
