### PR TITLE
CHE-661 unzip in quiet mode

### PR DESCRIPTION
**Pull request by benoitf**
Change-Id: If3a51cc6e01e243c47033d4d891858e3997ab725
Signed-off-by: Florent BENOIT fbenoit@codenvy.com

### CODE REVIEW

**Comment by riuvshin** [comment]
if we need that in codenvy hosted we need to change it here aswell:
https://github.com/codenvy/deployment/blob/master/puppet/modules/all_in_one/templates/machine.properties.erb#L26

https://github.com/codenvy/deployment/blob/master/puppet/modules/multi_server/templates/api_instance/machine.properties.erb#L29

**Comment by benoitf** [comment]
I can issue PR on erb files

**Comment by garagatyi** [comment]
Why you want to make it quiet?

**Comment by riuvshin** [comment]
@garagatyi on a meeting we've decided to get rid of that useless output when ws is starting.

**Comment by benoitf** [comment]
@garagatyi because it looks ugly to see that when we start agent and if unzip fails we will have error BTW

**Comment by garagatyi** [comment]
than ok

**Comment by garagatyi** [comment]
LGTM

**Comment by benoitf** [comment]
I will use -q and not -qq param

**Pull request merged**
