### PR TITLE
[Selenium] Fix scripts for nightly jobs on ci.centos

### PR DESCRIPTION
**Pull request by SkorikSergey**
### What does this PR do?
We need to fix ```nightly-happypath-test``` and ```cico-devfiles-test jobs``` scripts for nightly jobs on  ci.centos.

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/16704

### CODE REVIEW

**Comment by SkorikSergey** [comment]
[ci-test]

**Comment by SkorikSergey** [comment]
[ci-test]

**Comment by SkorikSergey** [comment]
[ci-test]

**Comment by SkorikSergey** [comment]
[ci-test]

**Comment by SkorikSergey** [comment]
[ci-test]

**Comment by SkorikSergey** [comment]
[ci-test]

**Comment by SkorikSergey** [comment]
[ci-test]

**Comment by SkorikSergey** [comment]
[ci-test]

**Comment by SkorikSergey** [comment]
[ci-test]

**Comment by SkorikSergey** [comment]
crw-ci-test

**Comment by SkorikSergey** [comment]
crw-ci-test

**Review by dmytro-ndp — APPROVED** [review]

**Pull request merged**
