### PR TITLE
Update the "DialogWindow.waitDialog" method

### PR DESCRIPTION
**Pull request by Ohrimenko1988**
### What does this PR do?
Update the "DialogWindow.waitDialog" method

### What issues does this PR fix or reference?
Issue: https://github.com/eclipse/che/issues/16830
Issue: https://github.com/eclipse/che/issues/16828

### CODE REVIEW

**Comment by Ohrimenko1988** [comment]
crw-ci-test

**Comment by Ohrimenko1988** [comment]
crw-ci-test

**Review by dmytro-ndp — APPROVED** [review]

**Comment by Ohrimenko1988** [comment]
crw-ci-test

**Comment by Ohrimenko1988** [comment]
crw-ci-test

**Pull request merged**
