### PR TITLE
Add small fixes for UD

### PR DESCRIPTION
**Pull request by olexii4**
Signed-off-by: Oleksii Orel <oorel@redhat.com>

### What does this PR do?
Add small fixes for UD. A list of fixes:
- remove the URL query string when back to UD
- remove unnecessary CHE6 message  'Starting workspace agent' from the factory page
- add the rule for hiding navbar
- code clean up for  'dashboard/src/app/ide/ide-iframe/ide-iframe.service.ts'
- add the rule for opening navbar after the path changing
- code clean up for  'dashboard/src/app/index.module.ts'
-  remove unused controller 'dashboard/src/app/navbar/navbar-selected.controller.ts'
-  remove navbar toggle which is unused.
- fix rootscope interface

### CODE REVIEW

**Comment by olexii4** [comment]
ci-test
crw-ci-test

**Comment by olexii4** [comment]
crw-ci-test

**Comment by olexii4** [comment]
@gorkem I have added a  list of small fixes covered on this PR

**Review by akurinnoy — APPROVED** [review]
@olexii4 Please provide a separate commit for each fix next time.

**Review by AndrienkoAleksandr — APPROVED** [review]

**Comment by olexii4** [comment]
@akurinnoy  OK. I'll do

**Review by dmytro-ndp — APPROVED** [review]
E2E tests results look good.

**Pull request merged**
