### PR TITLE
CHE-1491: add "+" button next to "Recent workspaces"

### PR DESCRIPTION
**Pull request by akurinnoy**
### What does this PR do?

It adds a "+" button next to "Recent workspaces" in order to let user quickly create a new workspace.
### What issues does this PR fix or reference?

[https://github.com/eclipse/che/issues/1768](https://github.com/eclipse/che/issues/1768)
[https://jira.codenvycorp.com/browse/CHE-1491](https://jira.codenvycorp.com/browse/CHE-1491)

Signed-off-by: Oleksii Kurinnyi okurinnyi@codenvy.com

### CODE REVIEW

**Comment by TylerJewell** [comment]
Attach screen shot.

**Comment by akurinnoy** [comment]
plus_button

**Comment by TylerJewell** [comment]
Lgtm

**Comment by slemeur** [comment]
+1

**Pull request merged**
