### PR TITLE
CHE-754: typo changes in project details when workspace stopped

### PR DESCRIPTION
**Pull request by akurinnoy**
**_2 Upvotes**_ Signed-off-by: Oleksii Kurinnyi okurinnyi@codenvy.com

### CODE REVIEW

**Comment by akurinnoy** [comment]
screenshot

**Comment by TylerJewell** [comment]
Delete the second gray sentence. It is not needed

**Comment by akurinnoy** [comment]
@TylerJewell wdyt?
screenshot 2

**Comment by TylerJewell** [comment]
Ok

**Comment by olexii4** [comment]
+1

**Comment by ashumilova** [comment]
+1

**Pull request merged**
