### PR TITLE
feat: provide minimal test for Camel on SpringBoot stack

### PR DESCRIPTION
**Pull request by apupier**
- check start of workspace
- check Camel and java language server initialized by checking
completion
- check build task

### What does this PR do?

provide minimal test for Camel on SpringBoot stack

### What issues does this PR fix or reference?

eclipse/che#14780

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [ ] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [ ] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [ ] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by apupier** [comment]
unfortunately, for now I wasn't able to play tests (cannot start a local che currently). I was hoping that they will be executed as PR check :-(

**Comment by apupier** [comment]
now able to launch a Che instance locally but cannto play tests succesfully, see https://mattermost.eclipse.org/eclipse/pl/8ia5qys7nfgepr1idif6zssjjy

**Comment by apupier** [comment]
made progress yesterday thanks to kfoniok on Che [mattermost](https://mattermost.eclipse.org/eclipse/pl/gbybaruj6inuppbxwx3tuoicgw) (and updated PR) But this morning I have this error:

```
ErrImagePull

Failed to run the workspace: "Plugins installation process failed. Error: Unrecoverable event occurred: 'Failed', 'Error: ErrImagePull', 'workspacecynta8g9mzuxdxz9.che-plugin-broker'"
```

**Comment by ScrewTSW** [comment]
> made progress yesterday thanks to kfoniok on Che [mattermost](https://mattermost.eclipse.org/eclipse/pl/gbybaruj6inuppbxwx3tuoicgw) (and updated PR) But this morning I have this error:
> 
> ```
> ErrImagePull
> 
> Failed to run the workspace: "Plugins installation process failed. Error: Unrecoverable event occurred: 'Failed', 'Error: ErrImagePull', 'workspacecynta8g9mzuxdxz9.che-plugin-broker'"
> ```

Is this still happening?
Do you have an URL to the image in question?
Is it present on `quay.io`? if not, and required, did you set-up image pulling proxy policy on the cluster?

Sorry for the late reply.

**Review by ScrewTSW — APPROVED** [review]
The test case code looks appropriate and perfectly clean :)

**Pull request closed without merging**
