### PR TITLE
Made Devfile commands optional

### PR DESCRIPTION
**Pull request by skabashnyuk**
### What does this PR do?
Made commands optional in devfile schema. Commands can be provided only by tools or editors.

#### Release Notes
n/a
#### Docs PR
n/a

### CODE REVIEW

**Comment by skabashnyuk** [comment]
CC @l0rd

**Review by sleshchenko — APPROVED** [review]
LGTM

**Review by mshaposhnik — APPROVED** [review]

**Comment by skabashnyuk** [comment]
ci-test

**Comment by skabashnyuk** [comment]
ci-test

**Pull request merged**
