### PR TITLE
RELEASE: Set next development version

### PR DESCRIPTION
**Pull request by riuvshin**

### CODE REVIEW

**Comment by ibuziuk** [comment]
@riuvshin could we make sure that eclipse/che#13204 got into the 7 beta 4 release?

**Comment by l0rd** [comment]
@ibuziuk I think the branch has already been created a few days ago https://github.com/eclipse/che/tree/7.0.0-beta-4.x
@riuvshin can you please pull latest master commits into beta-4 branch?

**Comment by riuvshin** [comment]
@l0rd will do

**Comment by l0rd** [comment]
@riuvshin another thing: next sprint release should be called 7.0.0-rc-1.0 hence can you please change the dev version to 7.0.0-rc-1.0-SNAPSHOT ?

**Review by skabashnyuk — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Review by ibuziuk — APPROVED** [review]

**Pull request merged**
