### PR TITLE
Allow to use bare "alpine" image

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?

alpine-sh

Add support for alpine image
### What issues does this PR fix or reference?

It uses sh instead of bash (but allowing to configure shell through "shell" attribute of commands)
It also need https://github.com/eclipse/che-lib/pull/14 to have static go binaries 
Workspace agent on Alpine uses OpenJDK8 as glibc is not provided by default (and Oracle JDK is requiring it)
Terminal agent is also updated to provide /bin/bash only if it's available else it provides /bin/sh access
### Previous behavior

(Remove this section if not relevant)
### New behavior
- use of /bin/sh for docker command invocation instead of /bin/bash
- allow to still use bash by providing a custom "shell" / "/bin/bash" attribute
### PR type
- [x] Minor change = no change to existing features or docs
### Minor change checklist
- [ ] New API required?
- [ ] API updated
- [ ] Tests provided / updated
- [x] Tests passed

### CODE REVIEW

**Comment by TylerJewell** [comment]
Super slick.  +1

**Comment by TylerJewell** [comment]
I noticed that there are updates done for the ws-agent and terminal agents.  Will the other agents that have been packaged work ok?

**Comment by benoitf** [comment]
@garagatyi @tolusha @mmorhun @vkuznyetsov  ?

**Comment by benoitf** [comment]
@TylerJewell yes I think

**Review by tolusha — APPROVED** [review]

**Comment by mmorhun** [comment]
LGTM

**Pull request merged**
