### PR TITLE
fix github OAuth redirect url

### PR DESCRIPTION
**Pull request by garagatyi**
@skabashnyuk @vparfonov

### CODE REVIEW

**Comment by vparfonov** [comment]
ok

**Comment by sleshchenko** [comment]
As I know We should not have configuration of oauth on machines. We should delete it at all. For now we don't use these values.

**Comment by garagatyi** [comment]
Are you sure Sergii? I tried logged in with gitub and got tomcat notfound page with this address. But OAuth redirect url is correct in conf of ws master.

**Comment by sleshchenko** [comment]
Hmm. What happens If you close page with "not found" and try to use github again? Can you provide full use case?

**Comment by garagatyi** [comment]
I figured out that it was because of my outdated settings of OAuth. Thank you Sergii. I'll close this PR.

**Pull request closed without merging**
