### PR TITLE
CHE-3011. Fix CentOS and RHEL 6 issues

### PR DESCRIPTION
**Pull request by ghost**
### What does this PR do?

Fixes workspace start error on Centos and RHEL 6

### What issues does this PR fix or reference?

https://github.com/eclipse/che/issues/3011

@tolusha please take a look

### CODE REVIEW

**Review by benoitf — COMMENTED** [review]
It is missing fix in unison script as well:
https://github.com/eclipse/che/blob/ebe31a9f822cdbe997a0ea05b8e7f1cd8053f129/wsmaster/che-core-api-agent/src/main/resources/agents/scripts/org.eclipse.che.unison.script.sh#L16-L17

**Comment by ghost** [comment]
Pushed

**Comment by tolusha** [comment]
Run `update-agent.sh` to update agents` descriptions and include them into the PR

**Comment by ghost** [comment]
Done

**Comment by ghost** [comment]
ci-build

**Comment by riuvshin** [comment]
ci-build

**Comment by tolusha** [comment]
Pls. format all `*.json` files to have less changes.

**Review by tolusha — APPROVED** [review]

**Pull request merged**
