### PR TITLE
Fix webpack config

### PR DESCRIPTION
**Pull request by olexii4**
Signed-off-by: Oleksii Orel <oorel@redhat.com>

### What does this PR do?
Fix webpack config.

### CODE REVIEW

**Comment by olexii4** [comment]
ci-test

**Comment by benoitf** [comment]
is it a fix or an upgrade ?

**Review by benoitf — APPROVED** [review]

**Comment by olexii4** [comment]
@benoitf Good catch. It is a fix. I just tried. It doesn't necessary to upgrade version.
I have fixed it.

**Review by benoitf — APPROVED** [review]

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/938/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/938//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11532
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/940/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/940//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11532
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by olexii4** [comment]
ci-test

**Review by akurinnoy — APPROVED** [review]

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/943/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/943//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11532
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Review by ashumilova — APPROVED** [review]

**Pull request merged**
