### PR TITLE
fix logwatch flaky tests

### PR DESCRIPTION
**Pull request by sparkoo**
Signed-off-by: Michal Vala <mvala@redhat.com>

### What does this PR do?
Fixes the container logwatch flaky tests

### What issues does this PR fix or reference?
n/a

### CODE REVIEW

**Review by mshaposhnik — APPROVED** [review]

**Review by skabashnyuk — APPROVED** [review]

**Comment by sparkoo** [comment]
ci-build

**Comment by sparkoo** [comment]
crw-ci-test

**Comment by sparkoo** [comment]
[ci-build]

**Comment by sparkoo** [comment]
crw-ci-test

**Pull request merged**
