### PR TITLE
K8s multiuser helm

### PR DESCRIPTION
**Pull request by guydc**
### What does this PR do?
Adds helm charts for deployment of Multi-User Che on Kubernetes (minikube).

Reuses images provided with https://github.com/eclipse/che/pull/8819 (thanks @eivantsov !). 

Multi/Single user is configurable with helm values (global.multiuser). 

Orchestration of deployment is performed with init-containers.
Post-Installation configuration is performed with Jobs. 
* Che & KeyCloak servers wait for postgres to be available (based on readiness/availability probes)
* KeyCloak configuration is performed after KeyCloak server is available, using a Job

KeyCloak can be served from a dedicated host, or a host shared with master (/auth). 

**Test PR**
Follow [instructions](https://github.com/guydaichs/che/tree/k8s-multiuser-helm/dockerfiles/init/modules/che-kubernetes-helm#deployment-types) to set up minikube, helm, tiller & deploy Che. 

### What issues does this PR fix or reference?

This PR is part of kubernetes infrastructure epic https://github.com/eclipse/che/issues/5908. 

#### Docs PR

[readme](https://github.com/guydaichs/che/tree/k8s-multiuser-helm/dockerfiles/init/modules/che-kubernetes-helm)

### CODE REVIEW

**Review by garagatyi — COMMENTED** [review]
I think we should stop putting stuff not related to dockerfiles into `dockerfiles` folder. We also discussed moving openshift stuff out of this folder.
@eivantsov @benoitf @riuvshin @l0rd WDYT?

**Comment by riuvshin** [comment]
@garagatyi I agree with you in general but keeping these files in `dockerfiles` folder might have a sense if it will be integrated with CLI.

**Comment by garagatyi** [comment]
@riuvshin I don't think it will be integrated with the CLI. The same for OS. Admins would expect to deploy Che with k8s/OS dependent flows, not with a CLI that runs inside of docker.

**Comment by l0rd** [comment]
@garagatyi agree but I don't think that we should block this PR for this. We can discuss on the [proper issue](https://github.com/redhat-developer/rh-che/issues/528) where we should move the files because I don't think we have an agreement yet.

And yes CLI extension to support OpenShift and k8s has been delayed/cancelled in favor of minishift addon and helm.

**Comment by garagatyi** [comment]
@l0rd I didn't mean that files placement topic is blocking this PR. Just started this conversation since it is tightly related to the PR. Sure we can merge files in the current place and then move it if needed.

**Comment by garagatyi** [comment]
@benoitf Can you review this PR? 
@guydaichs @riuvshin is on vacation, so he probably won't be able to review your PR till the next week.
AFAIK initial contribution of helm support was done by @perspectivus1 so it would be great if you can review this PR too.
@l0rd you were reviewing previous PR about helm, can you take a look on this one too?

**Comment by perspectivus1** [comment]
I'm been following @guydaichs' work on this PR. I actually saw the multiuser deployment in action. Looks good to me 👍

**Comment by skabashnyuk** [comment]
@guydaichs @perspectivus1 @garagatyi  @l0rd  here https://github.com/eclipse/che/pull/8982 we are doing some adjustments in K8s files can you take a look and let us know if you see any issues?

**Review by l0rd — APPROVED** [review]
I have tested and worked just fine. Great job @guydaichs! We can merge it tomorrow. 

In the meantime can you please add license headers to the files that don't have it and add a newline at the end of a couple of files that don't have it (`keycloak-configure-job.yaml` and `requirements.yaml`).

**Comment by skabashnyuk** [comment]
@guydaichs do you want something to add to this PR or you want to merge it? Are you going to squash commits or commiters can do that for you?

**Comment by guydaichs** [comment]
@l0rd - I added license headers. 
@skabashnyuk - please squash and merge.

**Comment by l0rd** [comment]
@guydaichs thanks

**Pull request merged**
