### PR TITLE
CHE-1086: expand classpath containers

### PR DESCRIPTION
**Pull request by svor**

### CODE REVIEW

**Comment by svor** [comment]
[demo](https://youtu.be/tpMjyvTgWbc)

**Comment by slemeur** [comment]
Can we reduce the width of the left part of the wizard ?
screen_shot_2016-04-27_at_16 53 36

**Comment by svor** [comment]
@slemeur yes, we can. Are you thinking to reduce the width only of the left part or whole window?

What do you think about this screenshot?
classpath

**Comment by slemeur** [comment]
@svor yes. By reducing the width of the left area, it will reduce the full width of the popup.

**Comment by vparfonov** [comment]
ok

**Comment by slemeur** [comment]
Could you please make the two lists the same height? 
list-size

**Comment by svor** [comment]
@slemeur take a look again please 
classpath2

**Comment by slemeur** [comment]
now you can reduce the height :) 
you have an empty area at the bottom of the popup - it is not necessary ;)

**Comment by svor** [comment]
@slemeur 
And finally :) 
classpath3

**Comment by slemeur** [comment]
Good for me ! Thanks @svor !!

**Pull request merged**
