### PR TITLE
Add commands to workspace when importing project samples

### PR DESCRIPTION
**Pull request by kaloyan-raev**
### What does this PR do?

If a project sample is imported from the IDE's Create Project wizard, the commands defined in the project sample will be added to the workspace. This way it will be the same like importing the project sample from the Dashboard.

### What issues does this PR fix or reference?

None.

### Previous behavior

Commands defined in the project sample were not added to the workspace.

### New behavior

The commands are now added.

#### Changelog
Add commands to workspace when importing project samples

Signed-off-by: Kaloyan Raev <kaloyan.r@zend.com>

### CODE REVIEW

**Comment by benoitf** [comment]
ci-build

**Comment by slemeur** [comment]
+1

**Comment by benoitf** [comment]
@vparfonov ?

**Comment by TylerJewell** [comment]
@kaloyan-raev - lets fix the conflicting files. I'm asking Vitalli to take this into next sprint for merge.  I'm going to ask all TLs to go through PR backlog now that we are 5.0.0 shipped.

**Comment by kaloyan-raev** [comment]
Conflicts resolved. Rebased to latest master.

**Comment by riuvshin** [comment]
@vparfonov what is the state of that issue? it is planned for 5.2.0 which going tobe released in few days.

**Pull request merged**
