### PR TITLE
Add ability of fast switching between IDE parts

### PR DESCRIPTION
**Pull request by RomanNikitenko**
### What does this PR do?
Add ability of fast switching between IDE parts(Editor, Project Explorer, Command Explorer, Terminal, Find part, Debugger, Event Logs, Contribute part) depends on the current state of IDE:

For example, for Terminal:
- Processes panel is invisible -> make it visible and active last active terminal, opens new terminal when terminal is absent
- Terminal is active -> make it invisible
- Terminal is inactive -> make it active

For Editor:
- Editor is inactive -> make it active
- Editor is active -> maximize it
- Editor is maximized -> set normal mode

For Project Explorer part:
- Project explorer is invisible -> make it visible and active
- Project explorer is active -> make it invisible
- Project explorer is inactive -> make it active

Hotkeys:
hotkeys

### What issues does this PR fix or reference?
#7024 

#### Docs PR

Signed-off-by: Roman Nikitenko <rnikiten@redhat.com>

### CODE REVIEW

**Review by vparfonov — APPROVED** [review]

**Comment by tolusha** [comment]
It is possible to add selenium test ?

**Comment by RomanNikitenko** [comment]
@tolusha yes, I think so! 
But we haven't planned it for current sprint. 
So we can consider adding selenium tests for this feature during next sprint.
@vparfonov WDYT?

**Comment by RomanNikitenko** [comment]
So we are going to add selenium tests for it within https://github.com/eclipse/che/issues/7758

**Comment by tolusha** [comment]
Up to you.
I just a bit worried not to break down functionality occasionally.  :)

**Review by tolusha — APPROVED** [review]

**Comment by RomanNikitenko** [comment]
ci-build

**Comment by RomanNikitenko** [comment]
ci-test

**Comment by RomanNikitenko** [comment]
I've fixed conflicts.
QA in progress

**Review by musienko-maxim — APPROVED** [review]

**Pull request merged**
