### PR TITLE
CODENVY-211: Provide configuration parameter to enable docker privileged mode

### PR DESCRIPTION
**Pull request by mmorhun**
**_1 Upvote**_ Signed-off-by: Mykola Morhun mmorhun@codenvy.com

### CODE REVIEW

**Comment by mmorhun** [comment]
@garagatyi check please

**Comment by garagatyi** [comment]
LGTM
@skabashnyuk Please take a look.

**Comment by skabashnyuk** [comment]
ok

**Comment by TylerJewell** [comment]
+1 - will add to docs once merged.

**Pull request merged**
