### PR TITLE
CODENVY-630: save a value of the library folder

### PR DESCRIPTION
**Pull request by svor**
Save value of the library folder for the javac project type. This value can change by using configuration wizard.

### CODE REVIEW

**Comment by benoitf** [comment]
do you think src/test/resources/projects/project/lib/a.jar could be generated during the test build instead of adding a binary into git repository ?

**Comment by svor** [comment]
@benoitf  this is rubbish :worried: 
I've deleted it. Thanks for this

**Comment by benoitf** [comment]
@svor ok thx

**Comment by vparfonov** [comment]
ok

**Pull request merged**
