### PR TITLE
Upgrade kubernetes-client to 5.3.1

### LINKED ISSUE #19743: Re-enable KubernetesNamespaceFactoryTest
### Is your task related to a problem? Please describe.
As part of https://github.com/eclipse/che/issues/19641 we disabled KubernetesNamespaceFactoryTest.
The goal of this task is to reenable it.
### Describe the solution you'd like
As soon as  https://github.com/fabric8io/kubernetes-client/issues/3038 would be fixed. We need to upgrade kubernetes-client for eclipse che. It can be 5.x or 4.x version

### Describe alternatives you've considered
n/a
### Additional context
https://github.com/eclipse/che/issues/19641

### PR DESCRIPTION
**Pull request by skabashnyuk**
### What does this PR do?
 Upgrade kubernetes-client to latest release 5.3.1
CQ https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23230

### Screenshot/screencast of this PR
Знімок екрана 2021-05-06 о 15 45 07

### What issues does this PR fix or reference?
It will help easily fix https://github.com/eclipse/che/issues/19743 as soon as the fix would be released in the next version.

### How to test this PR?
- deploy new che-server image ` quay.io/skabashn/che-server:newkubclient`
- Create workspace
- Start workspace.

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by sparkoo** [comment]
nice, so does it fix the test issue with mockserver?

From previous experience, I think we should merge it asap after the release, so we get it tested before next release.

**Comment by skabashnyuk** [comment]
>nice, so does it fix the test issue with mockserver?

No. 5.3.1 doesn't contain that fix yet.

>From previous experience, I think we should merge it asap after the release, so we get it tested before next release.

+1

**Comment by skabashnyuk** [comment]
crw-ci-test --rebuild

**Comment by skabashnyuk** [comment]
crw-ci-test

**Comment by skabashnyuk** [comment]
[crw-ci-test]

**Review by sparkoo — APPROVED** [review]
tested on minikube 1.20.0, working fine

**Comment by skabashnyuk** [comment]
[crw-ci-test --rebuild]

**Review by mshaposhnik — APPROVED** [review]

**Pull request merged**
