### PR TITLE
Make e2e Happy path tests more stable

### PR DESCRIPTION
**Pull request by dmytro-ndp**
### What does this PR do?
This PR adds workarounds to make e2e Happy path tests being more stable.

### CODE REVIEW

**Comment by dmytro-ndp** [comment]
new-ci-test

**Comment by dmytro-ndp** [comment]
new-ci-test

**Review by rhopp — CHANGES_REQUESTED** [review]
I'm strongly against putting these hard sleeps into our code even as a workaround. If something is not happening, we should implement active waiting loop, or something like that.

**Comment by dmytro-ndp** [comment]
@rhopp: agree

**Comment by dmytro-ndp** [comment]
new-ci-test

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by musienko-maxim** [comment]
Results of automated E2E Happy path tests of Eclipse Che Single User on K8S (minikube v1.1.1):
[Build details](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/CHE-7-Maven-PR-build-checker-codenvy-slave9/24/)
docker image: docker.io/maxura/che-server:14084
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by musienko-maxim** [comment]
Results of automated E2E Happy path tests of Eclipse Che Single User on K8S (minikube v1.1.1):
[Build details](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/CHE-7-Maven-PR-build-checker-codenvy-slave9/25/)
docker image: docker.io/maxura/che-server:14084
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by musienko-maxim** [comment]
E2E Happy path tests of Eclipse Che Single User on K8S (minikube v1.1.1) has been successful:
- [Build details](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/CHE-7-Maven-PR-build-checker-codenvy-slave9/34/)
- docker image: docker.io/maxura/che-server:14084

**Comment by musienko-maxim** [comment]
E2E Happy path tests of Eclipse Che Single User on K8S (minikube v1.1.1) has been successful:
- [Build details](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/CHE-7-Maven-PR-build-checker-codenvy-slave9/35/)
- docker image: docker.io/maxura/che-server:14084

**Comment by musienko-maxim** [comment]
E2E Happy path tests of Eclipse Che Single User on K8S (minikube v1.1.1) has been successful:
- [Build details](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/CHE-7-Maven-PR-build-checker-codenvy-slave9/36/)
- docker image: docker.io/maxura/che-server:14084

**Comment by dmytro-ndp** [comment]
new-ci-test

**Comment by dmytro-ndp** [comment]
new-ci-test

**Comment by dmytro-ndp** [comment]
new-ci-test

**Comment by dmytro-ndp** [comment]
new-ci-test

**Comment by dmytro-ndp** [comment]
new-ci-test

**Comment by dmytro-ndp** [comment]
new-ci-test

**Comment by dmytro-ndp** [comment]
new-ci-test

**Comment by dmytro-ndp** [comment]
new-ci-test

**Pull request closed without merging**
