### PR TITLE
#1895 codenvy/che-file improvements

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?

 #1895 codenvy/che-file docker image improvements
- Rework into promise, also start the workspace, check when workspace is booted and display that data
- allow to customize ram when creating workspace
- use static variables
- cleanup
- introduce che dir down, che dir status command
- introduce support of commands in Chefile
- post loading commands
  -more than 50 commits

### CODE REVIEW

**Comment by benoitf** [comment]
PR updated with new improvements

**Comment by dmytro-ndp** [comment]
_che-test_ works mostly as expected according to requirements of   https://github.com/codenvy/codenvy/issues/479 and https://github.com/eclipse/che/issues/2127
Only checking of creation of Spring project remains.

**Comment by benoitf** [comment]
Will require https://github.com/eclipse/che/pull/2211 to be merged

**Comment by dmytro-ndp** [comment]
+1 for merging changes related to **che-test** into the master before 26 Aug in aim to have them in tag _Che 4.7.0_.
We need to have fixed **che-test** in the **hub.docker.com** to be able to provide _post-flight Codenvy on-prem 4.7.0 installation check_ from within _Codenvy bootstrap script_.

**Pull request merged**
