### PR TITLE
Fixed typo in workspace list

### PR DESCRIPTION
**Pull request by hkolvenbach**
### What does this PR do?
Fixes a typo in workspace-item.html

#### Changelog

Fixed typo in workspace-iteml.html

### CODE REVIEW

**Comment by benoitf** [comment]
@hkolvenbach could you signed your commit with Signed-Off header and the Eclipse ECA ?
https://dev.eclipse.org/eclipse-webhook/services/status_details.php?id=598326a7111ca

without that we couldn't merge your fix :-/

thanks

**Comment by hkolvenbach** [comment]
@benoitf yes, will do that. did this pull request through github website that's why it didn't work.

**Comment by benoitf** [comment]
thanks @hkolvenbach

**Comment by benoitf** [comment]
this PR was moved to https://github.com/eclipse/che/pull/5895

**Pull request closed without merging**
