### PR TITLE
[WIP] Replace client side HTTP requests using the hostname that is in the address bar

### LINKED ISSUE #1644: Docker Launcher: Websockets are unable to comunicate with the wsagent when the server and the browser run on different networks
In scenarios where a `wsagent` has two different IP addresses: 
- An internal IP address that is used by Che server
- An external IP address that is used by the websockets in the browser

the creation of a new workspace and project fails.

I could reproduce that using Docker for Mac but the scenario should be reproducible wherever you have an internal/external IPs (e.g. amazon EC2). There is a workaround (rerouting the traffic to the internal IP address to the external IP address on the Docker host) and it's described [here](https://eclipse-che.readme.io/docs/usage-docker-for-mac). This issue is about removing the need to use this workaround and is related to #1482.

**Reproduction Steps:**
1. Run Che inside a container using Docker for Mac without setting the `lo0` alias
2. Access the dashbord using the URL http://localhost:8080
3. Create a new workspace and project

**Expected behavior:**

The workspace and project should be created successfully. The websocket should use the URL in the address bar to contact the wsagent (with a different port). 

**Observed behavior:**

The creations hangs after the wsagent is started:

> [STDOUT] 2016-07-04 15:40:41,950[main] [INFO] [o.a.catalina.startup.Catalina 642] - Server startup in 39359 ms
> [STDOUT] 2016-07-04 15:40:43,204[nio-4401-exec-4] [WARN ] [i.ContainerResponse$BodyWriter 90] - Client has aborted connection. Response writing omitted.

And after a few minutes a popup message with the following error:

> Workspace Connection Error
> It seems that your workspace is running, but we cannot connect your browser to it. This commonly happens when Che was not configured properly. If your browser is connecting to workspaces running remotely, then you must start Che with the --remote:<ip-address> flag where the <ip-address> is the IP address of the node that is running your Docker workspaces.Please restart Che with this flag. You can read about what this flag does and why it is essential at: https://eclipse-che.readme.io/docs/configuration#envrionment-variables

Opening the developers tools in Chrome I could see that the websocket is tring to connect to an host (`192.168.65.2`) that is not accessible from the Mac OS and that is different from the host I've put in the brwoser address bar (`localhost`)

**Che version:**  4.4.0-RC1-SNAPSHOT  
**OS and version:** Mac 10.11.5
**Docker version:** 

```
Client:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   906eacd
 Built:        Fri Jun 17 20:35:33 2016
 OS/Arch:      darwin/amd64
 Experimental: true

Server:
 Version:      1.12.0-rc2
 API version:  1.24
 Go version:   go1.6.2
 Git commit:   a7119de
 Built:        Wed Jun 29 10:03:33 2016
 OS/Arch:      linux/amd64
 Experimental: true
```

**Che install:**    Docker container   

**Additional information:**
- Problem started happening recently, didn't happen in an older version of Che: Yes
- Problem can be reliably reproduced, doesn't happen randomly: Yes

### PR DESCRIPTION
**Pull request by l0rd**
### What does this PR do?

Che used the wsagent internal IP address to send HTTP requests from the browser to the wsagent itself. This can be a problem when the browser cannot ping this IP address. In this PR we have fixed the HTTP requests to the wsagent replacing this internal IP address with the hostname from the browser address bar.
### What issues does this PR fix or reference?

This PR fixes #1644 and #1925 
### Previous Behavior

HTTP requests from the browser to the wsagent used the wsagent internal IP address
### New Behavior

HTTP requests from the browser to the wsagent use the hostname in the address bar
### Tests written?

Yes
### Docs requirements?

Users don't need to set some options anymore:
- the env variable `CHE_HOST_IP` in the launcher is useless
- the option `--remote:` in `che.sh` is useless

Signed-off-by: Mario Loriedo mloriedo@redhat.com

### CODE REVIEW

**Comment by garagatyi** [comment]
Hi Mario! I'm concerned on how will it work if I run che on **server1.mycompany.com** and run docker on **server2.mycompany.com**.
Can you elaborate?

**Comment by benoitf** [comment]
the fixHostName shouldn't be duplicated 4 times in different .js files, you should introduce an angular service instance that should handle this at a single place

example of a service: https://github.com/eclipse/che/blob/master/dashboard/src/components/injector/che-ui-elements-injector.service.js

as there is REGEXP I would like to see a unit test in the javascript as well
example of unit test with different urls
https://github.com/eclipse/che/blob/master/dashboard/src/components/validator/git-url-validator.spec.js

also do we need a regexp to replace a location ?

**Comment by l0rd** [comment]
@garagatyi To support this kind of scenario (che server and wsagent on different hosts) you could use a reverse proxy as traefik. This has a couple of benefits: 
- flexible multihost configuration: don't need to know the IP of the wsagent when starting the server, don't need to set the --net host option when running the server and it would be possible to have running wsagents on different hosts
- works well in scenarios where the browser just can't ping the wsagent IP (Docker for Mac and Windows, running inside VMs, firewall etc..)

@benoitf thank you for these feedbacks. I'll do the modifications. I haven't found anything better than a regexp to replace the hostname of an URL. Do you have something in mind?

**Comment by benoitf** [comment]
@l0rd https://jsfiddle.net/2tokq7m9/ (I didn't import angular in this fiddle but it's almost the same way)

**Comment by garagatyi** [comment]
@l0rd But if you merge this PR we will broke Che for those users who already use Che in a such way without proxy.
Do we want to break Che for some set of existing users to get better experience for some set of other users?
@TylerJewell Please comment on that.

**Comment by benoitf** [comment]
I'm not sure it will work right now on codenvy setup (with different machines that provides docker runners (where agents are running))

**Comment by l0rd** [comment]
Ok I wasn't aware of that scenario. How does it work? How can you share folders between servers and agents if they live in remote machines? 

To support it we could introduce a new property (`che.workspace.use.internal.IP`?). If this property is set to `true` fixHostName returns the original IP, otherwise it does the replacement.

**Comment by garagatyi** [comment]
It is possible in several cases:
1. Che where docker is remote to the API instance. FS of workspaces is placed where docker is placed, so there is no need share folders between servers.
2. Che that uses network FS, e.g. GlusterFS
3. Other implementations/extensions of Che that uses it's own code/infrastructure to share folders, e.g. Codenvy.

> To support it we could introduce a new property...

Properties are placed on server-side, so implementation on client side won't help. If you want to implement something like that you should do that on server-side.

**Comment by benoitf** [comment]
agents URLs are retrieved by the client by getting workspace runtime configuration so updating the value returned by the workspace master would work on all clients instead of patching each client

**Comment by TylerJewell** [comment]
@l0rd @benoitf @garagatyi - I unfortunately am not able to understand the implications well enough to be able to comment if the trade off is acceptable for end users.

Generally, yes, I agree that any sort of details that return hostnames or IP addresses for specific locations of a workspace should be done on the server-side.  This is necessary so that we can support multi-IDE scenarios where different IDEs can interrogate either the workspace or the Che server to find out the necessary configuration.

@l0rd - can you help by providing a mini-spec in the comments here on the various configurations that a user might need to do with Che to support the use case you are solving and those stated by @garagatyi?

**Comment by l0rd** [comment]
@benoitf I've updated this PR with your feedbacks on the UD side. Please review.

@garagatyi I've tested the configuration with wsmaster and wsagent(s) on remote hosts using traefik. It worked but that wasn't as easy as I thought. Should work better once that [traefik issue](https://github.com/containous/traefik/issues/444) get addressed. I will share the config here and we will discuss how to proceed.

Meanwhile I'll rename this PR as [WIP]

**Comment by TylerJewell** [comment]
@l0rd - can you post the configuration that you are using for testing?  Is the basic setup that che server and workspaces are on a remote VM, and the browser is on a different IP, and this configuration will now work without having to set CHE_HOST_IP or set --remote:ip?

If so - can you also post your traefik configuration? Will this traefik configuration allow for the possibility of routing all browser -> ws communications through a single port, with traefik redirecting traffic back to the right ephemeral port within the ws?

Thanks for working on this - very important - improvement.

**Comment by l0rd** [comment]
@TylerJewell Here are the details of how I've used Traefik to support the scenario where the Che Server and the Docker host are in different remote servers.

### The setup

 I've built my branch (`ws-url-fix`) and I've run Che using the following command `bin/che.sh run --remote:<ip> -s:uid`. 

On MacOS with Docker toolbox, running Che this way starts the server as java web app and the workspaces as containers in the guest OS (boot2docker). 

Server and workspaces have different IPs and that's the scenario I needed to test.

image

## Testing
- Run Che server 'bin/run.sh --remote:<ip> -s:uid`
- Open Che UD at http://localhost:8080
- Create a new workspace and confirm that:
  - The workspace is created successfully but...
  - The the browser failed to connect to it (the websocket tried to connecto to http://localhost:32773 instead of http://192.168.99.100:32773)
- Start traefik using the following configuration file (`./traefik -c traefik.toml` ). Now websockets can access the workspace container and the IDE is fully functional.

``` toml
# 192.168.99.100 is the VM IP 
# 32775 to 32781 are the ports exposed by the workspace

logLevel = "DEBUG"
defaultEntryPoints = ["http", "https"]

# Enable web console
[web]
address = ":8081"

# Entrypoints
[entryPoints]
   [entryPoints.wsagent1]
   address = ":32775"
   [entryPoints.wsagent2]
   address = ":32776"
   [entryPoints.wsagent3]
   address = ":32777"
   [entryPoints.wsagent4]
   address = ":32778"
   [entryPoints.wsagent5]
   address = ":32779"
   [entryPoints.wsagent6]
   address = ":32780"
   [entryPoints.wsagent7]
   address = ":32781"
   [entryPoints.wsagent8]
   address = ":32782"
   [entryPoints.wsagent9]
   address = ":32783"


[file]
# Frontends
[frontends]
    [frontends.wsagent1]
    backend = "backend1"
    passHostHeader = true
    entrypoints = ["wsagent1"]
        [frontends.wsagent1.routes.defaultroute]
        rule = "Host:localhost,{subdomain:[a-z]+}.localhost"

    [frontends.wsagent2]
    backend = "backend2"
    passHostHeader = true
    entrypoints = ["wsagent2"]
        [frontends.wsagent2.routes.defaultroute]
        rule = "Host:localhost,{subdomain:[a-z]+}.localhost"

    [frontends.wsagent3]
    backend = "backend3"
    passHostHeader = true
    entrypoints = ["wsagent3"]
        [frontends.wsagent3.routes.defaultroute]
        rule = "Host:localhost,{subdomain:[a-z]+}.localhost"

    [frontends.wsagent4]
    backend = "backend4"
    passHostHeader = true
    entrypoints = ["wsagent4"]
        [frontends.wsagent4.routes.defaultroute]
        rule = "Host:localhost,{subdomain:[a-z]+}.localhost"

    [frontends.wsagent5]
    backend = "backend5"
    passHostHeader = true
    entrypoints = ["wsagent5"]
        [frontends.wsagent5.routes.defaultroute]
        rule = "Host:localhost,{subdomain:[a-z]+}.localhost"

    [frontends.wsagent6]
    backend = "backend6"
    passHostHeader = true
    entrypoints = ["wsagent6"]
        [frontends.wsagent6.routes.defaultroute]
        rule = "Host:localhost,{subdomain:[a-z]+}.localhost"

    [frontends.wsagent7]
    backend = "backend7"
    passHostHeader = true
    entrypoints = ["wsagent7"]
        [frontends.wsagent7.routes.defaultroute]
        rule = "Host:localhost,{subdomain:[a-z]+}.localhost"

[backends]
  [backends.backend1]
    [backends.backend1.servers.server1]
    url = "http://192.168.99.100:32775"
  [backends.backend2]
    [backends.backend2.servers.server2]
    url = "http://192.168.99.100:32776"
  [backends.backend3]
    [backends.backend3.servers.server3]
    url = "http://192.168.99.100:32777"
  [backends.backend4]
    [backends.backend4.servers.server4]
    url = "http://192.168.99.100:32778"
  [backends.backend5]
    [backends.backend5.servers.server5]
    url = "http://192.168.99.100:32779"
  [backends.backend6]
    [backends.backend6.servers.server6]
    url = "http://192.168.99.100:32780"
  [backends.backend7]
    [backends.backend7.servers.server7]
    url = "http://192.168.99.100:32781"
```

## Considerations
- Next step could be to extend the che launcher with a new command that generates the configuration and start Traefik. But that's not a long term solution: Traefik is able to auto-configure itself listening to Docker events and should be used this way.
- A long term solution would be to use labels when creating workspaces (`docker run -l traefik...`). Frontends and beckends sections would be set/updated as soon as the container is started. Unfortunately a current Traefik limitation doesn't allow to configure multiple routes for one container that has multiple ports. And Che workspaces have 6 exposed ports.
- Another limitation is that Traefik entrypoints cannot be updated dynamically. As a consequence every time a new workspace is created, 6 extra entrypoints need to be added and traefik need to be restared. A solution could be to the same 6 entrypoints for all the Che workspaces. Using for example the workspaces internal ports as entrypoint addresses (8000, 8080, 9876, 22, 4401, 4403, 4411) and infer the route to the right backend based on HTTP Header.

**Comment by TylerJewell** [comment]
@l0rd - thanks for the contribution!

It's taken me some time to get around to reviewing this, but I have been through it now, and understand the approach and the analysis.

A few questions - these may be ignorant based upon my limited understand how multi-host or reverse proxies work. This area of technology is not my strong suit.

1:  If the browser is sending all port communications to the same host that the Che server is running on, then what are the types of code changes that are being made?  If the solution that you are proposing by adding in a reverse proxy communicating on the same host as the che-server, and that proxy is going to look for all communications over certain ports (to forward), shouldn't this solution work without any Che server code modifications?

2: Out of curiosity, what are the pros / cons of modifying the Che server to proxy these communications to the related workspace?  

BTW - I now recognize the power of Traefik - it really allows for moment-in-time reverse proxy deployment. We could deploy 1..n reverse proxies on-demand alongside a Che server or other system to be used as special purpose configurations to solve certain challenges with networking in multi-host situations.

**Comment by l0rd** [comment]
@TylerJewell 
1. Short term solution only need the changes already included in this PR (and these changes are needed). Long term solution should modify the che-server to add labels when running a new container.
2. Adding reverse proxy capability within Che would be possible and users would not need to use an external tool but:
   - 99% of Che users won't need a reverse proxy
   - building a reverse proxy is hard (think about the network performances)

**Comment by TylerJewell** [comment]
@l0rd - I am unsure of the path forward needed to let us merge these changes.  Is there perhaps an environment variable that we can set on the command line which would then trigger the che-launcher to launch a traefik reverse proxy?

If so, let's include those improvements into this PR and then launch the CLI, che-launcher and these improvements together.  Can you suggest additional command-line configuration details that would be present that would trigger this configuration?  Then we can make improvements together on the che-launcher and che cli.  I like this approach.

We will also need to do some detailed docs together.

**Comment by garagatyi** [comment]
I think that this PR is not needed anymore. #2402 is next idea on how to workaround the problem.
@l0rd  can we close this PR?

**Comment by l0rd** [comment]
@garagatyi I would prefer to keep it open. I would like to continue the work to integrate Traefik in the che-launcher here. I'm waiting proposal containous/traefik#444 is addressed before going any further.

**Comment by garagatyi** [comment]
Can you try idea from #2402 with IPTables? I think it would be even better than usage of traefik.

**Comment by l0rd** [comment]
Yes I'm trying that idea right now :-). That should fix the Docker for Mac issue.

However Traefik would add the ability to start a reverse proxy automatically configured to route requests to Che and the containers. That could still be valuable. wdyt @garagatyi?

**Comment by garagatyi** [comment]
What use-cases are covered by this approach?

**Comment by l0rd** [comment]
https://en.wikipedia.org/wiki/Reverse_proxy

**Comment by garagatyi** [comment]
I understand what reverse proxy is. I just want to understand what profit will get Che if we use reverse proxy in it?

**Comment by l0rd** [comment]
The "Uses of reverse proxy" section explains what are the benefits of a reverse proxy. In particular:

> - Reverse proxies can hide the existence and characteristics of an origin server or servers.
> - Reverse proxies can operate wherever multiple web-servers must be accessible via a single public IP address. The web servers listen on different ports in the same machine, with the same local IP address or, possibly, on different machines and different local IP addresses altogether. The reverse proxy analyzes each incoming request and delivers it to the right server within the local area network.

could make sense for Che.

**Comment by TylerJewell** [comment]
I think we want to continue exploring the embedded reverse proxy approach for the following use cases:
1. Users want to eventually route all traffic through a single port for both ws master & agents.  We'd need a central proxy to handle such traffic.
1. Users want to distribute che server and docker daemon onto different IPs - we can use a reverse proxy to manage that, if the iptables approach is not sufficient.

**Comment by l0rd** [comment]
A quick update on this PR. It was initially opened to fix issue #1644. This issue has now been fixed with #2402 but we would like to continue working on this PR for the use cases listed by @TylerJewell and to allow Che workspaces to run with OpenShift routes.

The goal would be to be able to contact a workspace service (e.g. wsagent) on port 80 or 443 using a specific hostname (e.g. `servicename.workspacename.mychehost.com`) and avoid exposing ephemeral TCP ports publicly.

Work on that PR should start as soon as Che will be able to start and stop workspaces as OpenShift pods (second bullet of #2847).

**Comment by TylerJewell** [comment]
This would be a substantial improvement - being able to hide the ephemeral ports - many people have asked for that.

**Comment by TylerJewell** [comment]
@l0rd - what is our plan with this PR given the release of 5.0?

**Comment by TylerJewell** [comment]
From a meeting with Red Hat. The current plan for this issue is that this will be replaced with a different implementation. The focus of the implementation will be to provide a new URL resolution strategy that allows browsers to channel traffic through a single Che port. Mario will open this new PR in the next couple weeks and then we will close this PR.

**Comment by l0rd** [comment]
This PR has been replaced by https://github.com/eclipse/che/pull/4351

**Pull request closed without merging**
