### PR TITLE
Update Lucene to 7.0.1

### PR DESCRIPTION
**Pull request by benoitf**
before merge:
- [x] Requires https://github.com/eclipse/che-dependencies/pull/67 to be merged
- [x] delete the commit that is increasing the version from this PR

### What does this PR do?
Update Lucene to version 7.0.1 which is java9 compliant

### What issues does this PR fix or reference?
#5326 

#### Release Notes
N/A

#### Docs PR
N/A

### CODE REVIEW

**Comment by benoitf** [comment]
ci-build

**Comment by vparfonov** [comment]
ci-test

**Comment by benoitf** [comment]
ci-build

**Comment by benoitf** [comment]
@vparfonov @musienko-maxim are the tests ok ? as there are some failures

**Comment by musienko-maxim** [comment]
Changes broke `FindTextTest`. Test has fallen because any occurrence that starts with Upper case won't be found.

**Comment by benoitf** [comment]
@musienko-maxim thanks

**Comment by benoitf** [comment]
ci-build

**Comment by benoitf** [comment]
ci-test

**Comment by benoitf** [comment]
@musienko-maxim could you check the new result of tests it seems I've fixed regressions

**Comment by benoitf** [comment]
ci-test

**Comment by musienko-maxim** [comment]
Last iteration of the tests did not find a regression

**Review by vparfonov — APPROVED** [review]

**Review by svor — APPROVED** [review]

**Pull request merged**
