### PR TITLE
Remove Eclipse Che Launcher: it has been supersede by new Docker CLI

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
It removes Eclipse Che launcher docker image. it has been supersede by new Docker CLI

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/3423#issuecomment-268056349

### Tests written?
No

### Docs updated?
AFAIK the launcher image is not anymore in the documentation

#### Changelog
Remove Eclipse Che Launcher: it has been supersede by new Docker CLI

### CODE REVIEW

**Comment by TylerJewell** [comment]
Let's also remove che.sh, che.bat, cli.sh, and Vagrantfile from the root of the repo, too.

**Review by TylerJewell — APPROVED** [review]

**Comment by benoitf** [comment]
@TylerJewell it's in https://github.com/eclipse/che/pull/3780 (I need to add as well Vagrantfile)

**Comment by TylerJewell** [comment]
Great, thanks.

**Comment by benoitf** [comment]
@l0rd and @riuvshin it's ok for you ?

**Review by l0rd — APPROVED** [review]

**Review by riuvshin — APPROVED** [review]

**Pull request merged**
