### PR TITLE
Add/Update OpenShiftConnector tests

### PR DESCRIPTION
**Pull request by amisevsk**
Add tests for OpenShift helper classes. There is still no test coverage for OpenShiftConnector itself, but I also can't see a good way of writing meaningful tests for that class.

### CODE REVIEW

**Comment by amisevsk** [comment]
@sunix I've rebased this PR onto the `openshift-connector-rebased` branch. Should make your life a little easier :)

**Comment by sunix** [comment]
@amisevsk thanks !!!

**Comment by amisevsk** [comment]
@sunix I've added tests for OpenShiftWorkspaceFilesCleaner and rebased again.

**Review by sunix — APPROVED** [review]
LGTM

**Pull request merged**
