### PR TITLE
[DO NOT MERGE] Add logging content of mounted namespace file

### PR DESCRIPTION
**Pull request by sleshchenko**
### What does this PR do?
PR is created to debug CI tests job. It adds logging content of mounted namespace file to clarify the cause of failure.

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/10916

### CODE REVIEW

**Comment by riuvshin** [comment]
ci-test

**Comment by sleshchenko** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/654/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/654//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10923)
docker image: eclipseche/che-server:10923
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by sleshchenko** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/655/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/655//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10923)
docker image: eclipseche/che-server:10923
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by riuvshin** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/658/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/658//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10923)
docker image: eclipseche/che-server:10923
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by skabashnyuk** [comment]
@sleshchenko I would suggest using guava instead of commons-io. It's much more maintainable and less conflict library.
```
URL url = Resources.getResource("foo.txt");
String text = Resources.toString(url, Charsets.UTF_8);
```

**Comment by sleshchenko** [comment]
@skabashnyuk Thanks. I'll use guava in further PRs.

@riuvshin looks like it's more OCP 3.10 issues than ours. 
Should we close this PR or it makes sense to investigate issues more?

**Comment by riuvshin** [comment]
@sleshchenko we can close it... since we've reverted to 3.9

**Pull request closed without merging**
