### PR TITLE
17178 use GITHUB_REF if set, or else use...

### PR DESCRIPTION
**Pull request by nickboldt**
### What does this PR do?

https://github.com/eclipse/che/issues/17178 use GITHUB_REF if set, or else use github.event.inputs.version for manual runs
fail if no release_version set; add quotes
add sinceTag to restrict to only issues in this week's release
set onlyLastTag:false to enable sinceTag and dueTag
use steps.prepare.outputs instead of github.event.prepare
exclude more labels: sprint/next, roadmaps, planning, dupes, in-progress and triage
fix formatting of bugs and enhancements

Change-Id: I4c995aaab82dbc81432e5d02af17e7ed0e927a96
Signed-off-by: nickboldt <nboldt@redhat.com>

### Screenshot/screencast of this PR
N/A

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/17178

### How to test this PR?
(see below)

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works, if one exists](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections What issues does this PR fix or reference and How to test this PR completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by nickboldt** [comment]
Running in https://github.com/eclipse/che/runs/2291150990?check_suite_focus=true

Results in https://github.com/eclipse/che/releases/tag/7.28.2

(I've already iterated this in 7.28.x branch to get it working this far.)

**Comment by sparkoo** [comment]
Looking at the https://github.com/eclipse/che/releases/tag/7.28.2 changelog, I'm confused. What's the difference between "Fixed Bugs:", "Issues in Current Sprint:" and "Closed issues:" ? Dedicated category for "New and Noteworthy Issues:" imho does not make much sense as well. What about split it into "Epics" (kind/epic), "Bugfixes" (kind/bug), "Improvements" (kind/task|enhancement|technical-debt), "Others" (kind/question|release (planning?) ) ? + Put main release issue (like https://github.com/eclipse/che/issues/19520) on top. wdyt?

**Comment by nickboldt** [comment]
Good questions! 

* "Fixed Bugs:" vs. "Closed issues:" -- not sure, but I think...
- Fixed bugs = kind/bug - https://github.com/eclipse/che/blob/7.28.x/.github/workflows/release-changelog.yml#L90-L91
- Closed issues = `issues:true` - https://github.com/eclipse/che/blob/7.28.x/.github/workflows/release-changelog.yml#L80

Do you see duplicates in those lists?

* Issues in current sprint are issues with "sprint/current" label - see https://github.com/eclipse/che/blob/7.28.x/.github/workflows/release-changelog.yml#L84

> Put main release issue on top

I'm specifically excluding the `kind/release` items since they're 95% of the time boilerplate with nothing interesting. Those issues only contain useful info if there's a hold on the release because dev needs more time before the Wed morning release start time that we put stuff in there, or if there's a release process blocker, like this week w/ DWCO integration. And those issues usually get closed AFTER the release (che release part happens quickly, but the release issue is closed AFTER chectl is released, hours or days later), so we'd see the 7.28.2 release issue in the 7.29.0 list, where it's meaningless and confusing. 

> Dedicated category for "New and Noteworthy Issues:" imho does not make much sense as well.

Disagree 100%. The whole point of having those labels is to make it easier to find the N&N items for each release. By generating that list every week, we can easily see what noteworthy changes have happened amidst the 50ish issues/PRs committed that week.

We can include tech debt items and tasks, if that's valuable. But I don't think the changelog should include planning items and questions. Those don't really define what HAS CHANGED but what WILL CHANGE. 

@l0rd @benoitf WDYT?

**Comment by sparkoo** [comment]
> 
> Do you see duplicates in those lists?

TBH I don't know. If I look at any changelog, I want to know what bugs were fixed, and what new features got into that release. I don't care about any labels, sprints etc.

> 
> I'm specifically excluding the `kind/release` items since they're 95% of the time boilerplate with nothing interesting. Those issues only contain useful info if ...

ok, you know better usefulness of these `kind/release` issues

> 
> > Dedicated category for "New and Noteworthy Issues:" imho does not make much sense as well.
> 
> Disagree 100%. The whole point of having those labels is to make it easier to find the N&N items for each release. By generating that list every week, we can easily see what noteworthy changes have happened amidst the 50ish issues/PRs committed that week.

I understand purpose of this label only to be able to filter interesting new issues. But at the end, they are either bugs or improvements as others. Maybe they can be put at the top of the bugs/improvements list, but having them in dedicated group is imho more confusing than useful. But maybe I misunderstand this label.

> 
> > "Improvements" (kind/task|enhancement|technical-debt), "Others" (kind/question|release (planning?) ) ?
> 
> We can include **tech debt** items and **tasks**, if that's valuable. But I don't think the changelog should include **planning** items and **questions**. Those don't really define what HAS CHANGED (past) but what COULD CHANGE (future).

makes sense

> 
> We have "Enhancements, Epics, and UX", derived from labels = kind/enhancement,kind/epic,kind/ux - https://github.com/eclipse/che/blob/7.28.x/.github/workflows/release-changelog.yml#L88-L89

Thinking about it, I would probably not make dedicated group for "Enhancements, Epics, and UX". I'm for starting with something really simple, only "bugfixes" (`kind/bug`) and "improvements" (everything except `kind/bug|planning|release|...`). Then if we see it's not enough for us, we can iterate.

Anyway, I would like to hear opinion of others on this topic.

**Comment by skabashnyuk** [comment]
code moved to https://github.com/eclipse-che/che-server/

**Comment by l0rd** [comment]
@nickboldt should we continue working on this PR? What I would like is that we filter out new and noteworthy issues only for each release.

**Pull request closed without merging**
