### PR TITLE
IDEX-3919

### PR DESCRIPTION
**Pull request by mmorhun**
Update dependencies for che-core-api-module

### CODE REVIEW

**Comment by skabashnyuk** [comment]
other ok. @vparfonov ?

**Comment by benoitf** [comment]
CLA is not signed

**Comment by benoitf** [comment]
Eclipse CLA status

**Comment by skabashnyuk** [comment]
Eclipse CLA confirmed for mmorhun@codenvy.com Eclipse CLA confirmed

**Comment by skabashnyuk** [comment]
PR is ok

**Comment by benoitf** [comment]
yes now email is correct

**Comment by vparfonov** [comment]
ok

**Pull request merged**
