### PR TITLE
DO NOT MERGE

### PR DESCRIPTION
**Pull request by riuvshin**
DO NOT MERGE

### CODE REVIEW

**Comment by riuvshin** [comment]
ci-build

**Comment by riuvshin** [comment]
Build success. https://ci.codenvycorp.com/job/che-pullrequests-build/4576/

**Comment by riuvshin** [comment]
ci-build

**Review by vparfonov — APPROVED** [review]

**Comment by riuvshin** [comment]
ci-build

**Comment by riuvshin** [comment]
ci-build

**Comment by riuvshin** [comment]
ci-build

**Comment by riuvshin** [comment]
ci-build

**Comment by riuvshin** [comment]
ci-build

**Comment by riuvshin** [comment]
ci-build

**Comment by riuvshin** [comment]
ci-build

**Comment by riuvshin** [comment]
ci-build

**Comment by riuvshin** [comment]
ci-build

**Pull request closed without merging**
