### PR TITLE
Used Google Java Codestyle

### PR DESCRIPTION
**Pull request by skabashnyuk**
### What does this PR do?
1. In current pr I've made formatting for all Java source code with  ```mvn com.coveo:fmt-maven-plugin:format``` . This plugin uses this Google's tool https://github.com/google/google-java-format to apply ```Google Java codestyle``` to all our source code. 

2. In this pr https://github.com/eclipse/che-parent/pull/21 I've enabled ```check``` phase of fmt-maven-plugin  by default. So if any formatting is missing you'll see

To fix it, you need to execute  ```mvn fmt:format```

3. To help you have the same format with you tool you can reuse IntelliJ or Eclipse code format. see more https://github.com/google/google-java-format or  https://google.github.io/styleguide/javaguide.html.

4. If IntelliJ or Eclipse plugin produces some difference with maven plugin. Maven plugin wins. It's last ```Single source of truth```

### What issues does this PR fix or reference?
 https://github.com/eclipse/che/issues/5772
Related to 
https://github.com/eclipse/che-lib/pull/34
https://github.com/eclipse/che-parent/pull/21

### CODE REVIEW

**Review by riuvshin — APPROVED** [review]

**Comment by riuvshin** [comment]
ci-build

**Review by tolusha — APPROVED** [review]

**Review by evidolob — APPROVED** [review]

**Review by vparfonov — APPROVED** [review]

**Review by garagatyi — APPROVED** [review]

**Review by l0rd — APPROVED** [review]

**Comment by slemeur** [comment]
What about this wiki page: https://github.com/eclipse/che/wiki/Coding-Guidelines 

Are you also planning to extend the development workflow guide with the information in the description of the issue: https://github.com/eclipse/che/wiki/Development-Workflow#code-style ?

**Comment by skabashnyuk** [comment]
@slemeur I'll revise header if this issues with @eivantsov and will provide content for https://github.com/eclipse/che/wiki/Development-Workflow#code-style.  https://github.com/eclipse/che/wiki/Coding-Guidelines eventually will be removed with link to https://google.github.io/styleguide/javaguide.html

**Comment by ghost** [comment]
https://github.com/eclipse/che/wiki/Development-Workflow#code-style and https://github.com/eclipse/che/wiki/Coding-Guidelines updated

**Comment by slemeur** [comment]
thanks guys.

**Pull request merged**
