### PR TITLE
Do not inform language server about file rename for not registered file type

### PR DESCRIPTION
**Pull request by RomanNikitenko**
### What does this PR do?
Do not inform language server about file rename for not registered file type

Signed-off-by: Roman Nikitenko <rnikiten@redhat.com>

### CODE REVIEW

**Review by vzhukovs — APPROVED** [review]

**Review by dkulieshov — APPROVED** [review]

**Comment by RomanNikitenko** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1132/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1132//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11825
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by RomanNikitenko** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1138/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1138//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11825
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Pull request merged**
