### PR TITLE
Add the re-selection of the project in the test 'AmendCommitTest'

### PR DESCRIPTION
**Pull request by artaleks9**
### What does this PR do?
* Add the re-selection of the project in the selenium test _AmendCommitTest_ to increase stabilty when run it on CI
* Use the static imports for calling _Menu_ commands 

### What issues does this PR fix or reference?
#10520

### CODE REVIEW

**Review by SkorikSergey — APPROVED** [review]

**Review by Ohrimenko1988 — APPROVED** [review]

**Comment by artaleks9** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/513/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/513//Selenium_tests_report)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10526)
docker image: eclipseche/che-server:10526
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by artaleks9** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/515/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/515//Selenium_tests_report)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10526)
docker image: eclipseche/che-server:10526
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Pull request merged**
