### PR TITLE
Fix authentication error when non-root path requested

### PR DESCRIPTION
**Pull request by mshaposhnik**
### What does this PR do?
When secure enpoint requested first time, IDE loader makes request to an endpoint to obtain cookies by appending `jwt/auth` part, like: 
`http://routed1h37d2q-admin-che.192.168.99.114.nip.io/jwt/auth`
If non-root resource requested, URL becames invalid like 
`http://routed1h37d2q-admin-che.192.168.99.114.nip.io/vs/editor/editor.main.cssjwt/auth`

Since we cannot remove the `path` part of URL due to single-host mode which uses path to differentiate servers, we need to do auth requests not using full initial redirect URL but the base URL which is set in approppriate server.

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/15430

#### Release Notes
N/A

#### Docs PR
None

### CODE REVIEW

**Review by mmorhun — APPROVED** [review]

**Comment by mshaposhnik** [comment]
ci-build

**Comment by mshaposhnik** [comment]
ci-test

**Comment by skabashnyuk** [comment]
>Since we cannot remove the path part of URL due to single-host mode which uses path to differentiate servers, we need to do auth requests not using full initial redirect URL but the base URL which is set in approppriate server.

Can you please provide more examples here?

**Comment by mshaposhnik** [comment]
@skabashnyuk 
In case of single host mode, cookie URL is `http://<route-xxx>/service/server/jwt/auth` - it's valid URL
In case of multi host but non-root request, cookie URL is `http://<route-xxx>/some_user_path/jwt/auth` which is incorrect. We cannot differentiate that in loader,  So we sill use URL from server itself, not the one which user requested. So it will be 
`http://<route-xxx>/service/server/jwt/auth` or `http://<route-xxx>/jwt/auth` which is both valid cases.

**Review by skabashnyuk — APPROVED** [review]

**Review by metlos — APPROVED** [review]
Genius!

As a small nitpick - maybe we should update the docs on the `asyncCheckServiceLink` method. The docs are highly misleading :)

**Comment by mshaposhnik** [comment]
crw-ci-test

**Pull request merged**
