### PR TITLE
CHE-715 change some workspace service paths

### PR DESCRIPTION
**Pull request by mshaposhnik**
**_2 Upvotes**_ Signed-off-by: Max Shaposhnik mshaposhnik@codenvy.com

### CODE REVIEW

**Comment by mshaposhnik** [comment]
@skabashnyuk @ashumilova @vparfonov @evoevodin

**Comment by voievodin** [comment]
https://github.com/eclipse/che/blob/32136b917abbc33693c2fe1daf2902c8c8d78837/dashboard/src/components/api/remote/che-remote-workspace.js#L30-L30

**Comment by sleshchenko** [comment]
Typo in commit message

**Comment by ashumilova** [comment]
+1

**Comment by skabashnyuk** [comment]
ok

**Comment by voievodin** [comment]
+1

**Pull request merged**
