### PR TITLE
Continue recovering workspaces when unchecked exception is thrown

### PR DESCRIPTION
**Pull request by amisevsk**
### What does this PR do?
This PR is broken into two commits:

- The first commit refactors `WorkspaceRuntimes` slightly (sorting methods, etc) to put them into the normal order (static, then public, then private, then private classes).
- The second commit ensures that runtimes recovery completes in case of an unchecked exception being thrown, instead of ending recovery early.

### What issues does this PR fix or reference?
When an unchecked exception is thrown, recovery stop and the internal runtime cache does not get fully populated. This interferes with things like the consistency check.

For example, in rhche we encounter the error 
```
java.lang.IllegalArgumentException: Environment contains '2' machines with wsagent server. Machines names: '[web/main, web/mysql]'
at org.eclipse.che.api.workspace.server.WsAgentMachineFinderUtil.getWsAgentServerMachine(WsAgentMachineFinderUtil.java:63)
at org.eclipse.che.api.workspace.server.spi.provision.ProjectsVolumeForWsAgentProvisioner.provision(ProjectsVolumeForWsAgentProvisioner.java:51)
at org.eclipse.che.api.workspace.server.spi.RuntimeInfrastructure.prepare(RuntimeInfrastructure.java:102)
at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.recoverOne(WorkspaceRuntimes.java:675)
at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$RecoverRuntimesTask.run(WorkspaceRuntimes.java:621)
at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:38)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
```

### CODE REVIEW

**Comment by amisevsk** [comment]
Rebased to avoid merge conflict.

**Review by garagatyi — APPROVED** [review]
Looks good

**Review by ibuziuk — APPROVED** [review]

**Comment by amisevsk** [comment]
ci-test

**Comment by amisevsk** [comment]
Not sure why build is failing, the logs are kind of unclear.

**Comment by ibuziuk** [comment]
ci-build

**Comment by ibuziuk** [comment]
@eclipse/eclipse-che-qa could you please provide approval from QA side, we want to have this change to be part of the 6.19.0 release cc @riuvshin

**Comment by SkorikSergey** [comment]
Selenium tests execution on Eclipse Che Multiuser on OCP (https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1582//Selenium_20tests_20report/) doesn't show any regression against this Pull Request.

**Comment by ibuziuk** [comment]
ci-build

**Review by sleshchenko — APPROVED** [review]
LGTM

**Pull request merged**
