### PR TITLE
move previewurl to stable

### PR DESCRIPTION
**Pull request by sparkoo**
### What does this PR do?
promotes previewurl in the devfile to stable `1.0.0` version and remove beta devfile version.

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/15412

#### Docs PR
https://github.com/eclipse/che-docs/pull/1025
https://github.com/redhat-developer/devfile/pull/57

### CODE REVIEW

**Review by mshaposhnik — APPROVED** [review]

**Review by skabashnyuk — APPROVED** [review]

**Review by sleshchenko — APPROVED** [review]

**Comment by sparkoo** [comment]
crw-ci-test

**Comment by sparkoo** [comment]
crw-ci-test

**Comment by sparkoo** [comment]
crw-ci-test

**Comment by sparkoo** [comment]
crw-ci-test

**Comment by sparkoo** [comment]
crw-ci-test

**Comment by sparkoo** [comment]
crw-ci-test

**Comment by sparkoo** [comment]
ci-test

**Comment by sparkoo** [comment]
crw-ci-test

**Review by rhopp — APPROVED** [review]
The test fialure is now expected. I'm working on a solution right now (issue: https://github.com/eclipse/che/issues/15586).
Anyway this PR looks fine to me and if you don't want to wait for my fixup of tests, feel free to merge ;-)

**Pull request merged**
