### PR TITLE
Adapt tests to multi-root workspaces related changes

### PR DESCRIPTION
**Pull request by RomanNikitenko**
Signed-off-by: Roman Nikitenko <rnikiten@redhat.com>

The changes should be merged together with https://github.com/eclipse/che-theia/pull/1053

### What does this PR do?
We are going to turn on the multi-root mode by default within https://github.com/eclipse/che-theia/pull/1053.  
The current changes adapt Happy Path tests to multi-root workspaces related changes.

### What issues does this PR fix or reference?

https://github.com/eclipse/che/issues/19390

### How to test this PR?

The Happy Path tests should pass for the https://github.com/eclipse/che-theia/pull/1053.

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Review by azatsarynnyy — APPROVED** [review]
LGTM

**Comment by SkorikSergey** [comment]
[crw-ci-test]

**Comment by RomanNikitenko** [comment]
@SkorikSergey 
The Happy path test for the current PR depends on the changes https://github.com/eclipse/che-theia/pull/1053

**Comment by rhopp** [comment]
We have cross-repo build configured in che-theia PR check and there, the PR check succeeded.
This PR seems simple enough. LGTM.
I guess the plan is to merge https://github.com/eclipse/che-theia/pull/1053 and soon after that merge this one, correct?

**Review by rhopp — APPROVED** [review]

**Comment by RomanNikitenko** [comment]
@rhopp 
thanks for the review!

About
> I guess the plan is to merge [eclipse/che-theia#1053](https://github.com/eclipse/che-theia/pull/1053) and soon after that merge this one, correct?

To be honest, I don't now what order is better for such cases.
So, I'll rely on your advise here...

**Comment by RomanNikitenko** [comment]
Today the question was raised - why the current PR was merged with unhappy tests.

To clarify it: 
I mentioned in the PR description:
> The current changes adapt Happy Path tests to multi-root workspaces related changes.

and 

> The changes should be merged together with eclipse-che/che-theia#1053

So, within current PR the tests were adapted to the changes on `che-theia` side: https://github.com/eclipse-che/che-theia/pull/1053

Also [in the comment](https://github.com/eclipse/che/pull/19406#issuecomment-808114023) I wrote that:
> The Happy path tests for the current PR depend on the changes eclipse-che/che-theia#1053

Finally, Radim (thanks!) [commented above](https://github.com/eclipse/che/pull/19406#issuecomment-808116762) that:
> We have cross-repo build configured in che-theia PR check and there, the PR check succeeded.  

It means that I had some changes on `che-theia` side and some adaptation for the `Happy path` tests in the current PR.
I used the mentioned by Radim mechanism to adapt (first) the `Happy Path` tests and (then) test that my changes in `che-theia` didn't break the tests. 
So, the tests actually have passed successfully [here](https://github.com/eclipse-che/che-theia/pull/1053#issuecomment-807643320).

I think it's more clear now.

**Pull request merged**
