### PR TITLE
Update RELEASE.md

### PR DESCRIPTION
**Pull request by vparfonov**

### CODE REVIEW

**Review by nickboldt — APPROVED** [review]

**Comment by nickboldt** [comment]
@vparfonov I tried to merge this but ci tests failed. You'll have to retrigger it I guess?

**Comment by nickboldt** [comment]
ci-test

**Comment by nickboldt** [comment]
ci-build

**Comment by benoitf** [comment]
ci-build

**Comment by benoitf** [comment]
ci-test

**Comment by benoitf** [comment]
crw-test

**Comment by benoitf** [comment]
crw-ci-test

**Comment by nickboldt** [comment]
thanks! love that I can merge a change **while tests are running** but not if tests have failed / stalled.

**Pull request merged**
