### PR TITLE
Remove unused docker version property

### PR DESCRIPTION
**Pull request by ghost**
We do not check Docker version, so this property isn't used anymore and it causes confusion.  

Signed-off-by: Eugene Ivantsov eivantsov@codenvy.com

### CODE REVIEW

**Comment by ghost** [comment]
@garagatyi @skabashnyuk please take a look

**Comment by azatsarynnyy** [comment]
I think that [DockerVersionVerifier](https://github.com/eclipse/che/blob/master/plugins/plugin-docker/che-plugin-docker-client/src/main/java/org/eclipse/che/plugin/docker/client/DockerVersionVerifier.java) should be removed as well

**Comment by garagatyi** [comment]
-1
We still have [class](https://github.com/eclipse/che/blob/867ec652424cd23a587f164f6acf3e8e44158bdf/plugins/plugin-docker/che-plugin-docker-client/src/main/java/org/eclipse/che/plugin/docker/client/DockerVersionVerifier.java) that uses that property even though it is not used anymore.
If you want to delete that property you should delete this class too.

**Comment by ghost** [comment]
Updated the PR

**Comment by garagatyi** [comment]
LGTM

**Comment by garagatyi** [comment]
@skabashnyuk @vparfonov Please take a look

**Comment by vparfonov** [comment]
ok

**Pull request merged**
