### PR TITLE
Fix the old-fashioned sample code (C++).

### PR DESCRIPTION
**Pull request by monaka**
### What does this PR do?

`$TITLE`

g++ in cpp-default stack can't compile it.

### What issues does this PR fix or reference?

No.

### CODE REVIEW

**Comment by monaka** [comment]
ci-build

**Comment by benoitf** [comment]
ci-build

**Comment by skabashnyuk** [comment]
ci-build

**Comment by skabashnyuk** [comment]
ci-test

**Review by vparfonov — APPROVED** [review]

**Comment by skabashnyuk** [comment]
@eclipse/eclipse-che-qa can you take a look?

**Comment by artaleks9** [comment]
Selenium tests execution on Eclipse Che Multiuser on OCP (https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1470/) doesn't show any regression against this Pull Request.

**Pull request merged**
