### PR TITLE
CHE-2300: fix usage of dockerfile as a source of machine in case of secured API

### LINKED ISSUE #2300: Creating new machine does not work
This bug is reproduced in the branch CHE-1818 on the local CHE.

**Reproduction Steps:**
1. Open the IDE and switch to the 'Operations Perspective'.
2. Got to 'Machine' -> 'Create..' and create new machine.

**Expected behavior:**
Should be created new machine.

**Observed behavior:**
New machine is not created.

**Che version:**   branch CHE-1818 
**OS and version:** Ubuntu 14.04  
**Docker version:**  1.11.1 
**Che install:**   local bundle  

**Additional information:**
See the attachment.
create-new-machine

### LINKED ISSUE #2426: NullPointer when starting a multi machine workspace
If a workspace contains more than one machine, workspace creation and boot fails

**Reproduction Steps:**
1. Create a workspace with the following custom recipe:

```

services:
 machine:
  image: codenvy/ubuntu_jdk8
  mem_limit: 2147483648
 dev-machine:
  image: codenvy/ubuntu_jdk8
  mem_limit: 2147483648
  depends_on:
    - machine
```

Client error:

image

Server logs:

```
2016-09-13 09:33:08,458[kspaceManager-0]  [ERROR] [o.e.c.a.w.s.WorkspaceManager 665]    - Start of environment wksp-afyi failed. Error: null
org.eclipse.che.api.core.ServerException: Start of environment wksp-afyi failed. Error: null
    at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.start(WorkspaceRuntimes.java:277) ~[che-core-api-workspace-5.0.0-M1-SNAPSHOT.jar:5.0.0-M1-SNAPSHOT]
    at org.eclipse.che.api.workspace.server.WorkspaceManager.lambda$performAsyncStart$1(WorkspaceManager.java:649) ~[che-core-api-workspace-5.0.0-M1-SNAPSHOT.jar:5.0.0-M1-SNAPSHOT]
    at org.eclipse.che.api.workspace.server.WorkspaceManager$$Lambda$94/2096118671.run(Unknown Source) [che-core-api-workspace-5.0.0-M1-SNAPSHOT.jar:5.0.0-M1-SNAPSHOT]
    at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalRunnable.run(CopyThreadLocalRunnable.java:28) [che-core-commons-lang-5.0.0-M1-SNAPSHOT.jar:5.0.0-M1-SNAPSHOT]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_31]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_31]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_31]
Caused by: java.lang.NullPointerException: null
    at org.eclipse.che.api.environment.server.CheEnvironmentEngine.applyAgents(CheEnvironmentEngine.java:517) ~[che-core-api-workspace-5.0.0-M1-SNAPSHOT.jar:5.0.0-M1-SNAPSHOT]
    at org.eclipse.che.api.environment.server.CheEnvironmentEngine.initializeEnvironment(CheEnvironmentEngine.java:492) ~[che-core-api-workspace-5.0.0-M1-SNAPSHOT.jar:5.0.0-M1-SNAPSHOT]
    at org.eclipse.che.api.environment.server.CheEnvironmentEngine.start(CheEnvironmentEngine.java:213) ~[che-core-api-workspace-5.0.0-M1-SNAPSHOT.jar:5.0.0-M1-SNAPSHOT]
    at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.start(WorkspaceRuntimes.java:246) ~[che-core-api-workspace-5.0.0-M1-SNAPSHOT.jar:5.0.0-M1-SNAPSHOT]
    ... 6 common frames omitted
```

### PR DESCRIPTION
**Pull request by garagatyi**
### What does this PR do?

Fixes usage of URL to dockerfile as a source/context of machine if URL points to API of Che.
Also adds some fixes and tests of agents usage.
### What issues does this PR fix or reference?

Fixes #2300 
Fixes #2426 
### Previous behavior

We sent url to dockerfile to the docker daemon. When API of Che is secured docker daemon was not able to download it.
### New behavior

We workaround that by downloading dockerfile if it is hosted by URL matching API endpoint of Che. Then we send tar context to docker daemon.
### PR type
- [x] Minor change = no change to existing features or docs
### Minor change checklist
- [x] Tests provided / updated
- [x] Tests passed

### CODE REVIEW

**Comment by garagatyi** [comment]
@skabashnyuk @evoevodin @tolusha Please review

**Comment by garagatyi** [comment]
@skabashnyuk @evoevodin @tolusha Please review

**Comment by tolusha** [comment]
OK concerning agents.

**Comment by skabashnyuk** [comment]
ok

**Comment by voievodin** [comment]
ok

**Pull request merged**
