### PR TITLE
fix dependency

### PR DESCRIPTION
**Pull request by akurinnoy**
Fix dependencies:
- remove angular-card
- add jQuery

related issue: https://github.com/eclipse/che/issues/1834

Signed-off-by: Oleksii Kurinnyi okurinnyi@codenvy.com

### CODE REVIEW

**Comment by olexii4** [comment]
+1

**Comment by riuvshin** [comment]
@skabashnyuk WDYT can we add `jquery": "2.1.4"` without CQ?

**Comment by ashumilova** [comment]
+1

**Comment by ashumilova** [comment]
https://docs.google.com/spreadsheets/d/10yhUKXOQX-UqUuV1LiYtDmfGqJ0lO5-MSihLigRFdDQ/edit#gid=0 We can use 2.1.3

**Comment by riuvshin** [comment]
@ashumilova you mean 2.1.3 ? should we downgrade to 2.1.3 in that PR?

**Comment by ashumilova** [comment]
yes, 2.1.3

**Comment by riuvshin** [comment]
OK, LGTM but please @akurinnoy make sure it works on Codenvy also.

**Comment by benoitf** [comment]
Is there a link to the PB CQ for jquery 2.1.3 ?

**Comment by akurinnoy** [comment]
@riuvshin Codenvy works fine on my side

**Comment by riuvshin** [comment]
@benoitf you mean this one https://dev.eclipse.org/ipzilla/show_bug.cgi?id=9503  ?

**Comment by benoitf** [comment]
@riuvshin this one is a a PB CQ but not for che

**Comment by riuvshin** [comment]
@benoitf yes it is for other project, but do we really need CQ for CHE with exactly same dependency? 
and can we merge this now?

**Comment by benoitf** [comment]
yes we need a PB like https://dev.eclipse.org/ipzilla/show_bug.cgi?id=9980

**Comment by benoitf** [comment]
https://wiki.eclipse.org/Development_Resources/Contribution_Questionnaire#Piggyback_CQs

**Comment by riuvshin** [comment]
I see, so please some one create CQ for that. and let me know when it will be merged.

**Comment by ashumilova** [comment]
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=11695

**Comment by benoitf** [comment]
1.8.1 is approved with PB CQ https://dev.eclipse.org/ipzilla/show_bug.cgi?id=10801

**Pull request merged**
