### PR TITLE
Fix e2e tests after GetStarted -> CreateWorkspace

### LINKED ISSUE #19557: Happy path E2E tests are failing on "Validation of workspace start" step
### Describe the bug
Happy path tests are failing on "**Validation of workspace start**" step:
```
1) Start workspace
Error: R] CheReporter runner.on.fail: Validation of workspace start Start workspace failed after 242236ms
  1 passing (4m)
  1 failing
  1) Validation of workspace start
       Start workspace:
     TimeoutError: Exceeded maximum visibility checkings attempts for 'By(xpath, //div[@id='page-sidebar']//a[text()='Workspaces'])' element, timeouted after 240000
      at DriverHelper.waitVisibility (/tmp/e2e/utils/DriverHelper.ts:156:15)
      at process._tickCallback (internal/process/next_tick.js:68:7)
```

Recent changes in Dashboard: https://github.com/eclipse/che-dashboard/pull/208
Related task: https://github.com/eclipse/che/issues/18980

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
Run Happy path tests against nightly Eclipse Che

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] Dev Sandbox (workspaces.openshift.com)
   - [ ] other: please specify

### PR DESCRIPTION
**Pull request by sleshchenko**
### What does this PR do?
Fix e2e tests after GetStarted -> CreateWorkspace.

### What issues does this PR fix or reference?
It fixes https://github.com/eclipse/che/issues/19557
It adapts tests after https://github.com/eclipse/che-dashboard/pull/208

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [ ] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [ ] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [ ] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by dmytro-ndp** [comment]
[crw-ci-test --rebuild]

**Review by Katka92 — APPROVED** [review]

**Review by Ohrimenko1988 — CHANGES_REQUESTED** [review]
Needs to be verified manually, because the "Happy-Path" test doesn't use changed dashboard pages and can't validate changes.
Let me verify that. I'll share results.

**Comment by sleshchenko** [comment]
@Ohrimenko1988 thanks a lot. Let me know if more help is needed.
FYI I've pushed these changes into https://github.com/eclipse/che/tree/multiRootBackCompatibility for https://github.com/eclipse-che/che-theia/pull/1074 to pick up made changes. But you know better how to verify that.

**Review by Ohrimenko1988 — APPROVED** [review]

**Review by sleshchenko — COMMENTED** [review]
LGTM after Ihor's changes

**Pull request merged**
