### PR TITLE
Rework the "Terminal.getText" method for avoiding tests failures

### PR DESCRIPTION
**Pull request by Ohrimenko1988**
### What does this PR do?
Rework the "Terminal.getText" method for avoiding tests failures
Fix problem with "NoSuchWindow" problem

### What issues does this PR fix or reference?
Issue: https://github.com/eclipse/che/issues/17343

### CODE REVIEW

**Comment by Ohrimenko1988** [comment]
[crw-ci-test]

**Comment by Ohrimenko1988** [comment]
crw-ci-test

**Comment by Ohrimenko1988** [comment]
[crw-ci-test]

**Comment by dmytro-ndp** [comment]
[crw-ci-test]

**Review by dmytro-ndp — APPROVED** [review]

**Comment by dmytro-ndp** [comment]
I have reverted [recent changes changes](https://github.com/eclipse/che/pull/17281#issuecomment-655054545) to fix test workspaces removal error.

**Pull request merged**
