### PR TITLE
CHE-3218: improves the documentation popup for LSP code completion

### LINKED ISSUE #3218: Issues with documentation popup for LSP code completion
The documentation popup for LSP code completion has some shortcomings:
- No scrollbars
- The documentation is displayed in plain text. Although LSP does not enforce any particular format yet (see https://github.com/Microsoft/language-server-protocol/issues/111), popular documentation formats like JavaDoc and PHPDoc contain HTML tags. It would be better to render them instead of displaying them raw, thus making the documentation more readable.
- Clicking on the popup hides it, thus making impossible to select and copy some text from the documentation.
- Flickering of the popup while typing

**Reproduction Steps:**

1. Build from the latest master.
2. Start a workspace with the PHP stack and some project sample.
3. Open the PHP editor.
4. Invoke code completion and wait for the documentation popup to appear.

**Expected behavior:**

- Scrollbars when necessary
- HTML tags are rendered
- Possible to select and copy some text from the documentation
- No flickering while typing

**Observed behavior:**

image

**Che version:**    latest master
**OS and version:** Fedora 24
**Docker version:** 1.10.3
**Che install:**    server (zip)

**Additional information:**

* Problem started happening recently, didn't happen in an older version of Che: [No]
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]

### PR DESCRIPTION
**Pull request by kaloyan-raev**
### What does this PR do?

Improves the documentation popup for LSP code completion.

### What issues does this PR fix or reference?

Fixes #3218

### Previous behavior

image

### New behavior

- Scrollbars when necessary
- HTML tags are rendered
- Possible to select and copy some text from the documentation
- No flickering while typing

image

Signed-off-by: Kaloyan Raev <kaloyan.r@zend.com>

### CODE REVIEW

**Comment by kaloyan-raev** [comment]
ci-build

**Comment by benoitf** [comment]
ci-build

**Comment by kaloyan-raev** [comment]
ci-build

**Comment by kaloyan-raev** [comment]
@benoitf I am a committer now, but the "ci-build" trick does not seem to work for me. Could you check if any configuration needs to be done?

**Comment by TylerJewell** [comment]
@kaloyan-raev @vparfonov - let's have this merged.  If there are open questions for Kaloyan, then we should get those addressed.

**Comment by benoitf** [comment]
ci-build

**Pull request merged**
