### PR TITLE
Set font to Roboto. Align popup text to the left.

### PR DESCRIPTION
**Pull request by mmorhun**
### What does this PR do?
Updates Che theme for Keycloak according to @bmicklea remarks during demo meeting:
- Sets font to Roboto
- Sets alignment of notifications to the left

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/5786

### CODE REVIEW

**Review by vkuznyetsov — APPROVED** [review]

**Review by benoitf — APPROVED** [review]

**Review by riuvshin — APPROVED** [review]

**Review by skabashnyuk — APPROVED** [review]

**Comment by slemeur** [comment]
@mmorhun Thanks ! Could you please attach a screenshot to show your changes?

**Comment by benoitf** [comment]
the font looks different from http://www.dafont.com/fr/roboto.font?text=Eclipse+Che

**Comment by mmorhun** [comment]
@benoitf the font is `Roboto`:
login-page-confirm-roboto
Just text decoration is different.

**Comment by benoitf** [comment]
@mmorhum : I see that you're asking for Roboto font, but it's not that font that is integrated in the page

could you try with the alternate way of importing font 
<link href="https://fonts.googleapis.com/css?family=Roboto:300" rel="stylesheet" type="text/css">

**Comment by slemeur** [comment]
Also all fields in the page are not using Roboto. (not only the Che logo)

**Comment by mmorhun** [comment]
@benoitf Roboto has been already integrated (as you can see from the screenshot). I see no need to change integration way.

**Comment by mmorhun** [comment]
@slemeur sorry, it was cached. They do use `Roboto` font:
input-font
@benoitf thanks for vigilance

**Comment by bmicklea** [comment]
And the pop up text is left-justified?

**Comment by mmorhun** [comment]
@bmicklea of course!
popup-alignment

**Comment by benoitf** [comment]
thanks @mmorhun it looks like the font is now rendering as expected

**Comment by slemeur** [comment]
Perfect, thanks @mmorhun !

**Review by slemeur — APPROVED** [review]

**Review by bmicklea — APPROVED** [review]

**Pull request merged**
