### PR TITLE
Moved win short directory conversion into bash

### PR DESCRIPTION
**Pull request by TylerJewell**
Signed-off-by: Tyler Jewell tjewell@codenvy.com

Two sets of changes:
1. Moved CHE_HOME short directory conversion of windows from che.bat into che.sh.  Thanks @SamHasler.
2. Convert JAVA_HOME to short directory if on Windows.

### CODE REVIEW

**Comment by TylerJewell** [comment]
@garagatyi @eivantsov wdyt?

**Comment by SamHasler** [comment]
That will fail if the che.sh isn't invoked from the directory it is in.

Try this:

```
echo `(cd "$( dirname "${BASH_SOURCE[0]}" )" && cmd //C 'FOR %i in (..) do @echo %~Si')`
```

The `%~dp0` variable only works in the context of a batch script. By invoking cmd and passing it as a command there is no script name or %0 parameter set. So `%i` ends up as `%~dp0\..\..`. I'm not sure how but `%~Si` is then geting evaluated to the short name directory of the dir below the current directory.

e.g.:

```
echo `(cmd //C 'echo %0')`
echo `(cmd //C 'FOR %i in (%~dp0\..\..) do @echo %i')`
echo `(cmd //C 'FOR %i in (%~dp0\..\..) do @echo %~Si')`
echo `(cd "$( dirname "${BASH_SOURCE[0]}" )" && cmd //C 'FOR %i in (..) do @echo %~Si')`
```

invoked from "C:\VERY LONG\PATH\WITH SUBDIR\" using `./testscript.sh` outputs:

```
%0         
%~dp0\..\..
C:\VERY~1\PATH~1\
C:\VERY~1\PATH~1\
```

invoked from "C:\Some\Other\Dir\" using `"/c/very long/path/with subdir/testscript.sh"` outputs:

```
%0         
%~dp0\..\..
C:\SOME~1\OTHER~1\
C:\VERY~1\PATH~1\
```

**Comment by TylerJewell** [comment]
Yep - good catch.  I thought our tests caught that scenario, but it didn't.
BTW, we convert JAVA_HOME now to its short path using the cycgpath utility that you pointed out.  Didn't know that existed.  Would have saved me 4 hours the first time I tried to solve this :-/

**Comment by SamHasler** [comment]
Glad I could help.

**Pull request merged**
