### PR TITLE
Stack Java-MongoDB.

### PR DESCRIPTION
**Pull request by Daniel-Dos**
Signed-off-by: daniel-dos <daniel.dias.analistati@gmail.com>

### What does this PR do?

Added a stack with Java using MongoDB

### What issues does this PR fix or reference?
n/a

#### Release Notes
n/a

#### Docs PR
n/a

### CODE REVIEW

**Comment by eivantsov** [comment]
Perhaps we need a MongoDB icon for this one

**Comment by Daniel-Dos** [comment]
Hi @eivantsov ,
I agreed wtih you .

but, what person is responsibility for create icon ?

thanks .

**Comment by skabashnyuk** [comment]
Hello, @Daniel-Dos  sorry for late response.
Unfortunately, we are not interested in new lang stack for GWT-based ide at this moment.

**Comment by Daniel-Dos** [comment]
No problem, thank you.

**Comment by garagatyi** [comment]
@Daniel-Dos I want to clarify a bit. We a working on a new generation of Che at the moment. It won't need current stacks since all the dev agents would be in a sidecar containers, and would be able to use pure application definitions provided by user. Such as kubernetes yaml with user's app production deployment configuration.

**Pull request closed without merging**
