### PR TITLE
Reload page if there is no debug configuration in Happy path test

### PR DESCRIPTION
**Pull request by dmytro-ndp**
Signed-off-by: Dmytro Nochevnov <dnochevn@redhat.com>

### What does this PR do?
It's adding step to reload the page if there is no debug configuration when check application stop in the breakpoint in Happy path tests

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/19887
https://github.com/eclipse/che/issues/20046

### How to test this PR?
Run Happy path tests

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [ ] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Review by Ohrimenko1988 — APPROVED** [review]

**Comment by Ohrimenko1988** [comment]
@dmytro-ndp Approved, but I am not 100% sure that refresh will help. Workaround which works is to open the ".theia/launch.json" file before test.

`
            Logger.warn('Workaround for the https://issues.redhat.com/browse/CRW-1526');
            await projectTree.expandPathAndOpenFile('.theia', 'launch.json');
`

**Review by Katka92 — APPROVED** [review]

**Comment by dmytro-ndp** [comment]
@Ohrimenko1988 : thanks for review!
Actually there is slightly different situation when IDE works in Debug mode: after refresh there is **DEBUG** panel, not **EXPLORER** in the left:
Screenshot from 2021-07-01 20-38-44

As a result, refresh of page has helped and Happy path test passed [1]:
```
...
19:18:49            ▼ Workaround to the https://github.com/eclipse/che/issues/19887
19:18:49            ▼ BrowserTabsUtil.refreshPage
19:18:49              ‣ DriverHelper.getDriver
19:18:49            ▼ Ide.waitAndSwitchToIdeFrame
19:18:49              ‣ DriverHelper.waitAndSwitchToFrame By(css selector, iframe#ide-iframe)
19:18:54            ▼ Ide.waitIde
19:18:54              ‣ DriverHelper.waitVisibility By(css selector, #theia-app-shell #theia-top-panel .p-MenuBar-content)
19:18:55              ‣ DriverHelper.waitVisibility - Polling timed out attempt #1, retrying with 1000ms timeout
19:18:56              ‣ DriverHelper.waitVisibility - Polling timed out attempt #2, retrying with 1000ms timeout
19:18:57              ‣ DriverHelper.waitVisibility - Element is located and is visible.
19:18:57              ‣ DriverHelper.waitVisibility By(css selector, #theia-left-content-panel)
19:18:57              ‣ DriverHelper.waitVisibility - Element is located and is visible.
19:18:57              ‣ DriverHelper.waitVisibility By(css selector, *[id="shell-tab-explorer-view-container"])
19:18:57              ‣ DriverHelper.waitVisibility - Element is located and is visible.
19:18:57            ▼ DebugView.clickOnDebugConfigurationDropDown
19:18:57              ‣ DriverHelper.waitAndClick By(css selector, select.debug-configuration)
19:18:57              ‣ DriverHelper.waitVisibility By(css selector, select.debug-configuration)
19:18:59              ‣ DriverHelper.waitVisibility - Element is located and is visible.
19:19:00            ▼ DebugView.clickOnDebugConfigurationItem "Debug (Attach) - Remote (petclinic)"
19:19:00              ‣ DriverHelper.waitAndClick By(xpath, //select[contains(@class,'debug-configuration')]//option[text()='Debug (Attach) - Remote (petclinic)'])
19:19:00              ‣ DriverHelper.waitVisibility By(xpath, //select[contains(@class,'debug-configuration')]//option[text()='Debug (Attach) - Remote (petclinic)'])
19:19:00              ‣ DriverHelper.waitVisibility - Element is located and is visible.
...
```
[1] https://github.com/eclipse/che/pull/20062#issuecomment-872381027

**Comment by dmytro-ndp** [comment]
[crw-ci-test]

**Comment by dmytro-ndp** [comment]
[crw-ci-test]

**Comment by dmytro-ndp** [comment]
[crw-ci-test]

**Review by ScrewTSW — APPROVED** [review]

**Pull request merged**
