### PR TITLE
get rid of hardcoded paths in che-server container

### PR DESCRIPTION
**Pull request by riuvshin**
### What does this PR do?
get rid of hardcoded paths

needed for https://github.com/eclipse/che/issues/5402

### CODE REVIEW

**Comment by benoitf** [comment]
-1 on removing the directory in the zip file. (when generating the assembly)

**Comment by benoitf** [comment]
BTW I understand the problem that you're trying to fix but IHMO the proposed solution is involving too many breaking changes which I think could be avoided by a different solution

**Comment by riuvshin** [comment]
@benoitf the biggest problem here is that each time in the che-server image we have folder with different names which is really painful to have. In codenvy we have have same as I did here. I thought about how can I workaround this without touching this but I didn't found any solution how can I know folder in container before I will start the container to properly mount files in right places. And I afraid that in time we could have more and more bad workarounds around that while it should be well predicted. I will try do dig more, but keeping this will introduce more problems in future...

Maybe is there a way to have folder in zip but with static name? like "eclipse-che" that could help but I don;t see how to do this, may be you @benoitf  @skabashnyuk know?

**Comment by benoitf** [comment]
well, first I said -1 to strip folder in the assemblies (tgz/zip) that we distribute.

You can still strip down the folder in the docker image or make an alias if it's easier for you
For example you can add in the Dockerfile after the add command
`RUN ln -s /home/user/eclipse-che-* /home/user/eclipse-che`

then inside an eclipse che container, you can use `/home/user/eclipse-che/` and it's still backward compliant.

also AFAIK, we do know the version of che when we're generating the template so version property could be part of the template as well.

**Comment by riuvshin** [comment]
@benoitf ah if you worried only about artifacts it is ok I could workaround in dockerfile, but I still think that this is bad thing to have... But I agree that we had that bad thing for a quite a while and some users may rely on that... 
I will think on this more...

**Comment by benoitf** [comment]
@riuvshin for you the bad thing is to have the directory part of the tgz/zip file ?
because I would say that it's a standard in OSS world.

**Comment by riuvshin** [comment]
to me bad thing is not a folder but it's name... each time you extract you have different folder, but ofc we can workaround it

**Comment by benoitf** [comment]
IMHO it's for people that unpack tools in a directory, they don't override their previous binaries of a previous version. (like overriding your current install of Tomcat 8.0.35 by Tomcat 8.0.36 files)
or if you want to have two versions in parallel, you only need to unpack two archives directly, no need to make mkdir, move files, etc

**Comment by riuvshin** [comment]
@benoitf I've updated PR

**Review by vparfonov — APPROVED** [review]

**Review by benoitf — APPROVED** [review]

**Review by skabashnyuk — APPROVED** [review]

**Pull request merged**
