### PR TITLE
Change the async storage provisioner service selector to select the correct pod

### LINKED ISSUE #18681: async storage sidecar fails to run backup job
### Describe the bug

On hosted che, using the latest async storage images

```
quay.io/eclipse/che-workspace-data-sync-storage:latest
quay.io/eclipse/che-sidecar-workspace-data-sync:latest
```

The sidecar agent fails to run the backup job that sends data to the storage container:

```
λ oc logs async-storage-6895d4f5c7-dgm9b 
passwd: must be suid to work properly
Generating public/private rsa key pair.
Your identification has been saved in /etc/ssh/ssh_host_rsa_key.
Your public key has been saved in /etc/ssh/ssh_host_rsa_key.pub.
The key fingerprint is:
SHA256:m/0ZkQTr1wkHbrXhY4drdRWNaOPyoFrPwcFlu1yzCrE user@async-storage-6895d4f5c7-dgm9b
The key's randomart image is:
+---[RSA 3072]----+
|          . ..oo+|
|           +*+.+o|
|         ..==oB +|
|         .*oo*o*.|
|        So.O+o=o |
|        o+E.+o.  |
|       ooo.o..   |
|      .   o..o   |
|            o    |
+----[SHA256]-----+
Generating public/private dsa key pair.
Your identification has been saved in /etc/ssh/ssh_host_dsa_key.
Your public key has been saved in /etc/ssh/ssh_host_dsa_key.pub.
The key fingerprint is:
SHA256:Fc5X6a4dQYthptodrVb+0351QXvPOUosi0rlj+DRWcc user@async-storage-6895d4f5c7-dgm9b
The key's randomart image is:
+---[DSA 1024]----+
|          .   .. |
|         o .+.o. |
|          ++.*...|
|         ...+ *o.|
|        S+ o.E o=|
|        = +.=o+o=|
|       + +..+o.o=|
|      o o.o.....+|
|       o.. .   .+|
+----[SHA256]-----+
λ oc logs workspaceg1y1syp0bkasd9gc.maven-7d99586f6d-tsln4  -c che-rsyncp4j
time="2020-12-21T18:57:39Z" level=info msg="read crontab: /etc/crontabs/backup-cron-job"
2020/12/21 18:58:22 exit status 255
time="2020-12-21T19:00:00Z" level=info msg=starting iteration=0 job.command=/scripts/backup.sh job.position=0 job.schedule="*/10 * * * *"
time="2020-12-21T19:00:03Z" level=info msg="ssh: connect to host async-storage port 2222: Host is unreachable" channel=stderr iteration=0 job.command=/scripts/backup.sh job.position=0 job.schedule="*/10 * * * *"
time="2020-12-21T19:00:05Z" level=info msg="ssh: connect to host async-storage port 2222: Host is unreachable" channel=stderr iteration=0 job.command=/scripts/backup.sh job.position=0 job.schedule="*/10 * * * *"
time="2020-12-21T19:00:05Z" level=info msg="rsync: connection unexpectedly closed (0 bytes received so far) [sender]" channel=stderr iteration=0 job.command=/scripts/backup.sh job.position=0 job.schedule="*/10 * * * *"
time="2020-12-21T19:00:05Z" level=info msg="rsync error: unexplained error (code 255) at io.c(226) [sender=3.1.3]" channel=stderr iteration=0 job.command=/scripts/backup.sh job.position=0 job.schedule="*/10 * * * *"
time="2020-12-21T19:00:05Z" level=error msg="error running command: exit status 255" iteration=0 job.command=/scripts/backup.sh job.position=0 job.schedule="*/10 * * * *"
```

### Che version

 - [ ] latest
 - [ ] nightly
 - [x] other: 7.22.0 (Hosted Che)

### Steps to reproduce

- Create a workspace
- Select 'Asynchronous' storage option

### Expected behavior

I expect to be able to check the async-storage pod after the cron has run and verify that my code has been `rsync`'d to `async-storage/$WORKSPACE_ID/projects`

### Runtime
   - [x] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [x] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [x] my computer
       - [ ] Windows
       - [x] Linux - CRC
       - [ ] macOS
   - [x] Cloud - Hosted Che
       - [ ] Amazon
       - [] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

### PR DESCRIPTION
**Pull request by tomgeorge**
Signed-off-by: Tom George <tgeorge@redhat.com>

### What does this PR do?

Currently the `async-storage` service uses the selector `app: che`, which does not select the correct async storage server pod, and clients can't `rsync` to them.

### What issues does this PR fix or reference?

Fixes #18681

### How to test this PR?

- build a version of che based on this code and set `cheImage` and `cheImageTag`

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by skabashnyuk** [comment]
test, docs?

**Comment by skabashnyuk** [comment]
Is there a way to test this pr on the "live" server?

**Review by sleshchenko — APPROVED** [review]

**Review by amisevsk — APPROVED** [review]

**Review by ibuziuk — APPROVED** [review]
:+1: wondering, at which point this got broken though. I believe we verified it on OSD v4 and Hosted Che and the feature worked as expected

**Comment by tomgeorge** [comment]
I'm really not sure, that code in `AsyncStorageProvisioner.java` hasn't changed since it was first written.  Maybe the labeling schema changed elsewhere?

**Pull request merged**
