### PR TITLE
Revert "Revert "CHE-10480: Fix NullPointerException (#11857)" (#11908)"

### PR DESCRIPTION
**Pull request by vinokurig**
### What does this PR do?
The revert #11857 was an experiment to fix the Jenkins job on CI. So this revert applies the changes back

### CODE REVIEW

**Review by riuvshin — APPROVED** [review]

**Comment by sleshchenko** [comment]
Reverting of revert looks a bit strange. Why don't you do new commit which fixed NPE? IMHO It would looks much clear and better

**Comment by vinokurig** [comment]
The revert of the commit was an experiment to fix the Jenkins job on CI. If I opened a PR with original title, it would look like a new PR. As it was approved earlier it has a revert title.

**Comment by sleshchenko** [comment]
OK, I just say that it looks unclear and strange to me. If you want to make it clear that the same changed were merged and reverted before - I think PR description, commit details are good places for such information.

It's just a common recommendation and you do not have to fix it no this PR.

**Comment by vinokurig** [comment]
Thank you for advice, I'll update the PR and commit description

**Pull request merged**
