### PR TITLE
Adding test of Factory URL to devfile test suite.

### PR DESCRIPTION
**Pull request by Katka92**
### What does this PR do?
Add test of factory URL to the devfile test suite that runs nightly.

### CODE REVIEW

**Comment by Katka92** [comment]
ci-build

**Comment by Katka92** [comment]
[ci-build]

**Comment by dmytro-ndp** [comment]
crw-ci-test

**Comment by dmytro-ndp** [comment]
crw-ci-test

**Comment by Katka92** [comment]
Devfile test suite includes factory test and it passed: https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Multiuser-Che-PR-check-E2E-Happy-path-tests-against-k8s/2919/console

**Review by dmytro-ndp — APPROVED** [review]
"Workspace creation via factory url" test [has passed on minikube](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Multiuser-Che-PR-check-E2E-Happy-path-tests-against-k8s/2919/consoleFull).

**Pull request merged**
