### PR TITLE
Fix initialization of servers statuses by DockerInfrastructure

### PR DESCRIPTION
**Pull request by mkuznyetsov**
### What does this PR do?
Machine servers will have "UNKNOWN" status, instead of `null`, when it is not being set by server checks/liveness probes

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/9094

### CODE REVIEW

**Review by sleshchenko — APPROVED** [review]

**Review by garagatyi — APPROVED** [review]

**Comment by mkuznyetsov** [comment]
ci-test

**Comment by mkuznyetsov** [comment]
ci-test

**Comment by mkuznyetsov** [comment]
ci-test

**Comment by mkuznyetsov** [comment]
ci-test

**Pull request merged**
