### PR TITLE
Generate a new SSH key if no keys are registered while ssh mount

### LINKED ISSUE #14411: Generate SSH keys when the user login for the first time
Majority of Che users require the SSH keys to work on their projects. For a first-time user, it can be a bit tricky to find a way to generate the keys.

The goal of this task is to generate a key pair automatically when the user login for the first time. So, after starting a workspace, in case if the user has no keys, he/she will see the notification about a key pair has been already generated automatically.

image

Uploading an SSH key to GitHub will be a separate task.

It's a part of Git+SSH flow epic https://github.com/eclipse/che/issues/13494

### PR DESCRIPTION
**Pull request by vinokurig**
### What does this PR do?
If no SSH keys are registered by user, a new SSH key will be automatically generated and mounted to all containers when a workspace starts.

### What issues does this PR fix or reference?
fixes https://github.com/eclipse/che/issues/14411

### CODE REVIEW

**Comment by dmytro-ndp** [comment]
crw-ci-test

**Comment by dmytro-ndp** [comment]
crw-ci-test

**Comment by vinokurig** [comment]
crw-ci-test

**Comment by vinokurig** [comment]
crw-ci-test

**Review by vparfonov — APPROVED** [review]

**Comment by dmytro-ndp** [comment]
crw-ci-test

**Comment by l0rd** [comment]
@vinokurig it worked fine on minikube but failed on OpenShift. That's Theia container log:

```log
root INFO Theia app listening on http://0.0.0.0:3100.
root INFO unzipping the plug-in 'eclipse_che_ports_plugin.theia' to directory: /tmp/theia-unpacked/eclipse_che_ports_plugin.theia
root INFO unzipping the plug-in 'eclipse_che_theia_containers_plugin.theia' to directory: /tmp/theia-unpacked/eclipse_che_theia_containers_plugin.theia
root INFO unzipping the plug-in 'eclipse_che_theia_factory_plugin.theia' to directory: /tmp/theia-unpacked/eclipse_che_theia_factory_plugin.theia
root INFO unzipping the plug-in 'eclipse_che_theia_ssh_plugin.theia' to directory: /tmp/theia-unpacked/eclipse_che_theia_ssh_plugin.theia
root INFO unzipping the plug-in 'eclipse_che_welcome_plugin.theia' to directory: /tmp/theia-unpacked/eclipse_che_welcome_plugin.theia
root INFO unzipping the plug-in 'task_plugin.theia' to directory: /tmp/theia-unpacked/task_plugin.theia
root INFO unzipping the plug-in 'theia_yeoman_plugin.theia' to directory: /tmp/theia-unpacked/theia_yeoman_plugin.theia
root INFO unzipping the VS Code extension 'vscode-git-1.3.0.1.vsix' to directory: /tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix
root INFO PluginTheiaDirectoryHandler: accepting plugin with path /tmp/theia-unpacked/eclipse_che_ports_plugin.theia
root INFO PluginTheiaDirectoryHandler: accepting plugin with path /tmp/theia-unpacked/eclipse_che_theia_containers_plugin.theia
root INFO PluginTheiaDirectoryHandler: accepting plugin with path /tmp/theia-unpacked/eclipse_che_theia_factory_plugin.theia
root INFO PluginTheiaDirectoryHandler: accepting plugin with path /tmp/theia-unpacked/eclipse_che_theia_ssh_plugin.theia
root INFO PluginTheiaDirectoryHandler: accepting plugin with path /tmp/theia-unpacked/eclipse_che_welcome_plugin.theia
root INFO PluginTheiaDirectoryHandler: accepting plugin with path /tmp/theia-unpacked/task_plugin.theia
root INFO PluginTheiaDirectoryHandler: accepting plugin with path /tmp/theia-unpacked/theia_yeoman_plugin.theia
root INFO PluginTheiaDirectoryHandler: accepting plugin with path /tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix
root INFO Resolved "vscode-git-1.3.0.1.vsix" to a VS Code extension "git@1.0.0" with engines: { vscode: '^1.5.0' }
root INFO PluginTheiaDirectoryHandler: accepting plugin with path /plugins/sidecars
root ERROR Failed to load plugin dependencies from '/plugins/sidecars' path Error: ENOENT: no such file or directory, open '/plugins/sidecars/package.json'
root INFO Deploying backend plugin "@eclipse-che/ports-plugin@0.0.1" from "/tmp/theia-unpacked/eclipse_che_ports_plugin.theia/lib/ports-plugin.js"
root INFO Deploying backend plugin "@eclipse-che/theia-containers-plugin@0.0.2" from "/tmp/theia-unpacked/eclipse_che_theia_containers_plugin.theia/lib/containers-plugin.js"
root INFO Deploying backend plugin "@eclipse-che/theia-factory-plugin@0.0.1" from "/tmp/theia-unpacked/eclipse_che_theia_factory_plugin.theia/lib/factory-plugin.js"
root INFO Deploying backend plugin "@eclipse-che/theia-ssh-plugin@0.0.1" from "/tmp/theia-unpacked/eclipse_che_theia_ssh_plugin.theia/lib/ssh-plugin-backend.js"
root INFO Deploying backend plugin "@eclipse-che/welcome-plugin@0.0.1" from "/tmp/theia-unpacked/eclipse_che_welcome_plugin.theia/lib/welcome-plugin.js"
root INFO Deploying backend plugin "task-plugin@0.0.1" from "/tmp/theia-unpacked/task_plugin.theia/lib/task-plugin-backend.js"
root INFO Deploying backend plugin "@theia/yeoman-plugin@0.0.1-1562576566" from "/tmp/theia-unpacked/theia_yeoman_plugin.theia/lib/theia-yeoman-plugin-backend-plugin.js"
root INFO Deploying backend plugin "git@1.0.0" from "/tmp/vscode-unpacked/vscode-git-1.3.0.1.vsix/extension/out/main"
root ERROR Uncaught Exception:  TypeError: Cannot read property 'model' of undefined
root ERROR TypeError: Cannot read property 'model' of undefined
    at /home/theia/node_modules/@eclipse-che/theia-remote/lib/node/hosted-plugin-remote.js:202:78
    at Array.forEach (<anonymous>)
    at HostedPluginRemote.handleLocalMessage (/home/theia/node_modules/@eclipse-che/theia-remote/lib/node/hosted-plugin-remote.js:201:29)
    at Websocket.websocket.onMessage (/home/theia/node_modules/@eclipse-che/theia-remote/lib/node/hosted-plugin-remote.js:152:23)
    at WebSocket.<anonymous> (/home/theia/node_modules/@eclipse-che/theia-remote/lib/node/websocket.js:38:19)
    at WebSocket.emit (events.js:198:13)
    at Receiver.receiverOnMessage (/home/theia/node_modules/ws/lib/websocket.js:720:20)
    at Receiver.emit (events.js:198:13)
    at Receiver.dataMessage (/home/theia/node_modules/ws/lib/receiver.js:414:14)
    at Receiver.getData (/home/theia/node_modules/ws/lib/receiver.js:346:17)
root WARN Failed to resolve module: @types/body-parser
root WARN Failed to resolve module: @types/bunyan
root WARN Failed to resolve module: @types/express
root WARN Failed to resolve module: @types/fs-extra
root WARN Failed to resolve module: @types/lodash.debounce
root WARN Failed to resolve module: @types/lodash.throttle
root WARN Failed to resolve module: @types/react
root WARN Failed to resolve module: @types/react-dom
root WARN Failed to resolve module: @types/react-virtualized
root WARN Failed to resolve module: @types/route-parser
root WARN Failed to resolve module: @types/ws
root WARN Failed to resolve module: @types/yargs
root WARN Failed to resolve module: font-awesome
root WARN Failed to resolve module: react
root WARN Failed to resolve module: react-dom
root WARN Failed to resolve module: react-virtualized
root WARN Failed to resolve module: @types/rimraf
root WARN Failed to resolve module: @types/tar-fs
root WARN Failed to resolve module: @types/touch
root WARN Failed to resolve module: @types/uuid
root WARN Failed to resolve module: @typefox/monaco-editor-core
root WARN Failed to resolve module: @types/base64-arraybuffer
root WARN Failed to resolve module: @theia/monaco
root WARN Failed to resolve module: @types/p-debounce
root WARN Failed to resolve module: @types/mime-types
root WARN Failed to resolve module: @types/diff
root WARN Failed to resolve module: @types/request
root WARN Failed to resolve module: @types/highlight.js
root WARN Failed to resolve module: @types/markdown-it
root WARN Failed to resolve module: @types/markdown-it-anchor
root WARN A handler with prefix term  is already registered.
root INFO [nsfw-watcher: 31] Started watching: /home/theia/.theia
root INFO [nsfw-watcher: 31] Started watching: /projects
root WARN e.onStart is slow, took: 500.51999999777763 ms
root INFO [nsfw-watcher: 31] Started watching: /projects
root ERROR Request getDeployedPluginIds failed with error: Cannot read property 'model' of undefined TypeError: Cannot read property 'model' of undefined
    at /home/theia/node_modules/@eclipse-che/theia-remote/lib/node/hosted-plugin-remote.js:232:170
    at Array.map (<anonymous>)
    at HostedPluginRemote.<anonymous> (/home/theia/node_modules/@eclipse-che/theia-remote/lib/node/hosted-plugin-remote.js:232:107)
    at step (/home/theia/node_modules/@eclipse-che/theia-remote/lib/node/hosted-plugin-remote.js:50:23)
    at Object.next (/home/theia/node_modules/@eclipse-che/theia-remote/lib/node/hosted-plugin-remote.js:31:53)
    at /home/theia/node_modules/@eclipse-che/theia-remote/lib/node/hosted-plugin-remote.js:25:71
    at new Promise (<anonymous>)
    at __awaiter (/home/theia/node_modules/@eclipse-che/theia-remote/lib/node/hosted-plugin-remote.js:21:12)
    at HostedPluginRemote.getExtraDeployedPluginIds (/home/theia/node_modules/@eclipse-che/theia-remote/lib/node/hosted-plugin-remote.js:230:16)
    at ServerPluginProxyRunner.getExtraDeployedPluginIds (/home/theia/node_modules/@eclipse-che/theia-remote/lib/node/server-plugin-proxy-runner.js:62:40)
root ERROR Failed to load plugins: Error: Request 'getDeployedPluginIds' failed
    at Proxy.<anonymous> (https://static.developers.redhat.com/che/theia_artifacts/theia.6c6f13cbd02928114839.js:1:1789599)
    at e.<anonymous> (https://static.developers.redhat.com/che/theia_artifacts/theia.6c6f13cbd02928114839.js:1:2465656)
    at https://static.developers.redhat.com/che/theia_artifacts/theia.6c6f13cbd02928114839.js:1:2461141
    at Object.next (https://static.developers.redhat.com/che/theia_artifacts/theia.6c6f13cbd02928114839.js:1:2461246)
    at https://static.developers.redhat.com/che/theia_artifacts/theia.6c6f13cbd02928114839.js:1:2460159
    at new Promise (<anonymous>)
    at a (https://static.developers.redhat.com/che/theia_artifacts/theia.6c6f13cbd02928114839.js:1:2459936)
    at e.syncPlugins (https://static.developers.redhat.com/che/theia_artifacts/theia.6c6f13cbd02928114839.js:1:2465371)
    at e.<anonymous> (https://static.developers.redhat.com/che/theia_artifacts/theia.6c6f13cbd02928114839.js:1:2464947)
    at https://static.developers.redhat.com/che/theia_artifacts/theia.6c6f13cbd02928114839.js:1:2461141
root WARN e.onStart is slow, took: 152.43499999996857 ms
root INFO [hosted-plugin: 48] PLUGIN_HOST(48) starting instance
```

**Comment by l0rd** [comment]
@vinokurig I have tested nightly and it's failing there as well so that should not be related to this PR.

**Comment by musienko-maxim** [comment]
I've checked this PR locally all steps from HappyPath scenario are passed.

**Review by musienko-maxim — APPROVED** [review]

**Comment by l0rd** [comment]
@musienko-maxim minishift or minikube?

**Comment by dmytro-ndp** [comment]
@l0rd: 
> @musienko-maxim minishift or minikube?

It was tested on minikube.
And E2E Happy path test had finnaly passed after fixup of test devfile https://github.com/eclipse/che/pull/14767#issuecomment-538730767

**Review by l0rd — APPROVED** [review]
LGTM I was able to test on both minikube and minishift. @vinokurig I would be glad if you could start working at https://github.com/eclipse/che/issues/14775 as soon as you merge this one.

**Review by amisevsk — APPROVED** [review]

**Pull request merged**
