### PR TITLE
CODENVY-566 make workspace export working again

### PR DESCRIPTION
**Pull request by benoitf**
- It has been broken when MachineServlet proxy has been removed as cors has been removed
- it has been broken when machine token was required but UD code was not updated

### CODE REVIEW

**Comment by skabashnyuk** [comment]
@evoevodin @mshaposhnik  wdyt about such cors configuration?

**Comment by mshaposhnik** [comment]
"*" is a worst thing, but if we can't avoid it for now - ok.

**Comment by benoitf** [comment]
for sure, the only way to remove it is if "exporting a workspace + create remote projects" is moved to server side and not kept client side else I don't see how it is possible.

**Comment by skabashnyuk** [comment]
ок

**Comment by vparfonov** [comment]
ok

**Pull request merged**
