### PR TITLE
Use HTTPS instead of HTTP in web links.

### PR DESCRIPTION
**Pull request by monaka**
### What does this PR do?

Fixes some `http://` links to `https://`

### What issues does this PR fix or reference?

N/A

#### Changelog
Use HTTPS instead of HTTP in web links for documentation and internal URLs.

### CODE REVIEW

**Comment by skabashnyuk** [comment]
ci-build

**Review by skabashnyuk — APPROVED** [review]
@JamesDrummond @bmicklea  please review

**Comment by bmicklea** [comment]
Where are these weblinks?  In the UI?

**Comment by skabashnyuk** [comment]
hard to say, a lot of different places

**Comment by TylerJewell** [comment]
Thanks @monaka - for the contribution.

**Review by bmicklea — APPROVED** [review]

**Review by JamesDrummond — APPROVED** [review]

**Review by vparfonov — APPROVED** [review]

**Review by ashumilova — APPROVED** [review]

**Comment by vparfonov** [comment]
merged here https://github.com/eclipse/che/pull/4276

**Comment by monaka** [comment]
@vparfonov Thanks for your help!

**Pull request closed without merging**
