### PR TITLE
[WIP - Do not merge] Add debug action to devfile

### LINKED ISSUE #15297: Add debug action to devfile used in Happy Path tests
### Is your task related to a problem? Please describe.
Happy Path test is currently adding launch/debug configuration by directly editing `launch.json` file.
We should modify the devfile to add that configuration directly (so no further edition of `launch.json` file is needed in the running workspace).

### Describe the solution you'd like
Here is example of how this can be achieved: https://github.com/eclipse/che-devfile-registry/blob/master/devfiles/java-web-spring/devfile.yaml#L54

### Additional context
This is followup of https://github.com/eclipse/che/issues/15183

### PR DESCRIPTION
**Pull request by Katka92**
### What does this PR do?
Add debug definition to the devfile. Change file with breakpoint so it can be properly tested.

### What issues does this PR fix or reference?
This PR fixes: https://github.com/eclipse/che/issues/15297

### CODE REVIEW

**Comment by Katka92** [comment]
crw-ci-test

**Comment by Katka92** [comment]
crw-ci-test

**Comment by Katka92** [comment]
crw-ci-test

**Comment by rhopp** [comment]
crw-ci-test

**Comment by Katka92** [comment]
crw-ci-test

**Comment by Katka92** [comment]
crw-ci-test

**Comment by Katka92** [comment]
crw-ci-test

**Comment by Katka92** [comment]
crw-ci-test

**Comment by Katka92** [comment]
crw-ci-test

**Comment by Katka92** [comment]
I was not able to get it running. Closing my PR.

**Pull request closed without merging**
