### PR TITLE
Removing CI section from the README since it points to che-server

### PR DESCRIPTION
**Pull request by ibuziuk**
### What does this PR do?
Removing CI section from the README since it points to che-server

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [ ] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [ ] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [ ] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Review by dmytro-ndp — APPROVED** [review]
Good catch!

**Review by sparkoo — APPROVED** [review]

**Comment by ibuziuk** [comment]
[crw-ci-test --rebuild]

**Comment by ibuziuk** [comment]
[crw-ci-test]

**Comment by ibuziuk** [comment]
[crw-ci-test --rebuild]

**Comment by ibuziuk** [comment]
[crw-ci-test]

**Comment by ibuziuk** [comment]
@dmytro-ndp any recommendations on how to have a green test CI?

**Comment by sparkoo** [comment]
While I think it is important to have passing CI jobs, do we really need to enforce it here? You're clearly changing only README file. If the CI checks are not in good shape and we can't rely on it, I would not enforce it or even care why it fails in PRs like this.

**Comment by ibuziuk** [comment]
that's fair, but as I recall there was an agreement to have the green status check before merging any PR

**Comment by ibuziuk** [comment]
[crw-ci-test]

**Comment by dmytro-ndp** [comment]
@ibuziuk: failed Happy path tests has already fixed in **main** branch.

At the same time this PR doesn't affect E2E tests at all, so it could be merged with approval from @sparkoo

**Review by dmytro-ndp — APPROVED** [review]

**Pull request merged**
