### PR TITLE
Fixed launcher bats tests and minor refactoring of launcher scripts

### PR DESCRIPTION
**Pull request by mlabuda**
### What does this PR do?
Fixes launcher tests and minor refactoring in launcher script for getting launcher image data 

### What issues does this PR fix or reference?
https://issues.jboss.org/browse/CHE-8

### Tests written?
Yes

### CODE REVIEW

**Comment by mlabuda** [comment]
Could someone please rerun check on ip-validation? I've signed CLA and it should pass now.

**Review by l0rd — APPROVED** [review]
@TylerJewell this shouldn't have an impact on anything else. Can we merge it right away? I think @mlabuda will work on a separate PR to add bats tests to the new CLI.

**Comment by l0rd** [comment]
@mlabuda you email does not pass Eclipse validation and we cannot merge your PR until you fix that https://dev.eclipse.org/eclipse-webhook/services/status_details.php?id=586b60255caa1

**Comment by TylerJewell** [comment]
Mario - as I was talking with Marla in slack, we are in the verge of cleaning up the repository and removing deprecated folders and code.  This would be one of the folders to look at once we have shipped 5.0.0 milestone.  So do we still want to merge this?

**Comment by l0rd** [comment]
@TylerJewell I would like to merge it as a recognition for @mlabuda work. Even if it will be removed shortly it's still an improvement and these same tests will be re-used to test new CLI code.

**Comment by TylerJewell** [comment]
Ok then - +1 from me.

**Pull request merged**
