### PR TITLE
Fix and rework PredefinedNamespace test

### PR DESCRIPTION
**Pull request by musienko-maxim**
### What does this PR do?
* This PR is removed using UI from the tests and works with API calls with oc/kubectl client and fixes logic errors (removing a Workspace from UI after deleting by API)

### What issues does this PR fix or reference?
https://issues.redhat.com/browse/CRW-5345

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [ ] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [ ] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [ ] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix or new feature ](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix-or-new-feature)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by dmytro-ndp** [comment]
IMHO, replacement of UI test with API test is too big change for the task to target issue: "fix test workspace removal after the test execution".
New test scenario is not actually covering Dashboard and Che server behavior when there is pre-defined user namespace.

What do you think about only removal of the next suites, which don't make sens after user workspace and namespace have been removed from cluster in previous suiteTeardown():
```
	suiteTeardown('Re-login with test user', async function (): Promise<void> {
		if (OAUTH_CONSTANTS.TS_SELENIUM_OCP_USERNAME !== userName) {
			await loginTests.logoutFromChe();
			await loginTests.loginIntoChe();
		}
	});

	suiteTeardown('Open dashboard and close all other tabs', async function (): Promise<void> {
		await dashboard.openDashboard();
		await browserTabsUtil.closeAllTabsExceptCurrent();
	});

	suiteTeardown('Stop and delete the workspace by API', async function (): Promise<void> {
		await testWorkspaceUtil.stopAndDeleteWorkspaceByName(WorkspaceHandlingTests.getWorkspaceName());
	});
```
?

P.S. Test screencast shows another problem - workspace failed to start: 
Screenshot from 2023-11-24 19-14-02

[output (32).webm](https://github.com/eclipse/che/assets/1197777/cd87e1bb-ee5c-4f16-9d91-d6102e32c704)

**Comment by musienko-maxim** [comment]
I can't entirely agree with saving the UI part. 
This test is not responsible for communicating with the dashboard. One reason for creating a workspace from the dashboard was the absence of the possibility of generating DevFiles. The main goal of the test is to check that a DW object is created in the dedicated Openshift project.
About the error on the screencast, I ran the test on my latest instance manually: create the Predefined NS by oc client and create the Empty workspace from the Dashboard - this problem was not reproduced.
I can check it manually one more time - to make sure 100% that the problem on the screencast is not reproduced

**Comment by dmytro-ndp** [comment]
@musienko-maxim : the test was initially created to [check user namespace provisioning](https://drive.google.com/file/d/1ad56GbRIHYwm7uTrRgjiLCCWn78Y53wK/view).

@ibuziuk, @l0rd: could you, please, say would it be enough to test user namespace provisioning at DevWorkspace level only not involving Che Dashboard and Che Server?

**Review by ibuziuk — APPROVED** [review]
+1 to remove the UI logic and fallback on oc / kubect

**Pull request merged**
