### PR TITLE
CLDIDE-2715 Add export workspace portability flow

### PR DESCRIPTION
**Pull request by benoitf**
**_3 Upvotes**_ It creates a remote workspace, start it and import projects that have a pre-defined remote location

requires https://github.com/eclipse/che/pull/327

Change-Id: I8b57c8656138ecb1832f10dd0401babf20a58e0c
Signed-off-by: Florent BENOIT fbenoit@codenvy.com

### CODE REVIEW

**Comment by benoitf** [comment]
fixed

**Comment by ashumilova** [comment]
+1

**Comment by akurinnoy** [comment]
+1

**Comment by olexii4** [comment]
+1

**Pull request merged**
