### PR TITLE
Fix selenium tests

### PR DESCRIPTION
**Pull request by tolusha**
Signed-off-by: Anatoliy Bazko <abazko@redhat.com>

### What does this PR do?
Fix selenium test for Camel stack

### CODE REVIEW

**Comment by tolusha** [comment]
ci-test

**Comment by tolusha** [comment]
ci-test

**Comment by tolusha** [comment]
ci-test

**Comment by SkorikSergey** [comment]
Selenium tests execution on Eclipse Che Multiuser on OCP (https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1809//Selenium_20tests_20report/) doesn't show any regression against this Pull Request.

**Comment by tolusha** [comment]
@skabashnyuk 
Could you approve then?

**Review by SkorikSergey — APPROVED** [review]

**Pull request merged**
