### PR TITLE
Selenium: remove selenium tests that check Che 6 compatible factories from CheSuite test suite

### PR DESCRIPTION
**Pull request by SkorikSergey**
### What does this PR do?
This PR removes selenium tests that check Che 6 compatible factories from **CheSuite** test suite according to https://github.com/eclipse/che/pull/13446.

### CODE REVIEW

**Review by dmytro-ndp — APPROVED** [review]

**Comment by SkorikSergey** [comment]
ci-build

**Comment by SkorikSergey** [comment]
ci-build

**Comment by SkorikSergey** [comment]
ci-build

**Comment by SkorikSergey** [comment]
ci-build

**Pull request merged**
