### PR TITLE
[WIP] CHE-7008: Use xterm.js in the console output widget

### PR DESCRIPTION
**Pull request by AndrienkoAleksandr**
### What does this PR do?
Requested changes:
Use jsinterop to wrap terminal script instead of outdated jsni.
Simplify terminal script injection flow (don't use requirejs to inject terimal script, use gwt to inject terminal  and speed up development process). 
Use xterm.js inside command output widget: this widget more fast and contains ansi control sequences parser.
Use linkifier feature of the xterm.js for implementation clickable stack trace. OutputCustomizers was replaced by Linkifiers.
Set up scroll back size for command output widget: 5000 lines instead of 500. 
Change OutPutConsole api to use ansi true color format to colorize output. 
UI changes: remove autoscroll button: xterm.js contains own, pretty clear, autoscroll behavior. 
Remove "Wrap the Text" button: xterm.js doesn't support yet this feature (in the feature versions of the xterm.js this feature is planned).

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/7008

#### Release Notes
Use xterm.js in the console output widget

#### Docs PR
No

### CODE REVIEW

**Review by azatsarynnyy — APPROVED** [review]
Just one note about using `name` parameter with `JsProperty` annotation.
AFAIK you can skip specifying the `name` parameter explicitly as `JsProperty` follows JavaBean style naming convention to extract the property name.
So instead of:
```java
@JsProperty(name = "cursorStyle")
public native String getCursorStyle();
```
you can write:
```java
@JsProperty
public native String getCursorStyle();
```

**Review by vparfonov — APPROVED** [review]

**Comment by skabashnyuk** [comment]
@AndrienkoAleksandr is this PR up to date?

**Comment by AndrienkoAleksandr** [comment]
Yes it's up to date. And it was done for xterm.js 2.4.0.

**Comment by AndrienkoAleksandr** [comment]
Pull request is out of dated. I need resolve merge conflict and adapted this code to the newer xterm.js

**Comment by musienko-maxim** [comment]
Can one of the admins verify this PR?

**Pull request closed without merging**
