### PR TITLE
Selenium: Add corrections to the tests from 'git' package

### PR DESCRIPTION
**Pull request by artaleks9**
### What does this PR do?
* Add corrections to selenium tests from the _git_ package to increase reliability when run on CI
* Related selenium tests: _AddFilesToIndexTest_, _BranchTest_.java

### What issues does this PR fix or reference?
#12216

### CODE REVIEW

**Comment by artaleks9** [comment]
ci-test

**Review by SkorikSergey — APPROVED** [review]

**Review by dmytro-ndp — APPROVED** [review]

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1328/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1328//Selenium_20tests_20report/)
docker image: eclipseche/che-server:12219
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by artaleks9** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1335/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1335//Selenium_20tests_20report/)
docker image: eclipseche/che-server:12219
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Pull request merged**
