### PR TITLE
CHE-494: fix machine and workspace models

### PR DESCRIPTION
**Pull request by olexii4**
**_1 Upvote**_ Signed-off-by: Oleksii Orel oorel@codenvy.com

### CODE REVIEW

**Comment by olexii4** [comment]
@ashumilova @benoitf  WDYT?

**Comment by benoitf** [comment]
I would say that this commit should be part of IDEX-4222 and https://github.com/eclipse/che/pull/350 so client and model changes will be merged together

**Comment by benoitf** [comment]
(but I'm already ok with content)

**Comment by ashumilova** [comment]
do we need to change here: https://github.com/eclipse/che/blob/CHE-494/dashboard/src/app/dashboard/welcome-back/welcome-back.controller.js#L72

**Comment by ashumilova** [comment]
and in this method:  https://github.com/eclipse/che/blob/CHE-494/dashboard/src/app/projects/create-project/create-project.controller.js#L346

**Comment by ashumilova** [comment]
+1

**Comment by olexii4** [comment]
Fixed

**Pull request merged**
