### PR TITLE
Return back Che Theia next version as default

### PR DESCRIPTION
**Pull request by vparfonov**
Signed-off-by: Vitalii Parfonov <vparfono@redhat.com>

### CODE REVIEW

**Review by ibuziuk — COMMENTED** [review]
@vparfonov getting a bit lost. Why do we fall back on `next` in master instead of the fixed version ?

**Comment by benoitf** [comment]
I think we should go a nightly version of che-theia coming from 7.0.0 branch
next is for development only

**Comment by vparfonov** [comment]
it should fix this issue https://github.com/eclipse/che/issues/13720, if plugin registry not deployed locally

**Review by benoitf — CHANGES_REQUESTED** [review]
next is development branch, needs to use a version coming from che-theia 7.0.0 branch

**Comment by benoitf** [comment]
@vparfonov I think to fix it you need a PR against https://github.com/openshiftio/saas-openshiftio/blob/master/dsaas-services/che-plugin-registry.yaml

**Pull request closed without merging**
