### PR TITLE
Added go test command

### PR DESCRIPTION
**Pull request by InnovativeInventor**
### What does this PR do?
It adds a test command to the default go stack.

### What issues does this PR fix or reference?
None, its an enhancement

#### Release Notes

Added a test command to the default go stack

### CODE REVIEW

**Comment by skabashnyuk** [comment]
ci-test

**Comment by skabashnyuk** [comment]
@InnovativeInventor have you test this pr. I see 1 ```{``` and 2 ```}``` ? do you have pr against master?

**Comment by InnovativeInventor** [comment]
No, do you want me to open a pull request to the master branch? If so, I'll add the go build command too. I didn't want to add it to this pull request because its titled "Added go test command".

**Comment by riuvshin** [comment]
@InnovativeInventor yes please, move this to master.

**Comment by riuvshin** [comment]
ci-test

**Pull request closed without merging**
