### PR TITLE
 Set stable version of selenium chrome-node 3.14.0-curium

### PR DESCRIPTION
**Pull request by dmytro-ndp**
### What does this PR do?
It downgrades version of _selenium chrome-node_ image to **3.14.0-curium** with _Google Chrome 68_ to fix unexpected regression of _E2E selenium tests_ because update 3.14.0 image to use _Google Chrome 69_.

### What issues does this PR fix or reference?
#11160

### CODE REVIEW

**Comment by dmytro-ndp** [comment]
ci-test

**Review by musienko-maxim — APPROVED** [review]

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/769/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/769//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/11165)
docker image: eclipseche/che-server:11165
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/770/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/770//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/11165)
docker image: eclipseche/che-server:11165
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/772/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/772//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/11165)
docker image: eclipseche/che-server:11165
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Pull request merged**
