### PR TITLE
CHE-1317: fix import project while creating a workspace

### PR DESCRIPTION
**Pull request by olexii4**
Signed-off-by: Oleksii Orel oorel@codenvy.com

### CODE REVIEW

**Comment by akurinnoy** [comment]
OK, as a temporary fix

**Comment by benoitf** [comment]
AFAIK it's not a fix, as if I import a project from git containing a pom.xml it will be imported as blank project and not as a maven project

**Comment by ashumilova** [comment]
by "fix" mean - fixing project import, cause now doesn't work at all. Imported projects will be blank, and then will provide ASAP fix for project type estimation, cause we detect project type base on it, and estimation doesn't work properly.

**Comment by slemeur** [comment]
I disagree with this quickfix. We need to fix the project type detection - this workaround can't be merged.

**Comment by gazarenkov** [comment]
https://jira.codenvycorp.com/browse/CHE-1331

**Pull request closed without merging**
