### PR TITLE
Remove Diagnostics widget on UD

### LINKED ISSUE #13525: Remove UD "Diagnostics" because it's not working
### Description
Dashboard diagnostic tests are using che 6 workspace and failing atm 

### Reproduction Steps
Open "Diagnostics" tab in run the tests

image

ERROR:

> REST Call on Workspace Agent
> Workspace has no runtime: unable to test workspace not started
>  --- ERROR

image

**OS and version:**    
- [x] che.openshift.io
- [x] rh-che minishift addon

Have not tested on pure upstream but I believe it would fail with the very same error

### PR DESCRIPTION
**Pull request by akurinnoy**
Signed-off-by: Oleksii Kurinnyi <okurinny@redhat.com>

### What does this PR do?

This PR removes Diagnostics directive and link to Diagnostics page in Dashboard footer.

### What issues does this PR fix or reference?

fix https://github.com/eclipse/che/issues/13525

### CODE REVIEW

**Review by ashumilova — APPROVED** [review]

**Comment by akurinnoy** [comment]
ci-test

**Review by benoitf — APPROVED** [review]

**Review by rhopp — APPROVED** [review]

**Comment by rhopp** [comment]
@SkorikSergey @artaleks9 @dmytro-ndp Was this covered by selenium tests? If so, we need to delete/disable them too...

**Comment by dmytro-ndp** [comment]
@rhopp : we don't have dedicated e2e tests to check Diagnostics tool.

**Review by l0rd — APPROVED** [review]

**Comment by SkorikSergey** [comment]
Selenium tests execution on Eclipse Che Multiuser on OCP (https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1896//Selenium_20tests_20report/) doesn't show any regression against this Pull request.

**Pull request merged**
