### PR TITLE
[WIP]Fix timeunit: set to seconds. Add checking after add to index

### PR DESCRIPTION
**Pull request by vparfonov**
Signed-off-by: Vitalii Parfonov <vparfonov@redhat.com>

### What does this PR do?

Fix timeunit: set to seconds. Add checking after add to index

### CODE REVIEW

**Comment by vparfonov** [comment]
ci-test

**Comment by vparfonov** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/706/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/706//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/11022)
docker image: eclipseche/che-server:11022
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by riuvshin** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/720/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/720//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/11022)
docker image: eclipseche/che-server:11022
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Review by dmytro-ndp — APPROVED** [review]

**Review by musienko-maxim — APPROVED** [review]

**Comment by vparfonov** [comment]
ci-test

**Pull request merged**
