### PR TITLE
[ WIP DO NOT MERGE ] Investigate #11697 issue for "ContextMenuEditorTest" selenium test

### PR DESCRIPTION
**Pull request by Ohrimenko1988**
### What does this PR do?
Investigate #11697 issue for "ContextMenuEditorTest" sleenium test

### What issues does this PR fix or reference?
Issue: https://github.com/eclipse/che/issues/11697

### CODE REVIEW

**Comment by Ohrimenko1988** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1167/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1167//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11921
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by vinokurig** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1169/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1169//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11921
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by Ohrimenko1988** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1181/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1181//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11921
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by Ohrimenko1988** [comment]
ci-test

**Comment by Ohrimenko1988** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1191/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1191//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11921
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by Ohrimenko1988** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1200/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1200//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11921
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by Ohrimenko1988** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1210/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1210//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11921
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by Ohrimenko1988** [comment]
This Pull Request is outdated

**Pull request closed without merging**
