### PR TITLE
[Selenium] Stabilize 'devtools-che-nightly-devfiles-test'  test job

### PR DESCRIPTION
**Pull request by SkorikSergey**
### What does this PR do?
Stabilize ```devtools-che-nightly-devfiles-test```  test job.

### CODE REVIEW

**Comment by SkorikSergey** [comment]
[ci-test]

**Comment by SkorikSergey** [comment]
[ci-test]

**Comment by SkorikSergey** [comment]
[ci-test]

**Comment by SkorikSergey** [comment]
[ci-test]

**Comment by SkorikSergey** [comment]
[ci-test]

**Review by dmytro-ndp — APPROVED** [review]
looks good

**Comment by SkorikSergey** [comment]
crw-ci-test

**Pull request merged**
