### PR TITLE
[E2E] Add export for all classes so we can reuse them on RH-Che side.

### PR DESCRIPTION
**Pull request by Katka92**
### What does this PR do?
Add all important classes to export, so they can be reused e.g. by RH-Che.

### What issues does this PR fix or reference?
Issue: https://github.com/redhat-developer/rh-che/issues/1536

### CODE REVIEW

**Comment by benoitf** [comment]
hello, linked issue is not telling if it's required for `7.0.0` and then can be merged in master

**Comment by musienko-maxim** [comment]
Can one of the admins verify this PR?

**Review by Ohrimenko1988 — APPROVED** [review]

**Comment by Ohrimenko1988** [comment]
I have approved this issue because I haven't any suggestions on the technical side. But please pay attention to the Floran's comment.

**Review by rhopp — APPROVED** [review]
One of the things mentioned on the F2F is that tests improvement can go to master even without the rigorosity required for other PRs.
As this PR greatly easies testing of che.openshift.io, I'm +1 for merging this PR even before GA.

**Comment by musienko-maxim** [comment]
E2E Happy path tests of Eclipse Che Single User on K8S (minikube v1.1.1) has been successful:
- [Build details](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/CHE-7-Maven-PR-build-checker-codenvy-slave9/37/)
- docker image: docker.io/maxura/che-server:14118

**Review by ibuziuk — APPROVED** [review]

**Comment by musienko-maxim** [comment]
E2E Happy path tests of Eclipse Che Single User on K8S (minikube v1.1.1) has failed:
- [Build details](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/CHE-7-Maven-PR-build-checker-codenvy-slave9/38/)
- docker image: docker.io/maxura/che-server:14118
- [test artifacts](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/CHE-7-Maven-PR-build-checker-codenvy-slave9/38//artifact/e2e/report/)
- https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by Katka92** [comment]
ci-test

**Comment by musienko-maxim** [comment]
E2E Happy path tests of Eclipse Che Single User on K8S (minikube v1.1.1) has been successful:
- [Build details](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/CHE-7-Maven-PR-build-checker-codenvy-slave9/40/)
- docker image: docker.io/maxura/che-server:14118

**Pull request merged**
