### PR TITLE
Use Java Base64 method instead of javax.xml.bind.DatatypeConverter

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?

Fix import when using Java11

Change-Id: I8434bc583734fb5fa2ceb007ab02628afed735d8
Signed-off-by: Florent Benoit <fbenoit@redhat.com>

### What issues does this PR fix or reference?
N/A

#### Release Notes
N/A

#### Docs PR
N/A

### CODE REVIEW

**Comment by benoitf** [comment]
ci-test

**Comment by benoitf** [comment]
ci-test

**Comment by benoitf** [comment]
ci-test

**Comment by SkorikSergey** [comment]
Selenium tests execution on Eclipse Che Multiuser on OCP (https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1550//Selenium_20tests_20report/) doesn't show any regression against this Pull Request.

**Review by musienko-maxim — APPROVED** [review]

**Pull request merged**
