### PR TITLE
Fix typo in Contributing.md

### PR DESCRIPTION
**Pull request by apupier**
Signed-off-by: Aurélien Pupier <apupier@redhat.com>

### CODE REVIEW

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by apupier** [comment]
ci-build ci-test

**Comment by apupier** [comment]
ci-build

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/820/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/820//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11239
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Review by vparfonov — APPROVED** [review]

**Review by benoitf — APPROVED** [review]

**Pull request merged**
