### PR TITLE
Remove code that supports namespace strategies other than per-user

### LINKED ISSUE #19536: Remove the code that support namespace strategies other than "per user"
### Is your task related to a problem? Please describe.
In 7.29 https://github.com/eclipse/che/issues/19365 we deprecated all namespace strategies other than "per user".
In 7.31 we want to left only the "per-user" strategy in the code.

### Describe the solution you'd like
Remove/Cleanup the code that supports namespace strategies other than "per user"

### Describe alternatives you've considered
n/a

### Additional context
https://github.com/eclipse/che/issues/19365

### PR DESCRIPTION
**Pull request by skabashnyuk**
### What does this PR do?
Remove code that supports namespace strategies other than per-user
Documentation changes -  in progress....

### Screenshot/screencast of this PR
Знімок екрана 2021-05-07 о 14 52 38

### What issues does this PR fix or reference?
Fixes https://github.com/eclipse/che/issues/19536

### How to test this PR?
1. Deploy che-server image `quay.io/skabashn/che-server:che19536`
2. Should create per-user k8s namespace by default
3. Setup `oc patch checluster eclipse-che -n eclipse-che --type=json -p '[{"op": "replace", "path": "/spec/devWorkspace/enable", "value": true}]`
4. Che server startup should fail with message `Only 'per user' is allowed.Using the <username> or <userid> placeholder is required in the 'che.infra.kubernetes.namespace.default' parameter. The current value is: '<workspaceid>-che'`

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [ ] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [ ] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [ ] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Review by themr0c — APPROVED** [review]
ACK for the `che.properties` changes

**Review by sparkoo — APPROVED** [review]
tested on minikube with multiple namespace configurations and pre-created namespaces, works fine.

Do you plan to update che-operator code to reflect these changes? For example che-operator sets `CHE_INFRA_KUBERNETES_NAMESPACE_ALLOW__USER__DEFINED` in `che` configmap.

**Comment by tolusha** [comment]
@skabashnyuk 
I will update operator not to set CHE_INFRA_KUBERNETES_NAMESPACE_ALLOW__USER__DEFINED in che configmap.

**Comment by skabashnyuk** [comment]
docs pr https://github.com/eclipse/che-docs/pull/1983

**Pull request merged**
