### PR TITLE
Update selenium chrome-node to 3.14.0

### PR DESCRIPTION
**Pull request by dmytro-ndp**
### What does this PR do?
It updates **selenium chrome-node** to version **3.14.0** which contains fresh version of _Google Chrome_ 68.0.3440.84.

### What issues does this PR fix or reference?
#10868

### CODE REVIEW

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/640/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/640//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10869)
docker image: eclipseche/che-server:10869
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/641/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/641//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10869)
docker image: eclipseche/che-server:10869
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/642/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/642//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10869)
docker image: eclipseche/che-server:10869
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/680/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/680//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10869)
docker image: eclipseche/che-server:10869
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/718/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/718//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10869)
docker image: eclipseche/che-server:10869
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by riuvshin** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/725/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/725//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10869)
docker image: eclipseche/che-server:10869
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/744/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/744//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10869)
docker image: eclipseche/che-server:10869
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/745/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/745//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10869)
docker image: eclipseche/che-server:10869
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Review by musienko-maxim — APPROVED** [review]

**Pull request merged**
