### PR TITLE
Fix e2e dashboard tests

### PR DESCRIPTION
**Pull request by olexii4**
Signed-off-by: Oleksii Orel <oorel@redhat.com>

### What does this PR do?
Fix the create workspace test.

### What issues does this PR fix or reference?

It is needed for https://github.com/eclipse-che/che-dashboard/pull/246

https://marvelapp.com/prototype/9a777d1/screen/75865190

### CODE REVIEW

**Review by sleshchenko — APPROVED** [review]

**Review by JPinkney — APPROVED** [review]

**Comment by sleshchenko** [comment]
I'm not sure that we have set up a mechanism to take care of two related PR in multiple repositories.
@dmytro-ndp What would be suggest to merge this PR and https://github.com/eclipse-che/che-dashboard/pull/246 ?

**Comment by dmytro-ndp** [comment]
@sleshchenko: let me fix Happy path PR check in Che Dashboard repo so that it accepts custom branch in Eclipse Che repo.

**Review by dmytro-ndp — APPROVED** [review]
Java maven devfile test has been passed 
https://main-jenkins-csb-crwqe.apps.ocp4.prod.psi.redhat.com/job/Che/job/e2e/job/minikube/job/pr-check/job/che-dashboard-pr-check/59/

So, IMHO, this PR is ready to merge after https://github.com/eclipse-che/che-dashboard/pull/246 has been merged.

**Review by Ohrimenko1988 — APPROVED** [review]

**Comment by sleshchenko** [comment]
It expected it to be merged in sync with https://github.com/eclipse-che/che-dashboard/pull/246, otherwise all happy path tests are going to fail until the referenced PR is merged, but I may be wrong.

**Comment by dmytro-ndp** [comment]
@sleshchenko: you are right - this MR shouldn't be merged before eclipse-che/che-dashboard#246 has been merged.

**Pull request merged**
