### PR TITLE
CHE-10538: improves workspace loader

### LINKED ISSUE #10538: Workspace-loader app should show error when request to start a workspace fails
### Description
When a request from workspace-loader app that starts a workspace fails workspace-loader should show an error and remove the progress bar since nothing is loading anymore. 
But instead, it just continues showing a progress bar and shows no sign of an error.
The error happens when workspace-loader sends next request:
`POST http://192.168.99.100.nip.io/api/workspace/workspaceiyt5iy9lvkaccrzr/runtime`
and receives a response with status 500 and body:
`{"message":"Error occurred on retrieval of feature org.eclipse.che.che-theia/0.0.4. Error: http://marketplace:80/feature/org.eclipse.che.che-theia/0.0.4"}`

### Reproduction Steps
Try to create a workspace with a Workspace.Next feature that doesn't exist (example for kubernetes infra started in minikube with IP 192.168.99.100):
```
curl 'http://192.168.99.100.nip.io/api/workspace?namespace=che&attribute=features:org.eclipse.che.che-theia/0.0.100' \
-H 'Content-Type: application/json;charset=UTF-8' \
--data-binary @- <<"EOF"
{
    "environments": {
        "default":{
            "recipe": {
                "contentType":"application/x-yaml",
                "type":"kubernetes",
                "content":"---\nkind: List\nitems:\n-\n  apiVersion: v1\n  kind: Pod\n  metadata:\n    name: wsnextdemo\n  spec:\n    containers:\n      -\n        image: eclipse/ubuntu_jdk8\n        name: app"},
            "machines": {
                "wsnextdemo/app": {
                    "attributes":{}
                }
            }
        }
    },
    "defaultEnv":"default",
    "name":"workspace-next"
}
EOF
```

**OS and version:**    

**Diagnostics:**

### PR DESCRIPTION
**Pull request by akurinnoy**
### What does this PR do?
When workspace loader starts a workspace and it fails, then an error appears and the progress bar hides.

restart

### What issues does this PR fix or reference?
fix #10538

#### Release Notes

N/A - bugfix

#### Docs PR

N/A - bugfix

### CODE REVIEW

**Comment by akurinnoy** [comment]
ci-test

**Review by benoitf — APPROVED** [review]

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/541/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/541//Selenium_tests_report)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10642)
docker image: eclipseche/che-server:10642
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by akurinnoy** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/543/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/543//Selenium_tests_report)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10642)
docker image: eclipseche/che-server:10642
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by akurinnoy** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/550/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/550//Selenium_tests_report)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10642)
docker image: eclipseche/che-server:10642
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by SkorikSergey** [comment]
Selenium tests execution on Eclipse Che Multiuser on OCP (lhttps://ci.codenvycorp.com/job/che-pullrequests-test-ocp/550/) doesn't show any regression against this Pull Request.

**Review by SkorikSergey — APPROVED** [review]

**Review by vitaliy-guliy — APPROVED** [review]

**Pull request merged**
