### PR TITLE
fixed minor "webscoket" typos

### PR DESCRIPTION
**Pull request by Patricol**

### CODE REVIEW

**Comment by benoitf** [comment]
thanks @Patricol for your contribution

could you please sign ECA so we can accept your contribution
https://www.eclipse.org/legal/ecafaq.php (step 10)

**Comment by benoitf** [comment]
ci-build

**Comment by Patricol** [comment]
I have done so. (Eclipse Foundation username: pcollins111)

**Comment by benoitf** [comment]
@Patricol you need as well to amend your commit by adding the "Signed-off-by" footer
https://wiki.eclipse.org/Development_Resources/Contributing_via_Git

if all is good, the "ip validation" check will become green

**Comment by benoitf** [comment]
@Patricol FYI you'll have to squash all your commits or rewrite all of them as they should all include the Signed-off-by footer

**Comment by Patricol** [comment]
Thank you for the info.

Is it possible, then, that my formatting on the "Signed off by" line is correct, and I just need to squash so that it's on every commit?

**Comment by benoitf** [comment]
It seems the email is valid
ECA for Patricol  : https://dev.eclipse.org/site_login/web-api/cla_decorator.php?email=patrickcp0@gmail.com ECA for Patricol  : https://dev.eclipse.org/site_login/web-api/cla_decorator.php?email=patrickcp0@gmail.com

but as you've 5 commits that are part of this pull request, you've to rewrite the history of these commits

$ git rebase -i HEAD~6
http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by Patricol** [comment]
My environment is really not cooperating, (and I only have 2 hours to sleep at this point...) so I'll cancel this pull request, redo it all from scratch, and send another pull request momentarily.

**Pull request closed without merging**
