### PR TITLE
Merge master into che6

### PR DESCRIPTION
**Pull request by skabashnyuk**
### What does this PR do?
Merge master into che6

### CODE REVIEW

**Comment by benoitf** [comment]
I suppose there is some collision with
https://github.com/eclipse/che/pull/6786 and
https://github.com/eclipse/che/pull/6785

**Comment by tolusha** [comment]
@benoitf What do you mean?
Should I close my PR?

**Comment by benoitf** [comment]
@tolusha no I just mean that if these linked PRs are merged, this PR will need to be refreshed

**Review by vparfonov — APPROVED** [review]

**Review by benoitf — APPROVED** [review]

**Review by tolusha — APPROVED** [review]

**Comment by skabashnyuk** [comment]
ci-build

**Pull request merged**
