### PR TITLE
Fix recovery of Devfile based workspaces

### PR DESCRIPTION
**Pull request by sleshchenko**
### What does this PR do?
This PR fixes recovery of Devfile based workspaces.
This is done by moving logic of converting Devfile to workspace config form WorkspaceManager to WorkspaceRuntimes, and perform this converting on recovering of workspace if needed.

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/13313

#### Release Notes
N/A

#### Docs PR
N/A

### CODE REVIEW

**Review by skabashnyuk — APPROVED** [review]

**Comment by sleshchenko** [comment]
ci-test

**Review by metlos — APPROVED** [review]

**Review by amisevsk — APPROVED** [review]

**Comment by sleshchenko** [comment]
ci-test

**Comment by sleshchenko** [comment]
ci-build

**Comment by sleshchenko** [comment]
ci-test

**Comment by SkorikSergey** [comment]
ci-test

**Comment by SkorikSergey** [comment]
ci-test

**Comment by SkorikSergey** [comment]
Selenium tests execution on Eclipse Che Multiuser on OCP (https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1791//Selenium_20tests_20report/) doesn't show any regression against this Pull Request.

**Pull request merged**
