### PR TITLE
CHE-1818: Add new WS environment types, machines attributes

### PR DESCRIPTION
**Pull request by garagatyi**
This PR adds 
- attributes map to machines in environment.
- new environment types `dockerimage` and `dockerfile` with single machine

Attribute `memoryLimitBytes` sets RAM limit for machine. If RAM limit is set in the environment recipe this property overrides limit.

### CODE REVIEW

**Comment by skabashnyuk** [comment]
ok

**Comment by benoitf** [comment]
how can you merge PR within minutes and not PR that are here since a couple of days for the same branch
https://github.com/eclipse/che/pull/2288 ?

**Comment by garagatyi** [comment]
They are both merged

**Comment by benoitf** [comment]
thx @garagatyi

**Pull request merged**
