### PR TITLE
Change plugin registry to v3

### PR DESCRIPTION
**Pull request by nickboldt**
Change-Id:...

Change plugin registry to v3

Change-Id: I68d71bdc7ee6df1e175d39b198efcfeff29ca4f1
Signed-off-by: nickboldt <nboldt@redhat.com>

### CODE REVIEW

**Comment by musienko-maxim** [comment]
Can one of the admins verify this PR?

**Comment by nickboldt** [comment]
Related to https://github.com/minishift/minishift/pull/3273 and https://github.com/eclipse/che/issues/13136 and https://github.com/eclipse/che/pull/11354/files#diff-700dab0819ba6724ee90d7050f15e35e

**Comment by benoitf** [comment]
ci-build

**Review by benoitf — COMMENTED** [review]
ci-test

**Review by metlos — APPROVED** [review]

**Review by skabashnyuk — APPROVED** [review]

**Comment by nickboldt** [comment]
I'll never understand why your process isn't "approve AND merge at the same time", rather than having the original submitter merge the change... but anyway, thanks! Merged.

**Pull request merged**
