### PR TITLE
Add support endpoints for VSCode extensions and Theia plugins.

### PR DESCRIPTION
**Pull request by AndrienkoAleksandr**
### What does this PR do?
Add support endpoints for VSCode extensions and Theia plugins.

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/14766

Signed-off-by: Oleksandr Andriienko <oandriie@redhat.com>

### CODE REVIEW

**Review by benoitf — APPROVED** [review]

**Review by amisevsk — APPROVED** [review]

**Comment by musienko-maxim** [comment]
crw-ci-test

**Comment by musienko-maxim** [comment]
ci-test

**Comment by musienko-maxim** [comment]
ci-build

**Comment by dmytro-ndp** [comment]
@AndrienkoAleksandr: it needs to take changes from master branch in order to get rid of [recent PR check failure](https://github.com/eclipse/che/pull/14937#issuecomment-544861893).

**Comment by AndrienkoAleksandr** [comment]
@dmytro-ndp rebased pr to latest master

**Comment by dmytro-ndp** [comment]
crw-ci-test

**Review by musienko-maxim — APPROVED** [review]

**Pull request merged**
