### PR TITLE
CHE-58: Fixing compilation error after rebase

### PR DESCRIPTION
**Pull request by ibuziuk**

### CODE REVIEW

**Comment by l0rd** [comment]
LGTM Thank you @ibuziuk!

**Comment by amisevsk** [comment]
Compilation without -Dskip-validate-sources still fails; the Copyright header in `DockerConnectorProvider.java` needs to have its year updated. We can just include this in a future PR though.

**Comment by ibuziuk** [comment]
@amisevsk good catch. Maybe it would be better to fix it now, so that we will be ready to provide neat ready-to-review initial OpenshiftConnector PR once CQs are resolved?

**Comment by l0rd** [comment]
+1 to fix it as soon as possible

**Comment by ibuziuk** [comment]
@l0rd PR with license fix - https://github.com/eclipse/che/pull/3730

**Pull request merged**
