### PR TITLE
Setup Sonar check for master and Github pull requests

### LINKED ISSUE #18507: Setup SonarCloud for Che server
### Is your task related to a problem? Please describe.
It would  be nice to know code coverage of che server component

### Describe the solution you'd like
Enable SonarCloud for Che server.
As a CI we can use Github Actions

### Describe alternatives you've considered
n/a
### Additional context
https://wiki.eclipse.org/SonarQube

### PR DESCRIPTION
**Pull request by skabashnyuk**
### What does this PR do?
Setup Sonar check for master and Github pull requests. Results can be found here `https://sonarcloud.io/dashboard?id=org.eclipse.che%3Ache-server`
I`ve decided not to change che-parent. But first, get stable sonar testing results, and after that with @nickboldt @mkuznyetsov can decide whatever we should move the sonar config to https://github.com/eclipse/che-parent or not.

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/18507

### How to test this PR?
- Setup `SONAR_TOKEN`
-  `mvn -B clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Psonar -Pintegration`

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by dmytro-ndp** [comment]
[ci-test]

**Comment by dmytro-ndp** [comment]
[crw-ci-test --rebuild]

**Comment by skabashnyuk** [comment]
[crw-ci-test]

**Comment by skabashnyuk** [comment]
[ci-build]

**Comment by skabashnyuk** [comment]
Sonar / Sonar (pull_request) failing   - that is ok because it has no access to secrets.

**Review by mshaposhnik — APPROVED** [review]

**Review by dmytro-ndp — APPROVED** [review]

**Comment by sparkoo** [comment]
> Sonar / Sonar (pull_request) failing - that is ok because it has no access to secrets.

it will have an access once it's in the master?

**Review by sparkoo — COMMENTED** [review]
Is rename `che-parent` to `che-server` required for this task? If not, I would consider do it in 2 PRs.

**Comment by skabashnyuk** [comment]
>it will have an access once it's in the master?

I'm really, really hope so.

>Is rename che-parent to che-server required for this task?

No. 

> If not, I would consider do it in 2 PRs.

oookey

**Pull request merged**
