### PR TITLE
Use Java 8u191 jdk for che master

### LINKED ISSUE #11872: Change Che master Java from JRE to JDK
### Description
Now we use JRE and it doesn't provide tools to analyze the weird behavior of JVM: jps, jstack, etc.
JDK has these tools and would be valuable in the image.

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

### PR DESCRIPTION
**Pull request by skabashnyuk**
### What does this PR do?
- replaced JRE with JDK
- Upgrade to latest java 8u191 

### What issues does this PR fix or reference?
fixes https://github.com/eclipse/che/issues/11872
#### Release Notes
n/a

#### Docs PR
n/a

### CODE REVIEW

**Comment by skabashnyuk** [comment]
ci-tet

**Comment by skabashnyuk** [comment]
ci-test

**Comment by benoitf** [comment]
hello, what's the size difference of the resulting image ?

**Comment by skabashnyuk** [comment]
@benoitf that is a good question. Here are my arguments why it's acceptable.
1.  The raw image is about 24% larger
```
[ 9:21:52]sj:che[master]#: docker images |grep 8u191
openjdk                                        8u191-jre-alpine    556cf01c8299        4 days ago          83.1MB
openjdk                                        8u191-jdk-alpine    21a93502ddd8        4 days ago          103MB
```
However the resulting image is ```316mb vs 335mb``` that is about 106% from original. As for me this an acceptable price for instruments that we get with jdk that will allow us to have live diagnostic in cases when workspace master behaves unexpectedly. I'm talking about ```jstack``` tool.

2. Also, the lifecycle of workspace master doesn't expect very frequent deployments. 

3. Some of the know to me downstream projects already uses jdk instead of jre in production images of workspace master.

**Review by benoitf — APPROVED** [review]

**Review by riuvshin — APPROVED** [review]

**Pull request merged**
