### PR TITLE
[release] Bump to 7.12.0-SNAPSHOT in master

### PR DESCRIPTION
**Pull request by mkuznyetsov**
Signed-off-by: Mykhailo Kuznietsov <mkuznets@redhat.com>

### CODE REVIEW

**Review by skabashnyuk — APPROVED** [review]

**Comment by mkuznyetsov** [comment]
ci-build

**Comment by mkuznyetsov** [comment]
crw-ci-test

**Comment by mkuznyetsov** [comment]
crw-ci-test

**Comment by mkuznyetsov** [comment]
crw-ci-test

**Comment by mkuznyetsov** [comment]
[ci-build]

**Pull request merged**
