### PR TITLE
DynaModule plugin test: Avoid timestamp usage when copying dependency + sorting files issue

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
-Use a fixed name for the dependency instead of using timestamped dependency artifact name if the dependency is downloaded from nexus
- Apply another filter for getting test module class as filesystem may not following lexicographical order

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/7140

#### Release Notes
N/A

#### Docs PR
N/A

### CODE REVIEW

**Review by skabashnyuk — APPROVED** [review]

**Comment by benoitf** [comment]
ci-test

**Comment by benoitf** [comment]
ci-build

**Review by skabashnyuk — APPROVED** [review]

**Comment by benoitf** [comment]
ci-build

**Comment by garagatyi** [comment]
I tried this PR and it fixes the build in my case

**Review by garagatyi — APPROVED** [review]

**Comment by RomanNikitenko** [comment]
@benoitf I have tested the PR on my machine and it fixes the build!

**Pull request merged**
