### PR TITLE
CHE-49: Improving 'waitAndRetrieveContainerID' method with checking Pod State

### PR DESCRIPTION
**Pull request by ibuziuk**
### What does this PR do?
Waiting until the pod get into the "Running" state

### What issues does this PR fix or reference?
https://issues.jboss.org/browse/CHE-49

### CODE REVIEW

**Comment by ibuziuk** [comment]
@l0rd could you please review? While testing on multi-machine image (Java-MySQL) I had random fails on setting workspace agent phase:
```
Error: Workspace agent server not found in dev machine.
java.util.concurrent.ExecutionException: org.eclipse.che.api.core.ServerException: Start of environment default failed
```
Not sure if it is coupled with this PR though

**Review by l0rd — APPROVED** [review]

**Comment by l0rd** [comment]
@ibuziuk I've approved your PR but you need to rebase. I'm sorry about that.

**Comment by ibuziuk** [comment]
@l0rd no problem I will rebase and perform more testing

**Comment by ibuziuk** [comment]
@l0rd I have updated PR but got some weird error on agent injections phase:
agent_error
It looks like the method does not look like expected

**Comment by ibuziuk** [comment]
can not reliably reproduce though

**Comment by l0rd** [comment]
@ibuziuk can you please check if you can reproduce the error on a version of Che that is precedent to your commit?

**Comment by ibuziuk** [comment]
@l0rd  on `openshift-connector` branch I was able to repro the following
error

**Pull request merged**
