### PR TITLE
CHE-LIB-57: Update xterm.js to the version 3.3.0

### PR DESCRIPTION
**Pull request by AndrienkoAleksandr**
### What does this PR do?
Update xterm.js to the version 3.3.0

### What issues does this PR fix or reference?
https://github.com/eclipse/che-lib/issues/57

#### Release Notes
Update xterm.js to the version 3.3.0

Signed-off-by: Oleksandr Andriienko <oandriie@redhat.com>

### CODE REVIEW

**Review by mmorhun — APPROVED** [review]

**Review by azatsarynnyy — APPROVED** [review]

**Review by vparfonov — APPROVED** [review]

**Comment by AndrienkoAleksandr** [comment]
@musienko-maxim, Could you check report, please?

**Comment by musienko-maxim** [comment]
All tests that depended on terminal fault (that was expected,  because current implementation of the terminal uses canvas instead of DOM element). So we should find way to adapt tests for the current implementation of the terminal.

**Comment by musienko-maxim** [comment]
We can start adaptation after resolving the issue: https://github.com/eclipse/che/issues/10258

**Review by musienko-maxim — CHANGES_REQUESTED** [review]
**Should be merged after fixing the issue:** https://github.com/eclipse/che/issues/10258 and adaptation dependent tests

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/544/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/544//Selenium_tests_report)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10037)
docker image: eclipseche/che-server:10037
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/545/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/545//Selenium_tests_report)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10037)
docker image: eclipseche/che-server:10037
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/546/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/546//Selenium_tests_report)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10037)
docker image: eclipseche/che-server:10037
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/548/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/548//Selenium_tests_report)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10037)
docker image: eclipseche/che-server:10037
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/549/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/549//Selenium_tests_report)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10037)
docker image: eclipseche/che-server:10037
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/565/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/565//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10037)
docker image: eclipseche/che-server:10037
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/568/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/568//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10037)
docker image: eclipseche/che-server:10037
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Review by musienko-maxim — APPROVED** [review]

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/575/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/575//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10037)
docker image: eclipseche/che-server:10037
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/576/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/576//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10037)
docker image: eclipseche/che-server:10037
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/579/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/579//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10037)
docker image: eclipseche/che-server:10037
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Review by vparfonov — APPROVED** [review]

**Review by dmytro-ndp — APPROVED** [review]

**Pull request merged**
