### PR TITLE
FileWatcher service: Add exclusive process in register/refer dirs.

### PR DESCRIPTION
**Pull request by monaka**
(This patch is not checked well. May need more fixes)

### What does this PR do?

Wait loop until the target dir is registered.

### What issues does this PR fix or reference?

#6203

### CODE REVIEW

**Comment by dkulieshov** [comment]
Hi @monaka,

It is very appreciated that you've discovered such a nasty bug. You're saying that the NPE is thrown because value of variable `dir` [here](https://github.com/eclipse/che/blob/5b373e6cf5bfeb16f278c4d750fe64361445eeb4/wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/vfs/watcher/FileWatcherService.java#L299) is **`null`** because the directory is not added to the registry yet. It is an excellent observation and to the best of my ability I see only one case where it is possible - if a file system event happens between [this](https://github.com/eclipse/che/blob/5b373e6cf5bfeb16f278c4d750fe64361445eeb4/wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/vfs/watcher/FileWatcherService.java#L194) and [that](https://github.com/eclipse/che/blob/5b373e6cf5bfeb16f278c4d750fe64361445eeb4/wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/vfs/watcher/FileWatcherService.java#L195) lines of code are executed.

However I'm not sure that the changes you provided fixes the issue efficiently. Correct me if I'm wrong but I do believe that these lines 
```java
if (dir == null) {
  LOG.debug("Reported directory is not registered - skipping.");
  continue;
}
``` 
are not necessary because according to the use case logic eventually folders are always registered (unless there may be other use cases that I'm missing here). If we agree that no extra **`null`** check is needed I think we can simply keep resetting watch key until the folder is registered (which should take as long as the second of the two mentioned earlier lines is executed - not long):
```diff
diff --git a/wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/vfs/watcher/FileWatcherService.java b/wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/vfs/watcher/FileWatcherService.java
index 6c74413af3..4460083dd4 100644
--- a/wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/vfs/watcher/FileWatcherService.java
+++ b/wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/vfs/watcher/FileWatcherService.java
@@ -277,6 +277,13 @@ public class FileWatcherService {
         WatchKey watchKey = service.take();
         Path dir = keys.get(watchKey);
 
+        if (dir == null){
+          resetAndRemove(watchKey, dir);
+
+          LOG.debug("Folder is not registered but watch key already has pending events, resetting");
+          continue;
+        }
+
         List<WatchEvent<?>> watchEvents = watchKey.pollEvents();
 
         if (suspended.get()) {
```

What do you think?

**Comment by monaka** [comment]
I think this issue is raised like this even though I've not checked well.

1. Executed line 194. https://github.com/PizzaFactory/che/blob/51378ed07bfc30dec3f86bec1221828764ec8788/wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/vfs/watcher/FileWatcherService.java#L194
2. Event was raised before executed line 195. https://github.com/PizzaFactory/che/blob/51378ed07bfc30dec3f86bec1221828764ec8788/wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/vfs/watcher/FileWatcherService.java#L195
3. `keys.get(watchKey);` returns null as line 195 have not executed yet.

So possibly calling `resetAndRemove()` is not the best solution.

**Comment by monaka** [comment]
So it may be better to use `syncronized(lockObj)` instead of the wait loop.

**Comment by monaka** [comment]
I pushed the another plan.
IMO, there is no case that @dkuleshov suggested above. But I added in my new patch for the stability.

**Comment by dkulieshov** [comment]
@monaka 

> I think this issue is raised like this even though I've not checked well.
>
> 1, Executed line 194. https://github.com/PizzaFactory/che/blob/51378ed07bfc30dec3f86bec1221828764ec8788/wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/vfs/watcher/FileWatcherService.java#L194
> 2. Event was raised before executed line 195. https://github.com/PizzaFactory/che/blob/51378ed07bfc30dec3f86bec1221828764ec8788/wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/vfs/watcher/FileWatcherService.java#L195
> 3. keys.get(watchKey); returns null as line 195 have not executed yet.
> So possibly calling resetAndRemove() is not the best solution.

Actually that is exactly what I was saying here in my previous [comment](https://github.com/eclipse/che/pull/6205#issuecomment-328515843) :smile: :

>  I see only one case where it is possible - if a file system event happens between [this](https://github.com/eclipse/che/blob/5b373e6cf5bfeb16f278c4d750fe64361445eeb4/wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/vfs/watcher/FileWatcherService.java#L194) and [that](https://github.com/eclipse/che/blob/5b373e6cf5bfeb16f278c4d750fe64361445eeb4/wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/vfs/watcher/FileWatcherService.java#L195) lines of code are executed.

Anyway I'm not sure that I follow you when you're saying
> So possibly calling `resetAndRemove()` is not the best solution. 

because in this specific case watch key is valid and not cancelled so this method will only call `java.nio.file.WatchKey#reset` which (according to the [java docs](https://docs.oracle.com/javase/7/docs/api/java/nio/file/WatchKey.html#reset())) 
> Otherwise if there are pending events for the object then this watch key is immediately re-queued to the watch service. If there are no pending events then the watch key is put into the ready state and will remain in that state until an event is detected or the watch key is cancelled.

So it will re-enqueue watch key with all pending events and iterate over the first part of the loop until [this](https://github.com/eclipse/che/blob/6e9825c699d34eef6b8bf36fc0194ff871cbee84/wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/vfs/watcher/FileWatcherService.java#L195) line is executed and then continue it's normal work and that is probably precisely what we all want here. Unless I'm missing something important here?

I'm also eager to understand your motivation for introducing synchronized blocks here. I mean I see that it will probably solve the issue but I'm not really sure if we will benefit in some way here by setting additional synchronization, because with or without synchronized blocks we will not go further in the loop until `dir` variable is put to `keys` map: 
- with synchronization block the loop is blocked entirely until `keys` monitor is released 
- in case we will use these lines
 ```diff
+        if (dir == null){
+          resetAndRemove(watchKey, dir);
+
+          LOG.debug("Folder is not registered but watch key already has pending events, resetting");
+          continue;
+        }
```
watch key will be repeatedly re-queued and a new iteration will be repeatedly run until 'dir' is put to 'keys'. Moreover, and that is important part I think, _re-queued_ means that it is put to the end of a queue so if there are more watch keys to take in the watch service they will be taken and processed normally and prior to our unfortunate watch key. In this case the loop won't be blocked at any time and the event processing process will be continuous. And that may be beneficial taking into account that we're talking about intensive file system event stream processing.

Not taking into account extra synchronization (IMHO) the solution looks good to me.

**Comment by monaka** [comment]
@dkuleshov Let me check it. Do you agree with my assumption? (that events are raised between L194 and L195)

**Comment by dkulieshov** [comment]
@monaka, your assumption is absolutely correct in my opinion :+1:

**Review by vparfonov — APPROVED** [review]

**Pull request merged**
