### PR TITLE
rh-che #379: Migrating to a new GitHub token endpoint

### PR DESCRIPTION
**Pull request by ibuziuk**
### What does this PR do?
backporting https://github.com/eclipse/che/pull/6809 to `che6`

### What issues does this PR fix or reference?
https://github.com/redhat-developer/rh-che/issues/379

#### Release Notes
N / A

#### Docs PR
N / A

### CODE REVIEW

**Comment by benoitf** [comment]
ci-build

**Comment by skabashnyuk** [comment]
I have a strong filling that we should remove ```che-multiuser-keycloak-token-provider ``` from che6. It's not using in  Eclipse Che. And looks a bit weird fixing code and linking issue from rh-che.
As alternative we can merge this pr to sync with master, but closer to release remove ```che-multiuser-keycloak-token-provider ``` wdyt?

**Review by benoitf — APPROVED** [review]

**Comment by benoitf** [comment]
@ibuziuk FYI there is a conflicting file also I don't know the status of this PR based on @skabashnyuk last comment. It was now a couple of month ago.

**Comment by skabashnyuk** [comment]
I think we need to remove KeycloakTokenProvider for couple of reasons 
1. We implement proper Kecloak-OAuth account linking feature https://github.com/eclipse/che/issues/5943
2. ```DEFAULT_KEYCLOAK_GITHUB_ENDPOINT="https://auth.openshift.io/api/token?for=https://github.com"``` Has nothing to do with Eclipse Che. It's sometihng very specific to OSIO.

I think it would be resonable to move ```KeycloakTokenProvider``` to rh-che

**Review by riuvshin — APPROVED** [review]

**Review by skabashnyuk — COMMENTED** [review]
Please lets discuss destiny of ```KeycloakTokenProvider``` before the merge

**Review by riuvshin — COMMENTED** [review]
+1 to discuss

**Comment by skabashnyuk** [comment]
Please change targe this pr to master branch.

**Pull request closed without merging**
