### PR TITLE
Upgrade guava and related dependencies to fix potential security issues

### PR DESCRIPTION
**Pull request by skabashnyuk**
### What does this PR do?
- upgrade guava to 30.1.1-jre
- upgrade google.http-client to 1.39.1
- upgrade restassured to 2.6.0
- upgrade  httpclient to 4.5.13
- upgrade httpcore to 4.4.14
 - removed mailing infrastructure (since it is not used and contains potential problematic code)

### CQ
- [x] checker-qual-3.8.0.jar ClearlyDefined -87 https://clearlydefined.io/definitions/maven/mavencentral/org.checkerframework/checker-qual/3.8.0 
- [x] error_prone_annotations-2.5.1.jar	 ClearlyDefined -80 https://clearlydefined.io/definitions/maven/mavencentral/com.google.errorprone/error_prone_annotations/2.5.1
- [x] google-http-client-1.39.1.jar https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23213
- [x] google-http-client-jackson2-1.39.1.jar https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23214
- [x] guava-30.1.1-jre.jar https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23002
- [x] httpcore-4.4.14.jar https://dev.eclipse.org/ipzilla/show_bug.cgi?id=21195
- [x] j2objc-annotations-1.3.jar https://dev.eclipse.org/ipzilla/show_bug.cgi?id=21995
- [x] opencensus-api-0.28.0.jar   ClearlyDefined -80  https://clearlydefined.io/definitions/maven/mavencentral/io.opencensus/opencensus-api/0.28.0
- [x] opencensus-contrib-http-util-0.28.0.jar  https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23215

### What issues does this PR fix or reference?
https://github.com/skabashnyuk/che/security/dependabot/pom.xml/com.google.guava:guava/open

### How to test this PR?
 - deploy che server image `quay.io/skabashn/che-server:updatedeps`
 - test if workspace started successfully

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Review by mshaposhnik — APPROVED** [review]

**Comment by skabashnyuk** [comment]
[crw-ci-test]

**Comment by dmytro-ndp** [comment]
[crw-ci-test --rebuild]

**Comment by skabashnyuk** [comment]
[crw-ci-test --rebuild]

**Comment by skabashnyuk** [comment]
crw-ci-test --rebuild

**Comment by dmytro-ndp** [comment]
[crw-ci-test --rebuild]

**Review by sparkoo — APPROVED** [review]

**Comment by skabashnyuk** [comment]
[crw-ci-test --rebuild]

**Pull request merged**
