### PR TITLE
CORS: use internal or external api url depending on needs

### PR DESCRIPTION
**Pull request by skabashnyuk**
### What does this PR do?
CORS: use internal or external api url depending on needs
On workspace agent  on Linux we have such variables
```
CHE_API_EXTERNAL=http://172.19.20.121:8080/api
CHE_API=http://che-host:8080/api
CHE_API_INTERNAL=http://che-host:8080/api
```
The issue was in fact that we use ```che-host:8080``` as an allowed host for CORS. But this URL 
is needed only to query che master from workspace agent.

After this PR we will use CHE_API_INTERNAL to query workspace master to get workspace config.
CHE_API_EXTERNAL as fallback url to determine cors allowed host if there is no other way.

Can't use "ide" link in workspace config since it depends on the way how workspace config was retrieved with help of internal API or external.

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/12463 Import/Create project does not work on docker platform

### CODE REVIEW

**Comment by skabashnyuk** [comment]
ci-build

**Comment by skabashnyuk** [comment]
ci-test

**Review by sleshchenko — APPROVED** [review]
LGTM

**Comment by skabashnyuk** [comment]
ci-test-docker-single

**Comment by skabashnyuk** [comment]
@eclipse/eclipse-che-qa please take a look at reports?

**Comment by artaleks9** [comment]
Selenium tests execution on Eclipse Che Multiuser on OCP (https://ci.codenvycorp.com/job/che-pullrequests-test/524/) doesn't show any regression against this Pull Request.

**Review by mkuznyetsov — APPROVED** [review]

**Pull request merged**
