### PR TITLE
warning: [MissingOverride] clone overrides method in Object; expected @Override

### PR DESCRIPTION
**Pull request by vzhukovs**
Findbugs warns with the following message:

`warning: [MissingOverride] clone overrides method in Object; expected @Override`

@ashumilova review it, please

### CODE REVIEW

**Comment by vzhukovs** [comment]
@vparfonov review it also, please

**Comment by vzhukovskii** [comment]
ci-build

**Comment by vzhukovs** [comment]
ci-build

**Review by ashumilova — APPROVED** [review]

**Comment by vzhukovs** [comment]
ci-build

**Pull request merged**
