### PR TITLE
CHE-9: improve error messages from Docker API

### PR DESCRIPTION
**Pull request by garagatyi**
@skabashnyuk @evoevodin @vparfonov

### CODE REVIEW

**Comment by vparfonov** [comment]
do we need some errorCode in DockerException?

**Comment by skabashnyuk** [comment]
ok

**Comment by garagatyi** [comment]
@vparfonov 
We used to used it before. Not sure it is still needed. I would not want to remove it right now.

**Comment by vparfonov** [comment]
ok

**Pull request merged**
