### PR TITLE
CHE-10121: fix behavior of the factory's "Create" button

### PR DESCRIPTION
**Pull request by akurinnoy**
### What does this PR do?
Any invalid factory name disables the factory's "Create" button.

### What issues does this PR fix or reference?
#10121 

#### Release Notes

N/A - bugfix

#### Docs PR

N/A - bugfix

Signed-off-by: Oleksii Kurinnyi <okurinny@redhat.com>

### CODE REVIEW

**Comment by akurinnoy** [comment]
ci-test

**Comment by SkorikSergey** [comment]
ci-test

**Review by olexii4 — APPROVED** [review]

**Review by ashumilova — APPROVED** [review]

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/604/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/604//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10778)
docker image: eclipseche/che-server:10778
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by akurinnoy** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/610/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/610//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10778)
docker image: eclipseche/che-server:10778
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by SkorikSergey** [comment]
Selenium tests execution on Eclipse Che Multiuser on OCP (https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/610/) doesn't show any regression against this Pull Request.

**Review by SkorikSergey — APPROVED** [review]

**Pull request merged**
