### PR TITLE
Add workspace ID to secret name (for self signed certs)

### PR DESCRIPTION
**Pull request by ghost**
### What does this PR do?

Adds wsID to certificate secret name, so that when workspaces are created in the same namespace, there are no conflicts.

This is a use case with tls mode on and self signed certs

### CODE REVIEW

**Comment by eivantsov** [comment]
ci-build

**Review by garagatyi — APPROVED** [review]

**Comment by garagatyi** [comment]
Please, sign your commits

**Review by sleshchenko — APPROVED** [review]
LGTM

**Comment by eivantsov** [comment]
Since current selenium tests do not cover such a use case, i have manually verified secrets get created as expected:

image

**Pull request merged**
