### PR TITLE
Set editor scroll position when editor is focused

### PR DESCRIPTION
**Pull request by RomanNikitenko**
### What does this PR do?
Set editor scroll position when editor is focused at restoring IDE state
Fix case related to saving wrong value of a top line for not focused editors at storing app state 

### What issues does this PR fix or reference?
#9456 
Signed-off-by: Roman Nikitenko <rnikiten@redhat.com>

### CODE REVIEW

**Comment by RomanNikitenko** [comment]
ci-test

**Comment by RomanNikitenko** [comment]
ci-test

**Comment by RomanNikitenko** [comment]
ci-test

**Comment by RomanNikitenko** [comment]
ci-test

**Comment by RomanNikitenko** [comment]
ci-test

**Review by vparfonov — APPROVED** [review]

**Pull request closed without merging**
