### PR TITLE
Correct update hierarchy of folders when user modifies maven project structure

### PR DESCRIPTION
**Pull request by vzhukovs**
### What does this PR do?
Improved mechanism of setting up properties to file resources after update operations on parent project. On the server side project config now injects into item reference when user retrieve a file tree. Removed temporary fix from maven messages handler.

Signed-off-by: Vladyslav Zhukovskyi <vzhukovs@redhat.com>

### What issues does this PR fix or reference?
#4376 

#### Release Notes
N/A

#### Docs PR
N/A

### CODE REVIEW

**Comment by vzhukovskii** [comment]
ci-test

**Comment by vzhukovskii** [comment]
ci-test

**Comment by vzhukovskii** [comment]
ci-test

**Comment by vzhukovskii** [comment]
ci-test

**Comment by vzhukovskii** [comment]
ci-test

**Comment by vzhukovs** [comment]
ci-test

**Comment by ashumilova** [comment]
@vzhukovskii Work in progress or ready for review?

**Comment by vzhukovs** [comment]
@ashumilova ready to review. Just to be sure that everything is ok, I've run selenium test cycle on this PR.

**Comment by vzhukovskii** [comment]
ci-test

**Review by dkulieshov — APPROVED** [review]

**Comment by vzhukovs** [comment]
ci-test

**Review by ashumilova — APPROVED** [review]

**Review by SkorikSergey — APPROVED** [review]

**Review by vparfonov — APPROVED** [review]

**Pull request merged**
