### PR TITLE
[TS_SELENIUM] Fix the logical mistake in the "Editor.ts" pageobject leads to "StaleElementReference" error

### PR DESCRIPTION
**Pull request by Ohrimenko1988**
Signed-off-by: Ihor Okhrimenko <iokhrime@redhat.com>

### What does this PR do?
Fix the logical mistake in the "Editor.ts" pageobject leads to "StaleElementReference" error

### What issues does this PR fix or reference?
Issue: https://github.com/eclipse/che/issues/15940

### CODE REVIEW

**Comment by dmytro-ndp** [comment]
@Ohrimenko1988: I am right that this PR makes it possible to address content of exact file tab in editor?

**Comment by Ohrimenko1988** [comment]
> @Ohrimenko1988: I am right that this PR makes it possible to address content of exact file tab in editor?

Yes, the reason why - If don't apply tab title for breakpoint xpath it may lead to the error when by provided xpath will be found a breakpoint from another editor tab.

Screenshot from 2020-02-06 12-32-16

**Review by rhopp — APPROVED** [review]
Given how rest of the Editor class is implemented, this change makes sense...

I would much rather see Editor class implemented in a way, that one instance of Editor would represent one specific editor page, but that would be pretty big refactoring and we don't have time for this right now :-(

**Comment by rhopp** [comment]
crw-ci-test

**Comment by Ohrimenko1988** [comment]
ci-test

**Review by dmytro-ndp — APPROVED** [review]

**Pull request merged**
