### PR TITLE
run npm audit fix to upversion versions in...

### PR DESCRIPTION
**Pull request by nickboldt**
run npm audit fix to upversion versions in package.json

Change-Id: I5e0b0b7ae945e3694fd0582976487df973eadc9f
Signed-off-by: nickboldt <nboldt@redhat.com>

### CODE REVIEW

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by nickboldt** [comment]
If you run `npm audit fix` in the che/dashboard folder you get the above changes.

If you run `npm audit fix --force` you get even more changes:

```
fixed 38 of 42 vulnerabilities in 35579 scanned packages
  4 vulnerabilities required manual review and could not be updated
  11 package updates for 38 vulns involved breaking changes
  (installed due to `--force` option)
```

```
 -25,21 +25,21 @@

-    "gulp": "~3.9.0",
+    "gulp": "^4.0.0",

-    "gulp-eslint": "~1.0.0",
+    "gulp-eslint": "^5.0.0",

-    "gulp-iconfont": "2.0.0",
-    "gulp-iconfont-css": "0.0.9",
+    "gulp-iconfont": "^10.0.2",
+    "gulp-iconfont-css": "^2.3.0",

-    "gulp-load-plugins": "~0.10.0",
+    "gulp-load-plugins": "^1.5.0",

-    "gulp-protractor": "~3.0.0",
+    "gulp-protractor": "^4.1.0",

-    "gulp-uglify": "~1.4.0",
-    "gulp-useref": "~1.3.0",
+    "gulp-uglify": "^3.0.1",
+    "gulp-useref": "^3.1.6",

-    "karma": "~0.13.9",
+    "karma": "^3.1.1",

-    "angular-moment": "0.9.0",
+    "angular-moment": "^1.3.0",

-    "angular-websocket": "1.0.9",
+    "angular-websocket": "^2.0.1",
```

**Comment by nickboldt** [comment]
No but I guess I can see if they're already in IPzilla or submit them, if you agree with these changes. 

No point submitting 5 or 16 CQ tickets if you don't like this update. Let me know!

**Review by ashumilova — APPROVED** [review]

**Comment by ashumilova** [comment]
CQ for angular-file-upload https://dev.eclipse.org/ipzilla/show_bug.cgi?id=18387

**Comment by ashumilova** [comment]
ci-test

**Comment by ashumilova** [comment]
ci-test

**Comment by ashumilova** [comment]
ci-build

**Comment by musienko-maxim** [comment]
Can one of the admins verify this PR?

**Comment by nickboldt** [comment]
I'm going to close this since it's sat untended since December.

**Pull request closed without merging**
