### PR TITLE
CHE-169: Git mixin should not appear if project is not under Git vcs

### PR DESCRIPTION
**Pull request by azatsarynnyy**
Signed-off-by: Artem Zatsarynnyi azatsarynnyy@codenvy.com
@vparfonov

### CODE REVIEW

**Comment by dmytro-ndp** [comment]
@azatsarynnyy: will we see error message "_Not a Git repository._" in **catalina.out** of _Che_ in time of opening the regular project which is not under _GIT_?

**Comment by azatsarynnyy** [comment]
I don't know. May be...

**Comment by dmytro-ndp** [comment]
@vparfonov: take a look at possible _error messages_ in **catalina.sh** as a side effect of this fix. To avoid those messages there should be correct _exception handler_ added in the caller of **GitValueProviderFactory** class.

**Comment by sleshchenko** [comment]
Also please take a look
https://jira.codenvycorp.com/browse/IDEX-3534
https://github.com/codenvy/che-core/commit/8ef8876a965113e5f465581183a817a096f0219d

**Pull request closed without merging**
