### PR TITLE
feat(skip-recording): Allow to skip ffmpeg recording if VIDEO_RECORDING=false env var is given

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
Allow to skip ffmpeg recording when running happy path tests

On some configuration with few cpu cores, ffmpeg is eating almost all the cpu available, thus having a way to disable it allow to spare CPU

### Screenshot/screencast of this PR
N/A

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/18653

### How to test this PR?
```bash
$ docker run ... -e VIDEO_RECORDING=false  ... quay.io/eclipse/che-e2e:nightly
```
note that without providing the variable it's as it is now (ffmpeg is on)

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

Change-Id: Ia26d4b8baa8e77e0010ca8030ee262f3d7528dd4
Signed-off-by: Florent Benoit <fbenoit@redhat.com>

### CODE REVIEW

**Comment by benoitf** [comment]
I'm unsure about the variable name convention

**Comment by rhopp** [comment]
@benoitf This is necessary to make happy path stable on github action agents? Having screencast is big help in figuring out what went wrong and removing it is a huge step back.

Or are there some executors, which have enough CPU power to handle the ffmpeg recording and thus disabling the ffmpeg will happen only in certain cases?

**Comment by rhopp** [comment]
As for the naming goes I don't have nay strong opinion. Even simple `SCREEN_RECORDING` is fine by me. But please make sure it's captured in the readme: https://github.com/eclipse/che/blob/master/dockerfiles/e2e/README.md

**Comment by benoitf** [comment]
> @benoitf This is necessary to make happy path stable on github action agents? Having screencast is big help in figuring out what went wrong and removing it is a huge step back.
> 
> Or are there some executors, which have enough CPU power to handle the ffmpeg recording and thus disabling the ffmpeg will happen only in certain cases?

@rhopp unfornately I was not able to have consistent successful runs with ffmpeg enabled. I did play with some preset as well on ffmpeg to reduce the load but it was not enough.
Also by default ffmpeg is sometimes not reporting any progress on the video as it's lagging.

Only 2 cores are allocated to all github action jobs and with kubernetes/che/selenium/etc it's not enough.
I agree as well that removing it is a huge step back but for now I haven't found a better workaround.

**Comment by benoitf** [comment]
> As for the naming goes I don't have nay strong opinion. Even simple `SCREEN_RECORDING` is fine by me. But please make sure it's captured in the readme: https://github.com/eclipse/che/blob/master/dockerfiles/e2e/README.md

I've updated the variable name to match downstream setting and updated README

**Review by Katka92 — APPROVED** [review]

**Review by ScrewTSW — APPROVED** [review]
LGTM

**Comment by ScrewTSW** [comment]
[ci-build]

**Comment by benoitf** [comment]
@ScrewTSW it is failing due to docker limit but ci.centos job is obsolete so I think we're fine :-)

**Pull request merged**
