### PR TITLE
Adapts Che to new dashboard next image

### PR DESCRIPTION
**Pull request by sleshchenko**
### What does this PR do?
This PR adapts Che to new dashboard next image which includes the existing dashboard, that's done in https://github.com/che-incubator/che-dashboard-next/pull/71
So, Che Server as previously copies resources from Dashboard + Dashboard Next resources.
Helm chart now serves the dashboard next from a separate deployment.

### What issues does this PR fix or reference?
It's a kind of prerequisites for https://github.com/eclipse/che/issues/17647

### How to test this PR?
For Che Server image testing, just run Che in any way and check that dashboard and dashboard next are available.

For helm chart, see more:
<details>
<summary>helm chart tested configurations</summary>

SingleUser Single host
```
export CHART_DIR=/home/sleshche/projects/che/deploy/kubernetes/helm/che
helm upgrade --install che \
  --force \
  --namespace che \
  --set global.cheDomain=$(minikube ip).nip.io \
  --set global.ingressDomain=$(minikube ip).nip.io \
  --set cheImage=sleshchenko/che-server:no-dashboards \
  --set global.serverStrategy=single-host \
  --set global.tls.useSelfSignedCerts=true \
  -f ${CHART_DIR}/values/tls.yaml \
  ${CHART_DIR}
```
Multiuser Single host gateway
```
export CHART_DIR=/home/sleshche/projects/che/deploy/kubernetes/helm/che
helm upgrade --install che \
  --force \
  --namespace che \
  --set global.cheDomain=$(minikube ip).nip.io \
  --set global.ingressDomain=$(minikube ip).nip.io \
  --set cheImage=sleshchenko/che-server:no-dashboards \
  --set global.tls.useSelfSignedCerts=true \
  --set global.serverStrategy=single-host \
  --set cheSinglehostGateway.deploy=true \
  --set global.singleHostExposure=gateway \
  -f ${CHART_DIR}/values/tls.yaml \
  -f ${CHART_DIR}/values/multi-user.yaml \
  ${CHART_DIR}
```
Multiuser Multihost
```
export CHART_DIR=/home/sleshche/projects/che/deploy/kubernetes/helm/che
helm upgrade --install che \
  --force \
  --namespace che \
  --set global.cheDomain=$(minikube ip).nip.io \
  --set global.ingressDomain=$(minikube ip).nip.io \
  --set cheImage=sleshchenko/che-server:no-dashboards \
  --set global.serverStrategy=multi-host \
  --set global.tls.useSelfSignedCerts=true \
  -f ${CHART_DIR}/values/tls.yaml \
  -f ${CHART_DIR}/values/multi-user.yaml \
  ${CHART_DIR}
```

</details>

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Review by akurinnoy — APPROVED** [review]
LGTM

**Comment by sleshchenko** [comment]
rebased against master to try to fix happy path test

**Comment by sleshchenko** [comment]
crw-ci-test

**Comment by sleshchenko** [comment]
Is WIP to avoid merging in 7.22

**Review by skabashnyuk — APPROVED** [review]

**Comment by sleshchenko** [comment]
Rebased against master to make sure everything works before merging

**Comment by sleshchenko** [comment]
Build fails with `[[1;31mERROR[m] Tests run: 2, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 0.756 s <<< FAILURE! - in org.eclipse.che.plugin.typescript.dto.TypeScriptDTOGeneratorMojoITest`
Probably I need to wait a bit to get syncs flashed after release

**Comment by sleshchenko** [comment]
build

**Comment by sleshchenko** [comment]
[crw-ci-test

**Comment by sleshchenko** [comment]
[crw-ci-tes]

**Comment by sleshchenko** [comment]
[crw-ci-test]

**Comment by ScrewTSW** [comment]
[ci-build]

**Comment by ScrewTSW** [comment]
[crw-ci-test --rebuild]

**Comment by sleshchenko** [comment]
[crw-ci-test --rebuild]

**Comment by ScrewTSW** [comment]
Interesting, it's still trying to look for `spring-petclinic-2.3.0.BUILD-SNAPSHOT.jar` instead of `spring-petclinic-2.4.0.BUILD-SNAPSHOT.jar` even though the changes were merged into upstream.

@sleshchenko could you try to rebase your PR based on the latest master of eclipse/che ?

**Comment by ScrewTSW** [comment]
[ci-build]

**Pull request merged**
