### PR TITLE
CODENVY-151: Stop all running workspaces within 1 minute

### PR DESCRIPTION
**Pull request by mmorhun**
**_1 Upvote**_ Signed-off-by: Mykola Morhun mmorhun@codenvy.com

### CODE REVIEW

**Comment by mmorhun** [comment]
@garagatyi check please

**Comment by garagatyi** [comment]
@evoevodin @sleshchenko @skabashnyuk WDYT?

**Comment by sleshchenko** [comment]
LGTM

**Comment by AndrienkoAleksandr** [comment]
+1

**Comment by garagatyi** [comment]
-1

**Comment by voievodin** [comment]
-1 

I don't think that it is a right way of destroying the machines.
1. You don't control the count of threads(so it is not guaranteed that you  shutdown each machine in the separate thread)
2. `.parallelStream` uses `ForkJoinPool.commonPool()` -> you are not waiting for machines to be destroyed. See `commonPool` documentation for more information. 

I suggest you to shutdown machines asynchronously each in the separate thread, to achieve this goal you can either reuse an existing executor + use `CountDownLatch`, or create a separate executor to perform machines destroy.

A few things to respect:
1. Each machine must be destroyed in the separate thread
2. You must wait until all the machines destroyed

**Comment by garagatyi** [comment]
@mmorhun since @evoevodin and me agreed that machine destroying should be implemented in a different way, please close this issue.

**Pull request closed without merging**
