### PR TITLE
Update folder type in case of changing maven project structure

### PR DESCRIPTION
**Pull request by vzhukovs**
### What does this PR do?
Work in progress PR. Testing fix for https://github.com/eclipse/che/issues/7109

Signed-off-by: Vladyslav Zhukovskyi <vzhukovs@redhat.com>

### What issues does this PR fix or reference?
#7109

### CODE REVIEW

**Comment by vzhukovskii** [comment]
ci-test

**Comment by vzhukovskii** [comment]
ci-test

**Comment by vzhukovs** [comment]
ci-test

**Comment by vzhukovs** [comment]
ci-test

**Review by musienko-maxim — APPROVED** [review]

**Review by ashumilova — APPROVED** [review]

**Pull request merged**
