### PR TITLE
Add target="_blank" to the link for "Make a wish" button.

### LINKED ISSUE #14036: Add target="_blank" to the link for "Make a wish" button.
### Is your enhancement related to a problem? Please describe.

At least on ChromeOS, when you press a `Make a wish` button, it will transition the window showing IDE to the Gmail page.

This is trivial and easy to fix. It is no need to add 7.0.0 end game, IMO.
 
### Describe the solution you'd like

This will be fixed by adding `target="_blank"` to the `<a>` element.
 
### Describe alternatives you've considered

No.

### Additional context

gmail

### PR DESCRIPTION
**Pull request by monaka**
Signed-off-by: Masaki Muranaka <monaka@monami-ya.com>

### What does this PR do?

Adds target="_blank" to the link for "Make a wish" button.

### What issues does this PR fix or reference?

fixes #14036

### CODE REVIEW

**Comment by musienko-maxim** [comment]
Can one of the admins verify this PR?

**Review by ashumilova — APPROVED** [review]

**Comment by l0rd** [comment]
Removing label `do-not-merge/hold`. @monaka can you rebase please?

**Comment by monaka** [comment]
@l0rd I did it.

**Comment by sleshchenko** [comment]
ci-build

**Pull request merged**
