### PR TITLE
Update license to EPL 2.0

### PR DESCRIPTION
**Pull request by mkuznyetsov**
### What does this PR do?
Update license to EPL 2.0

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/10465

### CODE REVIEW

**Review by skabashnyuk — APPROVED** [review]

**Review by tsmaeder — APPROVED** [review]

**Review by benoitf — APPROVED** [review]

**Comment by benoitf** [comment]
hello, what about these files ?
https://github.com/eclipse/che/search?q=epl-v10.html&unscoped_q=epl-v10.html

**Comment by skabashnyuk** [comment]
they are not part of maven license plugin configuration, so owners of that files have to think about them.

**Comment by benoitf** [comment]
It's a bit strange to not update the whole repository. It's like "each one updates its own file". The license is global to the repository so I was expecting the license will be updated everywhere.

**Comment by slemeur** [comment]
@skabashnyuk what's the plan for the rest of the files? Are owners informed about what they have to do and the timeline?

**Comment by skabashnyuk** [comment]
>It's a bit strange to not update the whole repository. It's like "each one updates its own file". The license is global to the repository so I was expecting the license will be updated everywhere.

We will take a look on the remaining list for the cases if files are not under plugin check list or were removed by mistake.

**Pull request merged**
