### PR TITLE
Fix for formatting for python language servers

### PR DESCRIPTION
**Pull request by dkulieshov**
Related issue: https://github.com/eclipse/che/issues/9854

Fixed full text formatting by correcting endLine and endCharacter values.

### CODE REVIEW

**Review by vparfonov — APPROVED** [review]

**Comment by SkorikSergey** [comment]
### Reproduction Steps
1. Create workspace from **C++** stack with **console-cpp-simple** project.
2. Enable **Clangd** language server installer if it need.
3. Open **hello.cc** file and add next content:
```cpp
                  int isEven(int x)     {
    return x % 2 ==               0;
                    }
```
4. Apply **Edit** -> **Format**.


**Expected result:** The content should be
```cpp
    int isEven(int x) { return x % 2 == 0; }
```

**Actual result:** The formatting is not applied correctly.

**Additional information:**
screencast-172 19 20 234-8080-2018 06 18-15-57-36

**Comment by musienko-maxim** [comment]
So, we check all existed selenium tests and checked all usecases according to manual test plan for language servers: https://github.com/eclipse/che/wiki/Test-plan-for-checking-Language-servers.
Other bugs, except described above, are not be found

**Comment by dkuleshov** [comment]
ci-test

**Comment by musienko-maxim** [comment]
The existed selenium tests did not find new regression. During manual test plan the we did not find new bugs.

**Review by musienko-maxim — APPROVED** [review]

**Pull request merged**
