### PR TITLE
Fix opening IDE with direct URL

### LINKED ISSUE #15733: Not able to open workspace with direct link
### Describe the bug
I was no able  to open workspace with a direct like this `https://che-che.apps-crc.testing/admin/gogo`
Знімок екрана  о 08 41 26
Знімок екрана  о 08 40 33
Знімок екрана  о 08 39 38

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
1. Create a workspace.
2. Open a direct link in a separate tab of the browser.
3. The workspace is not loaded correctly.

### Expected behavior
Workspace loaded correctly.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [X] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [ ] Linux
       - [x] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

### PR DESCRIPTION
**Pull request by olexii4**
### What does this PR do?
It's marked as 🚧 since it's not complete yet and there is a bug with new redirections rules.

- Removes IDE.html since it works only with removed GWT IDE hosted on Che Server.
- Fixes opening IDE with direct URL:
direct-url

### What issues does this PR fix or reference?
It's supposed to fix the issue along with https://github.com/eclipse/che-workspace-loader/pull/31

fixes https://github.com/eclipse/che/issues/15733

### CODE REVIEW

**Review by akurinnoy — APPROVED** [review]

**Review by sleshchenko — APPROVED** [review]
The fix is valid but seems it does not solve the referenced issue 
Screenshot_20200225_170631

**Comment by sleshchenko** [comment]
ci-build

**Review by skabashnyuk — APPROVED** [review]

**Comment by olexii4** [comment]
crw-ci-test

**Comment by olexii4** [comment]
ci-test

**Comment by SkorikSergey** [comment]
crw-ci-test

**Comment by SkorikSergey** [comment]
crw-ci-test

**Comment by olexii4** [comment]
We have a redirection problem after.
Screenshot from 2020-02-27 15-34-50
Should be fixed.

**Comment by olexii4** [comment]
crw-ci-test

**Comment by olexii4** [comment]
[crw-ci-test]

**Comment by artaleks9** [comment]
[ci-test]

**Comment by olexii4** [comment]
[ci-test]

**Comment by olexii4** [comment]
[ci-test]

**Comment by sleshchenko** [comment]
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-failsafe-plugin:2.22.1:verify (default) on project mysql-tck: There are test failures.
```
MySQL tests seem to be not stable

**Comment by sleshchenko** [comment]
[ci-build]

**Comment by sleshchenko** [comment]
[ci-test]

**Comment by SkorikSergey** [comment]
crw-ci-test

**Comment by olexii4** [comment]
Happy path test failed because of error that happen in https://github.com/eclipse/che/blob/4e2b39fa6f9ace5f9c6b3743ab37e2554f3e13f9/tests/.infra/crw-ci/pr-check/k8s/Jenkinsfile#L251
Request to Che host failed with 404
```
[sskoryk@sskoryk-redhat-com ~]$ curl -sL -I  che-eclipse-che.10.33.177.183.nip.io
HTTP/1.1 404 
Content-Type: text/html;charset=utf-8
Content-Language: en
Transfer-Encoding: chunked
Vary: Accept-Encoding
Date: Wed, 04 Mar 2020 13:51:26 GMT
Set-Cookie: e7e832c4d3d17f241325692f83b9abbe=75ec3b612dfddc543b2cafc457e5b0a0; path=/; HttpOnly
```

**Comment by sleshchenko** [comment]
> [sskoryk@sskoryk-redhat-com ~]$ curl -sL -I  che-eclipse-che.10.33.177.183.nip.io
> HTTP/1.1 404 

Should be fixed now

**Comment by SkorikSergey** [comment]
[ci-test]

**Comment by SkorikSergey** [comment]
crw-ci-test

**Comment by SkorikSergey** [comment]
[crw-ci-test]

**Comment by SkorikSergey** [comment]
[crw-ci-test]

**Comment by sleshchenko** [comment]
That's strange that happy-path test still faces 404 on `curl ${CHE_HOST}` because I locally tested `maxura/che-server:16127` and it works for me in both of multi/single users modes deployed with Operator
Screenshot_20200717_181909

**Comment by dmytro-ndp** [comment]
There was `maxura/che-server:16127` in `[checluster.yaml](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Multiuser-Che-PR-check-E2E-Happy-path-tests-against-k8s/3172/artifact/logs-and-configs/che-config/checluster.yaml/*view*/)`, and there was Che pod container [created from image `maxura/che-server:16127`](che-68dd574944-zckxf).
Coud you, please, ensure, your local `maxura/che-server:16127` image [has sha256:fceb4d3f4b79fdcd565be8538a73459e668734fbe53a2eea8b2bf227d778b617](https://hub.docker.com/layers/maxura/che-server/16127/images/sha256-fceb4d3f4b79fdcd565be8538a73459e668734fbe53a2eea8b2bf227d778b617?context=explore)?

**Comment by sleshchenko** [comment]
seems `-I` option makes curl display 404, but if we omit `-I` then we get redirect...
Screenshot_20200720_092129

Debugging shown that curl with -I makes HEAD http request but not GET.
From 
> 9.4 HEAD
The HEAD method is identical to GET except that the server MUST NOT return a message-body in the response. The metainformation contained in the HTTP headers in response to a HEAD request SHOULD be identical to the information sent in response to a GET request. This method can be used for obtaining metainformation about the entity implied by the request without transferring the entity-body itself. This method is often used for testing hypertext links for validity, accessibility, and recent modification.

https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html

So, I'm fixing the inconsistent behavior of Che Server.

**Comment by SkorikSergey** [comment]
[crw-ci-test]

**Comment by SkorikSergey** [comment]
[ci-test]

**Review by SkorikSergey — APPROVED** [review]

**Pull request merged**
