### PR TITLE
CHE-52. Improve styles for focused button on dialogs

### PR DESCRIPTION
**Pull request by RomanNikitenko**
**_1 Upvote**_ Signed-off-by: Roman Nikitenko rnikitenko@codenvy.com
@ashumilova @slemeur @vparfonov 
dark_primary_button
dark_button_focus
light_primary_button
light_button_focus

### CODE REVIEW

**Comment by vzhukovs** [comment]
Can you provide a screenshot where focus is on this button?
select-path-button-has-focus
I wonder how it will look like.

Thanks in advance.

**Comment by RomanNikitenko** [comment]
select_path

**Comment by vzhukovs** [comment]
Awesome! :+1:

**Comment by RomanNikitenko** [comment]
I've attached video here https://jira.codenvycorp.com/browse/CHE-52

**Comment by slemeur** [comment]
+1

**Comment by vparfonov** [comment]
ok

**Pull request merged**
