### PR TITLE
[Selenium] Stabilize selenium tests from factory package

### PR DESCRIPTION
**Pull request by SkorikSergey**
### What does this PR do?
Stabilize selenium tests from ```factory``` package.

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/15392

### CODE REVIEW

**Comment by SkorikSergey** [comment]
ci-test

**Comment by SkorikSergey** [comment]
crw-ci-test

**Comment by SkorikSergey** [comment]
crw-ci-test

**Review by dmytro-ndp — APPROVED** [review]
Looks good.

**Pull request merged**
