### PR TITLE
fix workspace name uniqueness validation

### PR DESCRIPTION
**Pull request by akurinnoy**
Signed-off-by: Oleksii Kurinnyi okurinnyi@codenvy.com

### CODE REVIEW

**Comment by benoitf** [comment]
if we're testing against workspaceId I would change the name of the directive then (it's id and not anymore name)

**Comment by akurinnoy** [comment]
The directive should test name of workspace to be unique so I would let it's name. Instead I've changed directive's attribute value. It's needed for current workspace not to compare to itself.

**Comment by benoitf** [comment]
what about merging it ?

**Comment by benoitf** [comment]
also I don't see JIRA issue in commit message

**Comment by ashumilova** [comment]
Jira issue is https://jira.codenvycorp.com/browse/CHE-1163, is not completed and @akurinnoy is ill at the moment

**Pull request merged**
