### PR TITLE
Set 'next' version for che-machine-exec as default

### PR DESCRIPTION
**Pull request by vparfonov**
Signed-off-by: Vitalii Parfonov <vparfono@redhat.com>

### What does this PR do?
Set 'next' version for che-machine-exec as default 
See: https://github.com/eclipse/che-plugin-registry/pull/194

### CODE REVIEW

**Review by l0rd — APPROVED** [review]

**Comment by vparfonov** [comment]
ci-test

**Comment by vparfonov** [comment]
ci-test

**Comment by vparfonov** [comment]
ci-test

**Comment by musienko-maxim** [comment]
ci-test

**Comment by musienko-maxim** [comment]
ci-test

**Comment by vparfonov** [comment]
ci-test

**Comment by musienko-maxim** [comment]
ci-test

**Pull request merged**
