### PR TITLE
Make Che 7 model fields use camel-case

### PR DESCRIPTION
**Pull request by garagatyi**
### What does this PR do?
Make Che 7 model fields use camel-case.

### What issues does this PR fix or reference?
Depends on https://github.com/eclipse/che/pull/12527

### CODE REVIEW

**Review by sleshchenko — DISMISSED** [review]

**Comment by metlos** [comment]
LGTM, but we need a non-wip PR + integration tests run

**Comment by metlos** [comment]
ci-test

**Comment by garagatyi** [comment]
It is not needed to run tests and unWIP it because it depends on your PR and tests would fail until you merge it

**Comment by garagatyi** [comment]
ci-test

**Comment by garagatyi** [comment]
@sleshchenko @metlos @skabashnyuk PR is not WIP anymore, please, review

**Review by sleshchenko — APPROVED** [review]
LGTM

**Comment by garagatyi** [comment]
@eclipse/eclipse-che-qa Please, take a look at the report

**Comment by artaleks9** [comment]
Selenium tests execution on Eclipse Che Multiuser on OCP (https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1498/) doesn't show any regression against this Pull Request.

**Comment by garagatyi** [comment]
@metlos @skabashnyuk Please, review

**Review by skabashnyuk — APPROVED** [review]

**Pull request merged**
