### PR TITLE
Implementers is Broken for Class Files #10337

### PR DESCRIPTION
**Pull request by vrubezhny**
Issue: #10337

Signed-off-by: Victor Rubezhny <vrubezhny@redhat.com>

### What does this PR do?

Fixes the Open Implementers functionality

### What issues does this PR fix or reference?

Issue: #10337

#### Release Notes

ls10337

### CODE REVIEW

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Review by tsmaeder — COMMENTED** [review]
lgtm, however, it's a sign that we have a problem with uri's

**Review by tsmaeder — APPROVED** [review]

**Pull request merged**
