### PR TITLE
Update dependencies versions

### PR DESCRIPTION
**Pull request by Katka92**
### What does this PR do?
This PR should fix dependency vulnerabilities.

### What issues does this PR fix or reference?
https://github.com/eclipse/che/security/dependabot

### How to test this PR?
The Happy path test should be passing.

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Review by Ohrimenko1988 — APPROVED** [review]

**Review by ScrewTSW — APPROVED** [review]
I believe that we can merge it before we finish the testing so that we can fix any downstream issues before the release

**Comment by dmytro-ndp** [comment]
@Katka92: it's still `selenium/standalone-chrome:87.0` in e2e test image: https://github.com/eclipse/che/blob/master/dockerfiles/e2e/Dockerfile#L1

**Comment by ScrewTSW** [comment]
> @Katka92: it's still `selenium/standalone-chrome:87.0` in e2e test image: https://github.com/eclipse/che/blob/master/dockerfiles/e2e/Dockerfile#L1

Good point Dmytro

**Comment by Katka92** [comment]
Thank you @dmytro-ndp! I've fixed that

**Pull request merged**
