### PR TITLE
Adding unit tests for UUID class

### PR DESCRIPTION
**Pull request by Wajihulhassan**
@garagatyi,  as discussed in the [PR1165](https://github.com/eclipse/che/pull/1165).

Signed-off-by: Wajih ul hassan wajih.lums@gmail.com

### CODE REVIEW

**Comment by garagatyi** [comment]
LGTM

**Comment by garagatyi** [comment]
ci-build

**Comment by Wajihulhassan** [comment]
@garagatyi , on a separate note, looking at `che/core/commons/che-core-commons-gwt/src/main/java/org/eclipse/che/ide/util` directory most of the classes there like `StringUtils.java`, `MathUtils.java`, `TextUtils.java` etc. are not being covered by any tests. Will you guys be interested in accepting good unit tests for some these classes?

**Comment by garagatyi** [comment]
Sure we would love to have more tests in all components of CHE. But maybe @vparfonov has some plans (remove these classes, refactor, etc).
@vparfonov WDYT?

**Pull request merged**
