### PR TITLE
Fix security vulnerability and Dashboard's workspace detail page

### PR DESCRIPTION
**Pull request by akurinnoy**
### What does this PR do?

- [Dashboard] activate first tab on workspace details page if no other tab was enabled in query params
- [e2e tests] update `axios` version  to avoid security vulnerability

### CODE REVIEW

**Review by Ohrimenko1988 — APPROVED** [review]

**Review by olexii4 — APPROVED** [review]

**Review by benoitf — APPROVED** [review]

**Comment by benoitf** [comment]
@akurinnoy do you have CQ ?

**Comment by SkorikSergey** [comment]
ci-build

**Comment by akurinnoy** [comment]
@benoitf 
yes, it was done by @evidolob a month ago https://dev.eclipse.org/ipzilla/show_bug.cgi?id=20719

**Comment by dmytro-ndp** [comment]
ci-build

**Comment by akurinnoy** [comment]
crw-ci-test

**Comment by SkorikSergey** [comment]
ci-test

**Comment by SkorikSergey** [comment]
Selenium tests execution on Eclipse Che Multiuser on OCP (https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/2424//Selenium_20tests_20report/) doesn't show any regression against this Pull Request.

**Pull request merged**
