### PR TITLE
Update version of openjdk base image to 8u131

### PR DESCRIPTION
**Pull request by l0rd**
### What does this PR do?
Update the base Docker image to `openjdk:8u131` (was `8u111` before)

### What issues does this PR fix or reference?
Version `8u111` was a quite old version (1yr old)

### CODE REVIEW

**Review by riuvshin — CHANGES_REQUESTED** [review]
unfortunately we can't update openJDK version just like that. Take a look on https://github.com/eclipse/che/blob/che6/dockerfiles/che/open-jdk-source-file-location

That file describes how OpenJDK was built on parent image which was requested by RH legal department. 
So that file must be updated to represent how newer openJDK version was built

**Comment by l0rd** [comment]
@riuvshin I have updated both PRs (this one and https://github.com/eclipse/che/pull/7439)

**Review by riuvshin — APPROVED** [review]

**Comment by riuvshin** [comment]
@l0rd AFAIK we also used exactly same version of JDK for workspaces images and agents that will install JDK if it is missing to keep ws master and agent on same version of JDK. Im not sure if we should update it also... @skabashnyuk WDYT?

**Comment by l0rd** [comment]
@riuvshin it doesn't look like it's the same version https://github.com/eclipse/che-dockerfiles/blob/master/recipes/stack-base/ubuntu/Dockerfile#L39. 

Said that I think we should update ubuntu stacks with the latest version of openjdk available for that distribution (i.e. `8u151-b12-0ubuntu0.16.04.2`).

**Pull request merged**
