### PR TITLE
Adding Quarkus devfile tests

### PR DESCRIPTION
**Pull request by ScrewTSW**
### What does this PR do?
This PR adds devfile tests for Quarkus.

### What issues does this PR fix or reference?
#16882 

#### Release Notes
N/A

#### Docs PR
N/A

### CODE REVIEW

**Review by Katka92 — APPROVED** [review]

**Review by Ohrimenko1988 — APPROVED** [review]

**Comment by ScrewTSW** [comment]
[vi-test]

**Comment by ScrewTSW** [comment]
[ci-test]

**Comment by ScrewTSW** [comment]
[ci-build]

**Comment by ScrewTSW** [comment]
crw-ci-test

**Pull request merged**
