### PR TITLE
Add phantomjs module

### PR DESCRIPTION
**Pull request by ashumilova**
**_2 Upvotes**_ Signed-off-by: Ann Shumilova ashumilova@codenvy.com

### CODE REVIEW

**Comment by benoitf** [comment]
+1

**Comment by skabashnyuk** [comment]
cq?

**Comment by benoitf** [comment]
it's already there it was transitive dependency of phantomjs-launcher but transitive dependencies is not working with npm >= 3.x

**Comment by ashumilova** [comment]
it's also "build and test" tool section

**Comment by olexii4** [comment]
+1

**Pull request merged**
