### PR TITLE
Initial cleanup of che6 legacy code

### PR DESCRIPTION
**Pull request by skabashnyuk**
### What does this PR do?
```
rm -rf core/che-core-gwt-maven-plugin/
rm -rf core/che-core-dynamodule-maven-plugin/
rm -rf ide/
rm -rf plugins/
rm -rf wsagent/
rm -rf agents/
rm -rf deploy/docker
rm -rf assembly/assembly-ide-war/
rm -rf assembly/assembly-wsagent-war/
rm -rf assembly/assembly-wsagent-server/
rm -rf multiuser/machine-auth/che-multiuser-machine-authentication-ide/
rm -rf multiuser/keycloak/che-multiuser-keycloak-ide/
rm -rf cypress-tests/
```

Initial cleanup of che6 legacy code

Build time comparison
Before
```
[INFO] Total time:  16:02 min
```
after
```
[INFO] Total time:  08:37 min
```

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/12243

#### Release Notes
n/a

#### Docs PR
n/a

### CODE REVIEW

**Comment by skabashnyuk** [comment]
CC @vparfonov

**Comment by skabashnyuk** [comment]
ci-test

**Comment by skabashnyuk** [comment]
@l0rd @slemeur @vparfonov is this kind of clean up we still interesting to do for GA?

**Comment by benoitf** [comment]
AFAIk we could delete cypress-tests as well as cypress is no longer used

**Comment by l0rd** [comment]
@skabashnyuk 👍

**Comment by skabashnyuk** [comment]
@rhopp can you confirm the destiny of cypress-tests  folder?

**Comment by artaleks9** [comment]
The _cypress-tests_ folder is deprecated and can be deleted.

**Comment by dmytro-ndp** [comment]
@skabashnyuk: there is dependency to `che-core-ide-stacks` remained https://github.com/eclipse/che/blob/che7cleanup/assembly/assembly-wsmaster-war/pom.xml#L204

**Comment by skabashnyuk** [comment]
@dmytro-ndp you are right. I've pushed appropriate changes.

**Comment by dmytro-ndp** [comment]
@skabashnyuk: thanks a lot for a quick fixup! Che builds as expected now:
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Che Parent ......................................... SUCCESS [  2.452 s]
[INFO] Che Core Parent .................................... SUCCESS [  0.031 s]
[INFO] Che Core :: Commons :: Parent ...................... SUCCESS [  0.040 s]
[INFO] Che Core :: Commons :: Annotations ................. SUCCESS [  3.044 s]
[INFO] Che Core :: Commons :: Java API extension classes .. SUCCESS [  4.763 s]
[INFO] Che Core :: API :: DTO ............................. SUCCESS [  5.868 s]
[INFO] Che Core :: Commons :: Json helpers ................ SUCCESS [  1.514 s]
[INFO] Che Core :: Commons :: Utilities for tests ......... SUCCESS [  1.848 s]
[INFO] Che Core :: Commons :: Dependency Injecting ........ SUCCESS [  3.729 s]
[INFO] Che Core :: Commons :: Scheduler service ........... SUCCESS [  1.992 s]
[INFO] Che Core :: API :: DTO Maven Plugin ................ SUCCESS [  1.959 s]
[INFO] Che Core :: API :: Core ............................ SUCCESS [ 15.460 s]
[INFO] Che Core :: Commons :: Auth ........................ SUCCESS [  0.452 s]
[INFO] Che Core :: Commons :: Commons Logback ............. SUCCESS [  0.373 s]
[INFO] Che Core :: Commons :: XML ......................... SUCCESS [  2.909 s]
[INFO] Che Core :: Commons :: Commons J2ee ................ SUCCESS [  1.693 s]
[INFO] Che Core :: Commons :: Mail sender ................. SUCCESS [  1.941 s]
[INFO] Che Core :: Commons :: Tracing ..................... SUCCESS [  0.219 s]
[INFO] Che Core :: API :: TypeScript DTO maven plugin ..... SUCCESS [ 15.926 s]
[INFO] Che Core :: API :: Model ........................... SUCCESS [  0.454 s]
[INFO] Che Core :: DB ..................................... SUCCESS [  2.908 s]
[INFO] Che Core :: DB :: Vendor H2 ........................ SUCCESS [  0.354 s]
[INFO] Che Core :: DB :: Vendor MySQL ..................... SUCCESS [  0.217 s]
[INFO] Che Core :: DB :: Vendor PostgreSQL ................ SUCCESS [  0.353 s]
[INFO] Che Core :: Tracing :: Core ........................ SUCCESS [  0.240 s]
[INFO] Che Core :: Tracing :: Web ......................... SUCCESS [  0.199 s]
[INFO] Che Core :: Metrics :: Core ........................ SUCCESS [  3.741 s]
[INFO] Che Core :: Tracing :: Metrics ..................... SUCCESS [  0.306 s]
[INFO] Che Master Parent .................................. SUCCESS [  0.029 s]
[INFO] Che Core :: API :: Workspace :: Shared ............. SUCCESS [  2.642 s]
[INFO] Che Core :: API :: Installer :: Shared ............. SUCCESS [  0.310 s]
[INFO] Che Core :: SQL :: Schema .......................... SUCCESS [  0.107 s]
[INFO] Che Core :: API :: Installer ....................... SUCCESS [  8.606 s]
[INFO] Che Core :: API :: Authentication :: Shared ........ SUCCESS [  1.362 s]
[INFO] Che Core :: API :: Authentication .................. SUCCESS [  2.328 s]
[INFO] Che Core :: API :: Authentication Github ........... SUCCESS [  0.318 s]
[INFO] Che Core :: API :: Project Templates :: Shared ..... SUCCESS [  1.413 s]
[INFO] Che Core :: API :: Project Templates ............... SUCCESS [  0.395 s]
[INFO] Che Core :: API :: Account ......................... SUCCESS [  5.091 s]
[INFO] Che Core :: API :: System Shared ................... SUCCESS [  1.256 s]
[INFO] Che Core :: API :: System .......................... SUCCESS [  4.370 s]
[INFO] Che Core :: API :: SSH :: Shared ................... SUCCESS [  1.266 s]
[INFO] Che Core :: API :: User :: Shared .................. SUCCESS [  1.299 s]
[INFO] Che Core :: API :: User ............................ SUCCESS [ 10.937 s]
[INFO] Che Core :: API :: SSH ............................. SUCCESS [  5.125 s]
[INFO] Che Core :: API :: Workspace ....................... SUCCESS [ 25.627 s]
[INFO] Che Multiuser :: Parent ............................ SUCCESS [  0.023 s]
[INFO] Che Multiuser :: API Parent ........................ SUCCESS [  0.022 s]
[INFO] Che Multiuser :: Permissions :: Shared ............. SUCCESS [  0.226 s]
[INFO] Che Multiuser :: Sql Schema ........................ SUCCESS [  0.047 s]
[INFO] Che Multiuser :: Permissions API ................... SUCCESS [  8.959 s]
[INFO] Che Multiuser :: Permissions Parent ................ SUCCESS [  0.024 s]
[INFO] Che Multiuser :: Workspace Permissions ............. SUCCESS [ 15.866 s]
[INFO] Che Core :: Workspace Activity ..................... SUCCESS [  9.560 s]
[INFO] Che Core :: API :: Factory :: Shared ............... SUCCESS [  1.653 s]
[INFO] Che Infrastructures Parent ......................... SUCCESS [  0.030 s]
[INFO] Infrastructure :: Docker :: Parent ................. SUCCESS [  0.031 s]
[INFO] Infrastructure :: Docker :: Docker Auth ............ SUCCESS [  3.180 s]
[INFO] Infrastructure :: Docker :: Environment ............ SUCCESS [  3.593 s]
[INFO] Che Multiuser :: API :: Authorization .............. SUCCESS [  2.644 s]
[INFO] Che Multiuser :: Machine Auth Parent ............... SUCCESS [  0.031 s]
[INFO] Che Multiuser :: Machine Authentication Shared ..... SUCCESS [  0.230 s]
[INFO] Che Multiuser :: Machine Authentication ............ SUCCESS [  9.344 s]
[INFO] Infrastructure :: Kubernetes ....................... SUCCESS [ 20.380 s]
[INFO] Che Core :: API :: Factory ......................... SUCCESS [ 12.434 s]
[INFO] Che Core :: API :: Factory Resolver Github ......... SUCCESS [  2.432 s]
[INFO] Che Core :: API :: Impl Local ...................... SUCCESS [  0.529 s]
[INFO] Integration Tests :: Parent ........................ SUCCESS [  0.021 s]
[INFO] Integration Tests :: Cascade Removal ............... SUCCESS [  8.478 s]
[INFO] Che Core :: API :: Logger :: Shared ................ SUCCESS [  1.041 s]
[INFO] Che Core :: API :: Logger .......................... SUCCESS [  3.736 s]
[INFO] Che Core :: API :: Metrics ......................... SUCCESS [  2.814 s]
[INFO] Che Multiuser :: API :: Authorization Impl ......... SUCCESS [  2.016 s]
[INFO] Che Multiuser :: Resource :: Shared ................ SUCCESS [  0.176 s]
[INFO] Che Multiuser :: Resource .......................... SUCCESS [ 10.188 s]
[INFO] Che Multiuser :: Organization :: Shared ............ SUCCESS [  0.226 s]
[INFO] Che Multiuser :: Organization ...................... SUCCESS [ 15.527 s]
[INFO] Che Multiuser :: JGroups API Implementation ........ SUCCESS [  0.399 s]
[INFO] Che Multiuser :: Workspace Activity ................ SUCCESS [  2.165 s]
[INFO] Che Multiuser :: User Permissions .................. SUCCESS [  4.211 s]
[INFO] Che Multiuser :: Devfile Permissions ............... SUCCESS [  3.973 s]
[INFO] Che Multiuser :: Workspace Activity Permissions .... SUCCESS [  3.900 s]
[INFO] Che Multiuser :: Factory Permissions ............... SUCCESS [  4.537 s]
[INFO] Che Multiuser :: System Permissions ................ SUCCESS [  3.895 s]
[INFO] Che Multiuser :: Installer Permissions ............. SUCCESS [  3.849 s]
[INFO] Che Multiuser :: Resource :: Permissions ........... SUCCESS [  5.021 s]
[INFO] Che Multiuser :: Logger Permissions ................ SUCCESS [  4.125 s]
[INFO] Che Multiuser :: Kubernetes Infrastructure Permissions SUCCESS [  2.213 s]
[INFO] Che Multiuser :: Keycloak Integration Parent ....... SUCCESS [  0.021 s]
[INFO] Che Multiuser :: Keycloak Shared module ............ SUCCESS [  0.143 s]
[INFO] Che Multiuser :: Personal account .................. SUCCESS [  1.865 s]
[INFO] Che Multiuser :: Keycloak Server ................... SUCCESS [  6.408 s]
[INFO] Che Multiuser :: Keycloak Token Provider ........... SUCCESS [  1.056 s]
[INFO] Che Multiuser :: Machine Authentication Agent ...... SUCCESS [  2.613 s]
[INFO] Che Multiuser :: Integration Tests ................. SUCCESS [  0.029 s]
[INFO] Che Multiuser :: Integration Cascade ............... SUCCESS [  8.820 s]
[INFO] Che Multiuser :: PostgreSQL Tck .................... SUCCESS [  0.711 s]
[INFO] Che Multiuser :: MYSQL Tck Tests ................... SUCCESS [  0.468 s]
[INFO] Infrastructure :: Docker :: Docker Client .......... SUCCESS [  6.418 s]
[INFO] Infrastructure :: Docker ........................... SUCCESS [  5.622 s]
[INFO] Infrastructure :: OpenShift ........................ SUCCESS [  6.233 s]
[INFO] Che Dashboard :: Web App ........................... SUCCESS [03:29 min]
[INFO] Che Workspace Loader :: Web App .................... SUCCESS [  1.178 s]
[INFO] Che IDE :: Parent .................................. SUCCESS [  0.027 s]
[INFO] Che IDE :: Compiling WS Master WAR ................. SUCCESS [  6.821 s]
[INFO] Che IDE :: War Packaging ........................... SUCCESS [  2.339 s]
[INFO] Che Workspace Loader :: War Packaging .............. SUCCESS [  0.273 s]
[INFO] Che IDE :: Assemblies Tomcat ....................... SUCCESS [  7.000 s]
```

**Comment by dmytro-ndp** [comment]
@skabashnyuk : could you, please, also, explain, if there is a reason to keep `org.eclipse.che.plugin` dependencies in root pom.xml besides we are removing `/plugins` directory?
https://github.com/eclipse/che/blob/994c4740f659678c46bc61d47119f12935108e98/pom.xml#L1161-L1911

**Comment by skabashnyuk** [comment]
> could you, please, also, explain, if there is a reason to keep org.eclipse.che.plugin

@dmytro-ndp no reason. I've removed it.

**Comment by skabashnyuk** [comment]
ci-test

**Comment by skabashnyuk** [comment]
@eclipse/eclipse-che-qa is that expected result for this branch?
Is there a way to run other "Happy path" tests?

**Comment by dmytro-ndp** [comment]
https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1927//Selenium_20tests_20report/ is expected result. There will be less regression after you will update PR with latest changes from master.
@SkorikSergey : could you, please, run newer Happy path tests against this PR once, locally, or on CRW Central CI, and then leave comment here with results?

**Comment by skabashnyuk** [comment]
@dmytro-ndp latest master already merged with this commit https://github.com/eclipse/che/pull/13788/commits/7600d76ddf79c029d33575cc112d3a4aa0b6ddb4

**Comment by skabashnyuk** [comment]
ci-test

**Review by benoitf — APPROVED** [review]

**Review by vparfonov — APPROVED** [review]

**Comment by skabashnyuk** [comment]
@nickboldt @rhopp wdyt?

**Comment by sleshchenko** [comment]
@skabashnyuk Should we consider removing docker infrastructure code as well?

**Comment by skabashnyuk** [comment]
>@skabashnyuk Should we consider removing docker infrastructure code as well?

 Maybe later. AFAIK some part of it reused in k8s/OS infrastructure.

**Comment by SkorikSergey** [comment]
> @SkorikSergey : could you, please, run newer Happy path tests against this PR once, locally, or on CRW Central CI, and then leave comment here with results?

@dmytro-ndp HappyPath test pass successfully on minikube.

**Comment by vparfonov** [comment]
@rhopp @dmytro-ndp @SkorikSergey Can some one from your team approve this PR? Would be great if it will be a part of RC4 release. Thanks

**Review by rhopp — APPROVED** [review]

**Pull request merged**
