### PR TITLE
chore: Adapt Happy Path tests to the changes related to the Monaco upgrade

### PR DESCRIPTION
**Pull request by RomanNikitenko**
**The PR should be merged at the same time with https://github.com/eclipse-che/che-theia/pull/1171**

Signed-off-by: Roman Nikitenko <rnikiten@redhat.com>

### What does this PR do?
The `Monaco` version was updated in `theia` repo.
The current PR provides some adaptation for `Happy Path` tests to get them working for `che-theia` PRs.

### What issues does this PR fix or reference?

https://github.com/eclipse/che/issues/20172

### How to test this PR?

The `Happy Path` tests should pass successfully for `che-theia` PRs.
I have got [the succeed tests](https://github.com/eclipse-che/che-theia/pull/1171#issuecomment-886730013) for the corresponding PR of `che-theia`

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Review by ScrewTSW — APPROVED** [review]
LGTM

**Comment by dmytro-ndp** [comment]
@Katka92 , @ScrewTSW , @Ohrimenko1988 : FYI: PR Happy path tests are failing till https://github.com/eclipse-che/che-theia/pull/1171 is merged.

Happy path tests from this PR are passing in Che-theia PR with changes in editor, which Happy path tests are adapted to: https://github.com/eclipse-che/che-theia/pull/1171#issuecomment-888217708

**Review by Ohrimenko1988 — APPROVED** [review]

**Review by Katka92 — APPROVED** [review]
Approving now, but expecting this to be merged together with the PR implementing changes in theia. Thanks for creating this PR!

**Comment by RomanNikitenko** [comment]
> @Katka92 , @ScrewTSW , @Ohrimenko1988 : FYI: PR Happy path tests are failing till [eclipse-che/che-theia#1171](https://github.com/eclipse-che/che-theia/pull/1171) is merged.
> 
> Happy path tests from this PR are passing in Che-theia PR with changes in editor, which Happy path tests are adapted to: [eclipse-che/che-theia#1171 (comment)](https://github.com/eclipse-che/che-theia/pull/1171#issuecomment-888217708)

thank you, Dmytro, I mentioned that in the PR description as well

**Pull request merged**
