### PR TITLE
[UD] Add ability to create a new workspace from the dashboard with a devfile

### LINKED ISSUE #13591: Add ability to create a new workspace from the dashboard with a devfile
### Description
Right now, the dashboard does not provide the ability to create a new workspace from a devfile.

In previous versions, we were providing the ability to create a workspace from a workspaceConfig. 

Capture d’écran 2019-06-20 à 12 46 02

The simplest and quickest way would be by adding tabs in the workspace creation:
CreateWorkspace-WithDevfile

Import Devfile URL

Import Devfile YML

### PR DESCRIPTION
**Pull request by akurinnoy**
### What does this PR do?

This PR adds ability to create a new workspace from User Dashboard with a devfile.

#### DEMO

new-workspace-from-devfile

### What issues does this PR fix or reference?

closes https://github.com/eclipse/che/issues/13591

### CODE REVIEW

**Comment by akurinnoy** [comment]
ci-test

**Comment by sparkoo** [comment]
@akurinnoy There is an issue with editing devfile name/generateName caused by frontend validation https://github.com/eclipse/che/issues/14695. Are your changes doing some frontend validation of workspace name or touching existing validation? Or it just sends the devfile to the server without any further validation?

**Comment by akurinnoy** [comment]
@sparkoo thank you for pointing that issue out, we are going to take it for next sprint. 
This PR doesn't change existing validation of workspace name.

**Comment by SkorikSergey** [comment]
Selenium tests execution on Eclipse Che Multiuser on OCP (https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/2970//Selenium_20tests_20report/) doesn't show any regression against this Pull request.

**Review by SkorikSergey — APPROVED** [review]

**Review by benoitf — APPROVED** [review]
👍

**Pull request merged**
