### PR TITLE
che #18914 Adding 'ReplicaSetCreateError' to the list of the unrecoverable events

### PR DESCRIPTION
**Pull request by ibuziuk**
### What does this PR do?
Adding 'ReplicaSetCreateError' to the list of the unrecoverable events

### What issues does this PR fix or reference?
#18914 

When the unrecoverable event is hit fail fast:

image

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by ibuziuk** [comment]
[crw-ci-test]

**Comment by ibuziuk** [comment]
[crw-ci-test]

**Review by amisevsk — APPROVED** [review]

**Comment by ibuziuk** [comment]
[crw-ci-test]

**Comment by dmytro-ndp** [comment]
[crw-ci-test]

**Review by sleshchenko — APPROVED** [review]

**Comment by ibuziuk** [comment]
[crw-ci-test]

**Comment by ibuziuk** [comment]
[crw-ci-test]

**Comment by ibuziuk** [comment]
[crw-ci-test]

**Comment by ibuziuk** [comment]
[crw-ci-test]

**Comment by ibuziuk** [comment]
[crw-ci-test]

**Comment by ibuziuk** [comment]
[crw-ci-test]

**Comment by ibuziuk** [comment]
[crw-ci-test --rebuild]

**Review by ohbus — APPROVED** [review]

**Comment by ibuziuk** [comment]
[crw-ci-test]

**Comment by ibuziuk** [comment]
[crw-ci-test]

**Comment by ibuziuk** [comment]
@dmytro-ndp @rhopp I get tired to trigger the build forever. Going to merge this PR without the crw-ci tests since it is dead broken :/

**Comment by ibuziuk** [comment]
[crw-ci-test --rebuild]

**Comment by ibuziuk** [comment]
[crw-ci-test]

**Comment by ibuziuk** [comment]
[crw-ci-test --rebuild]

**Comment by ibuziuk** [comment]
[crw-ci-test --rebuild]

**Comment by dmytro-ndp** [comment]
@ibuziuk: Could you, please, take latest changes from master branch? There are fixes of Happy path tests.

**Comment by ibuziuk** [comment]
@dmytro-ndp done, but `[crw-ci-test]` is still dead broken

**Review by dmytro-ndp — APPROVED** [review]
Test workspace have successfully started in Eclipse Che on minikube 1.1.1 in [Happy path PR check](https://github.com/eclipse/che/pull/18915#issuecomment-774167667):
https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Multiuser-Che-PR-check-E2E-Happy-path-tests-against-k8s/4483/artifact/tests/e2e/report/Validation_of_workspace_start_Wait_for_workspace_readiness/screenshot-Wait_for_workspace_readiness.png
screenshot-Wait_for_workspace_readiness (7)

**Pull request merged**
