### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by mkuznyetsov**
### What does this PR do?
Changes related to dependency upgrade

- removed guice-multibindings as it is a part of guice core dependency
- adapting to changes in jackson-dataformat-yaml / org.snakeyaml 

Must be merged with corresponding PR in che-parent https://github.com/eclipse/che-parent/pull/93

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/11902

### CODE REVIEW

**Comment by mkuznyetsov** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1177/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1177//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11944
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by mkuznyetsov** [comment]
ci-test

**Review by garagatyi — APPROVED** [review]

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1188/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1188//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11944
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by mkuznyetsov** [comment]
ci-test

**Comment by mkuznyetsov** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1199/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1199//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11944
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by mkuznyetsov** [comment]
Added more Google dependencies. Removed guice-multibinding as it would be a part of core guice in 4.2.2

**Comment by mkuznyetsov** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1205/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1205//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11944
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by mkuznyetsov** [comment]
ci-test

**Comment by artaleks9** [comment]
Selenium tests execution on Eclipse Che Multiuser on OCP (https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1208/) doesn't show any regression against this Pull Request.

**Review by skabashnyuk — APPROVED** [review]

**Comment by mkuznyetsov** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1238/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1238//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11944
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by mkuznyetsov** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1239/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1239//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11944
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by mkuznyetsov** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1240/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1240//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11944
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1261/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1261//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11944
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by mkuznyetsov** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1272/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1272//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11944
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Review by skabashnyuk — APPROVED** [review]

**Comment by skabashnyuk** [comment]
FYI @ibuziuk

**Comment by mkuznyetsov** [comment]
ci-build

**Pull request merged**
