### PR TITLE
Factory migration

### PR DESCRIPTION
**Pull request by mshaposhnik**
### What does this PR do?
Moves factories into CHE.

### What issues does this PR fix or reference?
#4091 #4093 #4291

#### Changelog
Adds Factories which automate workspace provisioning. 

#### Release Notes
In this release Codenvy has donated its Factory capability to the Che project for open source consumption. A Factory is a template used to generate new or open existing workspaces with a URL. Factories can be used to create replicas of existing workspaces or to automate the provisioning of statically or dynamically defined workspaces.

Factories are described by a `factory.json` file, identified by a unique hashcode and called by a URL. These URLs can be generated by going to the new Factories page in the dashboard or by invoking a URL within your workspace:
/ws/{workspace}/{user}/factory/{name}?save = `{your-che-hostname}/ws/my-workspace/tylerjewell/factory/starwars?save

Factories also allow you to set actions that will occur when a new user workspace is generated from the Factory URL. For example, files can be automatically opened so that a README or other key files are always open and easily found by new users of your Factory.

Commands can also be automatically run in the newly generated workspace. This can be helpful for pre-building applications or fetching dependencies at workspace startup.

Finally, Factories can be programmatically created in response to events like webhooks. This makes them very helpful for creating integrations between Che and other platforms.

As you can see there is a lot that you can do with Factories. Please read our Factory docs pages for all the details.

#### Docs PR
https://github.com/eclipse/che-docs/issues/173

### CODE REVIEW

**Review by skabashnyuk — COMMENTED** [review]
You can proceed to check-in your source code when ready

**Review by skabashnyuk — COMMENTED** [review]
You can proceed to check-in your source code when ready

**Review by benoitf — COMMENTED** [review]
It looks overall good but it's quite impossible to review 250+ files

**Review by bmicklea — APPROVED** [review]

**Comment by slemeur** [comment]
Cross linking with bugs that need to be fixed before merge:
https://github.com/eclipse/che/issues/4456
https://github.com/eclipse/che/issues/4457

**Comment by mshaposhnik** [comment]
We're about to merge this. Does anybody has thoughts that can prevent us ?

**Comment by musienko-maxim** [comment]
After launching functionality tests regression is absent

**Pull request merged**
