### PR TITLE
Use init broker to remove plugins files on brokering

### PR DESCRIPTION
**Pull request by garagatyi**
### What does this PR do?
Currently, che plugin broker cleans up /plugins folder. Since the order of brokers might be affected by different reasons it brings instability. For example, Theia plugin broker may add a plugin to `/plugins` that Che plugin broker, that is started right after, removes it.

This PR adds init broker that is used as init container for brokers pod.

### What issues does this PR fix or reference?
Depends on https://github.com/eclipse/che-plugin-broker/pull/21

### CODE REVIEW

**Comment by garagatyi** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1288/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1288//Selenium_20tests_20report/)
docker image: eclipseche/che-server:12163
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Review by skabashnyuk — APPROVED** [review]

**Review by sleshchenko — APPROVED** [review]

**Comment by garagatyi** [comment]
ci-test

**Comment by garagatyi** [comment]
ci-test

**Comment by garagatyi** [comment]
ci-test

**Review by musienko-maxim — APPROVED** [review]

**Pull request merged**
