### PR TITLE
Update theia generator0.0.1 1547641536

### PR DESCRIPTION
**Pull request by AndrienkoAleksandr**
### What does this PR do?
Update theia generator0.0.1 1547641536

### What issues does this PR fix or reference?
[Move che-theia-terminal-extension to the eclipse repo](https://github.com/eclipse/che/issues/12423)

### CODE REVIEW

**Review by benoitf — APPROVED** [review]

**Review by evidolob — APPROVED** [review]

**Comment by AndrienkoAleksandr** [comment]
ci-build

**Review by mmorhun — APPROVED** [review]

**Comment by AndrienkoAleksandr** [comment]
@benoitf Ok, but check tests in Your pr.

**Comment by benoitf** [comment]
@AndrienkoAleksandr `ci-test` ?

**Comment by AndrienkoAleksandr** [comment]
I mean sypress tests.

**Comment by benoitf** [comment]
@AndrienkoAleksandr as yes sure, BTW it's part of ci-build check that is mandatory :-)

**Pull request closed without merging**
