### PR TITLE
Store logs of test workspaces created by E2E tests from Dashboard

### PR DESCRIPTION
**Pull request by dmytro-ndp**
### What does this PR do?
It stores logs of test workspaces which are created by failed tests from _Eclipse Che Dashboard_ during the test execution.

Test workspace is linked with `TestWorkspace testWorkspace` field of test so that **SeleniumTestHandler** be able to read information about workspace if test failed, and pass it to the **TestWorkspaceLogsReader**.

It adds method `org.eclipse.che.selenium.core.workspace.TestWorkspaceProvider#getWorkspace()` to obtain information about existed workspace.

### What issues does this PR fix or reference?
#11506

### CODE REVIEW

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/941/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/941//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11542
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/951/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/951//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11542
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/955/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/955//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11542
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Review by Ohrimenko1988 — APPROVED** [review]

**Review by musienko-maxim — APPROVED** [review]

**Pull request merged**
