### PR TITLE
CHE-7407: Rework Git file change event detection to be depend on opened editors

### PR DESCRIPTION
**Pull request by vinokurig**
### What does this PR do?
Rework Git file change event detection to be related on opened editors

### What issues does this PR fix or reference?
#7407

#### Release Notes

N/A

#### Docs PR

N/A

### CODE REVIEW

**Review by tolusha — APPROVED** [review]

**Comment by tolusha** [comment]
ci-test

**Comment by davidwindell** [comment]
This will be a fantastic performance improvement for us, thanks for getting it done @vinokurig

**Comment by vinokurig** [comment]
ci-test

**Review by dkulieshov — APPROVED** [review]

**Comment by vinokurig** [comment]
All Git selenium test passed successfully after rerunning localy

**Review by artaleks9 — APPROVED** [review]

**Review by vparfonov — APPROVED** [review]

**Comment by davidwindell** [comment]
Any way this can be backported to Che 5?

**Comment by vinokurig** [comment]
I will create a PR for CHE-5

**Comment by vinokurig** [comment]
@davidwindell merged this to CHE-5

**Comment by davidwindell** [comment]
Brilliant, thanks

**Pull request merged**
