### PR TITLE
Fix resolving the User Dashboard route

### LINKED ISSUE #15821: Wrong behaviour on dashboard when click on 'Dashboard' item
### Describe the bug
* When you try open _Dashbord_ page by click on `Dashboard` item on nav-panel there is wrong behaviour  and there is error in web browser console

### Che version
 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce

- Open dashboard and create a workspace
- Click, e.g. on item `Factories` in nav-panel, on dashbord will open _All factories_ page
- Now click on `Dashboard` item
- there is left the _All factories_ page and there are errors in console web browser

### Expected behavior
- should be open _Dashboard_ page with the _Recent Workspaces_ widget

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [x] Openshift ( `oc v3.11.0+8de5c34
kubernetes v1.10.0+d4cacc0`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
dashboard-item-click

### Installation method
   - [x] chectl (`chectl/0.0.20200124-next.d12f18b linux-x64 node-v10.18.1`)
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

### Additional context
It seems it is related with merge PR https://github.com/eclipse/che/pull/15784

### LINKED ISSUE #15822: Wrong behaviour on dashboard when create workspace for organization
### Describe the bug
- There is a wrong behaviour to displaying of created workspace for a member of an organization
- There is unexpected error notification when click on specific name organization on  the _Organizations_ page

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
- log in under `admin` user and open dashboard
- create an organization and add a member
- logout from dashboard and login as user-member
- select organization and create a workspace 

### Expected behavior
- error notification should be absent
- workspace details should be displayed when click on created workspace

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [x] Openshift (`oc v3.11.0+8de5c34 kubernetes v1.10.0+d4cacc0`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots
che-org-ws-wrong

### Installation method
   - [x] chectl (`oc v3.11.0+8de5c34 kubernetes v1.10.0+d4cacc0`)
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [x] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify- log in under `admin` user and open dashboard
- create an organization and add a member

### Additional context
- It seems it is related with merge PR #15784
- Related issue: #15821

### PR DESCRIPTION
**Pull request by akurinnoy**
Signed-off-by: Oleksii Kurinnyi <okurinny@redhat.com>

### What does this PR do?

This PR fixes up the UD routes resolving for pages:
- Dashboard
- Workspace Details

### What issues does this PR fix or reference?

fixes https://github.com/eclipse/che/issues/15821
fixes https://github.com/eclipse/che/issues/15822

### CODE REVIEW

**Comment by SkorikSergey** [comment]
ci-build

**Comment by sleshchenko** [comment]
Tested `eclipseche/che-server:15833` - everything works as expected

**Review by sleshchenko — APPROVED** [review]

**Review by sleshchenko — APPROVED** [review]
Retested scenarios described in both referenced issues with the new image, everything seems fine :+1:

**Comment by artaleks9** [comment]
Selenium tests execution on Eclipse Che Multiuser on OCP (https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/3498/) doesn't show any regression against this Pull Request.

**Pull request merged**
