### PR TITLE
Add ability to provide additional build-info...

### PR DESCRIPTION
**Pull request by nickboldt**
Add ability to provide additional build-info in Che (#12919)

Change-Id: I40576adb4a299dbba8a3be8528640b2da24b43f1

### CODE REVIEW

**Comment by nickboldt** [comment]
ci-test

**Comment by nickboldt** [comment]
This is a cherry-pick of https://github.com/eclipse/che/pull/12919 to the 6.19.x branch (for inclusion in 6.19.3-SNAPSHOT). Should tick all the same boxes as the PR for master. 

But I wanted to run the ci-test on this just to be sure it's not using some new API from Che 7 and therefore breaks 6.19.

**Comment by vparfonov** [comment]
ci-test

**Comment by nickboldt** [comment]
CI test failed because Che parent 6.19.0 does not include these new properties/dependencies:

[che619x-deps-missing-new-properties-and-deps.diff.txt](https://github.com/eclipse/che/files/3018970/che619x-deps-missing-new-properties-and-deps.diff.txt)

Should we add these to the 6.19.1-SNAPSHOT version of che parent and release that? Or fork the ci-test job to not rely on these new deps that were added for Che 7?

**Comment by nickboldt** [comment]
Perhaps we only need this simpler change applied to 6.19.x?

https://github.com/eclipse/che-parent/commit/8a3750040ca7c9ea130fba0cb1c5dedcdf4a598a

**Review by ashumilova — APPROVED** [review]

**Comment by skabashnyuk** [comment]
@nickboldt this pr do not have any new dependencies. I see no reason to backport parent.

**Comment by riuvshin** [comment]
ci-build

**Review by vparfonov — APPROVED** [review]

**Review by skabashnyuk — APPROVED** [review]

**Comment by vparfonov** [comment]
@nickboldt Looks like our CI can't build you PR and this not related to changes provided in PR

**Comment by riuvshin** [comment]
ci-build

**Comment by riuvshin** [comment]
ci-build

**Comment by riuvshin** [comment]
ci-build

**Comment by riuvshin** [comment]
ci-build

**Comment by riuvshin** [comment]
@nickboldt our CI jobs for prchecks/build checks are not supposed to be working against release branches so fails are expected here, just ignore it.

**Review by mkuznyetsov — APPROVED** [review]

**Comment by nickboldt** [comment]
OK, if you guys are happy with a backport that fails the ci tests, so be it. Merged.

**Pull request merged**
