### PR TITLE
Upgrade gulp-stylus version

### PR DESCRIPTION
**Pull request by akervern**
### What does this PR do?

Upgrade gulp-stylus version to the latest one to fix a Node 6.x issue.
### Previous behavior

`gulp-stylus@2.0.7` takes `stylus@0.52.4` that contains a bug with Node 6.x
See: https://github.com/stylus/stylus/blob/dev/History.md#0545--2016-04-28 and https://github.com/shama/stylus-loader/issues/115 (after resolution)

So, using Node 6; Stylus do not correctly generate CSS and breaks the Dashboard styles.

```
che/dashboard $ node --version && gulp styles                                                                                                                                    
v6.6.0
Using remote Che server http://localhost:8080
[16:31:37] Using gulpfile ~/Work/Nuxeo/sources/che/dashboard/gulpfile.js
[16:31:37] Starting 'styles'...
[16:31:38] gulp-inject 102 files into index.styl.
[16:31:40] [Stylus] TypeError in plugin 'gulp-stylus'
Message:
    /Users/arnaud/Work/Nuxeo/sources/che/dashboard/src/app/index.styl:335:1
   331|   fill $che-white-color
   332|
   333| .noselect
   334|   user-select none
   335|
--------^

Path must be a string. Received undefined

[16:31:40] Finished 'styles' after 3.05 s
```

Please review [Che's Contributing Guide](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md) for best practices.

### CODE REVIEW

**Comment by benoitf** [comment]
ci-build

**Comment by TylerJewell** [comment]
@akervern - the CI checks indicate that your email address does not have a registered Eclipse CLA.  Can you confirm that you have executed one, please?  

@ashumilova - ok with the change, it can be merged for M6 or M7 once CLA is confirmed.

**Comment by slemeur** [comment]
Ok for me

**Comment by benoitf** [comment]
@akervern you may follow as well https://dev.eclipse.org/eclipse-webhook/services/status_details.php?id=58063442cceb3 and add Signed-Off comment (by amending your commit in the branch)

**Comment by akervern** [comment]
ok, got it. Signed-off header added.
Otherwise, waiting for eclipse.org account moderation... so I'm not yet able to login and sign for now.

**Comment by akervern** [comment]
Both errors are related to jgit stuff; can we trigger another build?

**Comment by benoitf** [comment]
@akervern we had issues on jgit tests on CI instance of pull requests so for me build is ok. We just need to figure out CLA

**Comment by benoitf** [comment]
@akervern do you have CLA signed ?
on https://projects.eclipse.org/user/cla/validate it is not validated

**Comment by akervern** [comment]
@benoitf Still not yet received the Eclipse account creation validation... 👎

**Pull request merged**
