### PR TITLE
CHE-57: Changing license owner for 'che-plugin-openshift-client' module

### PR DESCRIPTION
**Pull request by ibuziuk**
### What does this PR do?
Changes license owner to "Red Hat, Inc." for 'che-plugin-openshift-client' module

### CODE REVIEW

**Comment by ibuziuk** [comment]
@lord I forgot to update copyright owner in the previous PR

**Comment by skabashnyuk** [comment]
ci-build

**Comment by lord** [comment]
@ibuziuk no worries! This PR LGTM :shipit:

**Comment by ibuziuk** [comment]
@lord PR has been updated

**Comment by l0rd** [comment]
@ibuziuk s/lord/l0rd/ 😃 

@lord thank you for helping us with theses PRs 😛 

@skabashnyuk I will merge this PR to openshift-connector branch. That's a WIP branch that we use to share our work on Che OpenShift connector. CI build failures on this branch are ok for now.

**Comment by ibuziuk** [comment]
haha, thank you @lord :-)
@l0rd I just thought that you have changed your avatar ;-)

**Pull request merged**
