### PR TITLE
PostgreSQL debug mode

### PR DESCRIPTION
**Pull request by skabashnyuk**
### What does this PR do?
 - With ```POSTGRESQL_LOG_DEBUG=true``` allow to enable detailed PostgreSQL logger output.
 - Added ``` --postgres-debug``` paremeter to ocp.sh. 

#### Release Notes
Added PostgreSQL debug mode

#### Docs PR
n/a

### CODE REVIEW

**Comment by benoitf** [comment]
Hello, I have 2 questions
- could we use only a single image with env variable to switch from "production" to "debug" mode ?
- if not possible, could the debug image inherits from the existing image so it could be updated if main image is updated ?

**Comment by skabashnyuk** [comment]
@benoitf good points. Will try to experiment with it.

**Comment by skabashnyuk** [comment]
I'll try to use an existed image.

**Comment by skabashnyuk** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1040/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1040//Selenium_20tests_20report/)
docker image: eclipseche/che-server:9343
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1042/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1042//Selenium_20tests_20report/)
docker image: eclipseche/che-server:9343
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Review by riuvshin — APPROVED** [review]

**Comment by skabashnyuk** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1112/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1112//Selenium_20tests_20report/)
docker image: eclipseche/che-server:9343
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by skabashnyuk** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1117/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1117//Selenium_20tests_20report/)
docker image: eclipseche/che-server:9343
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Review by ghost — APPROVED** [review]

**Review by garagatyi — APPROVED** [review]

**Pull request merged**
