### PR TITLE
Improved find and navigate to file capabilities in IDE

### PR DESCRIPTION
**Pull request by vitaliy-guliy**
Improved `Navigate to file` popup:

- window borders and buttons have been removed
- added scroll bars to the popup with suggestions

navigatetofile

#### Changelog
Improve find and navigate to file capabilities in IDE

## Release Note:
- [x] Added to release not in enhancements section

### CODE REVIEW

**Comment by TylerJewell** [comment]
Super cool.  Thanks for making the title change requested.

Let's crosslink a matching docs issue and a release notes continent from PM into this PR.

**Review by vparfonov — APPROVED** [review]

**Comment by slemeur** [comment]
@vitaliy-guliy : here are some feedbacks
e2477994-de51-11e6-8557-261780b54011

Then:
- I'd like to know how this behave if you zoom in / use Che in a small window.
- We are displaying the complete path to the file. What is the mecanism you are using when the path is very long and cannot be displayed entirely on the screen? Should we truncate the text in some ways or show only the parts of it ?

**Comment by slemeur** [comment]
The description of the PR is not detailed enough.

You need to explain what are the changes that you did to this popup in order to improve it.

**Comment by slemeur** [comment]
@vitaliy-guliy I created the following doc issue: https://github.com/codenvy/che-docs/issues/74

**Comment by slemeur** [comment]
@vitaliy-guliy : we need you to work on the doc issue first. We will then be able to quickly edit the release note here:
https://docs.google.com/document/d/1cEbq32s9J2ygEfGd4d1ImvT3c7YZqfAbRL0PMC8HE48/edit#

**Comment by vitaliy-guliy** [comment]
I recorded a video of the behavior when resizing
https://youtu.be/y6W9QwGul1s

**Comment by vitaliy-guliy** [comment]
According to @slemeur feedback
- the rounded box on the popup is removed
- added more space on the left and right of the proposals box

navigate to file feature

**Comment by vitaliy-guliy** [comment]
For now we display the complete file path and truncate it when there is not enough space to display.
This is an easiest way to display it. Displaying the part of the path is more complex due to it's difficult to forecast how the browser will render the table with proposals.

**Review by ashumilova — APPROVED** [review]

**Review by slemeur — APPROVED** [review]
added to release note and updated title

**Pull request merged**
