### PR TITLE
[Selenium] Fix Java selenium tests to run against Che with next version for default plugins

### PR DESCRIPTION
**Pull request by SkorikSergey**
### What does this PR do?
After **Che** master has been switched to ```Che Theia``` next which based on **Theia** master branch, we need to adapt Java selenium test to be executed against Theia from master branch.

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/14325

### CODE REVIEW

**Comment by SkorikSergey** [comment]
crw-ci-test

**Comment by SkorikSergey** [comment]
crw-ci-test

**Comment by SkorikSergey** [comment]
crw-ci-test

**Comment by SkorikSergey** [comment]
crw-ci-test

**Comment by SkorikSergey** [comment]
crw-ci-test

**Comment by SkorikSergey** [comment]
crw-ci-test

**Comment by SkorikSergey** [comment]
ci-test

**Comment by SkorikSergey** [comment]
crw-ci-test

**Comment by SkorikSergey** [comment]
crw-ci-test

**Comment by SkorikSergey** [comment]
ci-build

**Comment by SkorikSergey** [comment]
crw-ci-test

**Comment by SkorikSergey** [comment]
ci-test

**Comment by SkorikSergey** [comment]
crw-ci-test

**Comment by SkorikSergey** [comment]
ci-test

**Review by dmytro-ndp — APPROVED** [review]
Looks good.

**Pull request merged**
