### PR TITLE
CODENVY-35 code clean up

### PR DESCRIPTION
**Pull request by olexii4**
**_2 Upvotes**_ Signed-off-by: Oleksii Orel oorel@codenvy.com

### CODE REVIEW

**Comment by olexii4** [comment]
@ashumilova WDYT?

**Comment by benoitf** [comment]
+1

**Comment by benoitf** [comment]
but remove from this commit
-action.redirect.to.support.title = Support
 +action.redirect.to.support.title = Community

**Comment by ashumilova** [comment]
+1

**Pull request merged**
