### PR TITLE
Log stacktrace when workspace start failure

### PR DESCRIPTION
**Pull request by sparkoo**
### What does this PR do?
log whole exceptions instead of just a message in `KubernetesInternalRuntime`. This will provide us much more precise information what really happened.

### What issues does this PR fix or reference?

n/a

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Review by amisevsk — COMMENTED** [review]
I thought we generally moved *away* from logging stacktraces at some point in the past. Will this log a stacktrace if I e.g. stop a workspace while it's in the `starting` state?

**Comment by sparkoo** [comment]
> I thought we generally moved _away_ from logging stacktraces at some point in the past. 

Was there any good reason for that? It's a guesswork to debug issues with only message. Stacktraces are there for a reason, why don't use them?

> Will this log a stacktrace if I e.g. stop a workspace while it's in the `starting` state?

Maybe, I didn't try that. However, if stopping starting workspace is not exceptional situation, we should not throw an exception in the first place...

**Comment by amisevsk** [comment]
I'm fine with logging stack traces (maybe at a higher level of verbosity?) though I think it looks sloppy -- we're basically admitting we there are enough bugs to warrant logging debug info by default.

As for whether cancelling a start is considered a failure, I get the message
> FailedRuntime start for identity 'workspace: workspacerzqs20lomoxx2su3, environment: default, ownerId: 4ede3680-42b9-461b-b9bb-362bc04745f0' is interrupted

(twice...) when testing it on che.openshift.io, and I know that it gets [included in failure metrics](https://github.com/eclipse/che/issues/14639), though I don't have access to logs to confirm.

**Comment by sparkoo** [comment]
> I'm fine with logging stack traces (maybe at a higher level of verbosity?) though I think it looks sloppy -- we're basically admitting we there are enough bugs to warrant logging debug info by default.

I'm sorry, but I strongly disagree with this. I have no issue to admit that we have bugs in code, as every other software in the world. Take this issue https://github.com/eclipse/che/issues/17999, I know that we have no permissions to list configmaps. But to know the context of the problem, I can only guess. I know probably where and how it happened, but I can't be sure so maybe I fix one place, but it actually failed somewhere else.

AND exceptions are not only our bugs. They're meant for exceptional states we didn't or can't expect. Like HW issues, network issues, wrong configuration, permissions issues etc. So when customers complains that something does not work, the more information we know about the problem, the better for us. The stacktrace is very valuable information.

I've probably saw too many customer cases in my career, to appreciate the power of this. Or better say, I can't imagine situation where exception stacktrace is unwanted. TBH, I'm surprised we're not focusing more on logging in general. I know how useful it is, when customer is waiting for your response on his issue, that is blocking half of his company and you're under SLA...

> 
> As for whether cancelling a start is considered a failure, I get the message
> 
> > FailedRuntime start for identity 'workspace: workspacerzqs20lomoxx2su3, environment: default, ownerId: 4ede3680-42b9-461b-b9bb-362bc04745f0' is interrupted
> 
> (twice...) when testing it on che.openshift.io, and I know that it gets [included in failure metrics](https://github.com/eclipse/che/issues/14639), though I don't have access to logs to confirm.

That looks very wrong to me and makes this metric useless. We should fix that.

**Comment by skabashnyuk** [comment]
I fully support @sparkoo .
At this moment quite hard to understand the concrete source of the failure. For example.
```
Failed to start Kubernetes runtime of workspace workspaceqycvd644cj6fsr1c. Cause: Failure executing: GET at: https://172.30.0.1/api/v1/namespaces/prcheck-1969/configmaps?labelSelector=che.workspace_id%3Dworkspaceqycvd644cj6fsr1c. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked. configmaps is forbidden: User "system:serviceaccount:prcheck-1969:rhche" cannot list resource "configmaps" in API group "" in the namespace "prcheck-1969". The error may be caused by an expired token or changed password. Update Che server deployment with a new token or password.
```
It's not easy to find where it comes from.

As for @amisevsk topic `cancelling a start`. I believe it might be legitimate too. Let's create an issue for that and discuss it there.

**Review by metlos — APPROVED** [review]

**Comment by metlos** [comment]
> I can't imagine situation where exception stacktrace is unwanted.

:+1: 

The only complaint I ever heard about stacktraces in logs is that they make log parsing and reading more complex. To that I personally say meh.

What we shouldn't do is to log a stacktrace and rethrow - that would probably lead to 1 problem being reported multiple times. But as far as I looked that is not the case in this PR.

What we may find though is that the stacktraces in some of the cases might not be that useful - especially in the context of weaved completable futures, where we're only gonna see the trace going to the executor and not the "true" cause that spawned the failing job asynchronously.

**Review by skabashnyuk — APPROVED** [review]

**Review by ibuziuk — APPROVED** [review]
will make it easier to investigate issues like https://github.com/eclipse/che/issues/17999

**Review by amisevsk — APPROVED** [review]

**Pull request merged**
