### PR TITLE
include default editor and plugins in /workspace/settings

### PR DESCRIPTION
**Pull request by sparkoo**
### What does this PR do?
include default editor and plugins in /workspace/settings REST method.
```
{
...
  "che.factory.default_plugins": "eclipse/che-machine-exec-plugin/nightly",
  "che.factory.default_editor": "eclipse/che-theia/next",
...
}
```

### Screenshot/screencast of this PR

20210205_135547_1024x807_scrot

### What issues does this PR fix or reference?

#18986 

### How to test this PR?

1. deploy che
2. call `/workspace/settings` REST API method

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by benoitf** [comment]
hi, could it include dashboard URL as well ?

**Review by skabashnyuk — COMMENTED** [review]
Looks good in general. Can you add a test and check if any documentation changes are needed. (including description update in che.properties)

**Comment by sparkoo** [comment]
> Looks good in general. Can you add a test and check if any documentation changes are needed. (including description update in che.properties)

Test is there: https://github.com/eclipse/che/pull/18996/files#diff-beb41221f27e617627258222fc157d9518c9249d7eb13e29470256a707ae3080R908

AFAIK we don't have any dedicated documentation in che-docs for REST API. I can add some note to che.properties that these properties are exposed on `/workspace/settings`, but others don't have it, so I'm not sure it's the right step here. WDYT?

**Review by sleshchenko — APPROVED** [review]

**Comment by sparkoo** [comment]
> hi, could it include dashboard URL as well ?

I would do it in separate PR/issue, it's not just a simple property. Can you please create an issue for it, with explaining why this is needed?

**Review by mshaposhnik — APPROVED** [review]

**Review by skabashnyuk — APPROVED** [review]

**Pull request merged**
