### PR TITLE
[WP] Used OpenShift 3.11

### PR DESCRIPTION
**Pull request by skabashnyuk**
### What does this PR do?
Used OpenShift 3.11
NOTE:
 - Not working on Mac

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/11582

#### Release Notes
n/a

#### Docs PR
n/a

### CODE REVIEW

**Comment by skabashnyuk** [comment]
ci-test

**Comment by skabashnyuk** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/996/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/996//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11627
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by skabashnyuk** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/997/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/997//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11627
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by skabashnyuk** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/998/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/998//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11627
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by skabashnyuk** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/994/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/994//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11627
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/999/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/999//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11627
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Review by l0rd — COMMENTED** [review]
Can't we just get latest release? https://help.github.com/articles/linking-to-releases/#linking-to-the-latest-release

**Comment by skabashnyuk** [comment]
I was not able to successfully complete this task.

**Pull request closed without merging**
