### PR TITLE
WIP: Add Che CLI with native scripts for Windows / Linux

### PR DESCRIPTION
**Pull request by TylerJewell**
### What does this PR do?

The implementation of #1969 - platform native scripts.
1. Adds Windows and Linux scripts.
2. Instructions for how CI systems modified to post these scripts onto hosted servers.
3. Simple single word syntax for launching all commands for che-launcher and che-file.

Usage:
che help
che start
che stop
che restart
che update
che init
che up

Users will install the files (windows requires git bash installed):

```
curl -sL http://eclipse.org/che/che.sh | sh
curl -sL http://eclipse.org/che/che.bat > che.bat
```

### CODE REVIEW

**Comment by l0rd** [comment]
I like it. 

I have a few comments:
- Use https. http is not acceptable. With a MITM attack we could easily take control of the machine where the script will run. 
- For windows why don't you use a [`curl` equivalent for powershell](http://superuser.com/questions/344927/powershell-equivalent-of-curl)? Or, since you ask users to have `git bash`, you could have a unique `.sh` script for both Linux and Windows.
- When I visit `http://eclipse.org/che/che.sh` with Chrome the script is downloaded automatically. If I visit `https://get.docker.com` the script source code is rendered by the browser and not downloaded. I prefer the latter as a default behaviour. Users can have easily a look at the script before actually run it.

**Comment by TylerJewell** [comment]
Yes - definitely on the `https`.

On the curl equivalent for powershell. The issue with powershell is that it requires the user to start a powershell session. Where as, if you have a standard windows command prompt open, then the Git Bash will provide a standard curl command.

On the syntax for preventing a file from being downloaded directly - how can we do that? We have limited controls for how such files are hosted with eclipse.org.

**Comment by l0rd** [comment]
When requesting the script in the header of the http response Content-Type should be set to `text/plain` but is `application/x-shellscript`:
image

**Comment by benoitf** [comment]
I tried to add a custom .htaccess file but it seems the override is not allowed on Eclipse website Server

**Comment by TylerJewell** [comment]
I will start a discussion with the eclipse foundation on any options we may have.

**Comment by benoitf** [comment]
maybe they could add to our che directory on Apache2 configuration the following content
http://git.eclipse.org/c/www.eclipse.org/che.git/plain/.htaccess

**Comment by TylerJewell** [comment]
Added changes

**Pull request closed without merging**
