### PR TITLE
[Selenium] stabilize selenium tests

### PR DESCRIPTION
**Pull request by SkorikSergey**
### What does this PR do?
Stabilize selenium tests on PR-check centos.ci job.

### CODE REVIEW

**Comment by SkorikSergey** [comment]
crw-ci-test

**Comment by SkorikSergey** [comment]
test

**Comment by SkorikSergey** [comment]
[test]

**Comment by SkorikSergey** [comment]
[test]

**Comment by rhopp** [comment]
[test]

**Comment by SkorikSergey** [comment]
[test]

**Comment by SkorikSergey** [comment]
[test]

**Comment by SkorikSergey** [comment]
[test]

**Comment by rhopp** [comment]
[test]

**Comment by SkorikSergey** [comment]
[test]

**Comment by SkorikSergey** [comment]
[test]

**Comment by SkorikSergey** [comment]
[test]

**Comment by SkorikSergey** [comment]
[test]

**Review by artaleks9 — APPROVED** [review]

**Pull request merged**
