### PR TITLE
Upgrade the version of theia-generator version to 0.0.1-1547456396

### PR DESCRIPTION
**Pull request by olexii4**
Signed-off-by: Oleksii Orel <oorel@redhat.com>

### What does this PR do?
Upgrade the version of theia-generator version to 0.0.1-1547456396

### What issues does this PR fix or reference?
https://github.com/eclipse/che-theia/issues/20

### CODE REVIEW

**Review by evidolob — APPROVED** [review]

**Review by benoitf — APPROVED** [review]

**Comment by benoitf** [comment]
FYI build is failing

**Comment by ashumilova** [comment]
ci-build

**Comment by ashumilova** [comment]
ci-build

**Review by vitaliy-guliy — APPROVED** [review]

**Comment by olexii4** [comment]
ci-build

**Comment by olexii4** [comment]
ci-build

**Pull request merged**
