### PR TITLE
Improvements on DTO Typescript generator

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
- [x] Add integration tests that test the TypeScript generated DTOs
- [x] Add toJson() method on DTO
- [x] Add support of constructor with empty object (like new MyDTOImpl().withName("hello"))
- [x] Integration tests can be disabled with -DskipIntegrationTests flag
### What issues does this PR fix or reference?

add serialization/ export of DTOs to JSON format + lot of tests
### New behavior

Allow to generate DTOs in TypeScript format for Serialization and Unserialization
### PR type
- [x] Minor change = no change to existing features or docs
### Minor change checklist
- [x] Tests provided / updated
- [x] Tests passed

Change-Id: I3bcc2de6bb549ef8e29a266270ebcf0735e696d1
Signed-off-by: Florent BENOIT fbenoit@codenvy.com

### CODE REVIEW

**Comment by TylerJewell** [comment]
@benoitf @ashumilova - if Anna is ok with this change, then lets merge and add into M5.

**Comment by benoitf** [comment]
@vparfonov ?

**Review by vparfonov — APPROVED** [review]

**Comment by skabashnyuk** [comment]
Do you need docker to run compiler?

**Comment by benoitf** [comment]
@skabashnyuk I tried using nashorn or rhino but it was not working
but this is only for tests that can be skipped

**Comment by skabashnyuk** [comment]
Can you clarify. Docker used only for tests of this  DTO Typescript generator module only?
You don't need it for DTO typescript generation. Yes?

**Comment by benoitf** [comment]
@skabashnyuk 
DTO plugin is converting Java DTO into TypeScript DTO (no docker at all : pure java)
Unit test check some basic conversion (no docker at all, but limited testing..) (can be skipped with -DskipTests=true )
Integration tests are using docker to compile TypeScript DTO and use them in order to check these objects are really working. (docker required). can be skipped with -DskipIntegrationTests=true (unit tests are still launched) or -DskipTests=true )

**Review by skabashnyuk — APPROVED** [review]

**Pull request merged**
