### PR TITLE
Remove exec/terminal agents from dependencies of ws-agent

### LINKED ISSUE #7482: Remove exec/terminal agents from dependencies of ws-agent
### Description
Currently, ws-agent installer [has terminal and exec agents as dependencies](https://github.com/eclipse/che/blob/master/wsagent/agent/src/main/resources/org.eclipse.che.ws-agent.json#L6). But it doesn't depend on it, to be honest.
I suggest removing these dependencies.

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

### PR DESCRIPTION
**Pull request by skabashnyuk**
### What does this PR do?
Remove exec/terminal agents from dependencies of ws-agent

### What issues does this PR fix or reference?
Fixes https://github.com/eclipse/che/issues/7482

Remove exec/terminal agents from dependencies of ws-agent

#### Release Notes
Remove exec/terminal agents from dependencies of ws-agent
This PR introduces some changes in behavior. Previously if you enable ws-agent installer
it also enables you terminal and exec agent even if you don't need it. After this pr that is no longer happen. You have to explicitly define terminal and exec agents. Fix in case someone wants terminal and exec agent, as well as ws-agent, is very simple: go to dashboard and enable terminal and(or) exec-agent.

#### Docs PR
n/a

### CODE REVIEW

**Comment by skabashnyuk** [comment]
ci-test

**Comment by garagatyi** [comment]
Have you considered making this PR backward compatible?

**Comment by skabashnyuk** [comment]
I don't see any backward compatible problems. Do you?

**Review by tolusha — APPROVED** [review]

**Comment by garagatyi** [comment]
@skabashnyuk I do. Currently, enabling of ws-agent without enabling terminal and exec agents enables last ones. After your PR it won't be true that may influence some workspaces. 
I do not say that we should add migration in this PR, but I say this out loud to start discussion to consider whether any migration or backward compatibility tool is needed.

**Comment by skabashnyuk** [comment]
ok. We may include a note about that we are going to change this behavior in this release and change it in a next release. As a backward compatibility user may include an old version of ws-agent installer.

**Comment by garagatyi** [comment]
@skabashnyuk sounds reasonable to me.

**Review by garagatyi — APPROVED** [review]

**Review by sleshchenko — APPROVED** [review]

**Comment by garagatyi** [comment]
@skabashnyuk I think that this PR description contains release notes section where you can describe this

**Comment by garagatyi** [comment]
@skabashnyuk Maybe you can add it in the PR - then it will be straightforward that release process responsible ppl are in charge of documenting it in the release information

**Comment by dmytro-ndp** [comment]
@Ohrimenko1988: shouldn't we add `"org.eclipse.che.exec"` into the installers list in next test factory templates as well?
- [factory/docker/minimal.json](https://github.com/eclipse/che/blob/che7482/selenium/che-selenium-test/src/test/resources/templates/factory/docker/minimal.json)
- [factory/openshift/minimal.json](https://github.com/eclipse/che/blob/che7482/selenium/che-selenium-test/src/test/resources/templates/factory/openshift/minimal.json)

**Comment by skabashnyuk** [comment]
ci-test

**Comment by skabashnyuk** [comment]
ci-test

**Pull request merged**
