### PR TITLE
[Selenium] Stabilize selenium tests on Centos CI

### PR DESCRIPTION
**Pull request by SkorikSergey**
### What does this PR do?
Stabilize selenium tests on Centos CI.

### CODE REVIEW

**Comment by SkorikSergey** [comment]
[ci-test]

**Comment by SkorikSergey** [comment]
ci-test

**Comment by dmytro-ndp** [comment]
[ci-test]

**Review by dmytro-ndp — APPROVED** [review]
`expandItemWithIgnoreExceptions()` doesn't look good, IMHO, but could be approved as a temporary solution

**Pull request merged**
