### PR TITLE
Clean up after merge che6 to master

### PR DESCRIPTION
**Pull request by riuvshin**
Clean up after merge che6 to master
part of: https://github.com/eclipse/che/issues/7971

### CODE REVIEW

**Review by benoitf — APPROVED** [review]
do we need to provide "nightlies" for 5.x branch ?

**Comment by riuvshin** [comment]
@benoitf che 5.x and codenvy will be supported only in maintenance mode. we will not have whole CI for that.
I going to remove everything 5.x related from CI soon

**Comment by benoitf** [comment]
well I would say that it's the case only once master is GA

**Comment by riuvshin** [comment]
not sure about that, we don't expect any changes in 5.x branches except blocker bugfixes
it means we will never have 5.23.0, 5.24 and so on only 5.22.1-n

**Review by skabashnyuk — APPROVED** [review]

**Review by garagatyi — APPROVED** [review]

**Pull request merged**
