### PR TITLE
CHE-4636: Remove usecase for unexisted feature

### PR DESCRIPTION
**Pull request by tolusha**
Signed-off-by: Anatoliy Bazko <abazko@redhat.com>

### What does this PR do?
Removes selenium test case for unexisted feature.

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/4636

### CODE REVIEW

**Comment by tolusha** [comment]
ci-build

**Review by vparfonov — APPROVED** [review]

**Comment by dmytro-ndp** [comment]
@tolusha: can you, please, explain which feature you treated as inexistent? Because of title and description of the PR say nothing about it.

**Comment by tolusha** [comment]
We can't figure out debug information if class isn't compiled with `-g` flag.

**Comment by dmytro-ndp** [comment]
I see. If user still have an ability to go inside the JRE class during the debug session, debug of JRE class, IMHO, is existed use case which can and ought to be tested, at least, to check that server is returning meaningful error message, instead of:
> Error: Failed to evaluate an expression.
> Reason: {}

**Comment by tolusha** [comment]
Any way no need to test this in selenium. I has to be a pure server side test.

**Pull request merged**
