### PR TITLE
Hotfix fix cookie policy approval

### PR DESCRIPTION
**Pull request by ScrewTSW**
### What does this PR do?
* Adds a new check for cookie policy approval

### Screenshot/screencast of this PR

N/A

### What issues does this PR fix or reference?

hotfix

### How to test this PR?

set variables and run `npm run test`

### Test Log
```
  The SmokeTest userstory
    Create workspace from factory:https://github.com/che-incubator/quarkus-api-example.git
          ? BrowserTabsUtil.navigateTo - https://devspaces.apps.sandbox-stage.gb17.p1.openshiftapps.com
          ? OcpRedHatLoginPage.login
          ? OcpLoginPage.waitAndClickOnLoginProviderTitle
          ? RedHatLoginPage.waitRedHatLoginWelcomePage
          ? RedHatLoginPage.waitAndConfirmCookiePolicy
          ? RedHatLoginPage.enterUserNameRedHat
          ? RedHatLoginPage.clickNextButton
          ? RedHatLoginPage.enterPasswordRedHat
          ? RedHatLoginPage.clickOnLoginButton
          ? RedHatLoginPage.waitDisappearanceRedHatLoginWelcomePage
          ? BrowserTabsUtil.maximize - TS_SELENIUM_LAUNCH_FULLSCREEN is set to true, maximizing window.
          ? Dashboard.waitStartingPageLoaderDisappearance
      ? Login (24756ms)
          ? Dashboard.waitPage
          ? WorkspaceHandlingTests.createAndOpenWorkspaceFromGitRepository - fetching user kubernetes namespace, storing auth token by getting workspaces API URL.
          ? ApiUrlResolver.obtainUserNamespace
(node:196798) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
          ? ApiUrlResolver.obtainUserNamespace - kubeapi success: osio-ci-devsandbox-periodic-stg-dev
          ? Dashboard.clickCreateWorkspaceButton
          ? CreateWorkspace.waitPage
          ? CreateWorkspace.waitTitleContains - text: "Create Workspace"
          ? BrowserTabsUtil.getCurrentWindowHandle
          ? CreateWorkspace.importFromGitUsingUI - factoryUrl: "https://github.com/che-incubator/quarkus-api-example.git"
          ? BrowserTabsUtil.waitAndSwitchToAnotherWindow
          ? BrowserTabsUtil.getAllWindowHandles
          ? BrowserTabsUtil.getAllWindowHandles
          ? BrowserTabsUtil.switchToWindow
      ? Create and open new workspace from factory:https://github.com/che-incubator/quarkus-api-example.git (1130ms)
      ? WorkspaceHandlingTests.obtainWorkspaceNameFromStartingPage - obtained workspace name from workspace loader page: quarkus-api-example-00xq
      ? Obtain workspace name from workspace loader page (16207ms)
          ? registerRunningWorkspace - with workspaceName:quarkus-api-example-00xq
      ? Register running workspace
          ? ProjectAndFileTests.waitWorkspaceReadinessForCheCodeEditor - waiting for editor.
          ? ProjectAndFileTests.waitWorkspaceReadinessForCheCodeEditor - editor was opened in 46915 seconds.
      ? Wait workspace readiness (46917ms)
          ? Function.getProjectNameFromGitUrl - https://github.com/che-incubator/quarkus-api-example.git
          ? Function.getProjectNameFromGitUrl - quarkus-api-example
          ? Function.getProjectNameFromGitUrl - https://github.com/che-incubator/quarkus-api-example.git
          ? Function.getProjectNameFromGitUrl - quarkus-api-example
      ? Check a project folder has been created (225ms)
          ? projectSection.findItem: find devfile.yaml
      ? Check the project files was imported (79ms)
          ? Dashboard.openDashboard
          ? Dashboard.waitPage
          ? Dashboard.stopWorkspaceByUI - "quarkus-api-example-00xq"
          ? Dashboard.clickWorkspacesButton
          ? Workspaces.waitPage
          ? Workspaces.waitWorkspaceListItem - "quarkus-api-example-00xq"
          ? Workspaces.waitWorkspaceWithRunningStatus - "quarkus-api-example-00xq"
          ? Workspaces.stopWorkspaceByActionsButton
          ? Workspaces.waitWorkspaceListItem - "quarkus-api-example-00xq"
          ? Workspaces.openActionsPopup - for the 'quarkus-api-example-00xq' list item
          ? Workspaces.clickActionsButton - of the 'quarkus-api-example-00xq' list item
          ? Workspaces.waitActionsPopup - of the 'quarkus-api-example-00xq' list item
          ? Workspaces.clickActionsStopWorkspaceButton - for the 'quarkus-api-example-00xq' list item
          ? Workspaces.waitWorkspaceWithStoppedStatus - "quarkus-api-example-00xq"
          ? BrowserTabsUtil.getAllWindowHandles
          ? BrowserTabsUtil.getCurrentWindowHandle
          ? BrowserTabsUtil.switchToWindow
          ? BrowserTabsUtil.switchToWindow
      ? Stop the workspace (4815ms)
          ? Dashboard.openDashboard
          ? Dashboard.waitPage
          ? Dashboard.deleteStoppedWorkspaceByUI - "quarkus-api-example-00xq"
          ? Dashboard.clickWorkspacesButton
          ? Workspaces.waitPage
          ? Workspaces.waitWorkspaceListItem - "quarkus-api-example-00xq"
          ? Workspaces.deleteWorkspaceByActionsButton
          ? Workspaces.waitWorkspaceListItem - "quarkus-api-example-00xq"
          ? Workspaces.openActionsPopup - for the 'quarkus-api-example-00xq' list item
          ? Workspaces.clickActionsButton - of the 'quarkus-api-example-00xq' list item
          ? Workspaces.waitActionsPopup - of the 'quarkus-api-example-00xq' list item
  [ERROR] DriverHelper.waitVisibility - failed with exception, out of attempts - TimeoutError: Waiting for element to be located By(xpath, //tr[td//a[text()='quarkus-api-example-00xq']]//button[@aria-label='Actions' and @aria-expanded='true'])
  Wait timed out after 1068ms
          ? Dashboard.openDashboard
          ? Dashboard.waitPage
          ? Dashboard.deleteStoppedWorkspaceByUI - "quarkus-api-example-00xq"
          ? Dashboard.clickWorkspacesButton
          ? Workspaces.waitPage
          ? Workspaces.waitWorkspaceListItem - "quarkus-api-example-00xq"
          ? Workspaces.deleteWorkspaceByActionsButton
          ? Workspaces.waitWorkspaceListItem - "quarkus-api-example-00xq"
          ? Workspaces.openActionsPopup - for the 'quarkus-api-example-00xq' list item
          ? Workspaces.clickActionsButton - of the 'quarkus-api-example-00xq' list item
          ? Workspaces.waitActionsPopup - of the 'quarkus-api-example-00xq' list item
          ? Workspaces.clickActionsDeleteButton - for the 'quarkus-api-example-00xq' list item
          ? Workspaces.waitDeleteWorkspaceConfirmationWindow
          ? Workspaces.clickToDeleteConfirmationCheckbox
          ? Workspaces.waitAndClickEnabledConfirmationWindowDeleteButton
          ? Workspaces.waitPage
          ? Workspaces.waitWorkspaceListItemAbsence - "quarkus-api-example-00xq"
      ? Delete the workspace (5910ms)
          ? Dashboard.logout
          ? Dashboard.openDashboard
          ? Dashboard.waitPage
      ? Logout (4049ms)

      ? Context.stopTheDriver - Chrome driver session stopped.

  10 passing (2m)
  ```

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix or new feature ](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix-or-new-feature)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by dmytro-ndp** [comment]
@ScrewTSW : I can see timeout error in test log you shared in PR description:
```
[ERROR] DriverHelper.waitVisibility - failed with exception, out of attempts - TimeoutError: Waiting for element to be located By(xpath, //tr[td//a[text()='quarkus-api-example-00xq']]//button[@aria-label='Actions' and @aria-expanded='true'])
```

The test is expected to has passed, isn't it?

**Comment by ScrewTSW** [comment]
> @ScrewTSW : I can see timeout error in test log you shared in PR description:
> 
> > [ERROR] DriverHelper.waitVisibility - failed with exception, out of attempts - TimeoutError: Waiting for element to be located By(xpath, //tr[td//a[text()='quarkus-api-example-00xq']]//button[@aria-label='Actions' and @aria-expanded='true'])
> 
> The test is expected to has passed, isn't it?

yes, that's just an internal error posted by DriverHelper.waitAndClick()

**Comment by dmytro-ndp** [comment]
Got it.

Another question: which problem does nvm usage fix?
I don't see information about it in PR description.

**Comment by ScrewTSW** [comment]
> Got it.
> 
> Another question: which problem does nvm usage fix? I don't see information about it in PR description.

unrelated to this PR, you're probably talking about https://github.com/eclipse/che/pull/22557

If you look at output of build log of the test docker image, the build hangs for 60 seconds on the installation of NodeJSv16
with a deprecation warning.

Also out `npm` is really outdated, the typescript is also complaining about v4, etc. all updated libs are only compatible with NodeJSv18 as far as I'm aware

**Comment by ScrewTSW** [comment]
> > unrelated to this PR, you're probably talking about #22557
> 
> I am talking about changes in this PR https://github.com/eclipse/che/pull/22554/files#diff-66aa83835daacb258b27a3e1bf53904a50a46c61113fca9eeb69ce12f06f1c5c

`nvm` is more durable way to install and manage nodejs versions

**Comment by dmytro-ndp** [comment]
Okay, then let's make it visible in PR title and description.

**Comment by dmytro-ndp** [comment]
Or better not to include changes from https://github.com/eclipse/che/pull/22557 into this PR.

**Comment by ScrewTSW** [comment]
> Or better not to include changes from #22557 into this PR.

that wasn't the plan for this PR, at least not for now, #22557 is not ready yet anyway

**Review by dmytro-ndp — APPROVED** [review]
Looks good to merge.

**Pull request merged**
