### PR TITLE
Travis icon should be removed from README as well

### PR DESCRIPTION
**Pull request by freewind**
Start to contribute :smile:

### CODE REVIEW

**Comment by benoitf** [comment]
why icon should be removed ?

**Comment by freewind** [comment]
The the previous commit is:  [Removed travis. Because of it instability](https://github.com/codenvy/che/commit/7b6e7d035bb56ae19c37c130aa356c363ca62a5d)

But the travis icon is still there and make me see the travis log why it's failed

**Comment by TylerJewell** [comment]
Hi - just to double check, since this is an Eclipse project, would you please make sure you are registered as an Eclipse contributor:

https://github.com/codenvy/che/blob/master/CONTRIBUTING.md

**Comment by freewind** [comment]
@TylerJewell  Thank and yes, I've signed the CLA yesterday

**Comment by benoitf** [comment]
hello,
https://projects.eclipse.org/user/cla/validate there is no CLA for email of the commit peng.li@rea-group.com

also, commit should include the contributor email
by adding something like
Signed-off-by: Random J Developer random@developer.example.org
https://git.eclipse.org/r/Documentation/user-signedoffby.html

**Comment by freewind** [comment]
@benoitf Thanks! I'm sorry that I didn't check well, it should be OK now

**Comment by benoitf** [comment]
Eclipse CLA confirmed for nowind_lee@qq.com Eclipse CLA confirmed

**Comment by freewind** [comment]
@benoitf  Thanks, I will try to contribute more ~

**Pull request merged**
