### PR TITLE
Revert "Added checksums to configmaps to enable pod restart on config map change

### PR DESCRIPTION
**Pull request by tolusha**
### What does this PR do?
This reverts commit 8b0e5e070dc4e4127e993382d8afa9415c6d9b3d.

@cccs-eric 
I revert changes since it causes some issues.

```
    (node:7413) [ENOENT] Error: spawn chectl ENOENT
    (Use `node --trace-warnings ...` to show where the warning was created)
     ›   Error: Error: Unable to execute helm command helm upgrade --install che 
     ›   --force --namespace eclipse-che --set global.cheDomain=192.168.49.2.nip.io
     ›    --set global.tls.useSelfSignedCerts=true --set 
     ›   che-keycloak.keycloakAdminUserPassword=jMAyUBov9bAX --set 
     ›   global.ingressDomain=192.168.49.2.nip.io --set 
     ›   cheImage=quay.io/eclipse/che-server:nightly --set che.disableProbes=false 
     ›   -f /home/runner/.cache/chectl/templates/kubernetes/helm/che/values/multi-u
     ›   ser.yaml -f 
     ›   /home/runner/.cache/chectl/templates/kubernetes/helm/che/values/tls.yaml 
     ›   -f test/e2e/resources/helm-patch.yaml 
     ›   /home/runner/.cache/chectl/templates/kubernetes/helm/che/ / Error: 
     ›   template: che/charts/che-plugin-registry/templates/deployment.yaml:35:28: 
     ›   executing "che/charts/che-plugin-registry/templates/deployment.yaml" at 
     ›   <include (print $.Template.BasePath "/configmap.yaml") .>: error calling 
     ›   include: template: no template 
     ›   "che/charts/che-plugin-registry/templates/configmap.yaml" associated with 
     ›   template "gotpl"
```

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Review by flacatus — APPROVED** [review]

**Comment by cccs-eric** [comment]
The path is different when you use `chectl`....  I'll look into it.

**Comment by cccs-eric** [comment]
@tolusha 
Looks like it is related to helm v2: https://github.com/helm/helm/issues/7265
I am using helm v3 and everything is fine.  Mind you I am not using `chectl`, but I copied the helm command that `chectl` is issuing and it works for helm 3.  I couldn't try helm v2 since my cluster doesn't have tiller installed.  Are you using helm v2 with `chectl` by any chance?

**Comment by cccs-eric** [comment]
@tolusha 
I managed to test `chectl` (I didn't know about the `--templates=` switch until now! 😄 ) with my changes and everything works.   But I'm using helm v3, not v2.  So I hope you are using helm v2!
If you are, I will say that helm v2 is **officially not supported anymore** as of November 13th: https://helm.sh/blog/helm-2-becomes-unsupported/.

**Comment by tolusha** [comment]
1. Clone the project https://github.com/eclipse/che
2. `git co 8b0e5e070dc4e4127e993382d8afa9415c6d9b3d`
3. Use --templates flag with chectl chectl server:deploy ...  --templates <CHE_PROJECT_DIR>/deploy

```
$ helm version
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"clean", GoVersion:"go1.14.11"}
```

```
chectl version
chectl/0.0.20201211-next.fa906ce linux-x64 node-v10.23.0
```

```
 Deploying Eclipse Che Helm Chart
      → Unable to execute helm command helm upgrade --install che --force --namespace che --set global.cheDomain=192.168.99.100.nip.io --set global.tls.useSelfSignedCerts=true --set che-keycloak.keycloakAdminUserPassword=EhNJJummrHo5 --set global.ingressDomain=192.168.99.10
…
 ›   Error: Error: Unable to execute helm command helm upgrade --install che --force --namespace che --set global.cheDomain=192.168.99.100.nip.io --set global.tls.useSelfSignedCerts=true --set che-keycloak.keycloakAdminUserPassword=EhNJJummrHo5 --set 
 ›   global.ingressDomain=192.168.99.100.nip.io --set cheImage=quay.io/eclipse/che-server:nightly --set che.disableProbes=false -f /home/tolusha/.cache/chectl/templates/kubernetes/helm/che/values/multi-user.yaml -f 
 ›   /home/tolusha/.cache/chectl/templates/kubernetes/helm/che/values/tls.yaml /home/tolusha/.cache/chectl/templates/kubernetes/helm/che/ / Error: template: che/charts/che-plugin-registry/templates/deployment.yaml:35:28: executing 
 ›   "che/charts/che-plugin-registry/templates/deployment.yaml" at <include (print $.Template.BasePath "/configmap.yaml") .>: error calling include: template: no template "che/charts/che-plugin-registry/templates/configmap.yaml" associated with template "gotpl"
 ›   Command server:deploy failed. Error log: /home/tolusha/.cache/chectl/error.log
```

**Comment by cccs-eric** [comment]
Ok, I know what is going on...  I have 2 PR on the go and in the other one, I introduced a configmap for both `che-devfile-registry` and `che-plugins-registry`.  I splitted my work into 2 PRs to isolate my change and in the one I submitted, the configmap is not there yet.  So the code is looking for a configmap when there isn't one.  I'll submit a new PR that fixes che's configmap only.  In my other PR, I'll had the checks for plugins and devfile registries' configmap.

Sorry for the inconvenience, I got my code mixed up. 😞

**Pull request merged**
