### PR TITLE
Upgrade Tomcat and change default CORS configuration

### PR DESCRIPTION
**Pull request by mkuznyetsov**
### What does this PR do?
Change default CORS configuration for Che on DOcker/Openshift/Kubernetes to following:

WS Master:

"cors.support.credentials" - false
"cors.allowed.origins" - '*'

WS Agent:

"cors.support.credentials" - true
"cors.allowed.origins" - '<if CHE_WSAGENT_CORS_ALLOWED_ORIGINS was not defined, then domain of ws-master would be provided automatically>'

Also adding more properties/variables for configuration of CORS on WS Agent:

* Turning WS Agent CORS on/off = `CHE_WSAGENT_CORS_ENABLED`
* Setting credentials support for WS Agent CORS = `CHE_WSAGENT_CORS_ALLOW__CREDENTIALS`

That way, all configuration options for WS Master, are now also available for configuration of all WS Agents, using environment variables for Che deployment.

Also, since configuration of WS Agent happens with the help of EnvVarProvider, slightly reworked EnvVarProvisioneer, that if provider returns null, then no variable should be provided (to avoid conditional binding of env var providers).

Should be merged with PR in che-parent: https://github.com/eclipse/che-parent/pull/96

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/12127

### CODE REVIEW

**Review by sleshchenko — APPROVED** [review]
LGTM

**Comment by mkuznyetsov** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1280/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1280//Selenium_20tests_20report/)
docker image: eclipseche/che-server:12144
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Review by skabashnyuk — APPROVED** [review]

**Comment by mkuznyetsov** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1307/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1307//Selenium_20tests_20report/)
docker image: eclipseche/che-server:12144
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by mkuznyetsov** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1308/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1308//Selenium_20tests_20report/)
docker image: eclipseche/che-server:12144
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by mkuznyetsov** [comment]
ci-test

**Comment by mkuznyetsov** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1310/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1310//Selenium_20tests_20report/)
docker image: eclipseche/che-server:12144
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by ibuziuk** [comment]
@skabashnyuk @mkuznyetsov am I correct that in 6.16.0 release the `CHE_WSAGENT_CORS_ALLOWED__ORIGINS` property is planned to be removed ? I still see it is used in this PR, but wondering if it will be eventually removed in 6.16.0 ? Wondering since it is currently used downstream [1]

[1] https://github.com/redhat-developer/rh-che/blob/master/openshift/rh-che.app.yaml#L366

**Comment by mkuznyetsov** [comment]
@ibuziuk no, actually I want to have all the options to configure CORS for WS Agent and WS Master
 - being able to turn them on/off 
- configure credentials support and/or allowed origins. 

And that variable would be still functioning the same.

 Once I finalize editing, I will update PR description and I can ping you for review once again.

**Comment by mkuznyetsov** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1321/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1321//Selenium_20tests_20report/)
docker image: eclipseche/che-server:12144
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by mkuznyetsov** [comment]
ci-test

**Comment by mkuznyetsov** [comment]
ci-test

**Review by skabashnyuk — APPROVED** [review]

**Comment by mkuznyetsov** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1331/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1331//Selenium_20tests_20report/)
docker image: eclipseche/che-server:12144
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by mkuznyetsov** [comment]
@ibuziuk PR is in final form btw.

**Review by ibuziuk — APPROVED** [review]

**Comment by mkuznyetsov** [comment]
ci-build

**Comment by mkuznyetsov** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1346/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1346//Selenium_20tests_20report/)
docker image: eclipseche/che-server:12144
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by SkorikSergey** [comment]
Selenium tests execution on Eclipse Che Multiuser on OCP (https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1346//Selenium_20tests_20report/) doesn't show any regression against this Pull Request.

**Pull request merged**
