### PR TITLE
"Minor typographical improvements to localization file" by zv-io  

### PR DESCRIPTION
**Pull request by vparfonov**
Fixes minor errors in grammar, spelling, and consistency within the localizations file.

### CODE REVIEW

**Comment by vparfonov** [comment]
ci-test

**Comment by musienko-maxim** [comment]
So, the existed selenium tests did find new regression. But some tests fault because was changed some UI parts depended on the tests. I have fixed this according to typographical improvements

**Review by musienko-maxim — APPROVED** [review]

**Comment by musienko-maxim** [comment]
ci-build

**Comment by vparfonov** [comment]
Fix build and tests for original PR https://github.com/eclipse/che/pull/8906

**Pull request merged**
