### PR TITLE
Used manually written Devfile POJOs instead of generated ones.

### PR DESCRIPTION
**Pull request by sleshchenko**
### What does this PR do?
Use manual written Devfile POJOs instead of generated ones.

### Is this PR tested?
Yes, I used the following Devfiles for testing:
<details>

<summary>Devfile multiple K8s components</summary>

```yaml
specVersion: 0.0.1
name: multiple-k8s-tools
projects:
  - name: nodejs-mongo-app
    source:
      type: git
      location: 'https://github.com/ijason/NodeJS-Sample-App.git'
components:
  - name: theia-editor
    type: cheEditor
    id: org.eclipse.che.editor.theia:1.0.0
  - name: exec-plugin
    type: chePlugin
    id: che-machine-exec-plugin:0.0.1
  - name: mongodb
    type: kubernetes
    reference: mongo.yaml
    referenceContent: |
      ---
      apiVersion: v1
      kind: List
      items:
      -
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          labels:
            name: mongo
          name: mongo-controller
        spec:
          template:
            metadata:
              labels:
                name: mongo
              name: mongo-controller
            spec:
              containers:
              - image: mongo
                name: mongo
                ports:
                - name: mongo
                  containerPort: 27017
                volumeMounts:
                    - name: mongo-persistent-storage
                      mountPath: /data/db
              volumes:
                - name: mongo-persistent-storage
                  persistentVolumeClaim:
                    claimName: mongo-persistent-storage
      -
        apiVersion: v1
        kind: Service
        metadata:
          name: mongo
          labels:
            name: mongo
          name: mongo
        spec:
          ports:
            - port: 27017
              targetPort: 27017
          selector:
            name: mongo
      -
        apiVersion: v1
        kind: PersistentVolumeClaim
        metadata:
          name: mongo-persistent-storage
        spec:
          accessModes:
           - ReadWriteOnce
          resources:
            requests:
              storage: 3Gi
  - name: nodejs
    type: openshift
    reference: node-js.yaml
    referenceContent: |
      apiVersion: v1
      kind: List
      items:
      -
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: web
          labels:
            app: nodejs
        spec:
          replicas: 2
          selector:
            name: web
          template:
            metadata:
              labels:
                app: nodejs
              name: web-controller
            spec:
              containers:
              - image: node:0.10.40
                command: ['tail', '-f', '/dev/null']
                args: []
                name: web
                ports:
                - containerPort: 3000
                  name: http-server
                volumeMounts:
                 - mountPath: /projects
                   name: projects
              volumes:
               - name: projects
                 persistentVolumeClaim:
                   claimName: projects
      - apiVersion: v1
        kind: PersistentVolumeClaim
        metadata:
          name: projects
        spec:
          accessModes:
           - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
      -
        apiVersion: v1
        kind: Service
        metadata:
          name: web
          labels:
            name: web
        spec:
          type: LoadBalancer
          ports:
            - name: web
              port: 80
              targetPort: 3000
              protocol: TCP
          selector:
            app: nodejs
      - apiVersion: v1
        kind: Route
        metadata:
          name: che
        spec:
          to:
            kind: Service
            name: web
          port:
            targetPort: web
commands:
  - name: run
    actions:
      - type: exec
        component: nodejs
        command: cd /projects/nodejs-mongo-app/EmployeeDB/ && npm install && sed -i -- ''s/localhost/mongo/g'' app.js && node app.js
        workdir: /projects/che
```

</details>

<details>

<summary>Devfile multiple dockerimage components</summary>

```yaml
specVersion: 0.0.1
name: multiple-dockerimages
projects:
  - name: nodejs-mongo-app
    source:
      type: git
      location: 'https://github.com/ijason/NodeJS-Sample-App.git'
components:
  - name: theia-editor
    type: cheEditor
    id: org.eclipse.che.editor.theia:1.0.0
  - name: exec-plugin
    type: chePlugin
    id: che-machine-exec-plugin:0.0.1
  - name: mongodb
    type: dockerimage
    image: mongo
    endpoints:
      - name: mongo
        port: 27017
        attributes:
          public: "false"
          discoverable: "true"
    mountSources: false
    volumes:
      - name: mongo-storage
        containerPath: /data/db
    memoryLimit: 250Mi
  - name: nodejs-app
    type: dockerimage
    image: node:0.10.40
    command: ['tail', '-f', '/dev/null']
    args: []
    endpoints:
      - name: app
        port: 3000
        attributes:
          public: "true"
    mountSources: true
    memoryLimit: 512Mi
commands:
  - name: run
    actions:
      - type: exec
        component: nodejs-app
        command: cd ${CHE_PROJECTS_ROOT}/nodejs-mongo-app/EmployeeDB/ && npm install && node app.js
```
</details>

<details>

<summary>Devfile with overridden entrypoints for K8s component</summary>

```yaml
specVersion: 0.0.1
name: entrypoint-test
projects:
- name: revapi
  source:
    type: git
    location: https://github.com/revapi/revapi.git
tools:
- name: theia
  type: cheEditor
  id: org.eclipse.che.editor.theia:1.0.0
- name: exec
  type: chePlugin
  id: che-machine-exec-plugin:0.0.1
- name: mvn
  type: kubernetes
  local: recipe
  localContent: |
    kind: Pod
    metadata:
      name: mvn-pod
    spec:
      containers:
      - image: maven:3.6.0-jdk-11
        name: mvn-container
  entrypoints:
  - command: ['tail']
    args: ['-f', '/dev/null']
```
</details>

### What issues does this PR fix or reference?
It is related to https://github.com/eclipse/che/issues/13018

#### Release Notes
N/A

#### Docs PR
N/A

### CODE REVIEW

**Comment by sleshchenko** [comment]
ci-test

**Review by mshaposhnik — APPROVED** [review]

**Comment by SkorikSergey** [comment]
Selenium tests execution on Eclipse Che Multiuser on OCP (https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1680//Selenium_20tests_20report/) doesn't show any regression against this Pull Request.

**Review by metlos — APPROVED** [review]

**Comment by sleshchenko** [comment]
Rebased against master (without any changes) before merge

**Comment by sleshchenko** [comment]
ci-build

**Pull request merged**
