### PR TITLE
CHE-5650: set fixed sorting order for prioritized stacks

### LINKED ISSUE #5650: Wrong order of stacks after sorting
**Reproduction Steps:**
 - Open "Dashboard"
 - Click on the "Workspace" -> "Add Workspace"
 - On "New Workspace" page click on the "ALL" button
 - Pay attention that first three stacks should be in the static order, independent from what sorting is used
 - Click on "NAME" button
 - Pay attention that buttons are changed their positions

**Expected behavior:**
First three stacks should be in the static order, regardless of what kind of sorting is used.

**Observed behavior:**
First three stacks change their order

**OS and version:**    
CHE 5.15.0 ; Chrome 59.0 ; Fedora 25
**Failed selenium test:** NewWorkspacePageTest

**Attachment:**

aaaa 1

### PR DESCRIPTION
**Pull request by akurinnoy**
### What does this PR do?
This PR sets fixed sorting order for some prioritized stacks. These 
stacks are marked by a 'thumb-tack' icon.

pinned

### What issues does this PR fix or reference?
fix #5650 

#### Release Notes

N/A - bugfix

#### Docs PR

N/A - bugfix

Signed-off-by: Oleksii Kurinnyi <okurinny@redhat.com>

### CODE REVIEW

**Review by benoitf — APPROVED** [review]

**Review by ashumilova — APPROVED** [review]

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/582/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/582//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10760)
docker image: eclipseche/che-server:10760
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by akurinnoy** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/596/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/596//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10760)
docker image: eclipseche/che-server:10760
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by SkorikSergey** [comment]
Selenium tests execution on Eclipse Che Multiuser on OCP (https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/596/) doesn't show any regression against this Pull Request.

**Review by olexii4 — APPROVED** [review]

**Pull request merged**
