### PR TITLE
Add binding of VS Code extension broker for Che 7

### PR DESCRIPTION
**Pull request by garagatyi**
### What does this PR do?
Adds binding of VS Code extension broker.
Demo of adding Sonarlint extension to Che https://youtu.be/5RLLs5J4qdg

### What issues does this PR fix or reference?
https://github.com/eclipse/che-plugin-broker/pull/19
https://github.com/eclipse/che-plugin-registry/pull/66
https://github.com/eclipse/che/issues/12292

### CODE REVIEW

**Review by sleshchenko — APPROVED** [review]

**Review by skabashnyuk — APPROVED** [review]

**Review by l0rd — APPROVED** [review]

**Comment by garagatyi** [comment]
Added demo of Sonarlint remote plugin in Che to issue description https://youtu.be/5RLLs5J4qdg

**Comment by ibuziuk** [comment]
@garagatyi are you planning to postpone merge until https://github.com/eclipse/che/issues/12292 is resolved ?

**Comment by garagatyi** [comment]
@ibuziuk no, this PR allows running extensions that do not execute commands, such as Sonarlint.

**Review by ibuziuk — APPROVED** [review]

**Comment by garagatyi** [comment]
ci-test

**Comment by garagatyi** [comment]
Since this PR only adds new broker and doesn't change work of anything else I decided to merge PR without analyzing functional tests results.

**Pull request merged**
