### PR TITLE
che #12187: Cancelling TimeoutProbeTask to avoid potential memory leak in ProbeScheduler

### PR DESCRIPTION
**Pull request by ibuziuk**
### What does this PR do?
Cancelling TimeoutProbeTask to avoid potential memory leak in ProbeScheduler

### What issues does this PR fix or reference?
#12187 

Cancelling TimeoutProbeTask to avoid potential memory leak in ProbeScheduler

#### Release Notes
N/A

#### Docs PR
N/A

### CODE REVIEW

**Review by sleshchenko — APPROVED** [review]

**Comment by garagatyi** [comment]
ci-test

**Comment by garagatyi** [comment]
I'm sorry. I closed PR by mistake. Missed the correct button.

**Review by garagatyi — APPROVED** [review]

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1344/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1344//Selenium_20tests_20report/)
docker image: eclipseche/che-server:12253
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by ibuziuk** [comment]
after discussion with @skabashnyuk it was decided that dereferencing httpconnection in the prob might also be a good idea to reduce RAM consumption.

**Comment by ibuziuk** [comment]
ci-test

**Review by skabashnyuk — APPROVED** [review]

**Pull request merged**
