### PR TITLE
Implementing test for Golang devfile

### PR DESCRIPTION
**Pull request by ScrewTSW**
### What does this PR do?
* Adds Golang devfile test into `npm run test-all-devfiles` suite
* Does some minor refactoring on other devfile tests and testsLibrary classes

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/15872

#### Release Notes
N/A

#### Docs PR
N/A

### CODE REVIEW

**Comment by ScrewTSW** [comment]
[ci-test]

**Comment by ScrewTSW** [comment]
@dmytro-ndp how can I re-run the prcheck build?

**Comment by Katka92** [comment]
ci-test

**Comment by Katka92** [comment]
[ci-test]

**Review by Ohrimenko1988 — APPROVED** [review]

**Review by Katka92 — APPROVED** [review]

**Comment by ScrewTSW** [comment]
[ci-test]

**Comment by ScrewTSW** [comment]
`ci.centos.org PR check (build)` is blocking the merge and I cannot re-trigger it. can some admin force-merge the PR?

**Comment by Katka92** [comment]
@ScrewTSW You should be able to trigger that by using 
[ci-build]

**Comment by ScrewTSW** [comment]
[ci-test]

**Pull request merged**
