### PR TITLE
Change Centos Nodejs stack Run Command

### PR DESCRIPTION
**Pull request by jarifibrahim**
### What does this PR do?
Change the default run command for `centos nodejs` stack from `node app.js` (which will work only if the entry point of the project is app.js) to `node .` (which will work for all nodejs projects which have a `main` section defined in `package.json` file. The `main` section defines the entry point.

Related to https://github.com/redhat-developer/rh-che/pull/1078

### What issues does this PR fix or reference?
 N/A

### CODE REVIEW

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by ibuziuk** [comment]
@jarifibrahim please add `Signed-Off-By` to the comit message. ip-validation check is failing currently

**Review by ibuziuk — APPROVED** [review]

**Comment by jarifibrahim** [comment]
@ibuziuk I've fixed the commit. Thank you for helping out :)

**Comment by ibuziuk** [comment]
@eivantsov @ashumilova do you think we can merge this one ? or there is a need to update node related samples first ?

**Review by ghost — APPROVED** [review]

**Review by ashumilova — APPROVED** [review]

**Comment by ibuziuk** [comment]
ci-build

**Comment by riuvshin** [comment]
ci-build

**Pull request merged**
