### PR TITLE
Remove implicit redirection from  `/api` to `/wsmaster/api` for all requests.

### PR DESCRIPTION
**Pull request by mshaposhnik**
### What does this PR do?
Removes implicit redirection from `/api` to `/wsmaster/api` by Tomcat valve.

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/6481

#### Release Notes
Removed internall rewrite  `/api` to `/wsmaster/api` 

#### Docs PR

https://github.com/eclipse/che-docs/pull/301/files

### CODE REVIEW

**Comment by benoitf** [comment]
It's more linked to the issue than the PR itself, but why wsmaster is deployed at /wsmaster and not on /api ?

**Comment by skabashnyuk** [comment]
AFAIK @TylerJewell decided to rename it.

**Comment by benoitf** [comment]
ok because it looks like it will be more simpler to deploy wsmaster.war on /api as it's basically only providing API stuff.

**Review by skabashnyuk — APPROVED** [review]

**Review by slemeur — CHANGES_REQUESTED** [review]
I don't see the value. These changes are going to make the api less readable.

WSMaster is an internal component - it does not have to be exposed in the URL.

`wsmaster/api/factory` for example is looking very bad.

**Comment by skabashnyuk** [comment]
@slemeur what is the value to make it readable. It's not something that end user will see or will have to input. Because that of my technical motivation was to make it work in one way.   ```/wsmaster/api```  or ```/api``` because it provides **real** technical issues.  So if you are against ```/wsmaster/api```  as it is right now - please propose and motivate another way.
BTW factory url that end-user will see **will not** change.

**Comment by skabashnyuk** [comment]
>> @benoitf  ok because it looks like it will be more simpler to deploy wsmaster.war on /api as it's >> basically only providing API stuff.

I don't know. It's more looks like exercise for exercise. If @TylerJewell  in one time decided that wsmaster is more appropriate name then let's finalize this task and play with single url, not with two.
It's quite strange to have two type of url in Eclipse Che, one in Codenvy. I would like to clean up this mess once and for all.

**Comment by benoitf** [comment]
@skabashnyuk I agree on the single URL but I would vote for /api

**Comment by skabashnyuk** [comment]
No problem lets do it in separate issue. 
This one is more related to finalization of rename initiated by @TylerJewell

**Comment by benoitf** [comment]
AFAIK we don't need a separate issue

**Comment by slemeur** [comment]
@skabashnyuk : 
- When you are working on an API, you actually have "end-users" who are developers. It's all about API Developer Experience and yes, names, paths are importants in order to make an API readable.

So I confirm: `/api` is much more simpler, logical, easy to discover and readable than `/wsmaster/api`.

**Comment by slemeur** [comment]
And because we are speaking about API DX, when doing those kind of things, you actually need to document it and notify your community.
I wonder how you can approve the PR, while there is no mention to be published in the release note and no information/help/guidance for our community on the change.

**Comment by vparfonov** [comment]
wsmaster/api/ is logical for me because it really Workspace Master in our terminology

**Review by vparfonov — APPROVED** [review]

**Comment by skabashnyuk** [comment]
One point to be ```wsmaster/api/``` basket is to distinct somehow from ws-agent url.
It would be easier for some kind incoming proxies to filter ws-master vs ws-agent urls if they do not start in the same way.

**Comment by benoitf** [comment]
@skabashnyuk I'm not sure `incoming proxies` reason is helping much there.
AFAIK the URLs are not targeting the same port so it's easy to distinct. 
And I would say that for production you may want to use a single port (like with Træfik) then the hosts are different as well so it's easy as well.

**Comment by slemeur** [comment]
@vparfonov : That's exactly the point. It is our terminology, which is logical for us but might not be for external contributors. 

At the end, it'll be your decision to move forward and to define what's the best. 
I wanted to give different elements, so that you can understand that this change is having a bigger impacts that what you may think at first. And those impacts also have to be managed (documentation, communication to the community, ...)

Making things simpler for us should not impact the ultimate goal which is to make the product simple for others (end-users, api consumer, community, contributors).

I give my -1 to the PR, as it is today because it does not meet the merge criterias - that you as maintainers should care about.

**Comment by gazarenkov** [comment]
/api is more clear

but my concern is more that path (which is visible part and I can imagine the cases when it makes sense to have other than default) should be independent on name of war (which is implementation details)

**Comment by mshaposhnik** [comment]
DOCS [PR](https://github.com/eclipse/che-docs/pull/301/files)

**Comment by benoitf** [comment]
@gazarenkov yes I agree as well that the name of the war can be anything.

**Pull request closed without merging**
