### PR TITLE
Fix small bugs for dashboard

### PR DESCRIPTION
**Pull request by olexii4**
### What does this PR do?
Fix empty 'Edit the machine' form error. Fix the regular expression for a workspace name.

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/10659
https://github.com/eclipse/che/issues/10732

### CODE REVIEW

**Comment by olexii4** [comment]
ci-test

**Review by benoitf — APPROVED** [review]

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/950/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/950//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11569
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by olexii4** [comment]
ci-test

**Review by akurinnoy — APPROVED** [review]

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/957/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/957//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11569
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by olexii4** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/964/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/964//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11569
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Review by akurinnoy — APPROVED** [review]

**Review by ashumilova — APPROVED** [review]

**Comment by SkorikSergey** [comment]
Selenium tests execution on Eclipse Che Multiuser on OCP (https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/964/) doesn't show any regression against this Pull Request.

**Pull request merged**
