### PR TITLE
Rework dependency management in go agents

### PR DESCRIPTION
**Pull request by skabashnyuk**
### What does this PR do?
- Used dep as dependency management format.
- Used github.com/gorilla/websocket,  github.com/kr/pty, github.com/julienschmidt/httprouter from original repositories. Che-lib versions can be removed after this pr.
- Jsorpc package moved and reused from github.com/eclipse/che-go-jsonrpc

### What issues does this PR fix or reference?
n/a
#### Release Notes
Rework dependency management in go agents

#### Docs PR
n/a

### CODE REVIEW

**Comment by skabashnyuk** [comment]
ci-test

**Review by AndrienkoAleksandr — APPROVED** [review]

**Review by garagatyi — APPROVED** [review]

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/731/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/731//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/11038)
docker image: eclipseche/che-server:11038
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by skabashnyuk** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/874/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/874//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11038
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by skabashnyuk** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/876/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/876//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11038
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by skabashnyuk** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/880/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/880//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11038
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by skabashnyuk** [comment]
@eclipse/eclipse-che-qa can you take a look on report?

**Comment by skabashnyuk** [comment]
ci-test

**Comment by skabashnyuk** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1043/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1043//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11038
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1038/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1038//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11038
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by skabashnyuk** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1054/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1054//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11038
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Pull request merged**
