### PR TITLE
Cherry-pick 19787 to che 7.30.x

### PR DESCRIPTION
**Pull request by ScrewTSW**
Migrated debug logic from downstream, add missing logic and refactored happy-path (#19787)

* Migrated debug logic from downstream, updated methods in Editor class

Signed-off-by: Tibor Dancs <tdancs@redhat.com>

* Added runTaskConsoleOutput method into codeExecution libs

Signed-off-by: Tibor Dancs <tdancs@redhat.com>

* Added goToDefinition method, renamed codenavigation to goToImplementations

Signed-off-by: Tibor Dancs <tdancs@redhat.com>

* Adding some extra missing methods into testsLibs, updated HappyPath login logic

Signed-off-by: Tibor Dancs <tdancs@redhat.com>

* Updated Login.spec.ts, added fullscreen value report to CheReporter.ts and modified definition in TestConstants, setting fullscreen to true by default

Signed-off-by: Tibor Dancs <tdancs@redhat.com>

### What does this PR do?
Cherry-picking #19787 to Che 7.30.x

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Review by Katka92 — APPROVED** [review]

**Review by Ohrimenko1988 — APPROVED** [review]

**Comment by ScrewTSW** [comment]
[crw-ci-test]

**Comment by ScrewTSW** [comment]
[crw-ci-test]

**Comment by ScrewTSW** [comment]
[crw-ci-test]

**Comment by ScrewTSW** [comment]
[crw-ci-test]

**Comment by ScrewTSW** [comment]
[crw-ci-test]

**Comment by ScrewTSW** [comment]
[crw-ci-test]

**Comment by ScrewTSW** [comment]
[crw-ci-test]

**Comment by ScrewTSW** [comment]
[crw-ci-test]

**Comment by ScrewTSW** [comment]
[crw-ci-test]

**Comment by ScrewTSW** [comment]
[crw-ci-test]

**Comment by dmytro-ndp** [comment]
@ScrewTSW: Happy path PR check is dedicated to **main** branch and **nightly Eclipse Che**. So, it is expected that failed with tests dedicated to previous version of Eclipse Che, like 7.30.x.

**Pull request merged**
