### PR TITLE
Issue 3029 - Add a 'warning' state for the notifications

### PR DESCRIPTION
**Pull request by xcoulon**
### Previous behavior
(Remove this section if not relevant)

### New behavior
(Explain the PR as it should appear in the release notes)

Please review [Che's Contributing Guide](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md) for best practices.

Using the `#F0AD4E` code for the darkish orange background, so the
font can remain white and be consistent with other types of notifications

Signed-off-by: Xavier Coulon <xcoulon@redhat.com>

### CODE REVIEW

**Comment by slemeur** [comment]
Thanks @xcoulon !

Please @ashumilova , @vzhukovskii + @vitaliy-guliy could you review?

**Review by slemeur — APPROVED** [review]
Ok for me

**Comment by vitaliy-guliy** [comment]
+1

**Review by vzhukovs — APPROVED** [review]

**Comment by benoitf** [comment]
ci-build

**Review by vitaliy-guliy — APPROVED** [review]

**Review by benoitf — APPROVED** [review]

**Comment by xcoulon** [comment]
thanks !

**Pull request merged**
