### PR TITLE
DO NOT MERGE

### PR DESCRIPTION
**Pull request by riuvshin**
DO NOT MERGE

### CODE REVIEW

**Comment by musienko-maxim** [comment]
ci-test

**Comment by musienko-maxim** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/461/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/461//Selenium_tests_report)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10372)
docker image: eclipseche/che-server:10372
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/462/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/462//Selenium_tests_report)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10372)
docker image: eclipseche/che-server:10372
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by vzhukovskii** [comment]
ci-build

**Pull request closed without merging**
