### PR TITLE
Avoid redirection loop in case if gwt-ide loaded in the sidecar

### PR DESCRIPTION
**Pull request by skabashnyuk**
### What does this PR do?
Changes introduced #12864 makes loading gwt ide a bit more complex. Now there is a redirection loop. This pr introduce circuit-breaker.

### What issues does this PR fix or reference?
n/a
#### Release Notes
n/a

#### Docs PR
n/a

### CODE REVIEW

**Comment by skabashnyuk** [comment]
ci-test

**Comment by skabashnyuk** [comment]
CC @monaka

**Comment by monaka** [comment]
@skabashnyuk Is your Che environment single-host?
I've not tested this patch because my env is multi-host and the similar issue will be fixed by #13142.
But in my opinion, this PR should be merged for running GWT-IDE under single-host env.

**Comment by skabashnyuk** [comment]
@monaka it was tested on single-user che on minishift.

**Comment by skabashnyuk** [comment]
ci-test

**Review by vparfonov — APPROVED** [review]

**Pull request merged**
