### PR TITLE
Selenium: Add the 'try-catch' to the 'GitPullTest'

### PR DESCRIPTION
**Pull request by artaleks9**
### What does this PR do?
* Add the _try-catch_ expression to the selenium test _GitPullTest_ according to the known issue #11648

### What issues does this PR fix or reference?
#11649

### CODE REVIEW

**Review by dmytro-ndp — APPROVED** [review]

**Comment by artaleks9** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1005/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1005//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11652
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Review by SkorikSergey — APPROVED** [review]

**Review by Ohrimenko1988 — APPROVED** [review]

**Comment by artaleks9** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1009/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1009//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11652
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1010/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1010//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11652
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Pull request merged**
