### PR TITLE
Adding debug commands for vertx & spring-boot stacks

### PR DESCRIPTION
**Pull request by ibuziuk**
Signed-off-by: Ilya Buziuk <ibuziuk@redhat.com>

### What does this PR do?
Adds debug commands for 'vert.x' and 'spring-boot' stacks

### What issues does this PR fix or reference?
https://github.com/redhat-developer/rh-che/issues/238

#### Changelog
Adding debug commands for 'vert.x' and 'spring-boot' stacks

#### Release Notes
Debug commands for 'vert.x' and 'spring-boot' stacks

#### Docs PR
N / A

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by benoitf** [comment]
commands are ok but it looks like the port for debugging (5005) is not exposed on the docker images.

**Comment by ghost** [comment]
@benoitf there's no need to expose it unless you need to remotely debug the app. Otherwise, Che debugger connects to localhost:5005

**Comment by benoitf** [comment]
@eivantsov yes I was thinking on remote debugging as well but it's not the primary case.

**Review by benoitf — APPROVED** [review]

**Review by sunix — APPROVED** [review]
LGTM

**Review by ashumilova — APPROVED** [review]

**Pull request merged**
