### PR TITLE
Returns 'add-source' execution into pom.xml for UD

### PR DESCRIPTION
**Pull request by olexii4**
Signed-off-by: Oleksii Orel <oorel@redhat.com>

### What does this PR do?
Returns 'add-source' execution into pom.xml.

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/11525

### CODE REVIEW

**Comment by olexii4** [comment]
ci-test

**Review by ashumilova — APPROVED** [review]

**Review by benoitf — APPROVED** [review]

**Review by sunix — APPROVED** [review]
LGTM

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/934/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/934//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11528
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1128/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1128//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11528
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Pull request merged**
