### PR TITLE
CHE-8909 fix add a new machine flow

### PR DESCRIPTION
**Pull request by olexii4**
Signed-off-by: Oleksii Orel <oorel@redhat.com>

### What does this PR do?
Fixed add a new machine flow.

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/8909
https://github.com/eclipse/che/issues/12047

### CODE REVIEW

**Comment by olexii4** [comment]
ci-test

**Comment by olexii4** [comment]
ci-test

**Comment by SkorikSergey** [comment]
ci-test

**Comment by SkorikSergey** [comment]
ci-test-docker-single

**Comment by SkorikSergey** [comment]
ci-test-docker-single

**Review by SkorikSergey — APPROVED** [review]

**Comment by SkorikSergey** [comment]
Selenium tests execution on Eclipse Che Multiuser on OCP (https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1393//Selenium_20tests_20report/) doesn't show any regression against this Pull Request.

**Review by akurinnoy — APPROVED** [review]

**Review by ashumilova — APPROVED** [review]

**Review by musienko-maxim — APPROVED** [review]

**Comment by olexii4** [comment]
https://docs.oracle.com/cd/E52668_01/E88884/html/kubectl-basics.html
```
...These must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character...
```

**Pull request merged**
