### PR TITLE
Fix project.version issue in dependencyManagement: Use maven property…

### PR DESCRIPTION
**Pull request by sunix**
… for che version instead. Do not force maven child projects to use the Che version.

### CODE REVIEW

**Comment by skabashnyuk** [comment]
How it related to other or repositories based on eclipse/che parent pom?

**Comment by sunix** [comment]
This is a fix, so there is nothing to do in other repositories.

**Comment by sunix** [comment]
Could you point me the repositories you are talking about ?

About openshift plugin, it is all fine as the versions are "aligned" (openshift version == che version), so the problem didn't occur. And this parent is used as a bom (scope import). So nothing to do for this one.

**Comment by skabashnyuk** [comment]
https://github.com/codenvy/artik-ide
https://github.com/codenvy/codenvy
https://github.com/codenvy/customer-saas
https://github.com/codenvy/plugin-openshift

**Comment by sunix** [comment]
Ok same comments for artik and codenvy: they use che as a bom and use aligned che version: nothing to do. Seems I don't have access to customer-saas

**Comment by skabashnyuk** [comment]
ci-build

**Comment by skabashnyuk** [comment]
@riuvshin  wdyt?

**Comment by riuvshin** [comment]
LGTM

**Comment by skabashnyuk** [comment]
LGTM

**Comment by sunix** [comment]
I've rebased + fix conflicts, it's ready again for merge

**Comment by benoitf** [comment]
@sun you've the commit rights to merge, no ?

**Comment by sunix** [comment]
Mh yes :)

Le lun. 30 mai 2016 19:19, Florent BENOIT notifications@github.com a
écrit :

> @sun https://github.com/sun you've the commit rights to merge, no ?
> 
> —
> You are receiving this because you authored the thread.
> 
> Reply to this email directly, view it on GitHub
> https://github.com/eclipse/che/pull/1335#issuecomment-222530340, or mute
> the thread
> https://github.com/notifications/unsubscribe/AAntS5ySKduwZYXqUbk8_Yq1eEMdh6Wgks5qGxwLgaJpZM4Ikfpq
> .
> 
> ## 

## 

_Sun Seng David TAN_
_Senior Java Developer__Eclipse Che commiter_

Mobile : +33 21 02 41 73

Email : _sun.tan@serli.com sun.tan@serli.com_

Site Web : www.serli.com

Suivez-nous sur Twitter : @SerliFr @sunsengdavidtan et Facebook : SerliFr

**Pull request merged**
