### PR TITLE
Use trash icon from FontAwesome for delete command operation

### PR DESCRIPTION
**Pull request by vzhukovs**
### What does this PR do?
This changes proposal replaces current icon for delete command button with the new one used from Font Awesome:

image

Signed-off-by: Vladyslav Zhukovskyi <vzhukovs@redhat.com>

### What issues does this PR fix or reference?
https://github.com/openshiftio/openshift.io/issues/1502

#### Release Notes
N/A

#### Docs PR
N/A

### CODE REVIEW

**Comment by vzhukovskii** [comment]
ci-build

**Comment by vzhukovs** [comment]
ci-build

**Comment by dkulieshov** [comment]
Hi,

Everything looks good, but I wonder what you think about the next thing. I'd rather added a separate method `createButton(String)` instead of making common method `getIconElement`, because though technically it is permissible, it seems to me a bit weird when you do `icon instanceof String`, because essentially icon and string are quite different entities. Or, by the way, we can have `createButton(Element)` and `createButtonElement(SVGResource resource)` and `createButtonElement(String iHtmlTag)`?

**Comment by vzhukovs** [comment]
@dkuleshov it's not a problem to refactor this PR. The main reason why I'm comparing with String is that we have `org.eclipse.che.ide.FontAwesome` class where icons described as html strings. There isn't any impediments to create two separate private methods to process two types of icon.

**Review by azatsarynnyy — APPROVED** [review]

**Review by ashumilova — APPROVED** [review]

**Review by vparfonov — APPROVED** [review]

**Comment by slemeur** [comment]
@vzhukovskii : Have you handle "deleting" using the keyboard ?

**Comment by slemeur** [comment]
This does not fix: https://github.com/eclipse/che/issues/7715

**Comment by vzhukovs** [comment]
@slemeur no, this PR just changes the icon with the new one.

**Comment by slemeur** [comment]
so where are the other improvementS?

**Comment by ashumilova** [comment]
The PR handled the description of the following issue only - https://github.com/openshiftio/openshift.io/issues/1502
this one will take into account - https://github.com/eclipse/che/issues/7715

**Pull request merged**
