### PR TITLE
Display notification with error instead of dialog window

### PR DESCRIPTION
**Pull request by RomanNikitenko**
### What does this PR do?
Display notification with error instead of dialog window when some error is happened at creating/importing/updating project.
For example, for creating project:
Current behavior:
create_old_behavior

New behavior:
new_create_error

### What issues does this PR fix or reference?
#10515

Signed-off-by: Roman Nikitenko <rnikiten@redhat.com>

### CODE REVIEW

**Comment by RomanNikitenko** [comment]
ci-test

**Comment by RomanNikitenko** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1057/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1057//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11698
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Review by vparfonov — APPROVED** [review]

**Comment by artaleks9** [comment]
Selenium tests execution on Eclipse Che Multiuser on OCP (https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1057/) doesn't show any regression against this Pull Request.

**Pull request merged**
