### PR TITLE
Fix typo.

### PR DESCRIPTION
**Pull request by monaka**
### What does this PR do?

Fix a typo.

### What issues does this PR fix or reference?

Inspired by #12012

### CODE REVIEW

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by skabashnyuk** [comment]
ci-build

**Comment by skabashnyuk** [comment]
ci-test

**Review by sleshchenko — CHANGES_REQUESTED** [review]
Well, Selenium tests are correct.
Typo needs to be fixed in factory extension
https://github.com/eclipse/che-theia-factory-extension/search?q=clonning&unscoped_q=clonning
and only then in tests otherwise it would fail.

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1217/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1217//Selenium_20tests_20report/)
docker image: eclipseche/che-server:12022
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by monaka** [comment]
I sent eclipse/che-theia-factory-extension#16.

**Comment by monaka** [comment]
ci-build

**Comment by skabashnyuk** [comment]
ci-build

**Comment by skabashnyuk** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1232/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1232//Selenium_20tests_20report/)
docker image: eclipseche/che-server:12022
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Review by sleshchenko — APPROVED** [review]
LGTM

**Comment by sleshchenko** [comment]
ci-test

**Comment by sleshchenko** [comment]
ci-build

**Review by benoitf — APPROVED** [review]

**Comment by benoitf** [comment]
@monaka you need to amend your commit by using Signed-Off so ip-validation check will be fine

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1234/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1234//Selenium_20tests_20report/)
docker image: eclipseche/che-server:12022
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by riuvshin** [comment]
ci-build

**Comment by riuvshin** [comment]
ci-build

**Pull request merged**
