### PR TITLE
Added subject propagation during WebSocket methods calls

### PR DESCRIPTION
**Pull request by sleshchenko**
### What does this PR do?
Adds subject propagation during WebSocket methods calls. It includes:
- Adds storing of Che Subject into http session in MachineLogin filters
- Removes excluding for WebSocket endpoint path from MachineLoginFilter binding;
- Adds settings subject into `EnvironmentContext` during WebSocket methods calls;

It also does the following small fix:
- Moves exclude of OIDCKeycloak.js to mapping instead of Filter class;

### What issues does this PR fix or reference?
It is needed for https://github.com/eclipse/che/issues/10861.

#### Release Notes
N/A

#### Docs PR
N/A

### CODE REVIEW

**Review by skabashnyuk — APPROVED** [review]

**Comment by sleshchenko** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/670/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/670//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10922)
docker image: eclipseche/che-server:10922
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by sleshchenko** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/674/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/674//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10922)
docker image: eclipseche/che-server:10922
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Pull request merged**
