### PR TITLE
Customize image names during image build

### PR DESCRIPTION
**Pull request by TylerJewell**
### What does this PR do?
This PR tackles the challenge of generating custom image names to run Che in a custom assembly. The issue is discussed here - https://github.com/eclipse/che/issues/4313#issuecomment-284398059.

The build scripts have been modified to generate images of the format `$ORGANIZATION/$PREFIX-$NAME:$TAG`. The default organization is `eclipse`, the default tag is `nightly`, and the default prefix is `che`.  You can proivde `--organization:<org>`, `--prefix:<prefix>`, or `--tag:<tag>` on the command line to customize the images that are generated.

`build-all.sh` script has been renamed to `build.sh`and allow to build the minimum set of images to generate a new Che server (with build.sh <dirs>), the CLI, and unit tests for these custom image names.  If you build the CLI image, we overwrite `/dockerfiles/cli/version/$TAG/images` file to include the customized names that have been provided before this image is built, so the registry within the Docker image is accurate.

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/4313

#### Changelog
[cli] Apply custom image names for Che and associated CLI images

#### Release Notes
You can now build Che with custom image names and also generate custom CLI images that reference those custom names. Changing the image name of Che has a number of beneficial use cases including allowing us to create tailored continuous integration flows with custom images for each branch, letting ecosystem developers generate custom image names for their custom assemblies, and engineers can create images tailored to the work they are doing without it conflicting with released images.

The build scripts have been modified to generate images of the format `$ORGANIZATION/$PREFIX-$NAME:$TAG`. The default organization is `eclipse`, the default tag is `nightly`, and the default prefix is `che`.  You can proivde `--organization:<org>`, `--prefix:<prefix>`, or `--tag:<tag>` on the command line to customize the images that are generated.

There is an updated `build.sh <dirs>` script which can now build any number of Docker images. You can provide the list of directories that it should build and it will iterate through each one. Also, builds the minimum set of images to generate a new Che server, the CLI, and unit tests for these custom image names.  If you build the CLI image, we overwrite `/dockerfiles/cli/version/$TAG/images` file to include the customized names that have been provided before this image is built, so the registry within the Docker image is accurate.

### CODE REVIEW

**Comment by riuvshin** [comment]
why we need custom images for base images? as I understand we need only custom images for for custom packages like saas which reuse eclipse/* base images.

**Comment by TylerJewell** [comment]
Custom assembly authors want the ability to rename the base images for branding purposes.

**Comment by riuvshin** [comment]
hm... this sounds strange to me, no one wants to put branding on dependencies, authors just using them. I believe that custom assembly authors want put branding on their own images for custom package but definitely not for dependencies. We don;t rename or repackage GWT framework we just use it to build our own product. 
And just imagine how hard for a user will be build own whole stack of images instead of using already built ones as dependencies

**Comment by TylerJewell** [comment]
Then they can skip building other base images.  But this improvement modifies the build scripts to enable changing one or all image names.

**Comment by benoitf** [comment]
Let say we want to publish che images for each pull request/some branches so everyone can locally test the changes
We need for that to build locally the base image so we're sure we are using that image and not the official base image (for example if a pull request is modifying the base image, we need to ensure it is working as well)
But these images, while they will be built, they may not be published

**Comment by riuvshin** [comment]
@benoitf totally agree this is useful! my concern was only about forcing users rebuild whole stack images for "branding" purposes.

**Comment by benoitf** [comment]
@riuvshin AFAIK I think it's separated

**Comment by TylerJewell** [comment]
It is just simpler this way to guarantee mutability.  They are already cloning the source tree and could modify any number of files.  So this guarantees isolation and a clean build.

**Comment by benoitf** [comment]
@TylerJewell maybe instead of having another script `build-che.sh`

we could rename build-all.sh to build.sh and have options to build all images (default) or some subset (like --something-to-define)

**Comment by TylerJewell** [comment]
Yeah that is a good idea florent.  How goes the testing?

**Comment by riuvshin** [comment]
@TylerJewell yeah but only in case where they really need customize base images. I think in most cases they will just use tags that we provide

**Comment by benoitf** [comment]
@TylerJewell In progress. BTW can we remove from this PR the changes on --follow and exec or merge https://github.com/eclipse/che/pull/4326 so that we only have build changes

**Comment by TylerJewell** [comment]
Then they can skip the build all steps and just build a single image.  But I will find debugging and supporting those accounts very difficult.  

It is easier to ask a support case to build all and have them get a custom base, init, che, cli image that passes unit tests.  And then the chain of accountability for debugging is cleaner.

**Comment by TylerJewell** [comment]
I am going to merge 4236 this am.

**Comment by benoitf** [comment]
I’ve done some changes
- Added optional .require files in directories. Allow us to detect dependencies of the image (for example cli is requiring base and bats)
- Add macros on Dockerfile. For example cli image is based on base image, so add macro to be able to change the parent image to be like FROM ${BUILD_ORGANIZATION}/${BUILD_PREFIX}-base:${BUILD_TAG}
- fix the path to version files (when building from top level folder it was not writing in the correct file)
- fix tests that tries to pull images (add skip pull)
- replace build-all.sh to be build.sh with more advanced options
```
     build.sh <list of directories to build>  : build all the specified images and their dependencies
     build.sh : build all the images
```

for example if I need to rebuild cli (with base as dependency) I only need to do on dockerfiles folder `: ./build.sh cli`
If I need to rebuild as well init
`./build.sh init cli`

**Comment by benoitf** [comment]
The new enhancements should fix https://github.com/eclipse/che/issues/3559

**Comment by benoitf** [comment]
- added template for images file
- fix test for checking online dockerhub images

**Comment by benoitf** [comment]
add fixes when checking remote dockerhub on not yet existing images

**Comment by TylerJewell** [comment]
@benoitf - I was able to build + run a custom Che in a Docker image.  +1 on this and ok for it to merge.

**Comment by benoitf** [comment]
should we remove "wip" on PR title ?

**Comment by TylerJewell** [comment]
Yes - it's definitely not wip now

**Comment by benoitf** [comment]
@riuvshin you want to give a try before merging ?

**Review by benoitf — APPROVED** [review]

**Pull request merged**
