### PR TITLE
Correct the selenium tests to make more reliability

### PR DESCRIPTION
**Pull request by artaleks9**
### What does this PR do?
* Correct the selenium tests to make them more reliability when run on CI

### What issue
#12804

### CODE REVIEW

**Comment by artaleks9** [comment]
ci-test

**Comment by artaleks9** [comment]
ci-test

**Comment by artaleks9** [comment]
ci-test

**Review by SkorikSergey — APPROVED** [review]

**Comment by artaleks9** [comment]
ci-test

**Pull request merged**
