### PR TITLE
rh-che #379: Migrating to a new GitHub token endpoint

### PR DESCRIPTION
**Pull request by ibuziuk**
### What does this PR do?
Changing parsing logic in `KeycloakTokenProvider` due to migration to a new GitHub token provider endpoint

### What issues does this PR fix or reference?
https://github.com/redhat-developer/rh-che/issues/379

Changing parsing logic in `KeycloakTokenProvider` due to migration to a new GitHub token provider endpoint

#### Release Notes
N/A

#### Docs PR
N/A

### CODE REVIEW

**Review by benoitf — COMMENTED** [review]
ci-build

**Review by davidfestal — APPROVED** [review]

**Review by riuvshin — APPROVED** [review]

**Review by l0rd — APPROVED** [review]
LGTM

**Comment by ibuziuk** [comment]
@benoitf are you ok, if I merge this one ?

**Review by benoitf — APPROVED** [review]

**Comment by benoitf** [comment]
@ibuziuk yes, also you'll need to provide a PR for che6 branch

**Comment by ibuziuk** [comment]
@benoitf ok, will do ;-)

**Pull request merged**
