### PR TITLE
Make embedded OAuth authentication model default for both singe and multiuser che && allow to get OAuth token with machine token

### PR DESCRIPTION
**Pull request by skabashnyuk**
### What does this PR do?
Make embedded OAuth authentication model default for both singe and multiuser che
- set OAuth `embedded` mode as default for singe/multi user Che.
- fixed dashboard, now it correctly adds user id for `api/oauth/authenticate` requests
- Allowed to get OAuth tokens with machine token.

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/15672

#### Release Notes
n/a

#### Docs PR
n/a

### CODE REVIEW

**Comment by skabashnyuk** [comment]
CC @ibuziuk

**Review by SkorikSergey — APPROVED** [review]

**Comment by skabashnyuk** [comment]
I've tested it with enabled OpenshiftOAuth and Github OAuth work correctly.
CC @ibuziuk @davidfestal 
openshift-github

**Review by akurinnoy — APPROVED** [review]

**Comment by skabashnyuk** [comment]
I have some concerns about extending the permission of the machine token. That makes sharing workspace too open and the user may not expect that if you share workspace you also make it possible to access all data that is available with machine token since we mount it as an environment variable. Here we have an open discussion about the future of sharing https://github.com/eclipse/che/issues/15304

@davidfestal @l0rd @benoitf what do you think, is this a legitimate concern?

**Review by benoitf — APPROVED** [review]
AFAIK ssh keys are already mounted so this PR is not opening the door when a workspace is shared.

**Pull request merged**
