### PR TITLE
Add sample for nodejs postgres stack

### LINKED ISSUE #12194: Application preview url isn't correct for project samples in 'Nodejs and Postgres Stack' stack
**Reproduction Steps:**
1. Create a workspace through **Dashboard** from ```Nodejs and Postgres Stack``` with "web-nodejs-simple" project sample.
2. Start the workspace and check that the IDE is fully initialized.
3. Start ```web-nodejs-simple:install dependencies``` command and wait it finished.
4. Start ```web-nodejs-simple:run``` command, click on **previewUrl** and check that application worked.

**Actual result:**
Preview url isn't correct - ```${server.9000/tcp}``` for this stack. 
 
**Che version**: 6.16.0-SNAPSHOT
**OS and version:** Fedora 28

**Additional information:**
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* See the attachment:

**Screenshot:**
selection_179

### PR DESCRIPTION
**Pull request by jarifibrahim**
### What does this PR do?
Add https://github.com/nodeshift-starters/nodejs-rest-http-crud to the list of samples for nodejs-postgres stack

Note: I have intentionally not added the run command for this sample. The nodejs-postgres stack already has the correct Run command.

Signed-off-by: Ibrahim Jarif <jarifibrahim@gmail.com>

### What issues does this PR fix or reference?
Fixes https://github.com/eclipse/che/issues/12194

### CODE REVIEW

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by jarifibrahim** [comment]
@SkorikSergey can you please review this PR?

**Comment by SkorikSergey** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1304/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1304//Selenium_20tests_20report/)
docker image: eclipseche/che-server:12198
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Review by SkorikSergey — APPROVED** [review]

**Comment by SkorikSergey** [comment]
Selenium tests execution on Eclipse Che Multiuser on OCP (https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1304//Selenium_20tests_20report/) doesn't show any regression against this Pull Request.

**Comment by jarifibrahim** [comment]
[test]

**Comment by jarifibrahim** [comment]
ci-test

**Comment by ibuziuk** [comment]
[ci-build]

**Comment by ibuziuk** [comment]
ci-build

**Review by ibuziuk — APPROVED** [review]

**Comment by ibuziuk** [comment]
@SkorikSergey could you please clarify the failure https://ci.codenvycorp.com/job/che-pullrequests-build/5070/ ?

**Comment by ibuziuk** [comment]
ci-build

**Comment by ibuziuk** [comment]
ci-build

**Pull request merged**
