### PR TITLE
Fixing Quarkus devfile tests flakyness

### PR DESCRIPTION
**Pull request by ScrewTSW**
### What does this PR do?
Fixes Quarkus flaky tests, in 7.14.2 the LS initialization string for Quarkus changed as well

### What issues does this PR fix or reference?
hotfix

#### Release Notes
N/A

#### Docs PR
N/A

### CODE REVIEW

**Review by rhopp — APPROVED** [review]

**Review by Katka92 — APPROVED** [review]

**Comment by ScrewTSW** [comment]
crw-ci-test

**Comment by ScrewTSW** [comment]
crw-ci-test

**Comment by ScrewTSW** [comment]
[crw-ci-test]

**Comment by ScrewTSW** [comment]
[crw-ci-test]

**Pull request merged**
