### PR TITLE
Enable support for CHE_DEBUG_SUSPEND in docker image's entrypoint.sh

### PR DESCRIPTION
**Pull request by metlos**
### What does this PR do?
`$TITLE`

### What issues does this PR fix or reference?

#12412 

#### Release Notes
* [x] https://github.com/eclipse/che-docs/pull/666

### CODE REVIEW

**Review by sleshchenko — APPROVED** [review]
Thanks for fixing it.

**Review by benoitf — APPROVED** [review]

**Comment by metlos** [comment]
ci-test

**Comment by skabashnyuk** [comment]
@eclipse/eclipse-che-qa  can you take a look on results?

**Comment by metlos** [comment]
QA-approved through @rhopp

**Pull request merged**
