### PR TITLE
Replace outdated images in configuration

### PR DESCRIPTION
**Pull request by musienko-maxim**
### What does this PR do?
Replace outdated images in the workspace templates for docker

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/11048

### CODE REVIEW

**Comment by musienko-maxim** [comment]
ci-test

**Review by dmytro-ndp — APPROVED** [review]

**Comment by musienko-maxim** [comment]
ci-build

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/742/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/742//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/11051)
docker image: eclipseche/che-server:11051
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by musienko-maxim** [comment]
The selenium test session passed as expected (without regression)

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/749/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/749//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/11051)
docker image: eclipseche/che-server:11051
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Pull request merged**
