### PR TITLE
Make E2E tests screenshots available in report on CI

### PR DESCRIPTION
**Pull request by dmytro-ndp**
### What does this PR do?
It makes screenshots available in failsafe-report.html on CI.

### What issues does this PR fix or reference?
#10257

### CODE REVIEW

**Comment by dmytro-ndp** [comment]
ci-test-docker-single

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test/512/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test/512//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10939)
docker image: eclipseche/che-server:10939
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by dmytro-ndp** [comment]
ci-test-docker-single

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test/513/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test/513//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10939)
docker image: eclipseche/che-server:10939
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by dmytro-ndp** [comment]
ci-test

**Review by Ohrimenko1988 — APPROVED** [review]

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/675/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/675//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10939)
docker image: eclipseche/che-server:10939
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/682/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/682//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10939)
docker image: eclipseche/che-server:10939
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Pull request merged**
