### PR TITLE
[Selenium] Change selenium tests from 'projectexplorer' package to wait that jdtls is fully initialized before working with project 

### PR DESCRIPTION
**Pull request by SkorikSergey**
### What does this PR do?
Change selenium tests from ```projectexplorer``` package to wait that **jdtls** is fully initialized before working with project.

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/12205

### CODE REVIEW

**Comment by SkorikSergey** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1313/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1313//Selenium_20tests_20report/)
docker image: eclipseche/che-server:12206
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by SkorikSergey** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1314/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1314//Selenium_20tests_20report/)
docker image: eclipseche/che-server:12206
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by SkorikSergey** [comment]
ci-test

**Comment by SkorikSergey** [comment]
ci-build

**Comment by dmytro-ndp** [comment]
@SkorikSergey: good fixup, Sergey.
Could we apply the same approach to the tests of [org.eclipse.che.selenium.refactor](https://github.com/eclipse/che/tree/master/selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor) and [org.eclipse.che.selenium.stack](https://github.com/eclipse/che/blob/master/selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/) packages as well?

**Review by dmytro-ndp — APPROVED** [review]

**Comment by SkorikSergey** [comment]
Selenium tests from https://github.com/eclipse/che/tree/master/selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/refactor package check jdtls initialization. I will update selenium tests from https://github.com/eclipse/che/blob/master/selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/stack/ package.

**Pull request merged**
