### PR TITLE
Add Proxy env variables for workspace containers in Openshift and Kub…

### PR DESCRIPTION
**Pull request by mkuznyetsov**
…ernetes infrastructires

### What does this PR do?
Add provisioning for http_proxy, https_proxy, no_proxy environment variables of workspace containers
in Kubernetes and Openshift deployment/template.

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/10350

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
can you use UPPER_CASE for proxy envs? `HTTP_PROXY`, `HTTPS_PROXY`, `NO_PROXY`

**Review by ghost — APPROVED** [review]

**Review by sleshchenko — APPROVED** [review]
LGTM

**Comment by mkuznyetsov** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/483/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/483//Selenium_tests_report)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10387)
docker image: eclipseche/che-server:10387
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Pull request merged**
