### PR TITLE
CHE-5040:Replace md5 calculation for avoid problem with big files

### PR DESCRIPTION
**Pull request by vparfonov**
Signed-off-by: Vitalii Parfonov <vparfonov@codenvy.com>

### What does this PR do?
Replace md5 calculation for avoid problem with big files

### What issues does this PR fix or reference?
#5040 

#### Changelog
Replace md5 calculation for avoid problem with big files

#### Release Notes
N/A

### CODE REVIEW

**Review by skabashnyuk — APPROVED** [review]

**Comment by benoitf** [comment]
It looks like there is a missing test

**Comment by vparfonov** [comment]
@benoitf I've don't add any new functionality

**Comment by benoitf** [comment]
@vparfonov what is telling me that there is no regression after the change ?

**Comment by vparfonov** [comment]
@benoitf nightly QA circle

**Comment by benoitf** [comment]
integration test is too late and is not appropriate for such things.

**Comment by vparfonov** [comment]
i will test before merge it

**Pull request merged**
