### PR TITLE
[factories] Add support for github PR urls

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
Add support for github Pull Request URLs in factories
pr-link

### What issues does this PR fix or reference?
#11045

#### Release Notes
Add support for github Pull Request URLs for factories

#### Docs PR

Change-Id: I6cd40ee1c620a22eac17dafd12a066a4fa89988b
Signed-off-by: Florent BENOIT <fbenoit@redhat.com>

### CODE REVIEW

**Review by slemeur — APPROVED** [review]
LGTM asap!

**Review by garagatyi — APPROVED** [review]
Cool feature! 
But the support of such a code might be quite nasty. So, I would recommend refactoring this code for simplification.
Apart from that Github may change HTML code of the page, so having static part of the page in the unit tests can be not the best approach. Why not grab pages of real PRs that were closed/merged in addition to the existing unit tests?

**Comment by benoitf** [comment]
not grabbing real page to allow offline tests

**Comment by skabashnyuk** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/758/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/758//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/11123)
docker image: eclipseche/che-server:11123
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Review by skabashnyuk — APPROVED** [review]

**Review by mshaposhnik — APPROVED** [review]

**Pull request merged**
