### PR TITLE
Add ability to fast reveal and collapse resources

### PR DESCRIPTION
**Pull request by RomanNikitenko**
### What does this PR do?
- Rename 'Reveal resource' to 'Reveal in project explorer' action title
- Add hotkeys:
Ctrl+↓ for Reveal in project explorer action
Ctrl+↑ for Collapse All action
- Move 'Reveal resource' action from 'Edit' menu in 'Options'

options
- Add 'Reveal resource' action to editor context menu

editorcontext
- Add 'Collapse All' action to resource context menu

projecttreecontext

### What issues does this PR fix or reference?
#7163 

Signed-off-by: Roman Nikitenko <rnikiten@redhat.com>

### CODE REVIEW

**Comment by RomanNikitenko** [comment]
ci-build

**Comment by RomanNikitenko** [comment]
ci-test

**Review by vparfonov — APPROVED** [review]

**Comment by dkulieshov** [comment]
Hi,

Do we have plans to have macOS hotkeys  for those actions as well?

**Comment by RomanNikitenko** [comment]
@dkuleshov What macOS hotkeys do you prefer for those actions?

**Comment by dkulieshov** [comment]
I personally have no preference over hotkeys for mentioned actions, perhaps you could check if there are hotkeys for such actions in other macOS applications?

**Comment by RomanNikitenko** [comment]
@dkuleshov  As far as I know, for example, Intellij Idea, does not have hotkeys for these actions. So could you, as macOS device owner, say what hotkeys you use or will be convenient for the case

**Comment by dkulieshov** [comment]
I personally don't use those actions and probably I am not that good at UX to give such advices. Moreover I'm not sure if that is indeed needed as at the moment, as far as I know, we do not properly support hotkeys for macOS. I'm just wondering if there are any plans to have those hotkeys for macOS.

**Comment by RomanNikitenko** [comment]
@dkuleshov I think we should investigate what hotkeys will be convenient for macOS users.
Moreover we need to review existed actions and hotkeys for macOS.
In light of the above I think it should be another issue.

**Comment by dkulieshov** [comment]
Also, if my understanding of the action is correct, on my macOS IntelliJ Idea it is called 'Scroll from source' 
scroll_from_source
 and the hotkey is not available by default, moreover in order to set a hotkey for that action there is a [specific](https://plugins.jetbrains.com/plugin/7606-scroll-from-source) plugin.

**Comment by RomanNikitenko** [comment]
@dkuleshov yes, you are right. FYI: this comment https://github.com/eclipse/che/issues/7163#issuecomment-350674862 has reference on discussion about "Scroll from source" feature

**Comment by dkulieshov** [comment]
@RomanNikitenko Understood, so currently we correctly support only hotkeys for Linux class operation systems, while macOS hotkeys need profound revisal, which obviously goes out of the scope of this issue. Thank you 👍

**Comment by dkulieshov** [comment]
> @dkuleshov yes, you are right. FYI: this comment #7163 (comment) has reference on discussion about "Scroll from source" feature

@RomanNikitenko I'm not arguing, mentioned just in case someone is not in a context of this question here.

**Comment by RomanNikitenko** [comment]
@dkuleshov the same from my side, just FYI and 

> in case someone is not in a context of this question here.

**Comment by RomanNikitenko** [comment]
ci-build

**Review by artaleks9 — APPROVED** [review]

**Review by musienko-maxim — APPROVED** [review]

**Pull request merged**
