### PR TITLE
[cli/chedir] Chefile: Add support of docker compose file

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
Adds support of docker compose file in Chefile

### What issues does this PR fix or reference?
#3144 

#### Changelog
Add support of docker compose file in Chefile

**Release Notes**: Add support of docker compose file in Chefile

### Docs Pull Request
Doc is already up-to-date at https://github.com/eclipse/che-docs/blob/master/src/main/_docs/chedir-portable-workspaces/chedir-chefiles.md

Change-Id: I9bd7185cb080ddcf77f609c88fd6531d1c75fac2
Signed-off-by: Florent BENOIT <fbenoit@codenvy.com>

### CODE REVIEW

**Review by slemeur — APPROVED** [review]
Added to RN ok for me

**Review by TylerJewell — APPROVED** [review]

**Comment by TylerJewell** [comment]
Can you paste a sample Chefile that references a dockerfile?  I'd like @JamesDrummond to add it into the docs and maybe we include it in the release notes.  We'll introduce this as a new feature of Chefiles.

**Comment by benoitf** [comment]
@TylerJewell the documentation was already documenting the case but the implementation was not implementing it and there was an example
https://www.eclipse.org/che/docs/chedir/chefiles/index.html

Here is a sample Chefile (the same Java/Mysql docker compose than inside stacks.json but without the extra \n)
```
workspace.runtime.docker.composefile=`services:
 db:
  image: mysql
  environment:
   MYSQL_ROOT_PASSWORD: password
   MYSQL_DATABASE: petclinic
   MYSQL_USER: petclinic
   MYSQL_PASSWORD: password
  mem_limit: 1073741824
 dev-machine:
  image: eclipse/ubuntu_jdk8
  mem_limit: 2147483648
  depends_on:
    - db
`
```

**Comment by TylerJewell** [comment]
Thanks - that is sufficient.  I think we are good here.

**Pull request merged**
