### PR TITLE
Remove npm from native workspace loader build.

### PR DESCRIPTION
**Pull request by qurben**
### What does this PR do?

The workspace loader uses yarn since #10694, but this was not added to
the native build.

Uses npx to not have a dependency on an installed yarn version, specify
the same yarn version as the Dockerfile does.

Signed-off-by: Gerben Oolbekkink <g.j.w.oolbekkink@gmail.com>

### What issues does this PR fix or reference?
N/A

#### Release Notes

N/A

#### Docs PR

N/A

### CODE REVIEW

**Comment by monaka** [comment]
I cherry-picked this and checked on my branch. LGTM.

**Comment by qurben** [comment]
@benoitf @vitaliy-guliy @ashumilova You know more about this right?

**Comment by benoitf** [comment]
ci-build

**Comment by benoitf** [comment]
ci-test

**Review by benoitf — APPROVED** [review]

**Comment by qurben** [comment]
Note that this change is does not influence CI, it only changes the `-Pnative` build of the `workspace-loader` module.

**Comment by benoitf** [comment]
@qurben yes ;-) was just dumb checks :-)

**Comment by benoitf** [comment]
@qurben ci-build check is mandatory to be able to merge the PR

**Comment by dneary** [comment]
Thank you for the change, @qurben!

**Pull request merged**
