### PR TITLE
CHE-9709: fix ability to create a factory from a Git URL

### LINKED ISSUE #9709: It is impossible to create a factory by git URL
### Reproduction Steps
 - Click on the "Factories" button on the dashboard
 - Click on the "Create Factory" button
 - In the opened page click on the "Git" button
 - In the "Git URL" field type link to existing on GitHub project
 - Pay attention that "Create" button is disabled

**Expected behavior:**
Create button is enabled and after clicking on it the factory is created 

**Observed behavior:**
Create button is disabled

**OS and version:**    
Che 6.6.0 ; Chrome 66.0 ; Fedora 25
**Failed selenium test:** CreateFactoryTest

**Attachment:**
eclipse che new factory

**Diagnostics:**

### PR DESCRIPTION
**Pull request by akurinnoy**
### What does this PR do?
This PR fixes the ability to create a factory from a Git URL.

### What issues does this PR fix or reference?
fix #9709

Signed-off-by: Oleksii Kurinnyi <okurinny@redhat.com>

### CODE REVIEW

**Comment by akurinnoy** [comment]
ci-test

**Review by ashumilova — APPROVED** [review]

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/629/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/629//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10843)
docker image: eclipseche/che-server:10843
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by riuvshin** [comment]
ci-test

**Review by olexii4 — APPROVED** [review]

**Review by benoitf — APPROVED** [review]

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/631/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/631//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10843)
docker image: eclipseche/che-server:10843
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by SkorikSergey** [comment]
Selenium tests execution on Eclipse Che Multiuser on OCP (https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/631/) doesn't show any regression against this Pull Request.

**Review by ashumilova — APPROVED** [review]

**Comment by akurinnoy** [comment]
ci-test

**Pull request merged**
