### PR TITLE
Fix latest image tag for release

### PR DESCRIPTION
**Pull request by mkuznyetsov**
Signed-off-by: Mykhailo Kuznietsov <mkuznets@redhat.com>

### What does this PR do?
Fig tagging latest images during release process

### CODE REVIEW

**Review by vparfonov — APPROVED** [review]

**Comment by vparfonov** [comment]
ci-test

**Comment by musienko-maxim** [comment]
ci-test

**Comment by musienko-maxim** [comment]
[ci-test]

**Comment by musienko-maxim** [comment]
ci-build

**Comment by musienko-maxim** [comment]
[ci-build]

**Pull request merged**
