### PR TITLE
chore(happy-path-tests): confirm trust git repository authors when necessary

### PR DESCRIPTION
**Pull request by vitaliy-guliy**
### What does this PR do?
Replies with `Yes, I trust` on a question whether the user trust the repository authors while cloning a project on workspace startup.

### Screenshot/screencast of this PR
Screenshot from 2021-08-30 16-08-22

### What issues does this PR fix or reference?

is needed for https://github.com/eclipse-che/che-theia/pull/1203
to solve https://github.com/eclipse/che/issues/20249

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by dmytro-ndp** [comment]
Happy path tests have passed in related PR https://github.com/eclipse-che/che-theia/pull/1203#issuecomment-908206904

**Review by Ohrimenko1988 — CHANGES_REQUESTED** [review]
The **tests/e2e/pageobjects/ide/plugins/WorkspacePlugin.ts** looks like duplication.
As far as I understood you need to click to "Yes I confirm" button in the notification.
For these purpose use please existing method **"Ide.waitNotificationAndClickOnButton"**.

**Comment by Ohrimenko1988** [comment]
[crw-ci-test]

**Comment by vitaliy-guliy** [comment]
It's kinda circular dependency.

Happy path tests on this PR, that check the notification when cloning the project are failed.

Just because they are using `che-theia:next` editor, which build is temporary broken. So, the latest image of the editor was published around 2 weeks ago and it does not contain yet the notification, added by https://github.com/eclipse-che/che-theia/pull/1203

It's not a problem to wait for fixing the build, but..

Happy path tests for all the PRs into che-theia will always fail. Tests for the PRs will be taken from che/main, which does not contain yet fixes from this PR. But che-theia editor will build from sources taken from the PR to che-theia, where the notification is already present. 

I think we need to broke the circle. Merging of this PR will allow to pass checks on all the PRs to che-theia.

**Review by Ohrimenko1988 — APPROVED** [review]

**Pull request merged**
