### PR TITLE
CRW-2 Should Che depend on the latest...

### PR DESCRIPTION
**Pull request by nickboldt**
Should Che depend on the latest che.ls.jdt.version = 0.0.3-SNAPSHOT ?

Change-Id: I8bbb8264c6f518938be9dec15e5e935b3d56b605
Signed-off-by: nickboldt <nboldt@redhat.com>

### CODE REVIEW

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by tolusha** [comment]
@nickboldt 
It won't be possible to release `eclipse/che` then.

**Comment by riuvshin** [comment]
@nickboldt Since che-ls-jdt has it's own versioning and release cycle we prefer to keep tag in master unless che changes requires SN based version of che-ls-jdt.

**Comment by l0rd** [comment]
@nickboldt is there a particular reason you are requesting this?

**Comment by nickboldt** [comment]
The reason I requested this was so that all the stuff I'm (re)building in Jenkins for CRW can simply pull from master branches to do continuous container builds. 

But if you prefer to use a tag than the branch, that's fine. I've already updated the Jenkinsfile to use 0.0.2 here: 

https://github.com/redhat-developer/codeready-workspaces/blob/master/Jenkinsfile#L92
https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/CRW_CI/view/Pipelines/job/crw_master/
also
https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/CRW_CI/view/Builds/job/eclipse-che-ls-jdt_master/ (from master, not tag 0.0.2)

**Comment by riuvshin** [comment]
this duplicates: https://github.com/eclipse/che/pull/12367

**Pull request closed without merging**
