### PR TITLE
Runtme log metrics

### PR DESCRIPTION
**Pull request by sparkoo**
first review https://github.com/eclipse/che/pull/16210 !

### What does this PR do?
Metrics for runtime log sent messages and bytes

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/16062

20200306_150723_1499x705_scrot

### Docs PR
https://github.com/eclipse/che-docs/pull/1119

### CODE REVIEW

**Review by skabashnyuk — APPROVED** [review]
if graphs have a logical minimum or maximum please don't forget to add it.

**Comment by sparkoo** [comment]
> if graphs have a logical minimum or maximum please don't forget to add it.

I'm not exactly sure what you mean by that.

**Comment by sparkoo** [comment]
ci-build

**Comment by sparkoo** [comment]
[ci-build]

**Comment by sparkoo** [comment]
crw-ci-test

**Comment by sparkoo** [comment]
crw-ci-test

**Comment by sparkoo** [comment]
crw-ci-test

**Comment by sparkoo** [comment]
crw-ci-test

**Comment by sparkoo** [comment]
crw-ci-test

**Comment by sparkoo** [comment]
crw-ci-test

**Review by metlos — APPROVED** [review]

**Pull request merged**
