### PR TITLE
Create workspace from devfile

### PR DESCRIPTION
**Pull request by ashumilova**
Signed-off-by: Anna Shumilova <ashumilo@redhat.com>

### What does this PR do?
Screenshot from 2019-06-04 13-49-00

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/13058
https://github.com/eclipse/che/issues/13354

### CODE REVIEW

**Comment by ashumilova** [comment]
ci-test

**Comment by ashumilova** [comment]
ci-test

**Comment by ashumilova** [comment]
ci-build

**Comment by ashumilova** [comment]
ci-build

**Comment by ashumilova** [comment]
ci-test

**Comment by ashumilova** [comment]
ci-test

**Comment by ashumilova** [comment]
ci-test

**Comment by ashumilova** [comment]
ci-test

**Comment by SkorikSergey** [comment]
ci-test

**Comment by SkorikSergey** [comment]
ci-test

**Review by benoitf — APPROVED** [review]

**Review by akurinnoy — APPROVED** [review]

**Review by sleshchenko — APPROVED** [review]

**Review by olexii4 — APPROVED** [review]

**Pull request merged**
