### PR TITLE
Update testNG to more actual version (7.0.0)

### PR DESCRIPTION
**Pull request by mshaposhnik**
### What does this PR do?
Fixes to update testNG to more actual version (7.0.0)

### CODE REVIEW

**Comment by mshaposhnik** [comment]
ci-test

**Comment by mshaposhnik** [comment]
ci-test

**Comment by mshaposhnik** [comment]
ci-test

**Comment by artaleks9** [comment]
ci-test

**Comment by mshaposhnik** [comment]
ci-test

**Comment by skabashnyuk** [comment]
CC @rhopp @dmytro-ndp

**Review by skabashnyuk — APPROVED** [review]

**Comment by mshaposhnik** [comment]
crw-ci-test

**Review by dmytro-ndp — APPROVED** [review]
Looks good.

**Pull request merged**
