### PR TITLE
Fix DocuementChange event for Orion editor

### PR DESCRIPTION
**Pull request by sunix**
Remove the TODO and fix the event: needed for pair programming demo

### CODE REVIEW

**Comment by skabashnyuk** [comment]
ip-validation  fail

**Comment by sunix** [comment]
i've sign the cla, but the hook doesn't seem to update ... I will try amending

**Comment by TylerJewell** [comment]
It's a bug in GitHub / Eclipse connector.  We can commit anyways.

**Comment by skabashnyuk** [comment]
@vparfonov ?

**Comment by sunix** [comment]
I've fixed the cla issue, it is ready te be merged

**Comment by vparfonov** [comment]
ok

**Pull request merged**
