### PR TITLE
Move dependency management pom to che repo

### LINKED ISSUE #16780: Move dependency management pom to che repo
### Is your task related to a problem? Please describe.
Reduce the time that is needed to have a maven release of che.

### Describe the solution you'd like
Move dependency management pom to che repo. 
Do not release che-parent that often.

### Additional context
we can't deprecate che-parent because che-dashboard and che-loader are continuing to be as maven artifacts and uses it for maven plugin configuration.

### PR DESCRIPTION
**Pull request by skabashnyuk**
### What does this PR do?

Move dependency management pom to che repo

### What issues does this PR fix or reference?
Fixes https://github.com/eclipse/che/issues/16780

### CODE REVIEW

**Review by vparfonov — APPROVED** [review]

**Review by sparkoo — APPROVED** [review]

**Comment by SkorikSergey** [comment]
[ci-test]

**Comment by skabashnyuk** [comment]
crw-ci-test

**Comment by skabashnyuk** [comment]
[crw-ci-test]

**Comment by dmytro-ndp** [comment]
[ci-test]

**Comment by skabashnyuk** [comment]
crw-ci-test

**Review by SkorikSergey — APPROVED** [review]

**Pull request merged**
