### PR TITLE
6.13.1

### PR DESCRIPTION
**Pull request by ibuziuk**
Issue https://github.com/eclipse/che/issues/11860
Service release, cherry-picking commits:
- 9560a437abbc378a0bf0dc5f2e8 #11794
- b5da3f821fd3d2014711f5205c #11840

### CODE REVIEW

**Comment by ibuziuk** [comment]
ci-test

**Review by davidfestal — APPROVED** [review]

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1147/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1147//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11859
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Review by amisevsk — APPROVED** [review]

**Review by garagatyi — APPROVED** [review]

**Comment by riuvshin** [comment]
No need to open PRs like that, I usually cherry-pick manually.

**Comment by riuvshin** [comment]
closing this as I've already cherry-picked these commits

**Pull request closed without merging**
