### PR TITLE
Added JSON-RPC back-end to Project API and removed deprecated VFS classes 

### PR DESCRIPTION
**Pull request by dkulieshov**
Original issue: https://github.com/eclipse/che/issues/6122

### JSON-RPC project API back-end
Added new JSON-RPC back-end and reworked components according to https://github.com/eclipse/che/issues/6219. Back-end is configured by this class: `org.eclipse.che.api.project.server.ProjectJsonRpcServiceConfigurator`
#### Get project
Request example:
```json
{  
   "jsonrpc":"2.0",
   "id":"0",
   "method":"project/get",
   "params":{  
      "wsPath":"/ws/path"
   }
}
```
Response example
```json
{  
   "jsonrpc":"2.0",
   "id":"0",
   "result":{  
      "projectConfigDto":{  

      }
   }
}
```
#### Create project
Request example:
```json
{  
   "jsonrpc":"2.0",
   "id":"0",
   "method":"project/create",
   "params":{  
      "wsPath":"/ws/path",
      "projectConfigDto":{  

      }
   }
}
```
Response example
```json
{  
   "jsonrpc":"2.0",
   "id":"0",
   "result":{  
      "projectConfigDto":{  

      }
   }
}
```
#### Update project
Request example:
```json
{  
   "jsonrpc":"2.0",
   "id":"0",
   "method":"project/update",
   "params":{  
      "wsPath":"/ws/path",
      "projectConfigDto":{  

      }
   }
}
```
Response example
```json
{  
   "jsonrpc":"2.0",
   "id":"0",
   "result":{  
      "projectConfigDto":{  

      }
   }
}
```
#### Delete project
Request example:
```json
{  
   "jsonrpc":"2.0",
   "id":"0",
   "method":"project/delete",
   "params":{  
      "wsPath":"/ws/path"
   }
}
```
Response example
```json
{  
   "jsonrpc":"2.0",
   "id":"0",
   "result":{  
      "projectConfigDto":{  

      }
   }
}
```
#### Recognize project
Request example:
```json
{  
   "jsonrpc":"2.0",
   "id":"0",
   "method":"project/recognize",
   "params":{  
      "wsPath":"/ws/path"
   }
}
```
Response example
```json
{  
   "jsonrpc":"2.0",
   "id":"0",
   "result":[  
      {  
         "type":"type1",
         "matched":true
      },
      {  
         "type":"type2",
         "matched":false
      }
   ]
}
```
#### Verify project
Request example:
```json
{  
   "jsonrpc":"2.0",
   "id":"0",
   "method":"project/verify",
   "params":{  
      "wsPath":"/ws/path",
      "type":"type1"
   }
}
```
Response example
```json
{  
   "jsonrpc":"2.0",
   "id":"0",
   "result": { 
      "sourceEstimation":{ 
         "type":"type1",
         "matched":true
      }
   }
}
```
#### Imort project
Request example:
```json
{  
   "jsonrpc":"2.0",
   "id":"0",
   "method":"project/import",
   "params":{  
      "wsPath":"/ws/path",
      "sourceStorageDto": {

      }
   }
}
```
Response example
```json
{  
   "jsonrpc":"2.0",
   "id":"0",
   "result": { 
      "projectConfigDto":{  

      }
   }
}
```

### Changes to Project Service:
`org.eclipse.che.api.project.server.ProjectService`
- Refactoring and decomposition
- Reworked some places according to new FS API

### Changes to Project Manager:
`org.eclipse.che.api.project.server.ProjectManager`
- Refactoring and decomposition
- Reworked package structure
- Split Guice configuration into several classes
- Reworked architecture (where it is possible) to comply DI pattern

### Changes to VFS
`org.eclipse.che.api.fs.server.FsManager`
- Removed all deprecated VFS related classes
- Rearranged code accordingly
- Provided new FS API where needed

### Changes to Search
`org.eclipse.che.api.search.server.Searcher`
- Reworked index classes that depend on VFS

### Changes to Guice configurations
- File system related (former VFS) stuff moved to a separated module: `org.eclipse.che.api.fs.server.FsApiModule`
- File watcher bindings moved to a separate module: `org.eclipse.che.api.watcher.server.FileWatcherApiModule`
- Created specific module for Searcher configuration: 
`org.eclipse.che.api.search.server.SearchApiModule`
- Project API module cleaned of previously mentioned configurations along with new bindings for `ProjectManager`, `ProjectQualifier` and `ProjectSynchronizer` interfaces

### What is yet to be done:
- [x] Pass selenium tests
- [x] Rework/add unit tests
- [x] Rework/add java docs

### CODE REVIEW

**Comment by benoitf** [comment]
why it's a new PR instead of https://github.com/eclipse/che/pull/6726 ?

**Comment by dkulieshov** [comment]
I have no rights to reopen a PR, so I created a new one

**Comment by dkulieshov** [comment]
ci-test

**Review by vparfonov — APPROVED** [review]

**Review by svor — APPROVED** [review]

**Review by azatsarynnyy — APPROVED** [review]

**Review by RomanNikitenko — APPROVED** [review]

**Review by gazarenkov — APPROVED** [review]

**Comment by dkulieshov** [comment]
ci-test

**Pull request merged**
