### PR TITLE
Update Bitnami stacks to latest versions

### PR DESCRIPTION
**Pull request by amrecio**
### What does this PR do?

Updates the Bitnami Stacks to the latest version. The containers now use Bitnami's own "minideb" image as a base, which reduces the size of the containers in comparison with the previous version.

### What issues does this PR fix or reference?

It doesn't reference an issue.

### New behavior
Bitnami stacks updated to latest version.

Please review [Che's Contributing Guide](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md) for best practices.

### CODE REVIEW

**Comment by benoitf** [comment]
ci-build

**Review by benoitf — APPROVED** [review]

**Comment by slemeur** [comment]
Thanks @amrecio .

We make the default stacks provided by Che allocating 2GB of RAM, this ensure that the workspace's agents that Che is injecting will get enough ressources and the user will get a workspace with decent ressources to work with. 
User still have the ability to change the RAM allocated but by default workspaces are created with 2GB of RAM.

Could you please update your PR?

**Comment by amrecio** [comment]
Of course, no problem. I've update the PR as requested.

Thanks for the clarification.

**Comment by amrecio** [comment]
Would it be possible to update the PR to bump the revision of the Laravel container image? The current one works but it contains an outdated version of MariaDB.

**Comment by slemeur** [comment]
Yes sure @amrecio

**Comment by amrecio** [comment]
Done.

**Review by slemeur — APPROVED** [review]

**Comment by benoitf** [comment]
ci-build

**Pull request merged**
