### PR TITLE
Remove functionality of adding exec agent to workspace configurations

### PR DESCRIPTION
**Pull request by mkuznyetsov**
### What does this PR do?
Remove functionality of exec agent adding to workspaces/stacks, if they had a terminal agent.

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/6784

Removed Exec agent installing to workspaces configurations, when it had a Terminal agent

#### Release Notes

N/A

#### Docs PR

N/A

### CODE REVIEW

**Comment by mkuznyetsov** [comment]
ci-build

**Review by garagatyi — APPROVED** [review]

**Comment by mkuznyetsov** [comment]
ci-test

**Comment by sleshchenko** [comment]
Shouldn't we remove [AddExecAgentInStackFilterTest](https://github.com/eclipse/che/blob/038c14df6afe68358e2a526647ac8ee9e3113ad3/wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/agent/server/filters/AddExecAgentInStackFilterTest.java) and [AddExecAgentInWorkspaceFilterTest](https://github.com/eclipse/che/blob/038c14df6afe68358e2a526647ac8ee9e3113ad3/wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/agent/server/filters/AddExecAgentInWorkspaceFilterTest.java)?

**Review by skabashnyuk — APPROVED** [review]

**Comment by sleshchenko** [comment]
Please remove also commented bindings for removed classes 
https://github.com/eclipse/che/blob/038c14df6afe68358e2a526647ac8ee9e3113ad3/assembly/assembly-wsmaster-war/src/main/java/org/eclipse/che/api/deploy/WsMasterModule.java#L206-L209

**Review by riuvshin — APPROVED** [review]

**Pull request merged**
