### PR TITLE
Update Che 7 stack to support kube as well

### PR DESCRIPTION
**Pull request by l0rd**
What does this PR do?
=====================

Update Che 7 stacks to be consistent with rh-che ones and make use
kubernetes recipe to make it compatible with both OpenShift and Kube.

### CODE REVIEW

**Comment by skabashnyuk** [comment]
ci-test

**Review by benoitf — APPROVED** [review]

**Comment by benoitf** [comment]
I'm still wondering if we need two stacks (it seems confusing for users)

**Comment by l0rd** [comment]
@benoitf the way to address this is to fix https://github.com/eclipse/che/issues/11690 (support for workspaces without a runtime).

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1083/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1083//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11739
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Review by garagatyi — APPROVED** [review]

**Pull request merged**
