### PR TITLE
Java Testing support Bug fixes and Enhancements - Step 2

### PR DESCRIPTION
**Pull request by davidfestal**
### What does this PR do?

This pull request is the second step of the work started in PR https://github.com/eclipse/che/pull/4303.
More precisely:
- it provides a better Test result view that also contains succeeded tests, with a small button to allow filtering successful tests, thus focusing on failures,
- it fixes navigation problems from the test result view to the related source code,
- it fixes the erratic behaviour of the `Test` contextual menu, that sometimes used to hide the project-wide test menu entries for no clear reason.
- it adds a better client-side error notification when an exception is triggered on the server-side during the test execution,   
- it adds the same enhancements / bug fixes to the TestNG testing support.

### What issues does this PR fix or reference?

https://issues.jboss.org/browse/CHE-111

and more precisely the following sub-tasks:

https://issues.jboss.org/browse/CHE-148
https://issues.jboss.org/browse/CHE-149
https://issues.jboss.org/browse/CHE-154
https://issues.jboss.org/browse/CHE-157

#### Changelog

Java Testing support Bug fixes and Enhancements - Step 2

#### Release Notes

Testing support enhancements:
- Faster test execution with on-the-fly project compilation if necessary
- Real-time notification of test execution,
- Better view of the successful tests with a filtering option,
- Navigation from the test view to the source code,

### CODE REVIEW

**Comment by TylerJewell** [comment]
@davidfestal - thank you for the contribution!

I'm thinking about how we get this packaged for marketing and release notes.  We'll need a few things to get this marketing-ready (in addition to the code review of the code itself):
1. Can you do one or more animated gifs that highlight the new features?  This will go into the release notes, into the feature list on www.eclipse.org/che features, and into the docs.  There can be either multiple small ones or one larger one.

2. Can you identify the docs pages from www.eclipse.org/che/docs (if any) that will need to be improved to support this?  Are there instructions needed to make use of the feature?  

3. The release notes wll be more marketing material, so we'll need to extend them to be suitable to be placed into a marketing blog announcing the feature, along with explanation from the docs on how to make use of the feature.

Thanks for this.

**Comment by vparfonov** [comment]
@davidfestal can you resolve conflicts, please?

**Comment by davidfestal** [comment]
I just did it locally today. I'll push very soon.

**Comment by davidfestal** [comment]
@vparfonov done !

**Comment by vparfonov** [comment]
thx @davidfestal, we made QA circle, got some regression so need to fix some Selenium tests. We will merge it next week

**Comment by davidfestal** [comment]
@TylerJewell : let me answer your 3 points:

1. I created 2 animated Gifs that you will find hereafter (If you need a better video quality I can join the original `ogv` videos):

    - The first video shows the very basic use-case of a single class test run, that doesn't even imply automatic compilation of the required sources. We can see the real-time testing output, the test result tree-view with the *Hide successful tests* option, and the way navigation to the source code is fixed.
1-basic-use-case-without-automatic-compilation-because-no-global-maven-build-command-available ogv

    - A second one that shows how, if a *`build`* maven command is found in the available workspace commands, then a *`test-compile`* is created based on the *`build`* command, and run automatically before starting the test session, to ensure that we test up-to-date classes.
2-test-with-automatic-compilation-based-on-the-global-maven-build-command ogv
 
2. I didn't find any doc page that present the Testing feature. I'm not sure it was officially documented until now.

3. Let me know how I can help here.

**Comment by davidfestal** [comment]
@vparfonov Thanks !

**Pull request merged**
