### PR TITLE
Fixes from 3.x

### PR DESCRIPTION
**Pull request by tareksha**
### What does this PR do?

Up-port relevant recent fixes from 3.x
- https://github.com/codenvy/che-core/pull/728
- https://github.com/codenvy/che-core/pull/726
- https://github.com/codenvy/che-core/pull/658
### New Behavior
- A new Guice type converter to java.nio.Path has been added
- DTOs can be created from JsonElement directly now
### Tests written?

Yes
### Docs requirements?

Include the content for all the docs changes required. 
1.  API changes  
2.  User docs changes

### CODE REVIEW

**Comment by tareksha** [comment]
hi @skabashnyuk am I missing something? my user is already registered for CLA

**Comment by TylerJewell** [comment]
The IP validation for Eclipse with Github has never worked for me.  It seems to selectively choose whether or not you have a CLA signed.

**Comment by tareksha** [comment]
@TylerJewell  that's strange because it did pass me when it was enabled in 3.x ...

**Comment by garagatyi** [comment]
LGTM

**Comment by tareksha** [comment]
@garagatyi @skabashnyuk please merge the commits

**Comment by voievodin** [comment]
Good! +1 for these changes

**Pull request merged**
