### PR TITLE
Use the names of the enums instead of their ordinals when storing them to DB

### PR DESCRIPTION
**Pull request by metlos**
### What does this PR do?

This PR changes the way enums listed in the issue #12208 are stored. Previously, the enums were stored using their ordinal values even though the columns were of VARCHAR type. It is generally a safer practice to store enums using their names because then they don't break when the enum is reordered or new enum values added in between existing ones.

### What issues does this PR fix or reference?

#12208 

### Note

This should only be merged after #12177 because it would break its DB upgrade script.

### CODE REVIEW

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by metlos** [comment]
ci-build

**Comment by metlos** [comment]
ci-test

**Comment by metlos** [comment]
thought I'd be able to run the `ci-*` now that I'm a committer :cry:

**Comment by skabashnyuk** [comment]
ci-test

**Review by skabashnyuk — APPROVED** [review]

**Review by sleshchenko — APPROVED** [review]
LGTM

**Comment by metlos** [comment]
ci-build

**Comment by metlos** [comment]
I've marked this as WIP just so that it is not accidentally merged. We will wait with this PR until #12177 is merged, at which point this PR will need to be modified with the actual needed numbering of the upgrade script.

**Pull request merged**
