### PR TITLE
Handle existed node in tree in case if explorer receives create event

### PR DESCRIPTION
**Pull request by vzhukovs**
### What does this PR do?
This changes proposal fixes the problem when disabling option "Show Artifact Id in Project Explorer" from maven preferences didn't hide the actual artifact id from the project title. 

Signed-off-by: Vladyslav Zhukovskyi <vzhukovs@redhat.com>

### What issues does this PR fix or reference?
#8113 

#### Release Notes
N/A

#### Docs PR
N/A

### CODE REVIEW

**Comment by vzhukovskii** [comment]
ci-test

**Comment by vzhukovskii** [comment]
ci-test

**Comment by vzhukovs** [comment]
ci-test

**Comment by vzhukovs** [comment]
ci-test

**Review by ashumilova — APPROVED** [review]

**Review by Ohrimenko1988 — APPROVED** [review]

**Pull request merged**
