### PR TITLE
Add CentOS based Golang stack to default assembly

### PR DESCRIPTION
**Pull request by dharmit**
Signed-off-by: Dharmit Shah <dshah@redhat.com>

### What does this PR do?
Adds CentOS based Golang stacks to default assembly

#### Changelog

Golang stack based on CentOS added to the default assembly

#### Release Notes

Added Golang stack based on CentOS added to the default assembly

cc: @l0rd

### CODE REVIEW

**Comment by dharmit** [comment]
I had this stack working OK some time back. But lately I'm seeing errors after spinning up a workspace from the stack.

The dashboard complains: `Unable to initialize IDE`.

And the container logs complain that it's unable to find the `che-stacks/centos-go` image. Why is it trying to use that image is not entirely sure to me. But I tried changing the image to `dharmit/centos-go` to use one from Docker hub. That didn't help either:
```
2017-06-06 14:35:36,680[nio-8080-exec-6]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 897]    - Workspace 'che/wksp-60gj' with id 'workspace00hdbuz1a9q3nibf' created by user 'che'
2017-06-06 14:36:25,663[aceSharedPool-2]  [WARN ] [.e.c.p.d.m.MachineProviderImpl 557]  - Failed to check image che-stacks/centos-go availability. Cause: Error response from docker API, status: 500, message: Invalid filter 'reference'
org.eclipse.che.plugin.docker.client.exception.DockerException: Error response from docker API, status: 500, message: Invalid filter 'reference'
        at org.eclipse.che.plugin.docker.client.DockerConnector.getDockerException(DockerConnector.java:1368)
        at org.eclipse.che.plugin.docker.client.DockerConnector.listImages(DockerConnector.java:230)
        at org.eclipse.che.plugin.docker.machine.MachineProviderImpl.isDockerImageExistLocally(MachineProviderImpl.java:553)
        at org.eclipse.che.plugin.docker.machine.MachineProviderImpl.pullImage(MachineProviderImpl.java:523)
        at org.eclipse.che.plugin.docker.machine.MachineProviderImpl.prepareImage(MachineProviderImpl.java:439)
        at org.eclipse.che.plugin.docker.machine.MachineProviderImpl.startService(MachineProviderImpl.java:334)
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.lambda$startEnvironmentQueue$6(CheEnvironmentEngine.java:785)
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startInstance(CheEnvironmentEngine.java:949)
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.startEnvironmentQueue(CheEnvironmentEngine.java:813)
        at org.eclipse.che.api.environment.server.CheEnvironmentEngine.start(CheEnvironmentEngine.java:268)
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.startEnvironmentAndPublishEvents(WorkspaceRuntimes.java:712)
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes.access$100(WorkspaceRuntimes.java:106)
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:977)
        at org.eclipse.che.api.workspace.server.WorkspaceRuntimes$StartTask.call(WorkspaceRuntimes.java:941)
        at org.eclipse.che.commons.lang.concurrent.CopyThreadLocalCallable.call(CopyThreadLocalCallable.java:30)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2017-06-06 14:36:30,158[aceSharedPool-2]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 692]   - Launching 'org.eclipse.che.exec' agent at workspace workspace00hdbuz1a9q3nibf
2017-06-06 14:36:32,753[aceSharedPool-2]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 692]   - Launching 'org.eclipse.che.terminal' agent at workspace workspace00hdbuz1a9q3nibf
2017-06-06 14:36:35,010[aceSharedPool-2]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 692]   - Launching 'org.eclipse.che.ws-agent' agent at workspace workspace00hdbuz1a9q3nibf
2017-06-06 14:38:43,209[aceSharedPool-2]  [INFO ] [o.e.c.a.w.s.WorkspaceRuntimes 692]   - Launching 'org.eclipse.che.ssh' agent at workspace workspace00hdbuz1a9q3nibf
2017-06-06 14:38:43,215[aceSharedPool-2]  [INFO ] [o.e.c.a.w.s.WorkspaceManager 757]    - Workspace 'che/wksp-60gj' with id 'workspace00hdbuz1a9q3nibf' started by user 'che'
```

Please let me know if I should open this as an issue instead and close this PR.

**Comment by ghost** [comment]
@dharmit I have tested this stack and it just worked for me. The only thing that I'd add is openjdk package, so that it's not downloaded every time a workspace starts.

**Comment by dharmit** [comment]
@eivantsov Thanks for your confirmation! I've added the `openjdk` devel package like we've done for all other images based on CentOS. You can refer the PR (https://github.com/eclipse/che-dockerfiles/pull/91) on che-dockerfiles repo.

**Review by l0rd — APPROVED** [review]
LGTM

**Comment by benoitf** [comment]
ci-build

**Review by benoitf — APPROVED** [review]

**Comment by benoitf** [comment]
@dharmit it requires a rebase to merge the PR

**Review by slemeur — APPROVED** [review]

**Comment by benoitf** [comment]
@dharmit ?

**Comment by dharmit** [comment]
@benoitf done. Sorry, I completely missed the notification for this.

**Pull request merged**
