### PR TITLE
CHE-434: improve experience to create a new project in an existing wo…

### PR DESCRIPTION
**Pull request by olexii4**
**_2 Upvotes**_ @ashumilova  WDYT?
selection_029
…rkspace

Signed-off-by: Oleksii Orel oorel@codenvy.com

### CODE REVIEW

**Comment by ashumilova** [comment]
Workspace "test" is not detected as selected, though is highlighted
selected_workspace

**Comment by ashumilova** [comment]
perhaps need to mark the stack of the workspace near workspace name (e.g. "Workspace1 (Stack: nodejs)" or separate column: Worskace1       nodejs stack)

**Comment by ashumilova** [comment]
when I choose existing workspace - the flow anyway tries to create new workspace with same name

**Comment by ashumilova** [comment]
Sample is not pre-selected on existing workspace selected:
selected_sample

**Comment by ashumilova** [comment]
+1 tested - works (one more issue added https://jira.codenvycorp.com/browse/CHE-881)

**Comment by akurinnoy** [comment]
+1

**Pull request merged**
