### PR TITLE
[WIP] Upgrade npm packages in dashboard.

### PR DESCRIPTION
**Pull request by monaka**
### What does this PR do?

Upgrades versions of node packages used in Dashboard.
The patches should be passed Eclipse CQ. (please see each commit log also)

### What issues does this PR fix or reference?

none.

### CODE REVIEW

**Comment by musienko-maxim** [comment]
Can one of the admins verify this PR?

**Review by benoitf — CHANGES_REQUESTED** [review]
missing CQs for updating direct dependencies
and missing CQ for new dev dependencies (like eslint)

**Comment by l0rd** [comment]
Beyond the CQs issue we cannot merge this before the GA release

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by l0rd** [comment]
Removing `do-not-merge/hold`. @monaka can you rebase please? What's the status of the CQs?

**Comment by monaka** [comment]
I rebased this. And some issues may be fixed by #14313. So I set `WIP` to this PR for now. This will be back after #14313 was merged.

**Comment by monaka** [comment]
I close it as it's too old.

**Pull request closed without merging**
