### PR TITLE
Don't register application id on ws agent

### PR DESCRIPTION
**Pull request by vzhukovs**
### What does this PR do?
Do not register websocket application id on workspace agent.

Signed-off-by: Vladyslav Zhukovskyi <vzhukovs@redhat.com>

### What issues does this PR fix or reference?
#10241 

#### Release Notes
N/A

#### Docs PR
N/A

### CODE REVIEW

**Comment by vzhukovskii** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/528/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/528//Selenium_tests_report)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10570)
docker image: eclipseche/che-server:10570
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/529/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/529//Selenium_tests_report)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10570)
docker image: eclipseche/che-server:10570
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by musienko-maxim** [comment]
In the functionality which is covered by selenium tests - new regression was not found

**Review by musienko-maxim — APPROVED** [review]

**Review by dkulieshov — APPROVED** [review]

**Review by vparfonov — APPROVED** [review]

**Pull request merged**
