### PR TITLE
Switch java selenium tests and typscript tests to test Che with TLS support

### PR DESCRIPTION
**Pull request by dmytro-ndp**
### What does this PR do?
After recent changes in che-operator Eclipse Che Operator installs Che with TLS support by default.
So we need to fix E2E _java selenium tests_ and _typescript selenium tests_ on ci.centos.org to be run against Eclipse Che with TLS support.

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/16299

### CODE REVIEW

**Review by rhopp — APPROVED** [review]

**Comment by dmytro-ndp** [comment]
[ci-test]

**Comment by dmytro-ndp** [comment]
[ci-test]

**Comment by dmytro-ndp** [comment]
[ci-test]

**Review by SkorikSergey — APPROVED** [review]

**Comment by dmytro-ndp** [comment]
[ci-test]

**Comment by dmytro-ndp** [comment]
crw-ci-test

**Pull request closed without merging**
