### PR TITLE
Change the default jwtproxy image to the latest one.

### PR DESCRIPTION
**Pull request by metlos**
### What does this PR do?
Changes the default jwtproxy image to the latest released.

This is only a temporary solution that we put in place to have something working before we employ a more complete solution that will be part of the re-opened #15651.

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/16112

### CODE REVIEW

**Review by ibuziuk — APPROVED** [review]

**Comment by Ohrimenko1988** [comment]
[ci-test]

**Comment by skabashnyuk** [comment]
[ci-test]

**Comment by skabashnyuk** [comment]
[ci-build]

**Comment by skabashnyuk** [comment]
[ci-test]

**Comment by ibuziuk** [comment]
@metlos do you plan to apply the same fix to 7.9.x?

**Comment by metlos** [comment]
I do, we're just waiting for a successful CI pass..

**Comment by metlos** [comment]
ci-test

**Comment by metlos** [comment]
[ci-test]

**Comment by SkorikSergey** [comment]
[ci-build]

**Pull request merged**
