### PR TITLE
expose endpoints with "requireSubdomain" attribute on subdomain with single-host

### PR DESCRIPTION
**Pull request by sparkoo**
Signed-off-by: Michal Vala <mvala@redhat.com>

### What does this PR do?
Allows endpoints to be forcefully exposed on subdomain in single-host mode. It's done by endpoint attribute `forceSubdomain` set to `true`.

Technically, I've only changed the internal `devfileEndpoint` attribute name to `forceSubdomain`, so it make more sense on plugins endpoints.

:question: opinions about `requireSubdomain` endpoint attribute name?

### What issues does this PR fix or reference?

https://github.com/eclipse/che/issues/18001
docs PR: https://github.com/eclipse/che-docs/pull/1623

### How to test this PR?

```
metadata:
  name: golang-lo30l
attributes:
  persistVolumes: 'false'
projects:
  - name: example
    source:
      location: 'https://github.com/golang/example.git'
      type: git
    clonePath: src/github.com/golang/example/
components:
  - type: cheEditor
    reference: >-
      https://gist.githubusercontent.com/sparkoo/9d5766be0fab04bb78bb2e8220cea82b/raw/b6134f24232e927f7ec06c4d7b374abe3eec895f/meta.yaml
    alias: mayteja
  - id: golang/go/latest
    memoryLimit: 512Mi
    preferences:
      go.lintTool: golangci-lint
      go.useLanguageServer: true
      go.lintFlags: '--fast'
    type: chePlugin
    alias: go-plugin
    env:
      - value: 'off'
        name: GO111MODULE
  - mountSources: true
    memoryLimit: 2Gi
    type: dockerimage
    image: 'quay.io/eclipse/che-golang-1.14:nightly'
    alias: go-cli
    env:
      - value: $(CHE_PROJECTS_ROOT)
        name: GOPATH
      - value: /tmp/.cache
        name: GOCACHE
apiVersion: 1.0.0
commands:
  - name: 1.1 Run outyet
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/src/github.com/golang/example/outyet'
        type: exec
        command: go get -d && go run main.go
        component: go-cli
  - name: 1.2 Stop outyet
    actions:
      - type: exec
        command: kill $(pidof go)
        component: go-cli
```
1. run Che in single-host mode
1. the devfile above has cheTheia with 13131 endpoint having `forceSubdomain:true` and the project is our go sample, but without specified 8080 endpoint
1. run the `Run outyet`, the port 8080 will get automatically mapped into theia port 13131
1. open the preview in another browser tab
1. see the app working and see it's on subdomain
1. you can open other theia ports, to see they're still on subpaths

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Review by mshaposhnik — APPROVED** [review]

**Comment by sparkoo** [comment]
ci-build

**Comment by sparkoo** [comment]
[ci-build]

**Comment by sparkoo** [comment]
[ci-build]

**Comment by sparkoo** [comment]
[ci-build]

**Comment by sparkoo** [comment]
[ci-build]

**Review by skabashnyuk — APPROVED** [review]

**Pull request merged**
