### PR TITLE
Updated: Set parent to a a new 7.15.0-SNAPSHOT version

### PR DESCRIPTION
**Pull request by mkuznyetsov**
Signed-off-by: Mykhailo Kuznietsov <mkuznets@redhat.com>

### What does this PR do?
Updated: Set parent to upcoming 7.15.0-SNAPSHOT version

### CODE REVIEW

**Comment by skabashnyuk** [comment]
Can you set to 7.15-snapshot. I want to add some changes https://github.com/eclipse/che-parent/pull/171 in next version.

**Review by skabashnyuk — APPROVED** [review]

**Review by vparfonov — APPROVED** [review]

**Comment by mkuznyetsov** [comment]
[ci-build]

**Comment by mkuznyetsov** [comment]
[ci-test]

**Comment by mkuznyetsov** [comment]
[ci-build]

**Comment by mkuznyetsov** [comment]
[ci-test]

**Pull request merged**
