### PR TITLE
Add selenium tests

### PR DESCRIPTION
**Pull request by tolusha**
Introduces selenium tests for Eclipse Che project (an issue https://github.com/codenvy/qa/issues/978).

CQ For Selenium source code: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=13952

### CODE REVIEW

**Comment by tolusha** [comment]
ci-build

**Comment by riuvshin** [comment]
ci-build

**Comment by tolusha** [comment]
ci-build

**Review by skabashnyuk — APPROVED** [review]

**Comment by gorkem** [comment]
To clarify this is both the test cases and selenium driver for Che included in the same commit?

**Comment by tolusha** [comment]
@gorkem Just test cases

**Pull request merged**
