### PR TITLE
CHE-12063: Fix WorkspaceLoader hanging when Che Server is unreachable

### PR DESCRIPTION
**Pull request by AndrienkoAleksandr**
### What does this PR do?
Fix WorkspaceLoader hanging when Che Server is unreachable

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/12063

Signed-off-by: Oleksandr Andriienko <oandriie@redhat.com>

### CODE REVIEW

**Review by evidolob — APPROVED** [review]

**Review by akurinnoy — APPROVED** [review]

**Review by mmorhun — APPROVED** [review]

**Comment by AndrienkoAleksandr** [comment]
ci-test

**Comment by AndrienkoAleksandr** [comment]
ci-test

**Comment by AndrienkoAleksandr** [comment]
@riuvshin Could You help, something wrong with permissions?

**Comment by SkorikSergey** [comment]
che-test-ci

**Comment by SkorikSergey** [comment]
ci-test

**Comment by SkorikSergey** [comment]
ci-test

**Comment by SkorikSergey** [comment]
Selenium tests execution on Eclipse Che Multiuser on OCP (https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1770//Selenium_20tests_20report/) doesn't show any regression against this Pull Request.

**Comment by AndrienkoAleksandr** [comment]
@SkorikSergey Thanks a lot!

**Pull request merged**
