### PR TITLE
Fire ProjectCreatedEvent on importProject

### PR DESCRIPTION
**Pull request by vparfonov**
Signed-off-by: Vitalii Parfonov <vparfonov@redhat.com>

### What does this PR do?
Fire ProjectCreatedEvent on importProject and during setting ProjectConfiguration firstly 

### What issues does this PR fix or reference?
#9924

### CODE REVIEW

**Comment by vparfonov** [comment]
ci-test

**Review by tsmaeder — CHANGES_REQUESTED** [review]
This PR does not cover the case of importZip, which is used for Selenium tests.

**Review by dkulieshov — APPROVED** [review]

**Comment by vparfonov** [comment]
@tsmaeder In case importZip we don't create Project in ProjectRegistry so fire event in this case no reason

**Comment by dkuleshov** [comment]
@tsmaeder 

> This PR does not cover the case of importZip, which is used for Selenium tests.

It is expected behavior, according to [this comment](https://github.com/eclipse/che/issues/9924#issuecomment-395003908), specifically
> In case of just creating folder in the projects root - configuration is not assigned explicitly => Project even is not fired.

**Comment by tsmaeder** [comment]
Yes, but a project appears in the navigator without a ProjectCreatedEvent ever being sent. Without the event being sent, I cannot tell jdt.ls to look at the project.
Perhaps just listening to file system events is the way to go for jdt.ls and to completely ignore che projects, but then we'll get into situations where what che thinks is a project and what jdt.ls thinks is a project will be different. The will be no fun to debug.

**Comment by vparfonov** [comment]
ok, got it. Looks like you are right

**Comment by dkuleshov** [comment]
@tsmaeder I think I understand what you mean. Just to be sure that we're on the same wave. We consider that the project is created **only** when corresponding configuration is added to project config registry. In other words when a folder is created/archive is unpacked in the projects' root we don't consider it as a project until its configuration is added.

For the case that you mentioned (selenium tests) they basically do two things: they unzip a folder and add a project configuration via `updateProject` API call. So you're right that the problem exists, however the problem is not that `importZip` API call does not publish an event, the problem is that when we add a project config with `updateProject` API call we do not publish project created event. 

So, eventually there are two bugs: 
- no `ProjectCreatedEvent` on project import 
- no `ProjectCreatedEvent` on project update, when we add new configuration

I also think that your suggestion to move project related events on a separate abstraction level to avoid event micromanagement and all related errors sounds good.

**Review by tsmaeder — APPROVED** [review]

**Pull request merged**
