### PR TITLE
Update Deployments yamls in helm charts to be compatible with k8s v1.16

### PR DESCRIPTION
**Pull request by l0rd**
### What does this PR do?

Update Helm charts deployments yamls because otherwise Che deployment fails on latest
version of Kubernetes.

### What issues does this PR fix or reference?

https://github.com/eclipse/che/issues/14697

### CODE REVIEW

**Review by sleshchenko — APPROVED** [review]
LGTM

Do you test if on K8s < v1.16
Are these changes compatible?

**Comment by l0rd** [comment]
ci-test

**Comment by l0rd** [comment]
@eclipse/eclipse-che-qa can you please review why PR check is failing?

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by Kenzim** [comment]
now that this has been merged, is there anything else i have to do? i have been trying to deploy this for a few days using the kubernetes tutorial but to no avail. i keep getting this error. any help would be greatly appreciated. thanks

**Comment by l0rd** [comment]
@Kenzim that's available in the nightly build not in the latest stable version of Che yet. Can you be more precise about how you are trying to deploy Che?

**Comment by Kenzim** [comment]
I just followed kubernetes tutorial, installed on a ubuntu vps, installed
helm tiller all that, and then am using chectl to start multi user instance.
thanks for reply.

**Comment by l0rd** [comment]
You can try to use chectl `next` channel instead of stable one:

```
chectl update next
```

If that doesn't work please open an issue of type `bug` providing all the informations required in the bug form that will help us to analyse your problem.

**Pull request merged**
