### PR TITLE
Fix LanguageServerException message for CSharp LS

### PR DESCRIPTION
**Pull request by xcoulon**
### What does this PR do?

Fix the message in the LanguageServerException for the CSharp LS (was referring to JSON)
### Previous behavior

(Remove this section if not relevant)
### New behavior

(Explain the PR as it should appear in the release notes)
### PR type
- [ ] Minor change = no change to existing features or docs
- [ ] Major change = changes existing features or docs
### Minor change checklist
- [ ] New API required?
- [ ] API updated
- [ ] Tests provided / updated
- [ ] Tests passed
### Major change checklist
- [ ] New API required?
- [ ] API updated
- [ ] Documentation provided (include here or link to docs)
- [ ] Tests provided / updated
- [ ] Tests passed

Please review [Che's Contributing Guide](https://github.com/eclipse/che/CONTRIBUTING.MD) for best practices.

Signed-off-by: Xavier Coulon xcoulon@redhat.com

### CODE REVIEW

**Comment by xcoulon** [comment]
@tolusha may I ask why the PR was closed but not merged ? AFAICS, the problem still exists on `master` branch: https://github.com/eclipse/che/blob/master/plugins/plugin-languageserver/che-plugin-languageserver-server/src/main/java/org/eclipse/che/plugin/languageserver/server/launcher/CSharpLanguageServerLauncher.java#L61

**Comment by tolusha** [comment]
@xcoulon 
Hello it seems Github automatically closed the PR when I merged and deleted `language-server` branch. Pls reopen a new one to `master` branch.

**Comment by xcoulon** [comment]
ok, sure.

**Comment by xcoulon** [comment]
@tolusha here you are: https://github.com/eclipse/che/pull/2532

**Pull request closed without merging**
