### PR TITLE
Adapt project selector widget to manage projects from devfile

### PR DESCRIPTION
**Pull request by ashumilova**
Signed-off-by: Anna Shumilova <ashumilo@redhat.com>

### What does this PR do?
Changes for projects selector widget:
- Removes Blank + Zip tas
- Displays added projects from devfile
- Samples content are provided from devfile
- Avoid usage samples.json
- Remove projects description

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/13678
https://github.com/eclipse/che/issues/13665

### CODE REVIEW

**Comment by ashumilova** [comment]
ci-test

**Review by akurinnoy — APPROVED** [review]

**Review by olexii4 — APPROVED** [review]

**Comment by monaka** [comment]
I cherry-picked it and checked on my instance. It works fine. cool.

**Review by rhopp — APPROVED** [review]
Yep... I've tried that too locally and LGTM. 
`crw-ci-e2e-happy-path-test` failure is unrelated.

**Comment by ashumilova** [comment]
@monaka and @rhopp thank you for trying and the feedbacks.

**Pull request merged**
