### PR TITLE
Set Y axis unit to none

### PR DESCRIPTION
**Pull request by tomgeorge**
Signed-off-by: Tom George <tg82490@gmail.com>

### What does this PR do?
Sets unit to none to properly show # of users/ # of workspaces

### What issues does this PR fix or reference?
#14681

### CODE REVIEW

**Comment by tomgeorge** [comment]
cc @ibuziuk @amisevsk

**Comment by skabashnyuk** [comment]
Can you provide a screenshot of the result and explain the motivation of this change?

**Review by amisevsk — APPROVED** [review]

**Review by amisevsk — COMMENTED** [review]
One comment (not sure if it's because I'm playing with the plots in the web UI) but the legend at the bottom of the plot still shows numbers in short form -- could you double check that this PR address that as well?

**Comment by amisevsk** [comment]
@skabashnyuk the issue https://coreos.slack.com/archives/CJP2KF717/p1569518392255600

**Review by skabashnyuk — APPROVED** [review]

**Comment by tomgeorge** [comment]
@amisevsk setting the unit to `none` seems to also affect the way it is displayed in the Legend.

**Review by ibuziuk — APPROVED** [review]

**Comment by skabashnyuk** [comment]
> Would a blurred image be clear enough to accept that the change had the intended result.

Sounds like we are missing some tooling. Let's think about how next time to testing without production.

**Review by ScrewTSW — APPROVED** [review]

**Comment by amisevsk** [comment]
ci-build

**Pull request merged**
