### PR TITLE
Update theia dev stack to use latest dev image.

### PR DESCRIPTION
**Pull request by AndrienkoAleksandr**
### What does this PR do?
Update theia dev stack to use latest dev image.

Signed-off-by: Oleksandr Andriienko <oandriie@redhat.com>

### CODE REVIEW

**Review by benoitf — APPROVED** [review]

**Comment by benoitf** [comment]
FYI build is failing

**Comment by monaka** [comment]
@benoitf Looks CI server side issue. https://ci.codenvycorp.com/job/che-pullrequests-build/6592/org.eclipse.che$exec-agent/console

**Review by mmorhun — APPROVED** [review]

**Review by ashumilova — APPROVED** [review]

**Comment by musienko-maxim** [comment]
ci-test

**Comment by SkorikSergey** [comment]
Selenium tests execution on Eclipse Che Multiuser on OCP (https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1777//Selenium_20tests_20report/) doesn't show any regression against this Pull Request.

**Comment by AndrienkoAleksandr** [comment]
Thanks a lot @SkorikSergey

**Pull request merged**
