### PR TITLE
[ TS_SELENIUM ] Use 80.0 Chrome driver in typescript selenium tests

### PR DESCRIPTION
**Pull request by Ohrimenko1988**
Signed-off-by: Ihor Okhrimenko <iokhrime@redhat.com>

### What does this PR do?
Use 80.0 Chrome driver in typescript selenium tests

### What issues does this PR fix or reference?
Issue: https://github.com/eclipse/che/issues/16090

### CODE REVIEW

**Comment by Ohrimenko1988** [comment]
CQ for new chrome version https://dev.eclipse.org/ipzilla/show_bug.cgi?id=21709

**Review by rhopp — APPROVED** [review]

**Review by musienko-maxim — APPROVED** [review]

**Review by dmytro-ndp — APPROVED** [review]

**Comment by SkorikSergey** [comment]
[ci-build]

**Comment by SkorikSergey** [comment]
ci-build

**Comment by SkorikSergey** [comment]
[ci-build]

**Pull request merged**
