### PR TITLE
Fixed code monospaced text in container location variable

### PR DESCRIPTION
**Pull request by mavimo**
### What does this PR do?
Fix a typo in docs

### Previous behavior
Variable is not correctly formatted on docs

### New behavior
Variable is correctly formatted on docs

### CODE REVIEW

**Comment by TylerJewell** [comment]
@mavimo - Thanks for getting involved and making a contribution.  Two things for you:
1) Can you confirm that you have filed an Eclipse CLA?  We need that for any contributions as it is how we verify IP integrity with the foundation.

2) You would not have known, but we are in the process of moving the docs from this repository into "github.com/eclipse/che-docs". The *actual* docs which are newer than these docs are currently staged at https://github.com/codenvy/che-docs until the Eclipse Foundation gives us the new repository. Anyways, can you duplicate this PR against that repository, as that is the latest version of the docs, and these are out of date - about to be removed.  Sorry for the one-time inconvenience.

**Comment by mavimo** [comment]
@TylerJewell 
1. Yes, I signed the CLA
2. Ok, I'll duplicate the PR if needed

**Comment by mavimo** [comment]
@TylerJewell PR done https://github.com/codenvy/che-docs/pull/14

**Comment by benoitf** [comment]
closing the PR as it has been merged in correct repository with https://github.com/codenvy/che-docs/pull/14

**Pull request closed without merging**
