### PR TITLE
Selenium: Change the wait timeout in the 'Menu' to increase stability selenium tests

### PR DESCRIPTION
**Pull request by artaleks9**
### What does this PR do?
* Change the wait timeout from 5 sec to 10 sec in the _Menu_ page object to increase stability selenium tests
* This has to help to achieve a stability of tests

### What issues does this PR fix or reference?
#10130

### CODE REVIEW

**Comment by artaleks9** [comment]
ci-test

**Review by SkorikSergey — APPROVED** [review]

**Comment by artaleks9** [comment]
Need to do running of test suite as minim two or three times, that be sure in the positive result.

**Comment by artaleks9** [comment]
ci-test

**Comment by artaleks9** [comment]
ci-test

**Review by dmytro-ndp — APPROVED** [review]

**Pull request merged**
