### PR TITLE
Add Che7 Go stack and samples

### PR DESCRIPTION
**Pull request by tolusha**
### What does this PR do?
Adds Che 7 Go stack and samples.

https://revel.github.io/examples/chat.html
Doesn't work due to errors
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x61937d]

goroutine 1 [running]:
github.com/revel/cmd/utils.FindSrcPaths(0xc42002211d, 0x21, 0x8b5c68, 0x16, 0x0, 0x0, 0x0, 0x7edba0, 0xc42006dcc0, 0xc420083c48, ...)
	/home/tolusha/gocode/src/github.com/revel/cmd/utils/file.go:358 +0x51d
github.com/revel/cmd/model.(*CommandConfig).SetVersions(0xc420168000, 0x8b47e0, 0x14)
	/home/tolusha/gocode/src/github.com/revel/cmd/model/command_config.go:301 +0xaa
github.com/revel/cmd/model.(*CommandConfig).UpdateImportPath(0xc420168000, 0x3a, 0x2)
	/home/tolusha/gocode/src/github.com/revel/cmd/model/command_config.go:154 +0x98f
main.main()
	/home/tolusha/gocode/src/github.com/revel/cmd/revel/revel.go:94 +0x164
```

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/13098
https://github.com/eclipse/che/issues/12620

### CODE REVIEW

**Comment by tolusha** [comment]
ci-test

**Comment by tolusha** [comment]
ci-test

**Comment by tolusha** [comment]
ci-test

**Comment by tolusha** [comment]
ci-test

**Comment by tolusha** [comment]
ci-test

**Review by l0rd — APPROVED** [review]

**Comment by l0rd** [comment]
@tolusha are you able to run https://revel.github.io/examples/chat.html locally? Can it be a memory size issue?

**Comment by tolusha** [comment]
@l0rd It doesn't work locally as well

**Pull request merged**
