### PR TITLE
Code cleanup

### PR DESCRIPTION
**Pull request by alexVengrovsk**
Signed-off-by: alextrentton@gmail.com

This is a light version of the [PR #1170](https://github.com/eclipse/che/pull/1170/files).

### CODE REVIEW

**Comment by garagatyi** [comment]
test this please

**Comment by garagatyi** [comment]
@alexVengrovsk it is command to Jenkins PR builder, ignore it

**Comment by garagatyi** [comment]
ci-build

**Comment by alexVengrovsk** [comment]
@garagatyi Would you please help me to understend what I am doing wrong. This PR contains changes for \core\ide\che-core-ide-generators. I have run `mvn clean install` for Che Core :: IDE :: Generators on my side after all chenges and got `BUILD SUCCESS`. I thought that all maven projects are isolated, but when Jenkins tried to make a build it ended up as [unstable](http://ci.codenvy-dev.com/jenkins/job/che-pullrequests-build/448/). And the interesting part is - all unstability came from [Che Plugin :: Maven :: Extension Maven Server](http://ci.codenvy-dev.com/jenkins/job/che-pullrequests-build/448/org.eclipse.che.plugin$che-plugin-maven-server/). I was confused and run `mvn clean install` for Che Plugin :: Maven :: Extension Maven Server on my side and the result was `BUILD SUCCESS`. So, why it is unstable in Jenkins?

**Comment by garagatyi** [comment]
@alexVengrovsk I do believe that we have problem with tests of maven plugin. I had the same situation several times

**Comment by garagatyi** [comment]
LGTM
@skabashnyuk Please take a look

**Pull request merged**
