### PR TITLE
Use proxy forwarding

### PR DESCRIPTION
**Pull request by ghost**
### What does this PR do?

Sets `PROXY_ADDRESS_FORWARDING` to true, to make sure the right protocol is used in all Keycloak pages

### What issues does this PR fix or reference?

https://github.com/eclipse/che/issues/10924

### CODE REVIEW

**Comment by eivantsov** [comment]
ci-test

**Review by l0rd — APPROVED** [review]

**Review by garagatyi — APPROVED** [review]

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/761/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/761//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/11137)
docker image: eclipseche/che-server:11137
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by eivantsov** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/766/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/766//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/11137)
docker image: eclipseche/che-server:11137
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by eivantsov** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/781/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/781//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/11137)
docker image: eclipseche/che-server:11137
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by eivantsov** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/783/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/783//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/11137)
docker image: eclipseche/che-server:11137
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by eivantsov** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/785/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/785//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11137
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by eivantsov** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/787/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/787//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11137
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by eivantsov** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/788/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/788//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11137
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by monaka** [comment]
@eivantsov  Why is this PR left? I've not tested this because I don't use Openshift.
But this will be strongly required on the plain Kubernetes.
I think Openshift also.

**Pull request merged**
