### PR TITLE
Fix improperly editor behavior when in debug mode

### PR DESCRIPTION
**Pull request by azatsarynnyy**
Signed-off-by: Artem Zatsarynnyi <azatsary@redhat.com>

### What does this PR do?
Fixes improperly editor behavior when in debug mode.

### What issues does this PR fix or reference?
#11398

### CODE REVIEW

**Comment by azatsarynnyy** [comment]
ci-test

**Comment by azatsarynnyy** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1024/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1024//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11672
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Review by vparfonov — APPROVED** [review]

**Review by vparfonov — APPROVED** [review]

**Review by vparfonov — APPROVED** [review]

**Comment by artaleks9** [comment]
Selenium tests execution on Eclipse Che Multiuser on OCP (https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1024/) doesn't show any regression against this Pull Request.

**Pull request merged**
