### PR TITLE
upgrade angular version to 1.7.9

### PR DESCRIPTION
**Pull request by olexii4**
Signed-off-by: Oleksii Orel <oorel@redhat.com>

### What does this PR do?
Upgrade angular version to 1.7.9.  

Need CQ
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=21227

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/15381

### CODE REVIEW

**Comment by olexii4** [comment]
crw-ci-test

**Comment by olexii4** [comment]
https://github.com/eclipse/che/pull/15257

**Comment by olexii4** [comment]
crw-ci-test

**Comment by olexii4** [comment]
crw-ci-test

**Review by AndrienkoAleksandr — APPROVED** [review]

**Review by akurinnoy — APPROVED** [review]

**Pull request merged**
