### PR TITLE
Properly handle no-environment in workspace config from UD

### PR DESCRIPTION
**Pull request by ashumilova**
Signed-off-by: Anna Shumilova <ashumilo@redhat.com>

### What does this PR do?
Handles the no-environment in UD. When workspace has no default environment set and no environments defined - the UD has to allow to work with such workspace - create stacks, create workspace, create and accept factory.

### CODE REVIEW

**Comment by ashumilova** [comment]
ci-test

**Review by benoitf — APPROVED** [review]

**Comment by ashumilova** [comment]
fixing [checkSsh](https://github.com/eclipse/che/blob/master/selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/dashboard/workspaces/details/WorkspaceDetailsSingleMachineTest.java#L210) test

**Comment by ashumilova** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1230/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1230//Selenium_20tests_20report/)
docker image: eclipseche/che-server:12028
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Review by benoitf — APPROVED** [review]

**Review by akurinnoy — APPROVED** [review]

**Comment by benoitf** [comment]
FYI it seems PR can't be merged right now

**Pull request merged**
