### PR TITLE
feat(machine-exec): Remove default machine-exec component as it is provided by che-theia meta/devfile now

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
remove default plug-in when starting workspaces
Only components requiring machine-exec should include it in their definition (like che-theia)

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/19215

### How to test this PR?
Happy path should be successful (also you can check there is only one machine-exec component starting in a given che-theia workspace and no che-machine-exec component if another editor is picked-up)

note: che-theia image is not yet published so it should fail happy path right now
After relaunching the test (once che-theia image is published) it should work :-)

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

Change-Id: I98ca453e305db71f9e947b9611a42df80b7d6776
Signed-off-by: Florent Benoit <fbenoit@redhat.com>

### CODE REVIEW

**Review by MichalMaler — APPROVED** [review]

**Comment by benoitf** [comment]
[crw-ci-test --rebuild]

**Comment by benoitf** [comment]
@dmytro-ndp it seems happy path tests are failing with

```
18:48:41 [Build Che including upstream projects] failure: repodata/repomd.xml from rhel-7-server-supplementary-os-rpms: [Errno 256] No more mirrors to try.
```

**Comment by benoitf** [comment]
[crw-ci-test --rebuild]

**Comment by benoitf** [comment]
rebasing to latest master as HappyPath tests has been fixed by https://github.com/eclipse/che/pull/19336

**Comment by benoitf** [comment]
[crw-ci-test]

**Comment by benoitf** [comment]
[crw-ci-test]

**Comment by benoitf** [comment]
[crw-ci-test --rebuild]

**Review by mshaposhnik — APPROVED** [review]

**Review by sparkoo — APPROVED** [review]

**Review by skabashnyuk — APPROVED** [review]

**Pull request merged**
