### PR TITLE
Fix k8s/OS workspace deployment cleanup when pod failed to start

### PR DESCRIPTION
**Pull request by amisevsk**
### What does this PR do?
Splits `KubernetesDeployment`'s delete flow into a delete pods method and a delete deployments method.

Previously, it was assumed that Deployments would always manage to create a pod, but this is not necessarily true. When a Deployment is created but is unable to create a Pod, the delete method fails to clean anything up, leaving that workspace in an inoperable state.

To avoid this issue, the previous `doDelete` method had to be split to accommodate the possible cases:
1. We're deleting a Deployment that is controlling a Pod (the standard)
2. We're deleting a Pod without a Deployment (included for backwards compatability)
3. We're deleting a Deployment with **no** Pod (new to this PR). 

This complicates the `delete()` method, as it has to enumerate all workspace resources, and there is no longer an easy way to do this (short of enumerating all deployments and pods).

### What issues does this PR fix or reference?
#11197 

#### Docs PR
N/A, regression fix.

### CODE REVIEW

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by amisevsk** [comment]
Note also that workspaces left in an inoperable state due to the #11197 are fixed by attempting (and failing) to start them, as this properly cleans up the broken deployment.

**Review by garagatyi — APPROVED** [review]
Looks good.
@sleshchenko @amisevsk we should consider removing bare pods support and refactoring this class not to have 1 thousand lines.

**Comment by garagatyi** [comment]
ci-test

**Comment by garagatyi** [comment]
@riuvshin please, add Angel to a verified users list

**Comment by riuvshin** [comment]
done

**Comment by garagatyi** [comment]
@riuvshin thanks!

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/823/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/823//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11253
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/824/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/824//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11253
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by amisevsk** [comment]
@garagatyi I agree that this class could use some refactoring as it's quite messy. I thought bare pods was still required for e.g. PVC clean up jobs, though.

**Pull request merged**
