### PR TITLE
Update PHP to 7.2

### PR DESCRIPTION
**Pull request by filips123**
It updates PHP from 7.0 to 7.2 in PHP stack description. See eclipse/che-dockerfiles#214.

### CODE REVIEW

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by musienko-maxim** [comment]
Can one of the admins verify this PR?

**Comment by monaka** [comment]
@musienko-maxim @filips123 This PR is blocked by  eclipse/che-dockerfiles#214. And must pass the ECA check.

**Comment by monaka** [comment]
@filips123 I think this PR is outdated. Just closing, or re-targeting to Che-6.x ?

**Comment by filips123** [comment]
@monaka How should I re-target it to Che 6?

**Comment by monaka** [comment]
This PR is obsolete by #13788. I close it.
@filips123 please make new PR to the `6.19.x` branch if you want to request merging this.

**Comment by monaka** [comment]
@filips123 How to re-target is like this.
 
1. create new branch from `6.19.x` branch on your fork.
2. cherry-pick your patch in this PR to new branch.
3. push your branch created on step 1.
4. create new PR and set the target branch `6.19.x` (not the master branch).

**Pull request closed without merging**
