### PR TITLE
Ffmpeg recording

### PR DESCRIPTION
**Pull request by rhopp**
### What does this PR do?
Replaces the method of generating one screenshot every second by proper recording of whole display by ffmpeg.

### CODE REVIEW

**Comment by rhopp** [comment]
crw-ci-test

**Comment by rhopp** [comment]
crw-ci-test

**Comment by rhopp** [comment]
crw-ci-test

**Comment by rhopp** [comment]
crw-ci-test

**Comment by dmytro-ndp** [comment]
Just a reminder: 
1) use /tmp/e2e/report/ instead of /tmp/ffmpeg_report/
2) ensure there is test report directory with screenshot, logs etc. remains in case of failure, like the following:`che/tests/e2e/report/Validation_of_workspace_start_Open_workspace/` :
Screenshot from 2020-03-13 18-27-22

**Comment by rhopp** [comment]
@dmytro-ndp 
1) I've already explained the reasoning on today's standup: When the tests are started, [the report folder is deleted ](https://github.com/eclipse/che/blob/master/tests/e2e/driver/CheReporter.ts#L69). That's why I have to put the recording into different folder and copy (or move if you prefer) it to the final report folder after the tests are finished.
2) Do you have some suspicion, that this is not happening? If yes, please point me to the code where you think I have it wrong.

P.S.: Ad 1) - I'm aware, that right now I'm archiving the video also in the case of successfull test. I'm not sure this is a problem, as video from successfull run has around 15Mb and we are keeping max 100 last builds - I believe we can handle this. We can change this if it proves to be problematic IMHO.

**Comment by dmytro-ndp** [comment]
@rhopp: in this case we are recording screencast anyway doesn't matter if test fails or not. So, let's keep screencast video in case of successful execution as well, to make it possible to check on possible warnings, triggered workarounds etc., besides video of 15 MB shouldn't be a problem for CRW CCI.

**Comment by dmytro-ndp** [comment]
Could you, please, provide failed Happy path test results to check how PR handles it?

**Review by musienko-maxim — APPROVED** [review]

**Comment by rhopp** [comment]
@dmytro-ndp Here ya go: https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/blue/organizations/jenkins/Multiuser-Che-PR-check-E2E-Happy-path-tests-against-k8s/detail/Multiuser-Che-PR-check-E2E-Happy-path-tests-against-k8s/2411/artifacts

**Comment by rhopp** [comment]
But it seems I have bug somewhere... The job is green even though the tests clearly failed. I'll take a look tomorrow.

**Comment by dmytro-ndp** [comment]
Got it. Thanks for deeper verification!

**Comment by rhopp** [comment]
crw-ci-test

**Review by dmytro-ndp — APPROVED** [review]
Looks good!

**Comment by rhopp** [comment]
note: my last force-push just switched `quay.io/rhopp/che-e2e:latest` to `quay.io/rhopp/che-e2e:nightly`

**Comment by rhopp** [comment]
crw-ci-tests

**Comment by rhopp** [comment]
crw-ci-test

**Comment by rhopp** [comment]
ci-test
crw-ci-test

**Comment by rhopp** [comment]
crw-ci-test

**Comment by rhopp** [comment]
crw-ci-test

**Comment by rhopp** [comment]
crw-ci-test

**Comment by dmytro-ndp** [comment]
crw-ci-test

**Comment by dmytro-ndp** [comment]
crw-ci-test

**Comment by dmytro-ndp** [comment]
crw-ci-test

**Comment by dmytro-ndp** [comment]
crw-ci-test

**Comment by dmytro-ndp** [comment]
@rhopp: [Happy path tests failed on build of Eclipse Che](https://github.com/eclipse/che/pull/16353#issuecomment-607126574). It seems your branch should updated to master branch.

**Pull request merged**
