### PR TITLE
factory will always use devfile generateName

### PR DESCRIPTION
**Pull request by sparkoo**
Signed-off-by: Michal Vala <mvala@redhat.com>

### What does this PR do?
Fixes possible workspace name collision when using factory with devfile. It takes `generateName` with precedence and converts `name` into `generateName`, when only `name` is defined. With this, we should always create uniquely named workspace that will have 5 random characters suffix.
- When devfile has only `name`, it use it as generateName -> `nameYYYYY`
- When devfile has only `generateName`, it uses that -> `generateNameYYYY`
- When devfile has both `name` and `generateName`, it uses `generateName` -> `generateNameYYYY`
(Y is random [0-9a-z] characted)

I've choosen to take `generateName` over `name` here, because there is higher chance that it would generate nicer name. If you have other opinion, please comment.

### What issues does this PR fix or reference?
#13683

### CODE REVIEW

**Review by sleshchenko — COMMENTED** [review]
Seems it should be modified as well https://github.com/eclipse/che/blob/8d3cc8054a4ff13e5405400cbaf7221243399b33/wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/urlfactory/URLFactoryBuilder.java#L154

**Review by metlos — APPROVED** [review]
Nice way of fixing #13683!

**Comment by sparkoo** [comment]
> Seems it should be modified as well
> 
> https://github.com/eclipse/che/blob/8d3cc8054a4ff13e5405400cbaf7221243399b33/wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/urlfactory/URLFactoryBuilder.java#L154

It doesn't have to. The devfile naming is "fixed" later in the process.

**Comment by sleshchenko** [comment]
> It doesn't have to. The devfile naming is "fixed" later in the process.

I stare like a few minutes and did not manage to find where it will be fixed.
BTW I think it would be more straightforward to set `generateName` right there instead of relying on `name` to `generateName` moving later. Or do you think there are props of moving these fields later?

**Comment by sparkoo** [comment]
> > It doesn't have to. The devfile naming is "fixed" later in the process.
> 
> I stared like a few minutes and did not manage to find where it will be fixed later.
> BTW I think it would be more straightforward to set `generateName` right there instead of relying on `name` to `generateName` moving later. Or do you think there are props of moving these fields later?

you're right, it's not fixed later. I've missed that, twice :) Thanks for the catch. fixed

**Review by sleshchenko — APPROVED** [review]
LGTM

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by mingfang** [comment]
I don't think this is a good idea.
If the intent is for the factory to always generate a new workspace then the devfile should have a `generateName`.
If the devfile one has `name` then the behavior should be to either generate the workspace if it doesn't exist or open the existing workspace with the same name.

**Pull request merged**
