### PR TITLE
[deploy/helm] backport changes from chectl for templates

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
backport changes from chectl for templates
Many of them are because helm v2.14 is now performing 'validation' phase on templates

### What issues does this PR fix or reference?
https://github.com/che-incubator/chectl/pull/110

Change-Id: I2e46d120237218be64061d4a6800124eedc9a919
Signed-off-by: Florent Benoit <fbenoit@redhat.com>

### CODE REVIEW

**Comment by sleshchenko** [comment]
I think it makes sense to make clear that some changes are done because of `helm v2.14 is now performing validation phase on templates`, as you mentioned
But others are from https://github.com/eclipse/che/pull/13399 (AFAIU this PR is not merged yet because of ECA check failure)

**Comment by benoitf** [comment]
@akervern is it ok for you to have your changes merged as part of this PR ?

**Review by sleshchenko — APPROVED** [review]
LGTM

**Review by l0rd — APPROVED** [review]

**Comment by benoitf** [comment]
ci-build

**Pull request merged**
