### PR TITLE
Running Che and workspaces as non-root in a Kubernetes cluster.

### PR DESCRIPTION
**Pull request by stnnguyen95**
Signed-off-by: Son Nguyen <son.nguyen@softwareag.com>

### What does this PR do?
When deploying Che in a Kubernetes cluster using the deploy/kubernetes/helm/che Helm chart, Che and Che workspaces start as a given non-root user. Also, the securityContext.fsGroup is set to the same value.

These values can be overwritten from the command line when running the hemp command by specifying --set global.security.runAsUser=yourPreferredUserId and --set global.securityContext.fsGroup=yourPreferredFsGroup.

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/12969

#### Release Notes
N/A

#### Docs PR
N/A

### CODE REVIEW

**Review by garagatyi — APPROVED** [review]
Looks good.
@sleshchenko FYI

**Comment by sleshchenko** [comment]
@stnnguyen95 
Looks like commit message is not correct. Could you fix it or person who will merge this PR will be able to fix it during `Squash and merge`?
Screenshot_20190326_113018

**Review by sleshchenko — APPROVED** [review]
LGTM

The only question: 
Is there a plan to get rid of using [cluster-admin](https://github.com/eclipse/che/blob/dcb00c53d09fc8ad71b0bc12d44115d7269d2481/deploy/kubernetes/helm/che/templates/cluster-role-binding.yaml#L16) or it is OK?

**Comment by eivantsov** [comment]
@sleshchenko good question but it's not related to this particular PR I think :)

**Comment by sleshchenko** [comment]
ci-build

**Review by ghost — APPROVED** [review]

**Comment by stnnguyen95** [comment]
@sleshchenko I can change the commit message by amending it (git commit --amend). Will that be enough or do I have to create a new PR because of the new commit by amend?

**Comment by sleshchenko** [comment]
@stnnguyen95 `git commit --amend` and then `git push -f` would be good enough.

**Comment by sleshchenko** [comment]
ci-build

**Pull request merged**
