### PR TITLE
Revert update to 3.10

### PR DESCRIPTION
**Pull request by ghost**
### What does this PR do?

Revert update to OKD 3.10 because of https://github.com/eclipse/che/issues/10916

### CODE REVIEW

**Comment by eivantsov** [comment]
ci-test

**Review by sleshchenko — APPROVED** [review]
Thanks. Can't wait to see this PR merged :+1: :heart:

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/661/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/661//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10947)
docker image: eclipseche/che-server:10947
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by eivantsov** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/662/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/662//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10947)
docker image: eclipseche/che-server:10947
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by artaleks9** [comment]
Selenium tests execution on Eclipse Che Multiuser on OCP (https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/662/) doesn't show any regression against this Pull Request.

**Pull request merged**
