### PR TITLE
Add different small improvements

### PR DESCRIPTION
**Pull request by sleshchenko**
### What does this PR do?
It includes the following small different improvements:
1. Add logging of original exception message when an error occurs on date parsing.
2. Fix typos while storing installer and output endpoints.
3. Make JwtProxyProvisioner reuse getConfigMap method.
4. Fix mistake in an error message in ApiAccessRejectionFilter.
5. Set image pull policy to Always for docker image environments.

### What issues does this PR fix or reference?
- 

#### Release Notes
N/A

#### Docs PR
N/A

### CODE REVIEW

**Comment by sleshchenko** [comment]
ci-test

**Review by mshaposhnik — APPROVED** [review]

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/862/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/862//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11367
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Review by skabashnyuk — APPROVED** [review]

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/863/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/863//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11367
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Review by garagatyi — APPROVED** [review]

**Comment by sleshchenko** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/868/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/868//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11367
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by Ohrimenko1988** [comment]
The selenium tests did not reveal any regression in next report https://github.com/eclipse/che/pull/11367#issuecomment-424811964

**Pull request merged**
