### PR TITLE
Backport rh-che changes to OpenShift deployment script

### PR DESCRIPTION
**Pull request by l0rd**
### What does this PR do?
Backport a fix merged in rh-che repository a few days ago (https://github.com/redhat-developer/rh-che/pull/320) to update the maven central URL where deployment configurations for Che are published.

### What issues does this PR fix or reference?
https://github.com/redhat-developer/rh-che/issues/315

### CODE REVIEW

**Review by benoitf — APPROVED** [review]

**Comment by garagatyi** [comment]
AFAIK @riuvshin is on vacation. He might be offline.
@l0rd Can you elaborate on why you treat this issue as a bug?

**Comment by benoitf** [comment]
it's a bug as it's not using the correct deployment configuration (repository has been changés)

**Comment by garagatyi** [comment]
From my point of view if something changes in a backward incompatible way projects that depend on it don't get bugs, but rather suffer from breaking change. But it is my lamentation, so you can totally ignore it.

**Comment by garagatyi** [comment]
I'm saying that bug makes ppl feel that it is some defect inside of a project. But in some cases, it is just decision made in another place that affected the stability of the project.
Just like in case of the leftpad - someone removed his artifact and thousands of projects got broken. Does it mean that all of those projects got the new bug? I doubt.
But on the other hand, I understand that if something is broken it is treated as a bug. Even when the source of a break is somewhere else.

**Review by riuvshin — APPROVED** [review]

**Comment by l0rd** [comment]
@garagatyi Maybe `kind/task` is the right label here ;-)

**Pull request merged**
