### PR TITLE
CHE-9449: Adapt Node Js debugger to node version 8

### PR DESCRIPTION
**Pull request by vinokurig**
### What does this PR do?
Adapt Node Js debugger to node version 8

### What issues does this PR fix or reference?
#9449 

#### Release Notes

Fixed nodeJs debugger

#### Docs PR

N/A

### CODE REVIEW

**Review by tolusha — APPROVED** [review]

**Comment by vinokurig** [comment]
ci-test

**Comment by tolusha** [comment]
sounds good.

**Review by vparfonov — APPROVED** [review]

**Comment by vinokurig** [comment]
ci-test

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by musienko-maxim** [comment]
The features that are covered by selenium tests passed as properly

**Comment by vinokurig** [comment]
ci-build

**Comment by vinokurig** [comment]
ci-build

**Pull request merged**
