### PR TITLE
UI improvements

### PR DESCRIPTION
**Pull request by vitaliy-guliy**
### What does this PR do?
Fixing bugs on workspace loading sequence.
- unable to select tab in processes panel when `Workspace-start` tab is opened
- pulling images does not shown on docker 17
- improved readability of the text in menu and editor tabs

https://docs.google.com/document/d/1b_W6M0wFDESKQipMHvJMMLL-NoXB70MQ6Cm9EAK2_YU/edit#

che6_3

### What issues does this PR fix or reference?

https://github.com/eclipse/che/issues/6820
https://github.com/eclipse/che/issues/7260
https://github.com/eclipse/che/issues/6933
https://github.com/eclipse/che/issues/7376
https://github.com/eclipse/che/issues/7425

CPU usage should be reduced
https://github.com/eclipse/che/issues/7424

### CODE REVIEW

**Comment by skabashnyuk** [comment]
Which version of docker is required to use to make it work?

**Comment by vitaliy-guliy** [comment]
ci-test

**Comment by vitaliy-guliy** [comment]
@skabashnyuk We don't specify docker version. Feature is working on docker 13 and 17.

**Comment by skabashnyuk** [comment]
Did you still parsing logs to show progress bars?

**Comment by vitaliy-guliy** [comment]
Yes. We have no variants for now.

**Comment by skabashnyuk** [comment]
As discussed it's strongly not advised to do that because docker has no obligation on the format and as you can see it was changed between Docker 11 and 17. Despite this, I'm +0.3141592 for this PR since it fixes it at least somehow. Because now loader almost useless on Docker 17

**Comment by ashumilova** [comment]
Can you please attach screenshots?

**Comment by ashumilova** [comment]
Now UI improvements are introduced, the loading stuff is going to be handled by https://github.com/eclipse/che/issues/7332

**Comment by vitaliy-guliy** [comment]
A screenshot added.

**Review by ashumilova — APPROVED** [review]

**Review by vparfonov — APPROVED** [review]

**Comment by musienko-maxim** [comment]
ci-test

**Review by musienko-maxim — APPROVED** [review]

**Pull request merged**
