### PR TITLE
Update fmt plugin to latest to enable skipping check #10554

### PR DESCRIPTION
**Pull request by vrubezhny**
The files are reformatted in order to suit the requirements of coveo maven fmt plug-in of v.2.5.1

Signed-off-by: Victor Rubezhny <vrubezhny@redhat.com>

### What does this PR do?
The PR contains all the classes that are reformatted in order to suit the requirements of coveo maven fmt plug-in of v.2.5.1

### What issues does this PR fix or reference?
Depends on https://github.com/eclipse/che-parent/pull/67

### CODE REVIEW

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Review by skabashnyuk — APPROVED** [review]

**Comment by skabashnyuk** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/547/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/547//Selenium_tests_report)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10667)
docker image: eclipseche/che-server:10667
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by vrubezhny** [comment]
This PR depends on https://github.com/eclipse/che-parent/pull/67 and cannot be built successfully without applying the mentioned PR first.

**Comment by dmytro-ndp** [comment]
@vrubezhny: PR selenium tests job ought to take into account upstream project **che-parent** in usual cases, but now [it have been skipped](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/547/) with resolution:
`>>>>>> Pull request is issued from fork, skipping upstream project branch checks <<<<<<`
As a result, test build failed:
```
14:00:32 [INFO] Processed 33 files (2 non-complying).
14:00:32 [ERROR] Found 2 non-complying files, failing build
14:00:32 [ERROR] Non complying file: /home/codenvy/workspace/che-pullrequests-test-ocp/core/che-core-api-dto/src/test/java/org/eclipse/che/dto/definitions/DtoWithDelegate.java
14:00:32 [ERROR] Non complying file: /home/codenvy/workspace/che-pullrequests-test-ocp/core/che-core-api-dto/src/test/java/org/eclipse/che/dto/ServerDtoTest.java
``` 
@riuvshin: it's interesting to know why PR selenum tests job skips upstream projects branches in case of PR is from the fork?

**Comment by vrubezhny** [comment]
The PR's commit is rebased and updated

**Comment by tolusha** [comment]
@dmytro-ndp 
Do we have your approval?

**Review by dmytro-ndp — APPROVED** [review]
Approved from the point of selenium tests codebase so as test resources haven't been changed.

**Review by tolusha — COMMENTED** [review]
I successfully built `che-parent` `che-docs` `che-libs` and `che` projects

**Review by tolusha — APPROVED** [review]

**Pull request merged**
