### PR TITLE
Update default plugin/devfile registries to use prod-preview

### PR DESCRIPTION
**Pull request by amisevsk**
### What does this PR do?
Use https://che-plugin-registry.prod-preview.openshift.io and https://che-devfile-registry.prod-preview.openshift.io/ instead of their production equivalents.

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/14266, https://github.com/eclipse/che/issues/14261

### CODE REVIEW

**Review by rhopp — APPROVED** [review]
I agree, this is step in right direction.

**Comment by ibuziuk** [comment]
hmm... I thought the plan was not to use OSIO registries at all by default, but rather deploy them together with Che Server

**Review by ibuziuk — COMMENTED** [review]
is it considered to be a temp solution?

**Review by ibuziuk — APPROVED** [review]
This sounds like a reasonable workaround for minishift addon case. But in general, I do believe upstream che should not fall back on osio plugin registries at all since it makes Hosted Che and Che release process dependent

**Comment by amisevsk** [comment]
@ibuziuk Yeah this is definitely to be a temporary solution, since rolling out nightlies of the registries will only work going forward if we somehow also roll out Che nightlies. I think that after all deployment methods are updated to deploy registries alongside Che, we should leave the `che.properties` values as `NULL`.

**Pull request merged**
