### PR TITLE
CHE-5564:  Fix encoding for full text search.

### PR DESCRIPTION
**Pull request by AndrienkoAleksandr**
### What does this PR do?
 Fix encoding for full text search.

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/5564

#### Release Notes
 Fix encoding for full text search.

#### Docs PR
Don't need bug fix.

### CODE REVIEW

**Review by RomanNikitenko — APPROVED** [review]

**Review by vparfonov — APPROVED** [review]

**Comment by AndrienkoAleksandr** [comment]
ci-build

**Comment by AndrienkoAleksandr** [comment]
ci-test

**Comment by davidwindell** [comment]
Can this be back-ported to Che 5 please?

**Review by artaleks9 — APPROVED** [review]

**Comment by AndrienkoAleksandr** [comment]
@davidwindell, Yes, of course I will do it.

**Comment by AndrienkoAleksandr** [comment]
@davidwindell done https://github.com/eclipse/che/pull/7864.

**Pull request merged**
