### PR TITLE
[root pom] support overriding the version of dashboard

### PR DESCRIPTION
**Pull request by nickboldt**
support overriding the version of che-dashbaord-war via new property che.dashboard.version

Change-Id: I3627f5572f8a0221e16bc0f08ec56407fe13a0f1
Signed-off-by: nickboldt <nboldt@redhat.com>

### CODE REVIEW

**Comment by nickboldt** [comment]
Tested this using three different variations and all assembled fine:

````
cd assembly/assembly-main
mvn clean install -Dche.dashboard.version=6.11.1
mvn clean install -Dche.dashboard.version=6.12.0-SNAPSHOT
mvn clean install -Dche.dashboard.version=6.12.0-20180920.164657-35
````

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Review by benoitf — APPROVED** [review]

**Comment by benoitf** [comment]
ci-build

**Comment by l0rd** [comment]
Why using `${che.version}` for `<che.dashboard.version>` but not for  `<che.docs.version>` and `<che.lib.version>`? I would prefer the 3 to be consistent.

**Comment by benoitf** [comment]
@l0rd it's because docs and lib are external repositories so they may have different versions

**Comment by l0rd** [comment]
> @l0rd it's because docs and lib are external repositories so they may have different versions

🤔 but currently they all use the same version (i.e. we need to manually update the version at every release).

**Comment by benoitf** [comment]
It's Romans script that do it automatically

**Comment by nickboldt** [comment]
@l0rd my original PR *DID* set all three from \${che.version} but was told that was not allowed for now.

So I did this: https://github.com/eclipse/che/pull/11313/commits/240fd8d83b1ed57614e096e7cf461f2b6a8dff5d 

Can someone merge this to master?

**Review by riuvshin — APPROVED** [review]

**Pull request merged**
