### PR TITLE
Remove pure kubectl deployment

### PR DESCRIPTION
**Pull request by mkuznyetsov**
### What does this PR do?
Remove pure kubectl deployment, use Helm as a main way to deploy Che on Kubernetes
Removed readme.md in deployment/kubernetes/helm/che, as all the information in it should be on the docs pages.

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/11135

#### Docs PR
in progress

### CODE REVIEW

**Review by l0rd — APPROVED** [review]

**Review by garagatyi — APPROVED** [review]
Please, provide a corresponding docs cleaning PR

**Comment by garagatyi** [comment]
@mkuznyetsov could you clarify why this PR is in WIP?

**Review by sleshchenko — APPROVED** [review]
LGTM

Please do not forget prepare the needed changes to Che Docs repo not to use removed deployment there https://www.eclipse.org/che/docs/kubernetes-single-user.html

**Comment by mkuznyetsov** [comment]
Removed readme.md in deployment/kubernetes/helm/che, as all the information in it should be on the docs pages.

**Review by riuvshin — APPROVED** [review]

**Pull request merged**
