### PR TITLE
Fixed README typo with linked text

### PR DESCRIPTION
**Pull request by KyeMaloy97**
### What does this PR do?
A tiny fix that makes the "review code changes" link the same as the text around it (as in the whole line is a link, before this the word review stood out as it wasn't a link).

#### Release Notes

N/A

### CODE REVIEW

**Comment by benoitf** [comment]
hello @KyeMaloy97 FYI in order to be able to merge your PR you need to sign the Eclipse ECA and add the Signed-Off section in your commit

**Comment by benoitf** [comment]
ci-build

**Comment by KyeMaloy97** [comment]
@benoitf I just signed off the commit and pushed it up, and i also signed the ECA :)

**Comment by benoitf** [comment]
thx

**Review by benoitf — APPROVED** [review]

**Pull request merged**
