### PR TITLE
[WIP]Distintiguish between workspace start and update.

### PR DESCRIPTION
**Pull request by metlos**
### What does this PR do?
This makes the server store the timestamp of a workspace start as a separate attribute. Before start and update of a workspace were both tracked by a single attribute called "updated".

This PR will enable us to track the long running workspaces in #12091.

Not sure about the impact of this change. Is this part of the public API? It seems to have been part of the contract forever.

### What issues does this PR fix or reference?

#12091 

#### Release Notes

The start time of a workspace is now stored as "started" attribute of a workspace. The "updated" attribute now only contains the timestamp of the last update of the workspace.

### CODE REVIEW

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Review by garagatyi — APPROVED** [review]
Looks good

**Comment by garagatyi** [comment]
@davidfestal Please, check whether it affects Woopra in any way

**Comment by benoitf** [comment]
I think it may affect all clients like dashboard that displays workspace in order of usage

**Comment by metlos** [comment]
k, so what about splitting it like this:

* keep `updated` as is - tracks update or start
* add `started` to track the last started time
* add `modified` to track the last modification time (if this is needed at all)

**Comment by skabashnyuk** [comment]
@metlos +1
we can 
 - for one or more releases, until we make sure other clients are not affected keep updated as is
 - not we can introduce  ```started``` to track the last started time
 - add modified to track the last modification time  - not sure 
- in one or two releases change or remove updated

**Comment by garagatyi** [comment]
And who will be working on checking clients?

**Comment by skabashnyuk** [comment]
>And who will be working on checking clients?

Work as usual with potentially breaking changes.
1. Notifying community about the change and a reason.
2. Giving some time to check and adapt.
3. In a reasonable time introduce change. 

Anyway, I'm not sure we have a proper proposal yet. I would like to work more on this task.

**Comment by metlos** [comment]
I'm closing this PR because the proposed change is no longer needed. We found a better solution to the problem by extending the functionality around workspace expiration (now called workspace activity).

**Pull request closed without merging**
