### PR TITLE
Fixed NPE during provisioning of selector for Deployments

### PR DESCRIPTION
**Pull request by sleshchenko**
### What does this PR do?
This bug was found during try to run a workspace with a single dockerimage component.
It fixes provisioning of selector for Deployment of dockerimage component and improves the code to avoid NPE if the user does not define selector in his recipe.

### What issues does this PR fix or reference?
It is a fix for functionality introduced in https://github.com/eclipse/che/pull/12967

#### Release Notes
N/A

#### Docs PR
N/A

### CODE REVIEW

**Comment by sleshchenko** [comment]
ci-test

**Review by metlos — APPROVED** [review]
LGTM but makes me worried where else do we assume k8s child objects to be non-null.

**Review by skabashnyuk — APPROVED** [review]

**Review by mshaposhnik — APPROVED** [review]

**Comment by SkorikSergey** [comment]
Selenium tests execution on Eclipse Che Multiuser on OCP (https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1678//Selenium_20tests_20report/) doesn't show any regression against this Pull Request.

**Comment by sleshchenko** [comment]
@rhopp Hi, this PR fixed regression introduced in https://github.com/eclipse/che/pull/12967. Do we have a chance to get basic Devfile functionalities covered with selenium tests?

**Comment by rhopp** [comment]
@sleshchenko I don't see much value in trying to cover devfile functionality with selenium tests in this moment... Selenium tests are UI tests and AFAIK there is no UI endpoint for devfile functionality, right?
Of course we could add workspace creation from devfile (by api call) into the cypress suite which is now in development, but beware, that this way we could cover only very limited number of possible "devfiles" (in the sense that we won't be able to test this way all possible devfile features and their combinations).

**Comment by sleshchenko** [comment]
@rhopp You're right that there is not Devfile specific UI, and there are two ways of creation workspace with Devfile - factory URL and API call. My point is to have some integration tests that make sure that no functionalities are broken.

> (in the sense that we won't be able to test this way all possible devfile features and their combinations).

something is better than nothing =)

**Comment by rhopp** [comment]
@sleshchenko Could you please check https://github.com/eclipse/che/issues/12728 (most importantly https://hackmd.io/s/BkVyU6crN) to see if that covers the basics for devfile and if not, could you provide feedback there? Thanks!

**Pull request merged**
