### PR TITLE
CODENVY-610: add possibility to set no_proxy ENV var in machine

### PR DESCRIPTION
**Pull request by riuvshin**
**_1 Upvote**_ Signed-off-by: Roman Iuvshin riuvshin@codenvy.com
@garagatyi @skabashnyuk  please review this.

### CODE REVIEW

**Comment by TylerJewell** [comment]
+1

**Comment by garagatyi** [comment]
LGTM

**Comment by skabashnyuk** [comment]
ок

**Comment by riuvshin** [comment]
:bow:

**Comment by TylerJewell** [comment]
@riuvshin - Is it possible to configure different no_proxy options for Codenvy installation vs. Codenvy machine / workspace?

I know that we have the --no-proxy option.  And the workspace environment variable no_proxy should (by default) be set to the value of --no-proxy. However, if a customer wants to install with a no-proxy, but have a different no_proxy for machines, is that possible?

**Pull request merged**
