### PR TITLE
Fix helm chart to install che

### PR DESCRIPTION
**Pull request by ssh24**
Signed-off-by: ssh24 <sakib@ibm.com>

### What does this PR do?

This PR fixes the helm chart to install che. Uncomment lines [70-73](https://github.com/eclipse/che/blob/master/deploy/kubernetes/helm/che/values.yaml#L70)

### What issues does this PR fix or reference?

https://github.com/eclipse/che/issues/13558

### CODE REVIEW

**Comment by musienko-maxim** [comment]
Can one of the admins verify this PR?

**Comment by l0rd** [comment]
@sleshchenko should we merge this one?

**Comment by sleshchenko** [comment]
@monaka is going to prepare another style fix https://github.com/eclipse/che/issues/13558#issuecomment-503932573
I'm OK to merge it as is at least there is no another fix.

**Review by sleshchenko — APPROVED** [review]

**Comment by monaka** [comment]
I'm also OK to merge this. And in addition, I'm going to make a patch.

**Comment by ssh24** [comment]
@monaka Sounds good. Are we good to land this now?

**Comment by monaka** [comment]
@ssh24 I have no permission for CI build that is required before merging.
And I pushed the fix the issue by the another way (#13598). Could you check there?

**Comment by sleshchenko** [comment]
ci-build

**Comment by tetchel** [comment]
Still seeing this bug, can we get the build fixed?

**Comment by benoitf** [comment]
ci-build

**Comment by monaka** [comment]
@tetchel This issue was fixed by #13598. Please try on the master branch.

**Pull request closed without merging**
