### PR TITLE
[E2E tests] Remove API calls

### PR DESCRIPTION
**Pull request by Katka92**
### What does this PR do?
As far as E2E tests should refer to user experience, it is not supposed to test API. 
The only API calls that were currently present were check for workspace state (which is represented in UI) and check that the plugin was added (which will be checked once working with file). 
Removing this API will make this tests usable for Single and Multi user approach, which make sense - user should still experience the same UI. 

I've tested these changes locally against Che 7.0.0-beta-5.0 running on minishift.

### CODE REVIEW

**Comment by Ohrimenko1988** [comment]
I strongly disagree with this PR. I don't see any reason why we should remove this functionality. API calls increase stability in the UI tests.

**Comment by musienko-maxim** [comment]
Can one of the admins verify this PR?

**Comment by SkorikSergey** [comment]
ci-build

**Comment by SkorikSergey** [comment]
ci-build

**Comment by Ohrimenko1988** [comment]
API calls increase stability by reducing capacity of UI checks calls. For example, if use just UI checks we will have a very hard, slow and unstable framework. API calls work great together with UI checks, especially when you need to wait a long time for some condition.
    Besides api call give much more information about object state than just UI check. For example when we check plugins initialization we check it by UI, and also we check it by API. This approach ensures that plugins successfully initialized and result is displayed. 
    For example if we remove API calls in the starting workspace logic we will have very unstable behavior of the selenium driver. And it leads to unstable tests.
    Besides we need this API calls for future work with devfiles.
    And also I don't agree with approach that we should check all by UI. My strong opinion that we should check functionality once by true way like a user. And for another checks, where this functionality just a part of the preparing work we should use API calls or another ways for reduce using UI in the prepare workspace for testing.

**Comment by ppitonak** [comment]
I suport this PR.

> API calls increase stability by reducing capacity of UI checks calls. For example, if use just UI checks we will have a very hard, slow and unstable framework. 

While it's true that API tends to be more stable than UI, this e2e test is testing user's interactions **using UI**, i.e. if user creates a workspace using UI, test should verify the result **using UI**.

>API calls work great together with UI checks, especially when you need to wait a long time for some condition.

UI should give the user regular feedback when an action takes long time. Using API for this will be easier for you but will not catch possible serious UX issue.

> Besides api call give much more information about object state than just UI check. For example when we check plugins initialization we check it by UI, and also we check it by API. This approach ensures that plugins successfully initialized and result is displayed.

While true in general, I don't see where/how you gather this additional information. For me, this is one of few strong arguments to do API calls. Can you point me to the code doing this?

> For example if we remove API calls in the starting workspace logic we will have very unstable behavior of the selenium driver. And it leads to unstable tests.

Can you elaborate more on this?

> Besides we need this API calls for future work with devfiles.

Can you elaborate more on this?

> And also I don't agree with approach that we should check all by UI. My strong opinion that we should check functionality once by true way like a user. And for another checks, where this functionality just a part of the preparing work we should use API calls or another ways for reduce using UI in the prepare workspace for testing.

I completely agree with you but e2e test is not the right place. E.g. `waitPluginAdding` - it's important to test that and I am OK with using API to test that but IMHO this test belongs to the dashboard test suite, not e2e.

**Comment by rhopp** [comment]
Thanks Palo for your feedback.
I'll just add few points to that.
* In general I agree, that using API calls could be beneficial (for example repetitive tasks - once do it in UI way, then it's ok to use API if it makes sense)
* `For example when we check plugins initialization we check it by UI, and also we check it by API. ` To check this properly (in this kind of tests) I would check the plugin functionality (some basic one) - if it was properly initialized, it should work.
* Again - in general I understand and agree, that API calls could not be avoided, but all API calls removed in this PR are unnecessary IMO (a.k.a. not needed, or should be replaced by another check). Few examples:
  * [This wait](https://github.com/eclipse/che/pull/13438/files#diff-80fdf57bc560f5160bd83e67ced4d59aL50). It waits for workspace to be in state RUNNING and then waits for all UI elements of IDE to be displayed. Is there a chance, when the workspace will not be running yet, but IDE will be displayed? This doesn't seem probable to me (and if it is I guess that's a bug)
  * [This wait](https://github.com/eclipse/che/pull/13438/files#diff-ae766ff9e2ddb6d55ca1a3a1b4a1517dL48). This method clicks on "Create&Open" workspace and waits for workspace to be in state STARTING. To me, when this method is already opening the workspace I guess it should also wait for proper IDE initialization (a.k.a. `Ide.waitIde` I guess?) (and also this method is not used anywhere :-D)

You also said we would "need" API calls to work with devfiles. Could you elaborate on that? I'm not aware of such requirement ATM, but I may be something missing...

**Comment by Ohrimenko1988** [comment]
Even if you will decide to remove API calls from the test, I don't understand why we should remove TestWorkspace.

**Pull request closed without merging**
