### PR TITLE
🔨 Fix e2e docker image (log output & crooked screencast)

### LINKED ISSUE #18602: Enormousness "INFO" messages in E2E typescript selenium tests output regardless TS_SELENIUM_LOG_LEVEL=ERROR
### Describe the bug
There were enormose `INFO` messages in E2E typescript selenium tests output regardless `- e TS_SELENIUM_LOG_LEVEL=ERROR`.

Command to run the tests
```
 docker run --shm-size=1g --net=host --ipc=host \
  -p 5920:5920 \
  -e TS_SELENIUM_HEADLESS='false' \
  -e TS_SELENIUM_DEFAULT_TIMEOUT=300000 \
  -e TS_SELENIUM_LOAD_PAGE_TIMEOUT=240000 \
  -e TS_SELENIUM_WORKSPACE_STATUS_POLLING=20000 \
  -e TS_SELENIUM_BASE_URL=${CHE_URL} \
  -e TS_SELENIUM_LOG_LEVEL='ERROR' \
  -e TS_SELENIUM_MULTIUSER="true" \
  -e TS_SELENIUM_USERNAME="admin" \
  -e TS_SELENIUM_PASSWORD="admin" \
  -v ${WORKSPACE}/che/tests/e2e:/tmp/e2e:Z \
  -e NODE_TLS_REJECT_UNAUTHORIZED=0 \
  quay.io/eclipse/che-e2e:nightly
```

Test log fragment https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/che-pr-tests/view/K8S/job/Che-Theia-PR-check-E2E-Happy-path-tests-against-K8S__reserved/2111/:
```
15:48:14   Validation of workspace start
15:48:14 Can not get bearer token. URL used: https:keycloak-eclipse-che.10.0.102.108.nip.io/auth/realms/che/protocol/openid-connect/token
15:48:14   [ERROR] PreferencesHandler.setPreferences failed to get user preferences
15:48:14 (node:228) UnhandledPromiseRejectionWarning: Error: Request failed with status code 400
15:48:14     at createError (/tmp/e2e/node_modules/axios/lib/core/createError.js:16:15)
15:48:14     at settle (/tmp/e2e/node_modules/axios/lib/core/settle.js:18:12)
15:48:14     at IncomingMessage.handleStreamEnd (/tmp/e2e/node_modules/axios/lib/adapters/http.js:202:11)
15:48:14     at emitNone (events.js:111:20)
15:48:14     at IncomingMessage.emit (events.js:208:7)
15:48:14     at endReadableNT (_stream_readable.js:1064:12)
15:48:14     at _combinedTickCallback (internal/process/next_tick.js:138:11)
15:48:14     at process._tickCallback (internal/process/next_tick.js:180:9)
15:48:14 (node:228) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
15:48:14 (node:228) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
15:48:15 Starting ChromeDriver 86.0.4240.22 (398b0743353ff36fb1b82468f63a3a93b4e2e89e-refs/branch-heads/4240@{#378}) on port 19585
15:48:15 Only local connections are allowed.
15:48:15 Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
15:48:15 ChromeDriver was started successfully.
15:48:15 13:48:15.745 INFO [LoggingOptions$1.lambda$export$1] - {"traceId": "347f406d5987fa79fcc41f728638a1bb","spanId": "9974c1e7c73085a4","spanKind": "INTERNAL","eventTime": 1607694495744677226,"eventName": "HTTP request received response","attributes": {"http.status_code": 200,"http.client_class": "org.openqa.selenium.remote.http.netty.NettyClient","http.url": "\u002fsession","http.method": "POST"}}
15:48:15 
15:48:15 13:48:15.752 INFO [ProtocolHandshake.createSession] - Detected dialect: W3C
15:48:15 13:48:15.775 INFO [LoggingOptions$1.lambda$export$1] - {"traceId": "347f406d5987fa79fcc41f728638a1bb","spanId": "b4cf74d4bde7b78d","spanKind": "INTERNAL","eventTime": 1607694495754147335,"eventName": "Driver service created session","attributes": {"upstream.dialect": "W3C","driver.url": "http:\u002f\u002flocalhost:19585","logger": "org.openqa.selenium.grid.node.config.DriverServiceSessionFactory","downstream.dialect": "OSS","session.capabilities": "Capabilities {browserName: chrome, chromeOptions: {args: [--no-sandbox, --disable-web-security, --allow-running-insecure-co..., --ignore-certificate-errors]}}","driver.response": "(Response: SessionID: 3a0c379339e2a87c93ac405ffa96637f, Status: 0, Value: {acceptInsecureCerts=false, browserName=chrome, browserVersion=86.0.4240.75, chrome={chromedriverVersion=86.0.4240.22 (398b0743353ff36fb1b82468f63a3a93b4e2e89e-refs\u002fbranch-heads\u002f4240@{#378}), userDataDir=\u002ftmp\u002f.com.google.Chrome.hnxYvJ}, goog:chromeOptions={debuggerAddress=localhost:40470}, networkConnectionEnabled=false, pageLoadStrategy=normal, platformName=linux, proxy=Proxy(), setWindowRect=true, strictFileInteractability=false, timeouts={implicit=0, pageLoad=300000, script=30000}, unhandledPromptBehavior=dismiss and notify, webauthn:virtualAuthenticators=true})"}}
15:48:15 
15:48:15 13:48:15.782 INFO [LoggingOptions$1.lambda$export$1] - {"traceId": "347f406d5987fa79fcc41f728638a1bb","spanId": "14247df40bdc02f8","spanKind": "INTERNAL","eventTime": 1607694495777524312,"eventName": "Session created by node","attributes": {"session.request.downstreamdialect": "[OSS]","upstream.dialect": "W3C","current.session.count": 0,"session.uri": "http:\u002f\u002flocalhost:19585","logger": "org.openqa.selenium.grid.node.local.LocalNode","session.request.capabilities": "Capabilities {browserName: chrome, chromeOptions: {args: [--no-sandbox, --disable-web-security, --allow-running-insecure-co..., --ignore-certificate-errors]}}","downstream.dialect": "OSS","session.capabilities": "Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 86.0.4240.75, chrome: {chromedriverVersion: 86.0.4240.22 (398b0743353ff..., userDataDir: \u002ftmp\u002f.com.google.Chrome.hnxYvJ}, goog:chromeOptions: {debuggerAddress: localhost:40470}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: linux, proxy: Proxy(), se:options: {cdp: http:\u002f\u002flocalhost:40470}, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:virtualAuthenticators: true}","session.id": "3a0c379339e2a87c93ac405ffa96637f"}}
...
```

### Recent changes
https://github.com/eclipse/che/commit/7cf011ba3875ce4a012c6b46b0ed92d2d8c201a6#diff-b96b2d264d519e3f7e46f5b4efcfd0ad8705484447198b5db1b054974ada813a

### PR DESCRIPTION
**Pull request by rhopp**
### What does this PR do?
Fixes #18602 and #18433

### Screenshot/screencast of this PR
Here's screenshot from the recording showing #18433 is fixed
image
Here's log output of run showing the logging is "fixed" (#18602 ):
https://pastebin.com/p8geHDhh

### What issues does this PR fix or reference?
This PR updates base image for e2e testing image to use selenium chrome image containing latest (87) chrome. 
It also changes screen color depth of xvfb (the low screen color depth was causing the crooked screencast from #18433 )
The base image is now based on selenium grid 3, instead of selenium grid 4. This is a quick workaround for #18602 until we cind better solution how to disable the openlogging output of selenium server

### How to test this PR?
Run the test, see the log output & screencast ;-)

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [ ] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [ ] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [ ] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by dmytro-ndp** [comment]
[crw-ci-test --rebuild]

**Review by benoitf — APPROVED** [review]
I tried on a github action https://github.com/benoitf/start-che-gh/runs/1571135535?check_suite_focus=true
video seems to work and tons of logs are gone

I'm still unable to have all tests passing but I like challenges :-)

off-topic:
on github action recording videos seem to eat all the cpu with ffmpeg so I don't know if there is way to have 'less cpu recording' or a way to skip record at all by providing some environment variables

**Comment by dmytro-ndp** [comment]
[crw-ci-test --rebuilt]

**Comment by dmytro-ndp** [comment]
[crw-ci-test --rebuild]

**Review by dmytro-ndp — APPROVED** [review]

**Comment by dmytro-ndp** [comment]
[Happy path tests results with image quay.io/fbenoit/che-e2e:rhoppv1 created by @benoitf](https://github.com/eclipse/che/pull/18646#issuecomment-747726015):
- [test log looks clear](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/che-pr-tests/view/K8S/job/Multiuser-Che-PR-check-E2E-Happy-path-tests-against-k8s/4218/console):
```
...
23:55:53           ▼ Waiting for debugger to connect (threads to appear in "Threads" view)
23:55:53           ▼ Waiting for debugger to connect (threads to appear in "Threads" view)
23:55:53           ▼ Waiting for debugger to connect (threads to appear in "Threads" view)
23:55:53           ▼ PreviewWidget.refreshPage
23:55:53           ▼ Editor.waitStoppedDebugBreakpoint title: "WelcomeController.java" line: "27"
23:55:53           ▼ Editor.isBreakpointPresent
23:55:53           ▼ Editor.isBreakpointPresent
23:55:53           ▼ Editor.isBreakpointPresent
23:55:53           ▼ Editor.isBreakpointPresent
23:55:54           ▼ Editor.isBreakpointPresent
23:55:54           ▼ Editor.isBreakpointPresent
23:55:54     ✓ Run debug and check application stop in the breakpoint (4239ms)
23:55:54 
23:55:54 
23:55:54   22 passing (6m)
23:55:54   1 pending
```
- [screencast has been recovered](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/che-pr-tests/view/K8S/job/Multiuser-Che-PR-check-E2E-Happy-path-tests-against-k8s/4218/artifact/tests/e2e/report/output.mp4)
Screenshot from 2020-12-18 00-17-37

**Pull request merged**
