### PR TITLE
CHE-1005: properly display machine type icons in console tree and targets view, fix logo size

### PR DESCRIPTION
**Pull request by ashumilova**
**_1 Upvote**_ Signed-off-by: Ann Shumilova ashumilova@codenvy.com

### CODE REVIEW

**Comment by ashumilova** [comment]
artik_console_panel

**Comment by TylerJewell** [comment]
@ashumilova - it looks weird to have the DEV icon and the artik icon different sizes.  I think they should both be the same size / alignment as the ARTIK icon.  So perhaps we should shrink the DEV icon so that everything looks aligned?

**Comment by vitaliy-guliy** [comment]
+1 to decrease DEV icon size

**Comment by ashumilova** [comment]
reduced a little
artik_console_panel1

**Comment by vitaliy-guliy** [comment]
Looks better

**Comment by TylerJewell** [comment]
Still looks weird to me.   I think we should leave it as ART instead.  That was cleaner than this.  It's because one is a box and another is a logo.  So they don't present cleanly.

**Pull request merged**
