### PR TITLE
Use of Chefile in new cli : new 'dir' command

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?

Add 'dir' command in new cli

### Previous behavior
new cli hasn't the command

### New behavior
`docker run.....   eclipse/che-cli:nightly dir <path-to-the-host-directory> <command>`

Change-Id: Iec4f40cfb503fe60c51d81ef06e07043e102db6a
Signed-off-by: Florent BENOIT <fbenoit@codenvy.com>

### CODE REVIEW

**Comment by skabashnyuk** [comment]
Can you describe a usecase where this command is used?

**Comment by benoitf** [comment]
https://eclipse-che.readme.io/docs/chefile

**Comment by TylerJewell** [comment]
Now that we have the Che docs updated in the `che-docs` branch, can you add to this PR:
1. Update to the CLI reference markdown which includes this command
2 Review of the Chedir markdown pages in that branch.

**Comment by benoitf** [comment]
ok I've added documentation in PR

**Review by TylerJewell — APPROVED** [review]

**Comment by TylerJewell** [comment]
The changes that are here are ok to be merged.  But we also have all of the changes that need to be made in these docs.  All of these docs assume you have the old CLI installed where you just type `che dir`. So we need to modify these docs with a couple of examples that show the full CLI syntax, and then provide explanation that we have a short-hand explanation for the rest of the commands.

Also, someone needs to go through each command and run it once to verify that the Che dir docs are still accurate.

https://github.com/eclipse/che/tree/master/docs/_docs/chedir-portable-workspaces

@benoitf - if you want to reassign this to Stevan because of your maternity holiday, that is probably ok to do now.

**Comment by bmicklea** [comment]
@slemeur there are some docs issues here - other than that this can be merged I believe.

**Comment by slemeur** [comment]
We will not merge this PR as we moved to another repository.
I'll take the changes into che-docs.

**Comment by slemeur** [comment]
Docs updated here: https://github.com/codenvy/che-docs/commit/47fdfee2b158c85b34aef2426a3ce53c625d39d6

**Comment by TylerJewell** [comment]
Thanks will try to review before end of day.

**Comment by slemeur** [comment]
@TylerJewell just took the updates from @benoitf in this PR and back ported them to che-docs repo.

chedir-portable-workspace is not updated yet.

**Pull request merged**
