### PR TITLE
[Happy Path] Resolve problem with debug step of the "Happy-Path" scenario

### PR DESCRIPTION
**Pull request by Ohrimenko1988**
### What does this PR do?
Resolve problem with debug step of the "Happy-Path" scenario

### What issues does this PR fix or reference?
Issue: https://github.com/eclipse/che/issues/14346

### CODE REVIEW

**Comment by Ohrimenko1988** [comment]
@dmytro-ndp could you launch CI job with images  "bujhtr5555/che-e2e:latest"
which includes PR changes ?

**Comment by dmytro-ndp** [comment]
Test failed https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/Single-Che-PR-check-E2E-Happy-path-tests-against-k8s-on-codenvy-slave9/293/:
```
 Validation of debug functionality

Sending interrupt signal to process
sh: line 1:  3931 Terminated              JENKINS_SERVER_COOKIE=$jsc '/bin/sh' -xe '/home/codenvy/workspace/Single-Che-PR-check-E2E-Happy-path-tests-against-k8s-on-codenvy-slave9@tmp/durable-36e86414/script.sh' > '/home/codenvy/workspace/Single-Che-PR-check-E2E-Happy-path-tests-against-k8s-on-codenvy-slave9@tmp/durable-36e86414/jenkins-log.txt' 2>&1
script returned exit code 143
```
screenshot-Open_file_and_activate_breakpoint

Test was run from branch https://github.com/eclipse/che/tree/che-14346

**Comment by dmytro-ndp** [comment]
Local tests ran successfully when been mounted to docker image `bujhtr5555/che-e2e:latest` https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/blue/organizations/jenkins/Single-Che-PR-check-E2E-Happy-path-tests-against-k8s-on-codenvy-slave9/detail/Single-Che-PR-check-E2E-Happy-path-tests-against-k8s-on-codenvy-slave9/297

**Comment by dmytro-ndp** [comment]
There tests had finished successfully been mounted to `cypress/browsers:node8.9.3-chrome73` image as well https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/blue/organizations/jenkins/Single-Che-PR-check-E2E-Happy-path-tests-against-k8s-on-codenvy-slave9/detail/Single-Che-PR-check-E2E-Happy-path-tests-against-k8s-on-codenvy-slave9/297/

**Comment by Ohrimenko1988** [comment]
@dmytro-ndp local run result
Screenshot from 2019-09-05 12-24-36

It looks like yours introduced problems related to CI configuration

**Comment by dmytro-ndp** [comment]
@Ohrimenko1988: could you, please, say if you had run the tests [here](https://github.com/eclipse/che/pull/14420#issuecomment-528280367) from inside `bujhtr5555/che-e2e:latest`?
If so, let's merge the changes, have `eclipse/che-e2e:latest` rebuilt tomorrow and then run the tests again on CI.

**Comment by Ohrimenko1988** [comment]
@dmytro-ndp This is launch result with using "bujhtr5555/che-e2e:latest" image without mounting e2e
Screenshot from 2019-09-05 13-04-02

the command which was used:
```
docker run -it --shm-size=2g --name selenium-e2e -e TS_SELENIUM_BASE_URL=$TS_SELENIUM_BASE_URL bujhtr5555/che-e2e:latest
```

**Comment by dmytro-ndp** [comment]
I have just noticed that the tests seem outdated: "Application is ready for use..." log message had been fixed in master several days ago. Cood you, please, renew the tests?

**Comment by Ohrimenko1988** [comment]
ci-test

**Review by Katka92 — APPROVED** [review]

**Review by rhopp — APPROVED** [review]

**Comment by Ohrimenko1988** [comment]
ci-test

**Review by dmytro-ndp — APPROVED** [review]
Looks good so that the tests have passed both with ["eclipse/eclipse/che-e2e:nightly" image](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/blue/organizations/jenkins/Single-Che-PR-check-E2E-Happy-path-tests-against-k8s-on-codenvy-slave9/detail/Single-Che-PR-check-E2E-Happy-path-tests-against-k8s-on-codenvy-slave9/311/) and ["cypress/browsers:node8.9.3-chrome73" image](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/blue/organizations/jenkins/Single-Che-PR-check-E2E-Happy-path-tests-against-k8s-on-codenvy-slave9/detail/Single-Che-PR-check-E2E-Happy-path-tests-against-k8s-on-codenvy-slave9/297/).

**Pull request merged**
