### PR TITLE
[ Selenium ] Get rid of legacy code in the "Consoles" selenium page object

### PR DESCRIPTION
**Pull request by Ohrimenko1988**
### What does this PR do?
Get rid of legacy code in the "Consoles" selenium page object 

### What issues does this PR fix or reference?
Issue: https://github.com/eclipse/che/issues/11217

### CODE REVIEW

**Comment by Ohrimenko1988** [comment]
ci-test

**Review by dmytro-ndp — APPROVED** [review]

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1156/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1156//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11889
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by Ohrimenko1988** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1159/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1159//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11889
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Pull request merged**
