### PR TITLE
IDEX-3260 Remove factory API from Eclipse Che

### PR DESCRIPTION
**Pull request by benoitf**
Change-Id: Icb28fc5a14c55a7c335bf4446373de33d67a9e2f
Signed-off-by: Florent BENOIT fbenoit@codenvy.com

### CODE REVIEW

**Comment by garagatyi** [comment]
Why do you want to remove factory API from Che?
Do you know why factory API was added to che?

**Comment by benoitf** [comment]
So answer about removal it's because it's not aligned with Che vs OnPrem vs SaaS definition of the products

It was added silently (no JIRA issue)
https://github.com/codenvy/sdk/commit/a464fe61af9e8b13ecac69dc40d248d090b032e5#diff-80a94067583b41469cdb86e5134d2bb1

**Comment by garagatyi** [comment]
OK

**Comment by garagatyi** [comment]
Is it Tyler idea?

**Comment by benoitf** [comment]
yes

**Comment by benoitf** [comment]
so is it ok to merge ?

**Comment by garagatyi** [comment]
It's ok from technical side, but I can't say GO to you to merge this PR. Please ask @skabashnyuk or @gazarenkov about that.

**Pull request merged**
