### PR TITLE
jackson-databind update version to 2.10.5.1

### PR DESCRIPTION
**Pull request by xbaran4**
Signed-off-by: Pavol Baran <pbaran@redhat.com>

### What does this PR do?
Updates version of com.fasterxml.jackson.core:jackson-databind to 2.10.5.1

### What issues does this PR fix or reference?

Adresses the security issue present in jackson-databind 2.10.3 (https://github.com/advisories/GHSA-288c-cq4h-88gq)

### How to test this PR?

Deploy on minikube through chectl. 
Create and delete workspaces.

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by sparkoo** [comment]
can you provide che-server image to test with? You can push it in your private quay.io

**Comment by xbaran4** [comment]
> can you provide che-server image to test with? You can push it in your private quay.io

quay.io/pbaran/che-server:latest

**Comment by skabashnyuk** [comment]
CQ is not needed since it a bugfix version.

**Review by skabashnyuk — APPROVED** [review]

**Review by sparkoo — APPROVED** [review]

**Review by mshaposhnik — APPROVED** [review]

**Comment by benoitf** [comment]
[crw-ci-test]

**Comment by benoitf** [comment]
[crw-ci-test --rebuild]

**Review by metlos — APPROVED** [review]

**Pull request merged**
