### PR TITLE
CHE-9547 fix RAM changes for editing the machine dialog for UD

### PR DESCRIPTION
**Pull request by olexii4**
Signed-off-by: Oleksii Orel <oorel@redhat.com>

### What does this PR do?
Fix RAM changes for editing the machine dialog for UD.

### What issues does this PR fix or reference?

https://github.com/eclipse/che/issues/9547

### CODE REVIEW

**Comment by olexii4** [comment]
ci-test

**Review by akurinnoy — APPROVED** [review]

**Comment by olexii4** [comment]
ci-test

**Review by ashumilova — APPROVED** [review]

**Comment by riuvshin** [comment]
ci-test

**Comment by olexii4** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test

**Review by benoitf — APPROVED** [review]

**Comment by olexii4** [comment]
ci-test

**Pull request merged**
