### PR TITLE
CHE-10097, CHE-10098, CHE-256: fix bugs related to installers on Stack Details page

### LINKED ISSUE #10097: User Dashboard installers: page scrolls down when enabling/disabling workspace api installer
### Description

dashboard

### LINKED ISSUE #10098: Multiple installers in UD
### Description

It is very confusing to see duplicate installers:

image

### LINKED ISSUE #10256: Save/Cancel buttons on stack details page is missed if reject changes in Agents list
### Reproduction Steps
1. From **Dashboard** open **Stacks** page.
2. Open any stack from **Stacks** list.
3. In the **Machines** section click on "**dev-machine**".
4. Do some changes for **Agents** list and click the **Cancel** button in the bottom of page.
5. Do some changes again.

**Expected result:**
The **Cancel** button appeared after changes.

**Actual result:**
The **Cancel** button is missed.

**OS and version:**  
 Che 6.8.0-SNAPSHOT; Chrome 66.0; Fedora 28

**Additional information:**
screencast-172 19 20 234-8080-2018 07 04-10-43-59

### PR DESCRIPTION
**Pull request by akurinnoy**
### What does this PR do?
Bugs which are fixed by this PR: 
- displaying multiple installers with the same id in the installers list;
- canceling changes once doesn't allow to save further changes;
- unexpected page scrolling after switching installers on or off;
- unexpected page scrolling after canceling changes when installers list in the viewport;

### What issues does this PR fix or reference?
fix #10097 
fix #10098 
fix #10256

#### Release Notes

N/A - bugfix

#### Docs PR

N/A - bugfix

### CODE REVIEW

**Comment by akurinnoy** [comment]
ci-test

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Review by benoitf — APPROVED** [review]

**Comment by SkorikSergey** [comment]
ci-test

**Comment by SkorikSergey** [comment]
ci-test

**Comment by SkorikSergey** [comment]
ci-test

**Comment by SkorikSergey** [comment]
ci-build

**Comment by SkorikSergey** [comment]
ci-test

**Comment by SkorikSergey** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test

**Review by ashumilova — APPROVED** [review]

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/460/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/460//Selenium_tests_report)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10367)
docker image: eclipseche/che-server:10367
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by SkorikSergey** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/467/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/467//Selenium_tests_report)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10367)
docker image: eclipseche/che-server:10367
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by akurinnoy** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/473/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/473//Selenium_tests_report)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10367)
docker image: eclipseche/che-server:10367
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by akurinnoy** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/493/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/493//Selenium_tests_report)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10367)
docker image: eclipseche/che-server:10367
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by akurinnoy** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/497/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/497//Selenium_tests_report)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10367)
docker image: eclipseche/che-server:10367
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by Ohrimenko1988** [comment]
Selenium tests execution on Eclipse Che Multiuser on OCP
(https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/497/Selenium_20tests_20report/)
doesn't show any regression against this Pull Request.

**Pull request merged**
