### PR TITLE
Fixing of letters cut-off in left menu.

### PR DESCRIPTION
**Pull request by Katka92**
### What does this PR do?
Show whole letters of workspace name in left menu.

### What issues does this PR fix or reference?
#9664

### CODE REVIEW

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by Katka92** [comment]
@ashumilova I've closed the previous PR because I was unable to add commit here. Now I can't see why check is failing, I can see only this:

Current status
Validation status unavailable. Contact support.

Could you please tell me what should I do to let this check pass? Thank you.

**Review by ashumilova — APPROVED** [review]

**Comment by ashumilova** [comment]
@Katka92 thank you for handling this bug.

**Comment by Katka92** [comment]
@benoitf thank you for your advice, not it passed :+1: 
@ashumilova thank you for your assistance :) now the check is green so if you agree, I think it can be merged.

**Comment by benoitf** [comment]
thanks @Katka92 
waiting result of CI https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/537/

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/537/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/537//Selenium_tests_report)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10632)
docker image: eclipseche/che-server:10632
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Pull request merged**
