### PR TITLE
Remove the factory from the navbar

### PR DESCRIPTION
**Pull request by olexii4**
Signed-off-by: Oleksii Orel <oorel@redhat.com>

### What does this PR do?
Hide the factory button from the navbar(it's totally unusable) until we implement the issue 
[Adopt devfile format for factories](https://github.com/eclipse/che/issues/12925).

### CODE REVIEW

**Comment by olexii4** [comment]
@slemeur, @l0rd  WDYT?

**Review by sleshchenko — APPROVED** [review]
My personal +1 to hide the factory button from the navbar until it's totally unusable.

**Review by akurinnoy — APPROVED** [review]

**Comment by l0rd** [comment]
> it's totally unusable

@sleshchenko @olexii4 creating a factory using a old template format still works right?

**Comment by sleshchenko** [comment]
> creating a factory using a old template format still works right?

@l0rd creating kind of working but not accepting:
old-factory

**Comment by slemeur** [comment]
Removing features, even if they are somehow broken, introduce a functional regression. 

Can't it use the devfile definition instead of the factory.json?

**Comment by skabashnyuk** [comment]
>Can't it use the devfile definition instead of the factory.json?

It's not implemented. It is a part of https://github.com/eclipse/che/issues/12925

**Comment by olexii4** [comment]
@slemeur As I understand, you agree with removing. Could you approve this PR?

**Pull request closed without merging**
