### PR TITLE
Selenium log output cleanup

### PR DESCRIPTION
**Pull request by skabashnyuk**
### What does this PR do?
Put some ex.printStackTrace into log.warn

#### Release Notes
n/a

#### Docs PR
n/a

### CODE REVIEW

**Comment by skabashnyuk** [comment]
ci-build

**Comment by skabashnyuk** [comment]
ci-test

**Review by tolusha — APPROVED** [review]

**Review by benoitf — APPROVED** [review]

**Review by riuvshin — APPROVED** [review]

**Comment by skabashnyuk** [comment]
ci-buil

**Comment by skabashnyuk** [comment]
ci-build

**Pull request merged**
