### PR TITLE
CHE-2090: fix machine removal from storage if machine creation fails

### LINKED ISSUE #2090: SSH machine is displayed as RUNNING after creating it with wrong credentials
SSH machine has status RUNNING when create it with wrong SSH credentials to the target.
The error message is displayed properly but the machine still has RUNNING status.

**Reproduction Steps:**
1. Create target pointed on existed device
2. Type wrong username or password in corresponding fields
3. Press Save and then Connect
4. See the result

**Expected behavior:**

The error message must be shown and the target must not be listed in the consoles

**Observed behavior:**

The target is listed in the consoles with status RUNNING

**Che version:** 4.7.0-SNAPSHOT

**Additional information:**
- Problem can be reliably reproduced, doesn't happen randomly: Yes

### PR DESCRIPTION
**Pull request by garagatyi**
### What does this PR do?

Fixes machines storage cleanup when machine creation fails.
### What issues does this PR fix or reference?

Fixes #2090 
### Previous Behavior

When credentials to SSH machine are incorrect machine is not removed after failed start.
### New Behavior

Machine is removed after failed start.
### Tests written?

No
### Docs requirements?

No

### CODE REVIEW

**Comment by garagatyi** [comment]
@skabashnyuk @evoevodin @mmorhun @AndrienkoAleksandr Please review

**Comment by voievodin** [comment]
ok

**Comment by skabashnyuk** [comment]
ок

**Comment by mmorhun** [comment]
+1

**Pull request merged**
