### PR TITLE
CHE-98: Restyle check-boxes position in 'git commit' view

### PR DESCRIPTION
**Pull request by vinokurig**
gitcommit
@vparfonov please review

### CODE REVIEW

**Comment by TylerJewell** [comment]
@vinokurig - it looks like the check boxes are not vertically spaced properly?

**Comment by vinokurig** [comment]
I have separated with space 'Amend previous commit' check-box because this operation differs from those that are above, @TylerJewell what do you think?

**Comment by TylerJewell** [comment]
@vinokurig - thank you for the explanation.  If you hadn't said that, i would have not understood it.  I think to the average user, it will look weird, though.  It would need to be separated by a separator to make it clear that we mean something different.  I think it's safer to keep it all evenly spaced only because it is not so intuitive.

**Comment by vinokurig** [comment]
gitcommit
Aligned all checkboxes in common way

**Comment by vparfonov** [comment]
ok

**Pull request merged**
