### PR TITLE
CHE-3492; Add filters for force or disable caching on the given resources paths.

### PR DESCRIPTION
**Pull request by mshaposhnik**
### What does this PR do?
Add filters for force or disable caching on the given resources paths.

### What issues does this PR fix or reference?
#3492 
### Previous behavior
None of the resources have proper cache control headers.

### New behavior
Resources will have proper cache control headers.

### Tests written?
Yes

### Docs updated?
Please add a matching PR to [the docs repo](http://github.com/eclipse/che-docs) and link that PR to this issue. Both will be merged at the same time. 

#### Changelog
Add filters for force or disable caching on the given resources paths.

### CODE REVIEW

**Comment by benoitf** [comment]
> What issues does this PR fix or reference?
CHE-3492

maybe we should provide hyperlink to the issue ? because CHE-3492 is not a valid github name while #3492 is

**Comment by skabashnyuk** [comment]
done

**Comment by benoitf** [comment]
does it break http etag ?
https://en.wikipedia.org/wiki/HTTP_ETag

https://github.com/eclipse/che/blob/8e5967613daddac84d9e3ea0ef47d53d08dbd11e/core/che-core-api-core/src/main/java/org/eclipse/che/everrest/ETagResponseFilter.java

**Comment by mshaposhnik** [comment]
@benoitf  No, it shouldn't. We use etag filter only for JSON-s, while the caching is oriented for IDE resources, which is mostly .js .css etc. But even if it is, etag  will just  help, so if the cached resource changed on the server side, another e-tag hash will be published and resource will be re-get from browser.

**Comment by benoitf** [comment]
@mshaposhnik ok thanks I was not sure if this filter was applying or not to JSON resources

**Comment by mshaposhnik** [comment]
@benoitf Should we apply those filters to dashbard war (in Codenvy we do block all caching by pattern `(?!_sso/).*$`, e.g. block caching for anything except `_sso` (which is excluded for login purposes i think))

**Comment by benoitf** [comment]
@mshaposhnik AFAIK you could do it on js and css of dashboard. Resources are minified and then each release has its own filename
like
scripts/app-cc9dbfedf4.js
scripts/vendor-b2dfa25cb3.js
styles/app-5e7a694a55.css

**Comment by mshaposhnik** [comment]
@benoitf So, i don't see the reason why we should not cache them. If it changes, it will have another stamp and re-downloaded. Why do we blocked caching in codenvy, do you remember?

**Comment by mshaposhnik** [comment]
https://github.com/codenvy/codenvy/blob/master/assembly/onpremises-ide-packaging-war-dashboard/src/main/java/com/codenvy/onpremises/deploy/DashboardServletModule.java#L50 that is what i mean

**Comment by benoitf** [comment]
@mshaposhnik yes I've understood.
probably a copy/paste error. BTW dashboard may still load some fragments (not .js or .css that are not minified and then have unique identifiers) so cache could not apply on the whole files. Those files are loaded from "assets/" folder of dashboard.war

**Comment by mshaposhnik** [comment]
@skabashnyuk @benoitf  pls review

**Review by benoitf — APPROVED** [review]

**Review by skabashnyuk — APPROVED** [review]

**Pull request merged**
