### PR TITLE
[TS_SELENIUM] Change bindings scope of the "e2e" project

### PR DESCRIPTION
**Pull request by Ohrimenko1988**
### What does this PR do?
Change bindings scope of the "e2e" project

### What issues does this PR fix or reference?
Issue: https://github.com/eclipse/che/issues/15881

### CODE REVIEW

**Review by musienko-maxim — APPROVED** [review]

**Comment by Katka92** [comment]
@Ohrimenko1988 could you explain why you do that and what should it solve, please?

**Comment by Ohrimenko1988** [comment]
@Katka92 it solves https://github.com/eclipse/che/issues/15881 (in PR description)

**Comment by Katka92** [comment]
@Ohrimenko1988 Sorry, I probably didn't ask clearly. I'll try that again ;) 
What is the difference between how it worked and how it will work after this PR is merged? Does it mean, that classes will not be singletons and will be created again every time when they are used? Or maybe could you put there a simple example of how it could be re-binded? Thank you

**Comment by Ohrimenko1988** [comment]
@Katka92 I'll add instruction to the issue #15881 after merging this PR. Because without these changes my instructions will not be valid.

**Review by Katka92 — APPROVED** [review]
It seems it can really fix all our issues. Thank you for your effort!

**Comment by Ohrimenko1988** [comment]
Instruction how to reuse upstream tests is here https://github.com/eclipse/che/issues/15881#issuecomment-580273205

**Pull request merged**
