### PR TITLE
Ensure proxy settings are provisioned for init containers

### PR DESCRIPTION
**Pull request by amisevsk**
This PR is a cherry-pick of https://github.com/eclipse/che/pull/15263

### CODE REVIEW

**Review by sleshchenko — APPROVED** [review]

**Comment by sleshchenko** [comment]
ci-build

**Review by metlos — APPROVED** [review]

**Comment by amisevsk** [comment]
ci-test

**Comment by ibuziuk** [comment]
@vparfonov @rhopp  am I correct that PR check is expected to fail on the 7.3.x branch?

**Review by ibuziuk — APPROVED** [review]
I checked with @vparfonov and the e2e failures are expected. So, I believe we are good to mere

**Pull request merged**
