### PR TITLE
Change the Dockerfile of e2e tests

### PR DESCRIPTION
**Pull request by Katka92**
### What does this PR do?
Change a user in a Dockerfile and docker image to run commands as a non-root user. That will allow us to use that image in a load test.

### CODE REVIEW

**Comment by dmytro-ndp** [comment]
@Katka92: if there is fixed image pushed somewhere? I would like to run E2E tests by using it.

**Review by dmytro-ndp — CHANGES_REQUESTED** [review]
Happy path tests failed [on CRW CCI](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/che-regular-tests/view/pre-release/job/Single-Che-pre-release-check-typescript-tests-against-K8S/10/console):
> docker run --shm-size=256m --net=host --ipc=host -e TS_SELENIUM_HEADLESS=true -e TS_SELENIUM_DEFAULT_TIMEOUT=300000 -e TS_SELENIUM_LOAD_PAGE_TIMEOUT=240000 -e TS_SELENIUM_WORKSPACE_STATUS_POLLING=20000 -e TS_SELENIUM_BASE_URL=https://che-che.10.0.100.253.nip.io -e TS_SELENIUM_LOG_LEVEL=DEBUG -e TEST_SUITE=test-happy-path -e TS_GITHUB_TEST_REPO_ACCESS_TOKEN=990040386b7d5bdf4f57001de4659e03a0b352e7 -e TS_GITHUB_TEST_REPO=chepullreq4/Spoon-Knife -e NODE_TLS_REJECT_UNAUTHORIZED=0 -e NODE_TLS_REJECT_UNAUTHORIZED=0 -v /mnt/hudson_workspace/workspace/Single-Che-pre-release-check-typescript-tests-against-K8S/tests/e2e:/tmp/e2e:Z quay.io/kkanova/upstream_e2e

```
18:06:18 npm ERR! Error: EACCES: permission denied, access '/tmp/e2e'
18:06:18 npm ERR!  { Error: EACCES: permission denied, access '/tmp/e2e'
18:06:18 npm ERR!   errno: -13,
18:06:18 npm ERR!   code: 'EACCES',
18:06:18 npm ERR!   syscall: 'access',
18:06:18 npm ERR!   path: '/tmp/e2e' }
18:06:18 npm ERR! 
18:06:18 npm ERR! Please try running this command again as root/Administrator.
18:06:19 npm ERR! Linux 3.10.0-957.el7.x86_64
18:06:19 npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
18:06:19 npm ERR! node v8.10.0
18:06:19 npm ERR! npm  v3.5.2
18:06:19 npm ERR! path npm-debug.log.361174484
18:06:19 npm ERR! code EACCES
18:06:19 npm ERR! errno -13
18:06:19 npm ERR! syscall open
18:06:19 
18:06:19 npm ERR! Error: EACCES: permission denied, open 'npm-debug.log.361174484'
18:06:19 npm ERR!  { Error: EACCES: permission denied, open 'npm-debug.log.361174484'
18:06:19 npm ERR!   errno: -13,
18:06:19 npm ERR!   code: 'EACCES',
18:06:19 npm ERR!   syscall: 'open',
18:06:19 npm ERR!   path: 'npm-debug.log.361174484' }
18:06:19 npm ERR! 
18:06:19 npm ERR! Please try running this command again as root/Administrator.
18:06:19 
18:06:19 npm ERR! Please include the following file with any support request:
18:06:19 npm ERR!     /tmp/e2e/npm-debug.log
```

**Comment by dmytro-ndp** [comment]
@Katka92: you can temporary replace quay.io/eclipse/che-e2e:nightly with your image quay.io/kkanova/upstream_e2e [in your PR](https://github.com/Katka92/che/blob/fix_e2e_dockerfile/tests/.infra/crw-ci/pr-check/k8s/Jenkinsfile#L319) to check changes using Happy path tests which are being triggered in PR.

**Comment by Katka92** [comment]
[crw-ci-test]

**Comment by Katka92** [comment]
[ci-build]

**Comment by Katka92** [comment]
Happy path with the new image passed [1]. I'll revert my last commit which changed Jenkinsfile to use my test image.
[1] https://github.com/eclipse/che/pull/16714#issuecomment-628515734

**Review by dmytro-ndp — APPROVED** [review]
Happy path tests passed, so devfile tests should not be affected as well.

**Pull request merged**
