### PR TITLE
CODENVY-128. Fix configure multimodular project with module without java files.

### PR DESCRIPTION
**Pull request by RomanNikitenko**
**_1 Upvote**_

### CODE REVIEW

**Comment by RomanNikitenko** [comment]
@benoitf WDYT?

**Comment by benoitf** [comment]
missing signed-off

**Comment by benoitf** [comment]
I think some unit tests will also fail

**Comment by RomanNikitenko** [comment]
@benoitf  All tests  - success

**Comment by RomanNikitenko** [comment]
@skabashnyuk  WDYT?

**Comment by benoitf** [comment]
@RomanNikitenko you're still missing Signed-Off in commit message

**Comment by RomanNikitenko** [comment]
@benoitf we can merge without Signed-Off in commit message

**Comment by benoitf** [comment]
+1

**Comment by skabashnyuk** [comment]
ok

**Pull request merged**
