### PR TITLE
Fix TLS enabled typos

### PR DESCRIPTION
**Pull request by akervern**
### What does this PR do?

Fix some typos around TLS enablement in Helm Template.
Plus add missing cert manager issuer in custom Keycloak ingress template.

### CODE REVIEW

**Comment by musienko-maxim** [comment]
Can one of the admins verify this PR?

**Comment by benoitf** [comment]
ci-build

**Comment by benoitf** [comment]
@akervern FYI ECA check is failing. (SignedOff)

**Comment by sleshchenko** [comment]
lifecycle/frozen

**Pull request closed without merging**
