### PR TITLE
Selenium: Fix logical mistakes in the "SeleniumWebDriverHelper" class methods

### PR DESCRIPTION
**Pull request by Ohrimenko1988**
### What does this PR do?
Fix logical mistakes in the "SeleniumWebDriverHelper" class methods

### What issues does this PR fix or reference?
Issue: https://github.com/eclipse/che/issues/10347

### CODE REVIEW

**Review by artaleks9 — APPROVED** [review]

**Review by SkorikSergey — APPROVED** [review]

**Review by musienko-maxim — APPROVED** [review]

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/524/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/524//Selenium_tests_report)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10556)
docker image: eclipseche/che-server:10556
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by Ohrimenko1988** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/525/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/525//Selenium_tests_report)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10556)
docker image: eclipseche/che-server:10556
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by Ohrimenko1988** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/526/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/526//Selenium_tests_report)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10556)
docker image: eclipseche/che-server:10556
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by Ohrimenko1988** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/527/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/527//Selenium_tests_report)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10556)
docker image: eclipseche/che-server:10556
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by Ohrimenko1988** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/530/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/530//Selenium_tests_report)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10556)
docker image: eclipseche/che-server:10556
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Pull request merged**
