### PR TITLE
Provide a sample for Apache Camel stack (#11353)

### PR DESCRIPTION
**Pull request by apupier**
provides the first basic Camel sample using xml dsl with a test checking
that it is building using the "build" command provided by the stack

Signed-off-by: Aurélien Pupier <apupier@redhat.com>

### CODE REVIEW

**Comment by apupier** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/858/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/858//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11357
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by apupier** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/860/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/860//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11357
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by apupier** [comment]
ci-test

**Comment by apupier** [comment]
ci-test

**Comment by apupier** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/878/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/878//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11357
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by apupier** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/881/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/881//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11357
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/882/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/882//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11357
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1129/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1129//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11357
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1130/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1130//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11357
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by dmytro-ndp** [comment]
@apupier: looks like the test [CreateWorkspaceFromCamelStackTest.java](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1130//Selenium_20tests_20report/failsafe-report.html#org.eclipse.che.selenium.stackCreateWorkspaceFromCamelStackTest) should be updated after the merge JDT.LS branch into the master.

**Comment by apupier** [comment]
abandoning this PR. We will do it for Che 7 only when the Camel stack will be available

**Pull request closed without merging**
