### PR TITLE
Get rid of non-working workaround to flakiness when Java LS server initialization failed

### PR DESCRIPTION
**Pull request by dmytro-ndp**
### What does this PR do?
It logs usage of workaround to failed check of LS server language initialization in E2E Happy path tests.

**_Update_**: it seems [existed workaround doesn't work, and has just hidden failure details](https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/blue/organizations/jenkins/Single-Che-PR-check-E2E-Happy-path-tests-against-k8s-on-codenvy-slave9/detail/Single-Che-PR-check-E2E-Happy-path-tests-against-k8s-on-codenvy-slave9/857/pipeline) .
So, that workaround has been removed https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/che-pr-tests/view/K8S/job/Single-Che-PR-check-E2E-Happy-path-tests-against-k8s-on-codenvy-slave9/862/console:
```
        ▼ Ide.waitStatusBarContains "Starting Java Language Server"
Known flakiness https://github.com/eclipse/che/issues/14944
    1) Java LS initialization


  3 passing (2m)
  1 failing

  1) Language server validation
       Java LS initialization:
     TimeoutError: Wait timed out after 21008ms
```

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/14944, https://github.com/eclipse/che/issues/14283

### CODE REVIEW

**Comment by dmytro-ndp** [comment]
crw-ci-test

**Review by musienko-maxim — APPROVED** [review]

**Comment by dmytro-ndp** [comment]
crw-ci-test

**Comment by dmytro-ndp** [comment]
crw-ci-test

**Comment by dmytro-ndp** [comment]
crw-ci-test

**Comment by dmytro-ndp** [comment]
crw-ci-test

**Comment by dmytro-ndp** [comment]
crw-ci-test

**Review by rhopp — APPROVED** [review]

**Review by musienko-maxim — APPROVED** [review]

**Comment by dmytro-ndp** [comment]
crw-ci-test

**Comment by dmytro-ndp** [comment]
crw-ci-test

**Comment by dmytro-ndp** [comment]
crw-ci-test

**Comment by dmytro-ndp** [comment]
ci-build

**Comment by dmytro-ndp** [comment]
ci-build

**Pull request merged**
