### PR TITLE
Switch update project to Json-rpc

### PR DESCRIPTION
**Pull request by RomanNikitenko**
### What does this PR do?
Switch update project to Json-rpc

### What issues does this PR fix or reference?
#11145

Signed-off-by: Roman Nikitenko <rnikiten@redhat.com>

### CODE REVIEW

**Comment by RomanNikitenko** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1048/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1048//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11691
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by RomanNikitenko** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1058/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1058//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11691
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Review by vparfonov — APPROVED** [review]

**Comment by artaleks9** [comment]
Selenium tests execution on Eclipse Che Multiuser on OCP (https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1058/) doesn't show any regression against this Pull Request.

**Pull request merged**
