### PR TITLE
CHE-525: Fix unexpected error message after refactoring

### PR DESCRIPTION
**Pull request by dimashnurenko**
**_1 Upvote**_ @vparfonov

### CODE REVIEW

**Comment by dimashnurenko** [comment]
@svor

**Comment by vparfonov** [comment]
ok

**Comment by svor** [comment]
:+1:

**Comment by TylerJewell** [comment]
Nice job.

I had a heart attack during the keynote demo as I was never sure what would trigger this bug.  Sometimes it happened in practice.  Other times it didn't!

**Pull request merged**
