### PR TITLE
[WIP] adapt RegularUserOcpCheLoginPage to login by OpenShift OAuth

### PR DESCRIPTION
**Pull request by dmytro-ndp**
### What does this PR do?
PR makes it possible to run E2E typescript selenium tests against Eclipse Che deployed to OCP with OS OAuth option enabled.

### What issues does this PR fix or reference?
#15585

### CODE REVIEW

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by dmytro-ndp** [comment]
crw-ci-test

**Comment by dmytro-ndp** [comment]
CRW User Stories test failed.
screenshot-Login

**Comment by SkorikSergey** [comment]
[ci-build]

**Comment by SkorikSergey** [comment]
Will be done by https://github.com/eclipse/che/issues/15585.

**Pull request closed without merging**
