### PR TITLE
Changed absolute paths to relative paths for zipped content

### PR DESCRIPTION
**Pull request by dkulieshov**
Relative issue: https://github.com/eclipse/che/issues/9397

Changed absolute paths to relative paths for zipped content

### CODE REVIEW

**Comment by dkuleshov** [comment]
ci-build

**Review by vparfonov — APPROVED** [review]

**Comment by dkuleshov** [comment]
ci-build

**Comment by dkuleshov** [comment]
ci-test

**Comment by xcariba** [comment]
Project import does not work if zip file does not contain folders, only paths.
Example (zipinfo): 
Does not work:
```
src/main/Example.txt
```
Does work:
```
src/
src/main/
src/main/Example.txt
```
ZipArchiver fails with FileNotFound exception.

**Comment by xcariba** [comment]
This change adds extra folder in zip archive. (ex. in 5.21 if I download folder "src" zip archive would contain only contents of the folder. After this changes zip archive contains "src" folder and it`s contents inside.
This is probably due to fsManager API, zip method has no "skip root" parameter.

**Comment by dkuleshov** [comment]
ci-test

**Comment by musienko-maxim** [comment]
The selenium tests passed without new regressions.
Also was checked next features manually: 
* download folder with files by context menu with check saving relative paths
* download projects with menu Workspace -> Download as Zip
* download a project with menu Project -> Download as Zip
We have not created autotests for checking this functionality. But i create issue for current sprint for developing tests:

**Pull request merged**
