### PR TITLE
One AsciiDoc reference file per parameter

### PR DESCRIPTION
**Pull request by themr0c**
To feed the discussion in https://github.com/eclipse/che/issues/19630

Now:

* The location of the files is maybe not optimal.
* This PR doesn't include changes to validate changes on `che.properties` or `multiuser.properties`.
* Added the script that generated the ref files for reference.
* Added an assembly file, which is not exactly following what we have in che-docs. Ordering need some work.

### CODE REVIEW

**Comment by themr0c** [comment]
How it would look like in the docs website:

Screenshot from 2021-04-21 17-29-03
Screenshot from 2021-04-21 17-28-49

**Comment by skabashnyuk** [comment]
Please merge the latest master to fix the build check.

**Comment by sparkoo** [comment]
default values in adoc files are prone to become obsolete, this is not safe.

**Comment by sparkoo** [comment]
how are adoc files going to be referenced from che/multiuser.properties ? Is it in the scope of this PR ?

**Comment by sparkoo** [comment]
why is there a script in this PR? My assumption was that the comments would be transferred in one batch, so why we need the script here? What will be the process.

**Comment by themr0c** [comment]
> default values in adoc files are prone to become obsolete, this is not safe. It's arguable if these default values are really default, because che-operator/helm might set them to something different with their default installation configuration.

* A change of the defaults in a properties file must be reflected in the documentation. This is the kind of thing we can catch at review time, if we don't manage to set up a scripted check.

* Default values (for documentation) are taken from the current content in the properties files. As it is in current docs. If we have to document 3 defaults: default, default for che-operator, default for helm, would it make sense to document here the defaults for the operator and for helm? That would build the case for the documentation entirely in che-docs.

**Comment by themr0c** [comment]
> why is there a script in this PR? My assumption was that the comments would be transferred in one batch, so why we need the script here? What will be the process.

Because it's a draft and I fear the content will get  obsolete before we reach consensus. Need to remove it before finalizing.

**Comment by themr0c** [comment]
> how are adoc files going to be referenced from che/multiuser.properties ? Is it in the scope of this PR ?

I believe we should do it in 2 different PR, change the comments once the documentation has done the transition.

I believe we could replace comments by:

```
# See: path/to/file.adoc
```

**Comment by themr0c** [comment]
* Is the path proposed here something that make sense? Any better / more reasonable idea?

**Comment by themr0c** [comment]
* New check for PR validation is missing, script here can maybe serve as a starting point.

**Comment by themr0c** [comment]
Closing, new plan described here: https://github.com/eclipse/che/issues/19630#issuecomment-831771136

**Pull request closed without merging**
