### PR TITLE
CHE-12917 Added an indicator to notify that the CHE 6 workspaces will not work anymore

### PR DESCRIPTION
**Pull request by olexii4**
Signed-off-by: Oleksii Orel <oorel@redhat.com>

### What does this PR do?
Added a visual indicator to notify the user that the CHE 6 workspaces will not work anymore and needs to be converted as a CHE 7 workspaces.

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/12917

    - display a visual indicator to notify the user that the CHE 6 workspace will not work anymore.

#### Docs PR

https://youtu.be/KnbFbQaPAbo

### CODE REVIEW

**Comment by olexii4** [comment]
ci-test

**Comment by olexii4** [comment]
ci-test

**Comment by olexii4** [comment]
ci-test

**Review by ashumilova — APPROVED** [review]

**Review by benoitf — APPROVED** [review]

**Review by akurinnoy — APPROVED** [review]

**Comment by olexii4** [comment]
@SkorikSergey  Che 6 based workspaces are not going to remain compatible with Che 7 and this PR  remove the ability to start the Che 6 workspace. Could you add the needed commit?

**Comment by SkorikSergey** [comment]
> @SkorikSergey Che 6 based workspaces are not going to remain compatible with Che 7 and this PR remove the ability to start the Che 6 workspace. Could you add the needed commit?

I think we need to delete from test suite all selenium tests that check workspace start/stopping from Dashboard. I will add changes to this PR.

**Comment by SkorikSergey** [comment]
ci-test

**Review by SkorikSergey — APPROVED** [review]

**Comment by slemeur** [comment]
Can change the wording that is used?
- Instead of "Not supported" in the list of workspaces "Not compatible"
- In the tooltip "This workspace is not supported in the current version of the product." by "This workspace is using old definition format which is not compatible anymore. Please follow the documentation to update the definition of the workspace and benefits from the latest capabilities."
- In the header of the detail page: "This workspace is using old definition format which is not compatible anymore. Please follow the documentation [Add link to create workspace] to update the definition of the workspace and benefits from the latest capabilities."

BTW, is that not easier to simply recreate a new workspace based on the new stack?

**Comment by olexii4** [comment]
@slemeur  As for me, it is easier just to add needed plugins(all installers should be automatically removed after)

**Comment by olexii4** [comment]
@slemeur  Done
Screenshot from 2019-05-17 14-55-01

Screenshot from 2019-05-17 14-58-47

**Comment by gorkem** [comment]
This is a good step forward but I think we can also add a button to `convert to latest specification` and to the conversion for the user, can't we ?

**Comment by slemeur** [comment]
@gorkem : We are not intending to do automatic convertion of che 6 workspace definition to che 7 workspace definition. While being nice, we removed that from the scope and will cover that with docs.

**Comment by gorkem** [comment]
@slemeur scope suggests a release. We should still have it as an item on the backlog

**Comment by olexii4** [comment]
@gorkem Yes, we can add a button to convert to the latest specification.  

@slemeur What should I do for this PR?

**Comment by slemeur** [comment]
@olexii4 : The PR is good to go. Automatic convertion would need a different issue and analyze anyway.

**Comment by pavangayakwad** [comment]
Guys! where is the documentation to troubleshoot this error? I have been searching for this and it is nowhere.

**Comment by slemeur** [comment]
cc @rkratky .

Hi @pavangayakwad, If you want to move a Che 6 workspace to a Che 7 workspaces, we would recommend you to create a devfile. You can learn more about devfile on the following repository (will be turned into documentation on che's docs):
- Devfile repository: https://github.com/redhat-developer/devfile
- Devfile docs: https://redhat-developer.github.io/devfile/
- Redefined stacks for Che 7: https://github.com/eclipse/che-devfile-registry/tree/master/devfiles
- You have some samples available here: https://github.com/redhat-developer/devfile/tree/master/samples 

Please let us know how this goes and if you have any issues, please create a new one Che repository. You'll not be the only user to do that effort and sharing the experience would be valuable to the community.

**Pull request merged**
