### PR TITLE
Selenium: Delete the 'try-catch' expression from 'refactor.parameters' tests

### PR DESCRIPTION
**Pull request by artaleks9**
### What does this PR do?
* Delete the _try-catch_ expression for the selenium tests in the package _refactor.parameters_ related to close issue
* Related selenium tests: _RenameParametersTest_, _FailParametersTest_

### What issues does this PR fix or reference?
#11185
#12209

### CODE REVIEW

**Review by SkorikSergey — APPROVED** [review]

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1316/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1316//Selenium_20tests_20report/)
docker image: eclipseche/che-server:12210
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by artaleks9** [comment]
ci-test

**Review by dmytro-ndp — APPROVED** [review]

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1317/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1317//Selenium_20tests_20report/)
docker image: eclipseche/che-server:12210
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by artaleks9** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1320/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1320//Selenium_20tests_20report/)
docker image: eclipseche/che-server:12210
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Pull request merged**
