### PR TITLE
fix #13660 - Replace mentions of 'oAuth', by more accurate 'OAuth'. (See https://oauth.net/)

### LINKED ISSUE #13660: In visible parts, replace mentions of 'oAuth', by more accurate 'OAuth'
### Description

The Eclipse Che user interface (Web UI, configuration files, logs) contains multiple mentions of `oAuth`, but it's supposed to be `OAuth`, as stated on  https://oauth.net/.

### Reproduction Steps

These are the occurences of `oAuth` that need to be changed:

1. ./multiuser/keycloak/che-multiuser-keycloak-server/src/main/java/org/eclipse/che/multiuser/keycloak/server/KeycloakServiceClient.java:        // we should threat this as unauthorized and send to oAuth login page.
2. ./assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties:# You can setup GitHub oAuth to automate authentication to remote repositories.
3. ./assembly/assembly-wsmaster-war/src/main/webapp/WEB-INF/classes/che/che.properties:# You need to first register this application with GitHub oAuth.
8. ./dashboard/src/app/workspaces/create-workspace/project-source-selector/add-import-project/import-github-project/oauth-dialog/no-github-oauth-dialog.controller.ts: * @description This class is handling the controller for the no Github oAuth dialog
9. ./dashboard/src/app/workspaces/create-workspace/project-source-selector/add-import-project/import-github-project/oauth-dialog/no-github-oauth-dialog.html:<che-popup title="GitHub oAuth" on-close="noGithubOauthDialogController.hide()">
10. ./dashboard/src/app/workspaces/create-workspace/project-source-selector/add-import-project/import-github-project/oauth-dialog/no-github-oauth-dialog.html:    <div>GitHub oAuth is not configured. {{noGithubOauthDialogController.message}}</div>
11. ./dashboard/src/components/api/che-o-auth-provider.factory.ts: * This class is handling the registered oAuth providers.
12. ./dashboard/src/components/api/che-api.factory.ts:   * The Che oAuth Provider API
13. ./wsmaster/che-core-api-user-shared/src/main/java/org/eclipse/che/api/user/shared/dto/UserDto.java:  @ApiModelProperty("User alias which is used for oAuth")
14. ./wsmaster/che-core-api-auth/src/main/java/org/eclipse/che/security/oauth/OAuthAuthenticatorTokenProvider.java:/** Retrieves oAuth token with help of OAuthAuthenticatorProvider. */
15. ./deploy/openshift/deploy_che.sh:Setup OpenShift oAuth: ${SETUP_OCP_OAUTH}
16. ./deploy/openshift/deploy_che.sh:        printInfo "Registering oAuth client in OpenShift"
17. ./deploy/openshift/deploy_che.sh:        # register oAuth client in OpenShift
18. ./deploy/openshift/deploy_che.sh:        printInfo "Registering oAuth client in Keycloak"
19. ./deploy/openshift/deploy_che.sh:        # setup Che variables related to oAuth identity provider
20. ./deploy/openshift/templates/che-server-template.yaml:  description: GitHub oAuth app client ID. Applicable to Che single user only!
21. ./deploy/openshift/templates/che-server-template.yaml:  description: GitHub oAuth app client servet. Applicable to Che single user only!
22. ./selenium/che-selenium-test/README.md:where `OPENSHIFT_TOKEN` is optional and is aimed to replace username/password when OpenShift is configured with oAuth. 
23. ./ide/che-core-ide-app/src/main/resources/org/eclipse/che/ide/CoreLocalizationConstant.properties:project.import.ssh.key.upload.failed.text=We are unable to clone your repository even though you\''ve configured oAuth access. \

### PR DESCRIPTION
**Pull request by themr0c**

### CODE REVIEW

**Comment by benoitf** [comment]
ci-build

**Review by mshaposhnik — APPROVED** [review]

**Comment by musienko-maxim** [comment]
Can one of the admins verify this PR?

**Review by skabashnyuk — APPROVED** [review]

**Comment by skabashnyuk** [comment]
ci-test

**Comment by skabashnyuk** [comment]
@themr0c your changes is not possible to compile.
can you take a look?
```
12:32:54 /home/codenvy/workspace/che-pullrequests-test-ocp/wsmaster/che-core-api-auth/src/main/java/org/eclipse/che/security/oauth/OAuthAuthenticationService.java:37: warning: [OvershadowingSubclassFields] Overshadowing variables of superclass causes confusion and errors. This variable is overshadowing a variable in superclass:  Service
12:32:54   @Context protected UriInfo uriInfo;
12:32:54                              ^
12:32:54     (see http://errorprone.info/bugpattern/OvershadowingSubclassFields)
12:32:54 /home/codenvy/workspace/che-pullrequests-test-ocp/wsmaster/che-core-api-auth/src/main/java/org/eclipse/che/security/oauth/OAuthAuthenticatorTokenProvider.java:27: error: cannot find symbol
12:32:54     this.oAuthAuthenticatorProvider = oAuthAuthenticatorProvider;
12:32:54         ^
12:32:54   symbol: variable oAuthAuthenticatorProvider
12:32:54 /home/codenvy/workspace/che-pullrequests-test-ocp/wsmaster/che-core-api-auth/src/main/java/org/eclipse/che/security/oauth/OAuthAuthenticatorTokenProvider.java:33: error: cannot find symbol
12:32:54         oAuthAuthenticatorProvider.getAuthenticator(oauthProviderName);
12:32:54         ^
12:32:54   symbol:   variable oAuthAuthenticatorProvider
12:32:54   location: class OAuthAuthenticatorTokenProvider
12:32:54 2 errors
12:32:54 1 warning
12:32:54 [JENKINS] Archiving disabled
```

**Comment by themr0c** [comment]
I had committed by mistake a change in a variable name. I fixed the error and amended the commit. Thank you @skabashnyuk and Jenkins.

**Comment by themr0c** [comment]
Fixed eclipsefdn/eca issue.

**Comment by benoitf** [comment]
ci-build

**Comment by skabashnyuk** [comment]
ci-test

**Comment by skabashnyuk** [comment]
@l0rd can we merge this pr at this moment or we'll postpone it after GA?

**Comment by l0rd** [comment]
@skabashnyuk PR was created yesterday so that's borderline. I am +1 if it's risk free from a QE point of view because. @rhopp if you see any risk merging this PR let's postpone it to 7.1.0, otherwise let's merge it to master.

**Review by ashumilova — APPROVED** [review]

**Comment by skabashnyuk** [comment]
ci-test

**Review by rhopp — APPROVED** [review]
Sorry I got to this PR with such delay. Going through PR I think it's safe to merge in 7.0.

**Comment by l0rd** [comment]
Label `do-not-merge/hold` removed

**Comment by skabashnyuk** [comment]
@eclipse/eclipse-che-qa can you take a look at the report?

**Comment by SkorikSergey** [comment]
Selenium tests execution on Eclipse Che Multiuser on OCP (https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1890//Selenium_20tests_20report/) doesn't show any regression against this Pull Request.

**Pull request merged**
