### PR TITLE
correct typo in comment

### PR DESCRIPTION
**Pull request by RickJWagner**
### What does this PR do?
Corrects a minor typo.

### What issues does this PR fix or reference?
None.

Correct explanatory comment in *WorkspaceServiceAccount classes for Kubernetes and OpenShift.

### CODE REVIEW

**Comment by RickJWagner** [comment]
It appears the workflow bots do not recognize my Eclipse Foundation license credentials.  These can be validated at https://accounts.eclipse.org/users/rwagnersph

**Comment by sleshchenko** [comment]
@RickJWagner Thanks for the contribution.

> It appears the workflow bots do not recognize my Eclipse Foundation license credentials

Could you please sign off your commit and repush?
```
git commit --amend --no-edit --signoff
git push -f ...
```

**Comment by metlos** [comment]
I forced revalidation of the ECA and it now passes.

**Review by amisevsk — APPROVED** [review]

**Review by sleshchenko — APPROVED** [review]

**Comment by sleshchenko** [comment]
ci-build

**Comment by sleshchenko** [comment]
@RickJWagner I've merged this PR. Thanks for your contribution :+1:

**Pull request merged**
