### PR TITLE
CHE-127: Load repo button on import from Github takes too much time

### PR DESCRIPTION
**Pull request by tolusha**
Signed-off-by: Anatoliy Bazko abazko@codenvy.com

### CODE REVIEW

**Comment by sleshchenko** [comment]
OK for me

**Comment by skabashnyuk** [comment]
Can you explain what is happening here?

**Comment by tolusha** [comment]
Missing dependency

**Comment by tolusha** [comment]
Dependency plugin requires this dependency to use @Nullable annotation

**Comment by skabashnyuk** [comment]
ok

**Pull request merged**
