### PR TITLE
[WIP] update according to changes in everrest

### PR DESCRIPTION
**Pull request by andrew00x**
Linked to https://github.com/codenvy/everrest/pull/23

### CODE REVIEW

**Comment by benoitf** [comment]
is it a work in progress pull request ? or it requires a new external component to be integrated in Che if so it should contains indicator about that or link to the required dependency "update version" issue/pr

**Comment by mkuznyetsov** [comment]
Some of the che-core-api-project tests fail on assertion of response "Location" header like here:
https://github.com/andrew00x/che/blob/master/wsagent/che-core-api-project/src/test/java/org/eclipse/che/api/project/server/ProjectServiceTest.java#L938

Expected :http://localhost:8080/api/project/file/my_project/a/b/c/test.txt
Actual     :http://localhost:8080/api/project/file/my_project%2Fa%2Fb%2Fc%2Ftest.txt

**Comment by mkuznyetsov** [comment]
If merged with current master branch, Che wsmaster won't start:
Tomcat logs - http://pastebin.com/71NzUSn9
Problematic service - https://github.com/eclipse/che-lib/blob/master/swagger/che-swagger-module/src/main/java/org/eclipse/che/swagger/rest/SwaggerSpecificationService.java

**Comment by mkuznyetsov** [comment]
If merged with master, on project importing, in the end it will start syncing with wsmaster.
It will start making PUT queries like:
http://localhost:8080/wsmaster/api/workspace/workspace6macbhg8qxr4ee0m/project/%2Fsmals 
It will return 400 error.

Syncing code:
https://github.com/eclipse/che/blob/658410556f8d0d5c91316890111ff7dc9d57cba1/wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/WorkspaceProjectsSyncer.java#L62-L62

In general, everything that uses workspace service's update project will fail similary

**Comment by mkuznyetsov** [comment]
```
protected void updateProject(ProjectConfig project) throws ServerException {

    final String href = UriBuilder.fromUri(apiEndpoint)
                                  .path(WorkspaceService.class)
                                  .path(WorkspaceService.class, "updateProject")
                                  .build(workspaceId, project.getPath()).toString();
    try {
        httpJsonRequestFactory.fromUrl(href).usePutMethod().setBody(asDto(project)).request();
    } catch (IOException | ApiException e) {
        throw new ServerException(e.getMessage());
    }

}
```

here:
href = "http://che-host:8080/wsmaster/api/workspace/workspacerakstqx7gu2gixh3/project/%2Fsimple-2"
project.getPath() = "/simple-2"

on master:
href = http://che-host:8080/wsmaster/api/workspace/workspacegt6uiep1lt9088kw/project//simple-2
project.getPath() = "/simple-2"

https://github.com/eclipse/che/blob/master/wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/WorkspaceHolder.java#L113

video, showing the problem on UI: https://youtu.be/iNzTRuR6WWw
archive with tomcat : https://www.dropbox.com/s/chg2o1talgln6sn/che-4.4.0-andrew00x.tar.gz?dl=0

**Comment by skabashnyuk** [comment]
https://github.com/eclipse/che/pull/1291

**Comment by mkuznyetsov** [comment]
closed as old duplicate of https://github.com/eclipse/che/pull/1625

**Pull request closed without merging**
