### PR TITLE
Add ability to get File Type by provider and avoid File Type collision

### PR DESCRIPTION
**Pull request by RomanNikitenko**
### What does this PR do?
- add ability to get File Type by provider and avoid File Type collision.
- clean up Language Server Registry and Editor Registry when a workspace is stopped or Ws agent server is stopped

### What issues does this PR fix or reference?
#9467 
Signed-off-by: Roman Nikitenko <rnikiten@redhat.com>

### CODE REVIEW

**Comment by RomanNikitenko** [comment]
ci-test

**Review by dkulieshov — APPROVED** [review]

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/540/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/540//Selenium_tests_report)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10640)
docker image: eclipseche/che-server:10640
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by RomanNikitenko** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/557/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/557//Selenium_tests_report)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10640)
docker image: eclipseche/che-server:10640
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by RomanNikitenko** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/580/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/580//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10640)
docker image: eclipseche/che-server:10640
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by RomanNikitenko** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/587/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/587//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10640)
docker image: eclipseche/che-server:10640
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by musienko-maxim** [comment]
The existed selenium tests did not find new regression

**Review by musienko-maxim — APPROVED** [review]

**Review by vparfonov — APPROVED** [review]

**Pull request merged**
