### PR TITLE
CODENVY-659: remove unnecessary data from workspace config

### PR DESCRIPTION
**Pull request by akurinnoy**
which is used in export workspace widget

Signed-off-by: Oleksii Kurinnyi okurinnyi@codenvy.com

### CODE REVIEW

**Comment by benoitf** [comment]
why are we not using the export workspace API anymore ?

**Comment by akurinnoy** [comment]
because this API provides full workspace config including unnecessary properties

**Comment by benoitf** [comment]
if there are runtime properties, then server side should have option to disable it, I don't see why client should do tons of parsing to cleanup server response

**Comment by ashumilova** [comment]
it's not only properties, links as well are not needed there

**Comment by benoitf** [comment]
ok as workaround before proper way provided through CHE-1355

**Comment by ashumilova** [comment]
Need to export workspace config and omit other workspace instance stuff.
For future - https://jira.codenvycorp.com/browse/CHE-1355

**Pull request merged**
