### PR TITLE
Refine underline style when tab marked with error or warning

### PR DESCRIPTION
**Pull request by vzhukovs**
### What does this PR do?
This changes proposal refines the styles in editor tab when the last one is marked with error or warning.

Before:
eclipse che 2017-12-13 15-12-44

After:
eclipse che 2017-12-13 15-54-05

Signed-off-by: Vladyslav Zhukovskyi <vzhukovs@redhat.com>

### What issues does this PR fix or reference?
N/A

#### Release Notes
Refine underline style when tab marked with error or warning

#### Docs PR
N/A

### CODE REVIEW

**Comment by vzhukovskii** [comment]
Or error underline may be more contrastive:
eclipse che 2017-12-13 15-54-05

**Comment by vitaliy-guliy** [comment]
More contrasting looks better.

**Comment by skabashnyuk** [comment]
Please change target branch of this pr to master branch.

**Comment by vzhukovs** [comment]
@skabashnyuk done

**Review by ashumilova — APPROVED** [review]

**Pull request merged**
