### PR TITLE
Avoid using unsupported project's properties

### PR DESCRIPTION
**Pull request by ashumilova**
### What does this PR do?
- Avoid using unsupported "path" and "displayName" properties in projects
- Cleanups the console output from error: "Property 'githubToken' does not exist on type 'Storage'." 

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/13991

### CODE REVIEW

**Comment by ashumilova** [comment]
ci-test

**Review by olexii4 — APPROVED** [review]

**Review by nickboldt — APPROVED** [review]
+0, no opinion.

**Comment by ashumilova** [comment]
ci-test

**Comment by artaleks9** [comment]
Selenium tests execution on Eclipse Che Multiuser on OCP (https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1947/) doesn't show any regression against this Pull Request.

**Pull request merged**
