### PR TITLE
Loader fix

### PR DESCRIPTION
**Pull request by mshaposhnik**
### What does this PR do?
Contains loader.html fixes for correct `reridectUr`l validation (check if any server url is a subpart or a redirectUrl)

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/10349

### CODE REVIEW

**Review by akurinnoy — APPROVED** [review]

**Review by skabashnyuk — APPROVED** [review]

**Comment by mshaposhnik** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/533/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/533//Selenium_tests_report)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10619)
docker image: eclipseche/che-server:10619
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by mshaposhnik** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/536/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/536//Selenium_tests_report)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10619)
docker image: eclipseche/che-server:10619
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Pull request merged**
