### PR TITLE
IDEX-3871: Update name of Che modules

### PR DESCRIPTION
**Pull request by TylerJewell**
1. Change "assembly-sdk" -> "assembly"
2. Change "assembly-sdk-war" -> "assembly-war"
3. Fix maven-assembly plug-in to no longer attempt to include examples.

Moved all of the plug-in example files out of master branches.  Will update plug-in examples for Che in another issue and PR.

### CODE REVIEW

**Comment by garagatyi** [comment]
Looks like you have deleted ALL sh files. I think you just moved them because of renaming parent folder.
By default not indexed yet sh files are ignored due to our .gitignore file.
Take a look at your file system and check if all changes was indexed by git.
To add sh file to index use **git add -f /path/to/file**

**Comment by garagatyi** [comment]
Description of this issue doesn't describe why you added server.xml file. Remove it or add comment.

**Comment by garagatyi** [comment]
You removed .bat files. Is it on purpose?

**Comment by garagatyi** [comment]
Also please synchronize your PR with current master

**Comment by TylerJewell** [comment]
Merged this branch with IDEX-3975 updates, and fixed remaining issues.  Merge the other PR before merging this branch.

**Comment by garagatyi** [comment]
@skabashnyuk @vparfonov WDYT?

**Comment by garagatyi** [comment]
You changed eclipse license file. You can compare: 
https://raw.githubusercontent.com/codenvy/che/master/assembly-ide/src/assembly/LICENSE.txt
https://raw.githubusercontent.com/codenvy/che/IDEX-3871/assembly-main/src/assembly/LICENSE

**Comment by vparfonov** [comment]
ok

**Comment by skabashnyuk** [comment]
ok

**Pull request merged**
