### PR TITLE
Optimize Dockerfile

### PR DESCRIPTION
**Pull request by ghost**
Signed-off-by: Eugene Ivantsov eivantsov@codenvy.com

### CODE REVIEW

**Comment by ghost** [comment]
Removed curl and ca-certificates

**Comment by benoitf** [comment]
seems we lost comment instruction on first line from previous PR ?

**Comment by juampe** [comment]
¿Optimize? This is literraly a rip of ubuntu docker che flavour.

**Comment by TylerJewell** [comment]
It reduces the deault image to run Che by 200MB.  The workspace images are still based upon ubuntu.

**Comment by juampe** [comment]
Sorry, now I got it

some test

```
root@rails:/opt/che# docker build -t codenvy/che -f Dockerfile .Sending build context to Docker daemon 53.53 MB
Step 1 : FROM alpine:3.4
 ---> 4e38e38c8ce0
Step 2 : ENV LANG C.UTF-8 JAVA_HOME /usr/lib/jvm/default-jvm/jre PATH ${PATH}:${JAVA_HOME}/bin CHE_HOME /home/user/che
 ---> Using cache
 ---> d61ea4bcd9ec
Step 3 : RUN echo "http://dl-4.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories &&     apk upgrade --update &&     apk add --update docker openjdk8 sudo bash &&     addgroup -S user -g 1000 &&     adduser -S user -h /home/user -s /bin/bash -G root -u 1000 -D &&     adduser user docker &&     adduser user user &&     echo "%root ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers &&     rm -rf /tmp/* /var/cache/apk/*
 ---> Using cache
 ---> a4d3d9547fee
Step 4 : EXPOSE 8000 8080
 ---> Using cache
 ---> f85695eccdb9
Step 5 : USER user
 ---> Using cache
 ---> 7ffccc7b76a6
Step 6 : ADD /assembly/assembly-main/target/eclipse-che-*/eclipse-che-* /home/user/che/
No source files were specified

```

I supose  I must got the che compitation in /assembly/assembly-main/target/eclipse-che-_/eclipse-che-_

**Comment by TylerJewell** [comment]
Yes.

Why build it though?  You can just docker pull Codenvy/Che.

**Pull request merged**
