### PR TITLE
Revert status bar panel

### PR DESCRIPTION
**Pull request by vzhukovs**
### What does this PR do?
This changes proposal reverts deletion of status bar panel.

Signed-off-by: Vladyslav Zhukovskyi <vzhukovs@redhat.com>

### What issues does this PR fix or reference?
#7314 

#### Changelog
Revert status bar panel

#### Release Notes
N/A

#### Docs PR
N/A

### CODE REVIEW

**Comment by vzhukovs** [comment]
ci-test

**Review by ashumilova — APPROVED** [review]

**Comment by ashumilova** [comment]
Can you please attach screenshot?

**Comment by vzhukovs** [comment]
@ashumilova sure:
eclipse che _ workspacefss2wu 2017-11-27 13-46-46

**Review by vitaliy-guliy — APPROVED** [review]

**Review by vparfonov — APPROVED** [review]

**Comment by slemeur** [comment]
@vzhukovskii : As discussed, please update the border's style around the loader.
You should use a style that is consistent (like the button border in the top navigation bar)

**Comment by vzhukovs** [comment]
@slemeur, I'd propose to remove the border at all, for example, this variant looks better as for me:
eclipse che _ workspacefss2wu 2017-11-27 15-52-46
than this one:
eclipse che _ workspacefss2wu 2017-11-27 15-54-38
(the border is painted the same as button border in top menu)

**Review by musienko-maxim — APPROVED** [review]

**Comment by vzhukovs** [comment]
As for styling the loader, it will be related directly to the maven plugin functionality. So there is need to create a dedicate issue.

**Pull request merged**
