### PR TITLE
CHE-6114: Fix problems with project explorer performance in big projects

### LINKED ISSUE #6114: Workspaces stuck consuming 100% CPU since 5.17
We are experimenting with v5.17.0. It seems a bug has been introduced that causes che to get stuck (indefinitely) consuming 100% of the CPU when retrieving the project file tree.

I can reliably reproduce this by switching between v5.16.0 (where it doesn't happen) to v5.17.0 where it does.

The process in question is the main workspace process:

`/usr/lib/jvm/java-1.8.0-openjdk-amd64/bin/java -Dnop -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Xms256m -Xmx2048m -Djava.security.egd=file:/dev/./urandom -Dche.logs.dir=/home/user/che/ws-agent/logs -Dche.logs.level=INFO -Djuli-logback.configurationFile=file:/home/user/che/ws-agent/conf/tomcat-logger.xml -Djdk.tls.ephemeralDHKeySize=2048 -Djava.protocol.handler.pkgs=org.apache.catalina.webresources -agentlib:jdwp=transport=dt_socket,address=4403,server=y,suspend=n -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dche.local.conf.dir=/mnt/che/conf -classpath /home/user/che/ws-agent/conf/:/usr/lib/jvm/java-1.8.0-openjdk-amd64/lib/tools.jar:/home/user/che/ws-agent/bin/bootstrap.jar:/home/user/che/ws-agent/bin/tomcat-juli.jar -Dcatalina.base=/home/user/che/ws-agent -Dcatalina.home=/home/user/che/ws-agent -Djava.io.tmpdir=/home/user/che/ws-agent/temp org.apache.catalina.startup.Bootstrap start`

I'm happy to provide access to che devs to the workspace in question if that helps debug the issue.

Large project trees seem to be the most affected.

### PR DESCRIPTION
**Pull request by vinokurig**
### What does this PR do?
1. Add ability to get Git status with filter.
2. Reworked Injecting VCS status info in Project service to make Status request only once instead of requesting each time in the loop.
3. Removed `format` parameter from get status method in Git Service, because it is redundant and do not affects to anything, since we use Jgit as a Git engine.

The main goal of calling git status with filter is to increase performance. Git status request without filter might be slow if project contains a lot of files.

### What issues does this PR fix or reference?
fixes https://github.com/eclipse/che/issues/6114

#### Changelog
Add ability to get Git status with filter

#### Release Notes
Fixed problems with project explorer performance in big project.

#### Docs PR

N/A

### CODE REVIEW

**Review by vparfonov — APPROVED** [review]

**Comment by davidwindell** [comment]
:+1:

**Comment by skryzhny** [comment]
@riuvshin  can we have it in bugfix release?
I'm observing big increaser of CPU usage after updating to 5.17.0

**Comment by vinokurig** [comment]
@tolusha Reworked `null` filter parameter of Git status to `emptyList()`

**Review by tolusha — APPROVED** [review]

**Comment by vinokurig** [comment]
Checking QA results

**Comment by bmicklea** [comment]
@vparfonov will this be merged in this sprint?

**Comment by vinokurig** [comment]
@bmicklea Selenium tests passed, I am going to merge it today

**Comment by davidwindell** [comment]
Thanks for all the work on this @vinokurig

**Pull request merged**
