### PR TITLE
Do not execute selenium tests under repair by default

### PR DESCRIPTION
**Pull request by dmytro-ndp**
### What does this PR do?
It excludes from test execution by default those tests which is treated as "been under repair", that is fails because of known failure.

It would simplify an analysis of regression test results.

### What issues does this PR fix or reference?
#11688

### CODE REVIEW

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1023/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1023//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11689
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1025/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1025//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11689
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1026/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1026//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11689
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1029/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1029//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11689
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1030/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1030//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11689
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1032/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1032//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11689
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1036/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1036//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11689
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1039/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1039//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11689
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1099/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1099//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11689
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1100/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1100//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11689
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1101/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1101//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11689
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by dmytro-ndp** [comment]
ci-test-docker-single

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Single user on Docker:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test/515/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test/515//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/11689)
docker image: eclipseche/che-server:11689
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by dmytro-ndp** [comment]
ci-test-docker-single

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Single user on Docker:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test/516/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test/516//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/11689)
docker image: eclipseche/che-server:11689
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1125/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1125//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11689
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1126/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1126//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11689
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Review by SkorikSergey — APPROVED** [review]

**Review by Ohrimenko1988 — APPROVED** [review]

**Review by artaleks9 — APPROVED** [review]

**Pull request merged**
