### PR TITLE
CHE-301 Enable Processes panel in machine and project perspective

### PR DESCRIPTION
**Pull request by vitaliy-guliy**
**_1 Upvote**_ Signed-off-by: Vitaliy Guliy vguliy@codenvy.com

### CODE REVIEW

**Comment by slemeur** [comment]
A snapshot?

**Comment by vitaliy-guliy** [comment]
screenshot from 2016-05-16 15 56 29

**Comment by slemeur** [comment]
OK for me

**Comment by ashumilova** [comment]
+1

**Comment by vparfonov** [comment]
ok

**Pull request merged**
