### PR TITLE
switch email from wish@codenvy.com to che-dev@eclipse.org

### LINKED ISSUE #12076: Update support email from wish@codenvy.com to che-dev@eclipse.org
### Description
Currently, support email still points to wish@codenvy.com [1]. Probably it would be better to update it and point to che-dev@eclipse.org

This email is currently used for `Make a wish` functionality. 

image

[1] https://github.com/eclipse/che/blob/master/dashboard/src/assets/branding/product.json#L12

### PR DESCRIPTION
**Pull request by sr229**
### What does this PR do?

Switches "Make a wish" link to `che-dev@eclipse.org` as stated on #12076 

### What issues does this PR fix or reference?

fixes eclipse/che#12076

#### Release Notes

N/A

#### Docs PR

N/A

### CODE REVIEW

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Review by ibuziuk — APPROVED** [review]

**Review by benoitf — APPROVED** [review]

**Comment by benoitf** [comment]
ci-build

**Comment by benoitf** [comment]
ci-test

**Comment by slemeur** [comment]
Thanks for the PR @sr229 !

**Comment by benoitf** [comment]
@ibuziuk waiting for QE

**Comment by slemeur** [comment]
sure

**Comment by benoitf** [comment]
@ibuziuk AFAIK check of ci-integration-tests is green just because it's finished, not because everything is ok.

**Comment by benoitf** [comment]
@ibuziuk why did you merge without QA approval ?

**Comment by ibuziuk** [comment]
@benoitf oh, sorry. I have not seen the comment regarding QA approval :/ I thought that if it is green we are good to merge

**Comment by artaleks9** [comment]
Selenium tests execution on Eclipse Che Multiuser on OCP (https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1281) doesn't show any regression against this Pull Request.

**Comment by benoitf** [comment]
thx @artaleks9

**Comment by dneary** [comment]
Tagging @bmicklea since right now he gets these emails.

**Pull request merged**
