### PR TITLE
[TS_SELENIUM] Create image for the "Happy Path" tests based on the "quay.io/eclipse/che-java11-maven" image

### PR DESCRIPTION
**Pull request by Ohrimenko1988**
### What does this PR do?
Create image for the "Happy Path" tests based on the "quay.io/eclipse/che-java11-maven" image

### What issues does this PR fix or reference?
Issue: https://github.com/eclipse/che/issues/14737

### CODE REVIEW

**Review by rhopp — APPROVED** [review]
I'm approving this PR, with two comments: 
• I'm a bit worried about `FROM quay.io/eclipse/che-java11-maven:nightly` - depending on nightly is OK for nightly builds... but these images are also built as part of the relase process, if I'm not mistaken... Is that OK with us?
• After merge of this PR, jobs building these dockerfiles would need to be updated (to include this new image).

It's up to you to consider this and merge/do changes.

**Comment by rhopp** [comment]
@Ohrimenko1988 So.... https://github.com/eclipse/che-devfile-registry/pull/111 is merged. During the night, the image should be published here: https://quay.io/repository/eclipse/happy-path (by this job: https://ci.centos.org/job/devtools-che-devfile-registry-nightly/)

One slight change I think it's good to mention. I've copied the mvn resources directly into `/home/user/.m2/repository`, so no further copying etc. is needed in test execution.

a.k.a.:
```
mkdir -p /projects/petclinic/?/.m2/repository && cp -r /.m2/* /projects/petclinic/?/.m2/repository
```
Parts like these ^^ we have in devfile commands should be unecessary. (I don't grok how they worked in the first place... What's the `?` location?)

**Comment by Ohrimenko1988** [comment]
ci-test

**Comment by Ohrimenko1988** [comment]
ci-build

**Comment by Ohrimenko1988** [comment]
ci-test

**Comment by Ohrimenko1988** [comment]
crw-ci-test

**Comment by Ohrimenko1988** [comment]
crw-ci-test

**Review by rhopp — APPROVED** [review]

**Pull request merged**
