### PR TITLE
CHE-436: replace "Open in IDE" to "Open project in IDE"

### PR DESCRIPTION
**Pull request by akurinnoy**
**_3 Upvotes**_ Signed-off-by: Oleksii Kurinnyi okurinnyi@codenvy.com

### CODE REVIEW

**Comment by akurinnoy** [comment]
@benoitf @ashumilova

**Comment by benoitf** [comment]
+1

**Comment by ashumilova** [comment]
+1

**Comment by olexii4** [comment]
+1

**Pull request merged**
