### PR TITLE
CHE-12329 Rework the way of retrieving editor provider by file-type

### LINKED ISSUE #12329: Regexp for pom.xml not working in LanguageServerConfig
### Description

The issue emerged between 6.15 (it's ok in 6.15) and 6.16.

In Bayesian language server config, the following regexp is used. However, Language Server isn't initialized when pom.xml is opened. LS is inited for package.json and requirements.txt though.

```
      public Map<String, String> getLanguageRegexes() {
        return ImmutableMap.<String, String>builder()
            .put(BayesianLanguageServerModule.TXT_LANGUAGE_ID, ".*requirements\\.txt")
            .put(JsonModule.LANGUAGE_ID, ".*package\\.json")
                // todo revert back to pom.xml when 
            .put("pom", ".*pom\\.xml")
            .build();
      }
```

Interestingly, `".*\\.xml"` works fine, however, in this case LS is initialized for all .xml files.

### PR DESCRIPTION
**Pull request by vinokurig**
### What does this PR do?
Fixes bug when a maven file-type (without linked editor provider) is registered and another file type for `pom.xml` files (with linked editor provider) is registered as well, but when the `pom.xml` file is opened default editor provider is returned. The fix iterates registered editor providers if the the default provider is registered for the found file type.

### What issues does this PR fix or reference?
fixes #12329 

#### Release Notes

N/A

#### Docs PR

N/A

### CODE REVIEW

**Review by RomanNikitenko — CHANGES_REQUESTED** [review]
What about recovery editor state after refreshing page for example?
I guess we have the same problem for this case and the corresponding logic is placed in the same file.
So may be we should apply the same fix for this case.
WDYT?

**Review by RomanNikitenko — APPROVED** [review]

**Comment by vinokurig** [comment]
@RomanNikitenko Agree, added changes

**Comment by vinokurig** [comment]
ci-test

**Review by dkulieshov — APPROVED** [review]

**Comment by eivantsov** [comment]
Are we good to merge this one?

**Comment by vinokurig** [comment]
I think we need to check the selenium tests report @musienko-maxim

**Comment by vinokurig** [comment]
ci-test

**Comment by vinokurig** [comment]
ci-test

**Review by musienko-maxim — APPROVED** [review]

**Pull request merged**
