### PR TITLE
Remove deploy.sh

### PR DESCRIPTION
**Pull request by tolusha**
Signed-off-by: Anatoliy Bazko <abazko@redhat.com>

### What does this PR do?
Removes `deploy.sh` `ocp.sh` scripts as deprecated.

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/13888

### CODE REVIEW

**Review by benoitf — APPROVED** [review]

**Review by skabashnyuk — APPROVED** [review]

**Comment by ibuziuk** [comment]
@tolusha could you clarify why the script was removed, but all the templates are still there?

**Comment by tolusha** [comment]
@ibuziuk 
I was not sure about templates. 
I assumed that they are used somewhere besides `deploy.sh` script

**Comment by ibuziuk** [comment]
AFAIK no cc: @skabashnyuk

**Comment by skabashnyuk** [comment]
yeh. this part https://github.com/eclipse/che/tree/master/deploy/openshift/templates/monitoring is still used. We are going to replace it with operator logic soon.

**Pull request merged**
