### PR TITLE
Upgrade java8 version for workspace master

### PR DESCRIPTION
**Pull request by skabashnyuk**
### What does this PR do?
Upgrade java8 version for workspace master and che-selenium-test

### What issues does this PR fix or reference?
n/a

#### Release Notes
n/a

#### Docs PR
n/a

### CODE REVIEW

**Comment by skabashnyuk** [comment]
ci-test

**Comment by skabashnyuk** [comment]
@eclipse/eclipse-che-qa wdyt?

**Review by riuvshin — APPROVED** [review]

**Review by benoitf — APPROVED** [review]

**Comment by skabashnyuk** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1201/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1201//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11977
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Pull request merged**
