### PR TITLE
Fix account linking url for frontend.

### PR DESCRIPTION
**Pull request by AndrienkoAleksandr**
Signed-off-by: Oleksandr Andriienko <oandriie@redhat.com>

### What does this PR do?
Fix account linking url for frontend.

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/18791

### How to test this PR?
Install Eclipse Che with help of chectl using `operator` or `OLM` installer. Set up github oAuth: https://www.eclipse.org/che/docs/che-7/administration-guide/configuring-authorization/#configuring-github-oauth_che. Add project to the devfile using user dashboard: how to do that described in the issue: https://github.com/eclipse/che/issues/18791

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by AndrienkoAleksandr** [comment]
[crw-ci-test]

**Review by skabashnyuk — APPROVED** [review]

**Comment by AndrienkoAleksandr** [comment]
I rebased pr.

**Comment by AndrienkoAleksandr** [comment]
I referenced Sonar lint proposal to the separated issue https://github.com/eclipse/che/issues/18818

**Comment by tolusha** [comment]
Tested. It works.
Pls backport changes to 7.24.x branch
Screenshot from 2021-01-18 14-29-40
Screenshot from 2021-01-18 14-33-42

**Review by tolusha — APPROVED** [review]

**Pull request merged**
