### PR TITLE
make it possible to disable closure compiler to speed up build

### PR DESCRIPTION
**Pull request by garagatyi**
**_1 Upvote**_ @evidolob @vparfonov @evoevodin

### CODE REVIEW

**Comment by voievodin** [comment]
As far as i understand it gives you ability to skip _JavaScript_ optimization during _cbuild_ build, which is almost 1 minute.
Nice improvement, Good Job! 

:+1:

**Comment by garagatyi** [comment]
For me is 1m 20s

**Comment by evidolob** [comment]
:+1:

**Comment by garagatyi** [comment]
We decided to move this property to parent pom

**Pull request closed without merging**
