### PR TITLE
Move the Openshift scripts from the cli image to the init image

### PR DESCRIPTION
**Pull request by davidfestal**
### What does this PR do?

It moves the Openshift scripts from the `cli` image to the `init` image, so that they are available locally after a `docker run cli:config`.

### What issues does this PR fix or reference?

This PR moves the files in a better place, which is consistent with the work done on PR https://github.com/eclipse/che/pull/6195.
So the merge of this PR would simplify the merge of PR #6195 (see [this comment](https://github.com/eclipse/che/pull/6195#discussion_r138675613)

### CODE REVIEW

**Comment by benoitf** [comment]
Documentation should be updated 
Initial Reference is at https://github.com/eclipse/che-docs/pull/280

**Comment by benoitf** [comment]
ci-build

**Review by l0rd — APPROVED** [review]

**Review by riuvshin — APPROVED** [review]

**Comment by davidfestal** [comment]
> Documentation should be updated

@benoitf done

**Review by benoitf — APPROVED** [review]

**Comment by l0rd** [comment]
The problem now is that if someone want to deploy on OpenShift and looks at [the documentation](https://www.eclipse.org/che/docs/setup/openshift/index.html) he will get an error:

```bash
curl https://raw.githubusercontent.com/eclipse/che/master/dockerfiles/init/scripts/openshift/deploy_che.sh
404: Not Found
```

@slemeur how long will it take to have https://github.com/eclipse/che-docs/pull/293 published?

**Pull request merged**
