### PR TITLE
feat: change Login, Logout, Stop and delete workspace tests to be hooks (suileSetup, suiteTeardown)

### LINKED ISSUE #22587: Change Login, Logout, Stop and delete workspace tests to be hooks (suileSetup, suiteTeardown)
### Is your task related to a problem? Please describe

On previous approach when each test was starting on new stage there was necessary to have Login tests before each test file. Now, if we run test one by one it looks redundant. We should keep one test spec to check login and logout, in other cases move this logic into suiteSetup hook, which will check if user logged and perform login if not. 
The same with deleting workspace by UI. We can check once and perform this action by API to save regression run time.

### Describe the solution you'd like

https://github.com/eclipse/che/blob/0811b7e4873b8d7ab3625eb4988a534fa538993d/tests/e2e/tests-library/LoginTests.ts#L31

Method should be updated according to logic above. Test files which used the methods should be updated. 

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by nallikaea**
### What does this PR do?
Closes #22587 

### What issues does this PR fix or reference?

#22587 

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [ ] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [ ] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [ ] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix or new feature ](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix-or-new-feature)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by nallikaea** [comment]
Trying to run on Jenkins

**Comment by nallikaea** [comment]
https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/Testing/job/e2e/job/basic/job/typescript-tests/13673/consoleFull

**Comment by dmytro-ndp** [comment]
@nallikaea : while PR looks commonly good, it's strange to see `[ERROR] CheReporter runner.on.fail: "Start workspace with existed workspace name" test PSI online-ocp 4.14 Stop created workspace failed after 35380ms` [1]:
- there is workspace remained existed which means removal through API failed;
- I would ignore stop / delete workspace by API error - just log error message, but not fail test results additionally, and don't save screenshot

[1] https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/Testing/job/e2e/job/basic/job/typescript-tests/13673/artifact/test-repo/tests/e2e/report/Start_workspace_with_existed_workspace_name_test_PSI_online-ocp_4.14_Stop_created_workspace/screenshot-Stop_created_workspace.png

**Comment by nallikaea** [comment]
@dmytro-ndp fixed

**Comment by nallikaea** [comment]
@dmytro-ndp run wih fixups https://reportportal-crw.apps.ocp-c1.prod.psi.redhat.com/ui/#devspaces/launches/all/155

**Comment by nallikaea** [comment]
https://github.com/eclipse/che/issues/22639

**Comment by nallikaea** [comment]
https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/Testing/job/e2e/job/basic/job/typescript-tests/13892/

**Review by dmytro-ndp — APPROVED** [review]
Thank you for various fixes, @nallikaea !

PR looks gooks to merge.
I will open followup issue to deal with `Failed to send log. Error: Item with tempId "undefined" not found` error (test run https://main-jenkins-csb-crwqe.apps.ocp-c1.prod.psi.redhat.com/job/Testing/job/e2e/job/basic/job/typescript-tests/13898/ )

P.S.: an issue: https://github.com/eclipse/che/issues/22648

**Pull request merged**
