### PR TITLE
Reduce warnings reported by Sonarqube

### PR DESCRIPTION
**Pull request by monaka**
### What does this PR do?

Fixes potential issues reported by SonarQube.

### What issues does this PR fix or reference?

No.

### CODE REVIEW

**Comment by monaka** [comment]
ci-build

**Comment by garagatyi** [comment]
It is great to have code cleaned up, but I'm concerned about addition of annotations without analysis whether it improves code quality. Also I'm not a big fan of putting final keyword everywhere, so not sure we need to apply it too.
But my opinion here is not very strong, so would like to hear other opinions.

**Comment by monaka** [comment]
@garagatyi I also don't think "all developers must add `final` to all variables." :-)
At the same, it is effective to reduce some kind of bugs by using `final`.
`public static` is a typical case.

Indeed I added some `final` to some auto variables. They are just my mater of taste.
The point of them are not `final` but another issues (possibility of NPE or resource leak).

**Comment by musienko-maxim** [comment]
Can one of the admins verify this PR?

**Comment by monaka** [comment]
I close this as it was obsolete.

**Pull request closed without merging**
