### PR TITLE
Fix websocket terminal launching in ssh machine

### PR DESCRIPTION
**Pull request by garagatyi**
@skabashnyuk @vparfonov @riuvshin Please review

### CODE REVIEW

**Comment by skabashnyuk** [comment]
How?

**Comment by garagatyi** [comment]
If you ment how this PR fix the problem then answer is my mistake when I implemented that feature. At that point it worked because of several coincedences and I decided that it works, but later I discovered that it doesn't work mostly.

**Comment by garagatyi** [comment]
So this PR changes permissions setting for websocket terminal files

**Comment by skabashnyuk** [comment]
Ok

**Comment by riuvshin** [comment]
LGTM

**Pull request merged**
