### PR TITLE
CODENVY-433 Rework recipes and stacks for compatibility with new permissions API

### PR DESCRIPTION
**Pull request by sleshchenko**
@gazarenkov @skabashnyuk Please review my changes

### CODE REVIEW

**Comment by TylerJewell** [comment]
@sleshchenko - can you merge your modifications to stacks.json with the modifications made this morning by @ddementieva?  Daria implemented a different ordering of the stacks based upon optimal engagement by the user.

**Comment by sleshchenko** [comment]
I've updated my branch to master

**Comment by sleshchenko** [comment]
@TylerJewell Yes, of course. I've updated my branch to master

**Comment by skabashnyuk** [comment]
ok

**Comment by benoitf** [comment]
it will break here
https://github.com/eclipse/che/blob/a8dfb6bf541940c636590119ef2fb45c1fa659c9/dashboard/src/components/api/che-recipe-template.factory.js#L32
https://github.com/eclipse/che/blob/2e5c0fefba8ec6c825334fd224e1149a49f4b2b5/dashboard/src/app/projects/create-project/create-project.controller.js#L749

**Comment by sleshchenko** [comment]
@benoitf Thanks, I'll fix it

**Comment by skabashnyuk** [comment]
ок

**Comment by voievodin** [comment]
ok

**Pull request merged**
