### PR TITLE
Add PHP and PHP + MySQL Che-7 stacks with samples

### PR DESCRIPTION
**Pull request by svor**
### What does this PR do?
Adds PHP and PHP + MySQL Che-7 stacks which include next plugins:

- [php-intelephense](https://github.com/eclipse/che-plugin-registry/blob/master/v3/plugins/redhat/php/latest/meta.yaml)
- [php debug](https://github.com/eclipse/che-plugin-registry/blob/master/v3/plugins/redhat/php-debugger/latest/meta.yaml)

Adds samples:

- [Hello World](https://github.com/che-samples/web-php-simple)
- [Laravel Real World example App](https://github.com/gothinkster/laravel-realworld-example-app)
- [Symfony demo application](https://github.com/symfony/)
- [Sample CRUD PHP+MySQL](https://github.com/taniarascia/pdo/tree/master)

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/13307

### CODE REVIEW

**Comment by svor** [comment]
ci-test

**Review by sleshchenko — APPROVED** [review]
LGTM
Just wondering if we need the corresponding devfiles in Che Devfile Registry, maybe a separate issue to port them. @l0rd WDYT?

**Review by tolusha — APPROVED** [review]

**Comment by tolusha** [comment]
ci-test

**Comment by l0rd** [comment]
@sleshchenko @svor yes it would be better to start contributing to the devfile-registry directly. But that can be done on a separate PR as well.

**Review by l0rd — APPROVED** [review]

**Comment by SkorikSergey** [comment]
Selenium tests execution on Eclipse Che Multiuser on OCP (https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1819//Selenium_20tests_20report/) doesn't show any regression against this Pull Request.

**Pull request merged**
