### PR TITLE
Upgrade fabric8-kubernetes-client version to v.4.1.0

### LINKED ISSUE #11112: Upgrade fabric8-kubernetes-client version to v.4.1.0
### Description
Che Server needs to create the special service account, role and role binding for workspace but role and role binding are not included into Kubernetes API of client version which we use. It is needed to update fabric8-kubernetes-client verion to v.4.0.4 as there is [the commit](https://github.com/fabric8io/kubernetes-client/pull/1111/commits/b5892eb158ad53fa33012b5c99b657de131860e4) which adds an ability to use RBAC objects via Kubernetes API.

It is needed for providing an access token for `terminal` and `exec` sidecars on Kubernetes Infrastructure https://github.com/eclipse/che/issues/10991

### PR DESCRIPTION
**Pull request by skabashnyuk**
### What should be done **BEFORE MERGE**:
- [x] Wait CQs for new version of fabric8-kubernetes client
  - [x]  kubernetes-client 4.1.0 https://dev.eclipse.org/ipzilla/show_bug.cgi?id=18047
  - [x]   kubernetes-model  4.1.0 https://dev.eclipse.org/ipzilla/show_bug.cgi?id=18048
  - [x]    openshift-client 4.1.0 https://dev.eclipse.org/ipzilla/show_bug.cgi?id=18049
- [x] Make sure that new fabric8-kubernetes client is compatible with old OCP versions where `Deployment` API is located under `extensions` but not `app`

### What does this PR do?
Upgrade fabric8-kubernetes-client version to v.4.1.0

### What issues does this PR fix or reference?
Fixes https://github.com/eclipse/che/issues/11112
Related to https://github.com/eclipse/che-parent/pull/89

#### Release Notes
n/a

#### Docs PR
n/a

### CODE REVIEW

**Comment by skabashnyuk** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1107/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1107//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11768
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by amisevsk** [comment]
@skabashnyuk I've added a commit moving changing the deployments calls:

```java
clientFactory.create(workspaceId)
             .extensions()
             .deployments()
```
to
```java
clientFactory.create(workspaceId)
             .apps()
             .deployments()
```
to reflect the deprecation of [`v1beta2` deployments](https://github.com/fabric8io/kubernetes-client/blob/master/CHANGELOG.md#400)

**Comment by skabashnyuk** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1110/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1110//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11768
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by skabashnyuk** [comment]
it's not working for now because of 
```
2018-10-30 07:30:28,789[aceSharedPool-3]  [WARN ] [.i.k.KubernetesInternalRuntime 224]  - Failed to start Kubernetes runtime of workspace workspacek8ih0yx3ls5q7ccb. Cause: Failure executing: POST at: https://172.29.4.74:8443/apis/apps/v1/namespaces/eclipse-che/deployments. Message: Deployment.apps "workspacek8ih0yx3ls5q7ccb.dockerimage" is invalid: [spec.selector: Required value, spec.template.metadata.labels: Invalid value: map[string]string{"che.original_name":"dockerimage", "che.workspace_id":"workspacek8ih0yx3ls5q7ccb", "che.deployment_name":"workspacek8ih0yx3ls5q7ccb.dockerimage"}: `selector` does not match template `labels`]. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=spec.selector, message=Required value, reason=FieldValueRequired, additionalProperties={}), StatusCause(field=spec.template.metadata.labels, message=Invalid value: map[string]string{"che.workspace_id":"workspacek8ih0yx3ls5q7ccb", "che.deployment_name":"workspacek8ih0yx3ls5q7ccb.dockerimage", "che.original_name":"dockerimage"}: `selector` does not match template `labels`, reason=FieldValueInvalid, additionalProperties={})], group=apps, kind=Deployment, name=workspacek8ih0yx3ls5q7ccb.dockerimage, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Deployment.apps "workspacek8ih0yx3ls5q7ccb.dockerimage" is invalid: [spec.selector: Required value, spec.template.metadata.labels: Invalid value: map[string]string{"che.original_name":"dockerimage", "che.workspace_id":"workspacek8ih0yx3ls5q7ccb", "che.deployment_name":"workspacek8ih0yx3ls5q7ccb.dockerimage"}: `selector` does not match template `labels`], metadata=ListMeta(_continue=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, 
```

**Comment by amisevsk** [comment]
@skabashnyuk Sorry, I didn't test the changes very well. I'll take a look and fix.

**Comment by amisevsk** [comment]
@skabashnyuk Sorry about that, I'm looking into it. From what I can tell, there isn't any difference in the deployment spec on the API, so this is strange.

**Comment by amisevsk** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1118/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1118//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11768
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by skabashnyuk** [comment]
ci-test

**Review by garagatyi — APPROVED** [review]
If tests are OK I'm OK with the change

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1119/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1119//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11768
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by SkorikSergey** [comment]
Selenium tests execution on Eclipse Che Multiuser on OCP (https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1119/) doesn't show any regression against this Pull Request.

**Comment by sleshchenko** [comment]
What should be done **BEFORE MERGE**:
- [ ] Create cq for new version of fabric8-kubernetes client
- [ ] Make sure that new fabric8-kubernetes client is compatible with old OCP versions where `Deployment` API is located under `extensions` but not `app`

**Comment by sleshchenko** [comment]
According to the [compatibility matrix](https://github.com/fabric8io/kubernetes-client#compatibility-matrix) from Fabri8 Kubernetes Client repository, there is no difference between 3.11.2 and 4.1.0
screenshot_20181101_161446

**Comment by garagatyi** [comment]
@sleshchenko I'm not sure that this matrix says that it is OK to use `/api/app` instead of `/api/extensions` on old versions of OS. I would check it live before merging the change. And we would still need to check it with the old versions of Kubernetes installations, right?

**Comment by sleshchenko** [comment]
@garagatyi I think (but not sure too) that matrix says that using of `kubernetes-client 4.0.0` is compatible with `OpenShift 3.6.0` and client (we) should not care where real API is located, he just uses available K8s Client API.

I'm OK to check it live before merging but I didn't find information in which OpenShift version API is moved to `app` instead of `kubernetes`.
And the question is which versions of Kubernetes and OpenShift we should check? 
I'll try Kubernetes 1.6.0 and OpenShift 3.6.0.

**Comment by sleshchenko** [comment]
I tried to do live check but:
1. I tried to install minikube v0.25.2 where 1.9.0 kubernetes is default but Kubernetes Dashboard failed to start because of some reasons. I took a look dashboard pod logs and didn't find clear error that I could be able to fix.
2. I installed minikube v0.26.0 but Kubernetes 1.10.0 is there by default and Deployment is on `api/v1` API but not `extensions`.
3. I tried to start minikube v0.26.0 but with specified 1.9.0 Kubernetes to use and minikube start to start
```
serg@sergpad:~/projects/che/deploy/openshift/templates$ minikube start --cpus 2 --memory 4096 --extra-config=apiserver.authorization-mode=RBAC --kubernetes-version v1.9.0
Starting local Kubernetes v1.9.0 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
^[[6~Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
E1102 16:01:29.279763   11087 start.go:276] Error starting cluster:  kubeadm init error sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests --ignore-preflight-errors=DirAvailable--data --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml --ignore-preflight-errors=Swap  running command: : running command: sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests --ignore-preflight-errors=DirAvailable--data --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml --ignore-preflight-errors=Swap 
 output: [init] Using Kubernetes version: v1.9.0
[init] Using Authorization modes: [Node RBAC]
[preflight] Running pre-flight checks.
        [WARNING DirAvailable--etc-kubernetes-manifests]: /etc/kubernetes/manifests is not empty
        [WARNING Swap]: running with swap on is not supported. Please disable swap
        [WARNING ExtraArgs]: kube-apiserver: failed to parse extra argument --require-kubeconfig=true
[preflight] Some fatal errors occurred:
        [ERROR CRI]: unable to check if the container runtime at "/var/run/dockershim.sock" is running: exit status 1
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
: running command: sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests --ignore-preflight-errors=DirAvailable--data --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml --ignore-preflight-errors=Swap 
.: Process exited with status 2
```
4. I've tried to test Che on minishift v1.3.1 where
```
OpenShift Master: v1.5.1+7b451fc
Kubernetes Master: v1.5.2+43a9be4
```
and `Deployment API` is located on `exstensions` but not `apps`
But Che Server failed to start because of
```
Error syncing pod, skipping: failed to "StartContainer" for "che" with RunContainerError: "GenerateRunContainerOptions: secrets \"openshift-identity-provider\" not found"
```


<br>I think we can upgrade fabric8 client version without live check since it requires a lot of effort.
Please let me know if someone thinks that live check is **REQUIRED**

**Comment by sleshchenko** [comment]
ci-test

**Review by sleshchenko — APPROVED** [review]

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1144/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1144//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11768
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by dmytro-ndp** [comment]
[E2E test results here](https://github.com/eclipse/che/pull/11768#issuecomment-436619870) looks without regression linked to pull request.
There are only slaky tests fails, and `TheiaBuildPluginTest` test failed unexpectedly because previous test workspace hadn't been removed in time.

**Pull request merged**
