### PR TITLE
CHE-12376: Fix IDE link navigation

### PR DESCRIPTION
**Pull request by vparfonov**
### What does this PR do?
Fix link navigation, now should work correct for GWT IDE and for Theia IDE

### What issues does this PR fix or reference?
#12376

### CODE REVIEW

**Review by slemeur — CHANGES_REQUESTED** [review]
No - we don't want to change the URL to access a workspace.

**Comment by vparfonov** [comment]
ok, will try to found other solution

**Comment by vparfonov** [comment]
ci-test

**Comment by vparfonov** [comment]
ci-test

**Comment by vparfonov** [comment]
ci-test

**Comment by vparfonov** [comment]
ci-test

**Comment by vparfonov** [comment]
ci-test

**Comment by vparfonov** [comment]
ci-test

**Comment by artaleks9** [comment]
Selenium tests execution on Eclipse Che Multiuser on OCP (https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1517/) doesn't show any regression against this Pull Request.

**Review by slemeur — APPROVED** [review]

**Comment by ibuziuk** [comment]
@riuvshin @vparfonov any chance we could include this to 6.18.0 or it is too late ?

**Pull request merged**
