### PR TITLE
Manage the list of plugins from Che plugins registry

### PR DESCRIPTION
**Pull request by ashumilova**
Signed-off-by: Anna Shumilova <ashumilo@redhat.com>

### What does this PR do?
Brings ability for the user to select Che plugins on workspace details page on "Plugins" tab.

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/10780

### CODE REVIEW

**Comment by ashumilova** [comment]
ci-test

**Review by benoitf — APPROVED** [review]
A screenshot of UI would be nice in PR's description

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/763/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/763//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/11143)
docker image: eclipseche/che-server:11143
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by slemeur** [comment]
How does this work?

Is this tab displayed for all workspaces, or only the ones with Theia?
Could/Should we remove the "Installers" tab if the "Plugins" tab is there?

Otherwise the table is efficient and good.
Maybe instead of "Use" I would say "Enable".

Question (not a priority right now):
Is this list sorted? Can I filter by the one enabled/disabled?

**Comment by ashumilova** [comment]
@slemeur 
1. the Plugins tab is displayed, when Che settings have the plugin registry location property set. It's displayed for all workspaces, cause it gives an opportunity to enable IDE ("theia-ide" on screenshot), so in general should not depend on the workspace's machine definition. 
2. yes, we can hide installers, when plugins are there - perhaps QE will have to adapt the tests
3. can easily change "Use" to "Enabled"
4. sorting by enabled - perhaps will bring to "dancing" items -> I will enable the last and it will go to the top.
5. filtering works by name

**Review by akurinnoy — APPROVED** [review]

**Comment by garagatyi** [comment]
Cool!

**Pull request merged**
