### PR TITLE
Deployment of tracing/monitoring/debug on OpenShift

### LINKED ISSUE #12541: Deploy Prometheus/Grafana   stack in OpenShift templates
### Description

We would like to add an ability to deploy Prometheus/Grafana with Che OpenShift templates.
- Deploy Prometheus/Grafana
- Connect  Prometheus to Che metric endpoint.
- Configure Grafana to use core metrics from Prometheus data source.
- Nice to have: connect Keycloak OAuth to  Prometheus/Grafana. To be able to manage admins users with keycloak

### PR DESCRIPTION
**Pull request by skabashnyuk**
### What does this PR do?
Added ability to enable
- Tracing with jaeger 
- Metrics collection with Prometheus and Grafana
- Correctly configured debug mode of che server.
- Added Che dashboard (based on @metlos  work)
-  Che Master JVM data

### What issues does this PR fix or reference?
Fixes https://github.com/eclipse/che/issues/12541

#### Release Notes
n/a

#### Docs PR
n/a

### CODE REVIEW

**Review by mshaposhnik — APPROVED** [review]

**Comment by skabashnyuk** [comment]
CC @rhopp

**Comment by skabashnyuk** [comment]
ci-test

**Review by garagatyi — APPROVED** [review]

**Review by sleshchenko — APPROVED** [review]

**Review by metlos — APPROVED** [review]

**Comment by skabashnyuk** [comment]
ci-test

**Comment by skabashnyuk** [comment]
@eclipse/eclipse-che-qa can you take a look?

**Review by l0rd — APPROVED** [review]

**Comment by metlos** [comment]
Maybe we should put the same dashboards into our helm chart as well? The one there is very rudimentary.

**Comment by skabashnyuk** [comment]
>Maybe we should put the same dashboards into our helm chart as well? The one there is very rudimentary.

@metlos yeah. It would be a nice thing to do too.

**Review by ibuziuk — APPROVED** [review]

**Comment by SkorikSergey** [comment]
Selenium tests execution on Eclipse Che Multiuser on OCP (https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1548//Selenium_20tests_20report/) doesn't show any regression against this Pull Request.

**Pull request merged**
