### PR TITLE
CHE-3210: Integration xterm.js instead of xterm.

### PR DESCRIPTION
**Pull request by AndrienkoAleksandr**
Signed-off-by: Aleksandr Andrienko <aandrienko@codenvy.com>

### What does this PR do?
Integrate xterm.js (version 2.2.3) widget instead of xterm. Source code of xtermjs: https://github.com/sourcelair/xterm.js. Site: http://xtermjs.org/

#### Changelog
Integrate xterm.js (version 2.2.3) widget instead of xterm.

#### Release Notes
We have replaced our terminal implementation with xterm.js, a Web terminal that is well-supported by Microsoft and Sourcelair. This update resolves a number of outstanding bugs and brings forward new terminal : 

1. Text-based application support: Use terminal to work with applications like bash and git
2. Curses-based application support: Use terminal to work with applications like vim and tmux
3. Mouse events support, which lets extension developers captural click and scroll events passing them to back-end controlling processes
4. Chinese, Japanese, and Korean character support
5. Insert international characters using IME input with your keyboard
6. Hotkeys for copy text: "Ctrl/Insert" and "Shift/Insert"
7. Horizontal scroll bar

The [xTerm project](http://github.com/sourcelair/xterm.js) and its various collaborators keep a rich set of terminal documentation. We are really pleased with the richness of the features, stability of the terminal, and the ecosystem commitment. We have and will continue to give contributions back as we make additional improvements.

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/3529

@azatsarynnyy @vparfonov @olexii4 @akurinnoy @skabashnyuk review please.

### CODE REVIEW

**Comment by TylerJewell** [comment]
Missing Changelog, Release Notes, and Docs PR.  We can see examples of what need to be done with this PR:  https://github.com/eclipse/che/pull/3940

Also - we should identify the PM that will review the release notes and docs PRs to verify completeness.  I recommend @JamesDrummond for this.

@JamesDrummond - as part of this review, we need to go through any old videos on Che site and any docs where we discuss terminal and make sure we are providing up to date information.

@AndrienkoAleksandr - this is very impressive work.

**Comment by skabashnyuk** [comment]
I suggest instead of copy entire xterm.js source code in our codebase inherit sources as maven dependency
```
<dependency>
    <groupId>org.webjars.npm</groupId>
    <artifactId>github-com-sourcelair-xterm-js</artifactId>
    <version>2.2.3</version>
</dependency>
```
and apply patches if needed. It will:
- simplify version upgrades
- reduce our codebase
- easy to see how we differ from upstream project

**Comment by AndrienkoAleksandr** [comment]
qa found bug https://github.com/eclipse/che/issues/3947 . I need fix it. I analyzed this issue: this is bug xterm.js parser. Midnight Commander send restore cursor sequence "8l", but xterm.js didn't save valid cursor position.

**Comment by AndrienkoAleksandr** [comment]
And we need fix (reproduces seldom) second bug: https://github.com/eclipse/che/issues/3958

**Comment by JamesDrummond** [comment]
@AndrienkoAleksandr Will this terminal have a "timeout" period? Currently the terminal after a period of inactivity will become unresponsive. I would like there to be no "timeout" period.

**Comment by AndrienkoAleksandr** [comment]
ci-build

**Comment by AndrienkoAleksandr** [comment]
ci-build

**Comment by TylerJewell** [comment]
Updated release notes.  I think we should merge this in time for 5.3.  The outstanding bugs seem like P2 bugs, and acceptable issues.  We can include advisory in the release notes for any known issues.  But @AndrienkoAleksandr @vkuznyetsov - let's plan to merge on Monday.

**Comment by bmicklea** [comment]
@AndrienkoAleksandr and @vkuznyetsov - this needs to be merged as part of 5.3. I've added milestone and blocker labels.

**Review by vparfonov — APPROVED** [review]

**Review by skabashnyuk — COMMENTED** [review]
Unsure the you adding third-party files that was part of CQ.

**Comment by AndrienkoAleksandr** [comment]
ci-build

**Comment by JamesDrummond** [comment]
Please provide status label.

**Pull request merged**
