### PR TITLE
Process isnt terminated when stopped from the Consoles panel

### PR DESCRIPTION
**Pull request by tolusha**
### What does this PR do?

Stops process that has been started in the terminal and close terminal.
### What issues does this PR fix or reference?

https://jira.codenvycorp.com/browse/CHE-1056
### Previous Behavior

The terminal is closed but process continue running
### Tests written?

Manual testing
### Docs requirements?

No

Please review [Che's Contributing Guide](https://github.com/eclipse/che/CONTRIBUTING.MD) for best practices.

### CODE REVIEW

**Comment by garagatyi** [comment]
Have you tested that with shell script that starts other process?
Have you tested that with GDB?

**Comment by tolusha** [comment]
@sleshchenko 
@garagatyi 
@skabashnyuk

**Comment by tolusha** [comment]
Unfortunately gdbserver can't be stopped in this way. Since it ignores Ctrl+C and Ctrl+Z.
`sleep` command for instance stops well.

**Comment by skabashnyuk** [comment]
Have you tested this on Windows and OSX?

**Comment by garagatyi** [comment]
This PR is not related to CHE-1056. Please remove issue number from PR and commit message

**Pull request closed without merging**
