### PR TITLE
6.11.1

### PR DESCRIPTION
**Pull request by amisevsk**
Point release, cherry-picking commits 
- `f838ea5a60` : https://github.com/eclipse/che/pull/10902
- `631729d447` : https://github.com/eclipse/che/pull/11253

### CODE REVIEW

**Review by mshaposhnik — APPROVED** [review]

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/833/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/833//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11292
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by ibuziuk** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/834/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/834//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11292
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by ibuziuk** [comment]
@riuvshin looks like there is a problem with parent pom 
```
16:33:21 [ERROR] [ERROR] Some problems were encountered while processing the POMs:
16:33:21 [FATAL] Non-resolvable parent POM for org.eclipse.che:che-parent:6.11.1-SNAPSHOT: Failure to find org.eclipse.che.depmgt:maven-depmgt-pom:pom:6.11.1-SNAPSHOT in https://oss.sonatype.org/content/repositories/snapshots/ was cached in the local repository, resolution will not be reattempted until the update interval of ossrh has elapsed or updates are forced and 'parent.relativePath' points at wrong local POM @ line 17, column 13
```
how should we proceed with it ?

**Comment by riuvshin** [comment]
you should submit PR against master, if it goes well then I will backport it to bugfix branch

**Comment by ibuziuk** [comment]
@riuvshin but PRs are already merged in master:

- `f838ea5a60` : https://github.com/eclipse/che/pull/10902
- `631729d447` : https://github.com/eclipse/che/pull/11253

**Review by riuvshin — APPROVED** [review]

**Review by ibuziuk — APPROVED** [review]

**Pull request merged**
