### PR TITLE
Add plugins widget on workspace creation

### PR DESCRIPTION
**Pull request by ashumilova**
Signed-off-by: Anna Shumilova <ashumilo@redhat.com>

### What does this PR do?
Adds plugin widget on workspace creation page.
Fixes tests.

### CODE REVIEW

**Comment by ashumilova** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/832/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/832//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11291
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by ashumilova** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/836/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/836//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11291
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Review by akurinnoy — APPROVED** [review]

**Review by benoitf — APPROVED** [review]

**Pull request merged**
