### PR TITLE
Fixed fetching content of files referenced in Devfile

### PR DESCRIPTION
**Pull request by sleshchenko**
### What does this PR do?
Fixed fetching content of files referenced in Devfile.

### What issues does this PR fix or reference?
This PR fixes a bug introduced in https://github.com/eclipse/che/pull/12743

#### Release Notes
N/A

#### Docs PR
N/A

### CODE REVIEW

**Review by skabashnyuk — APPROVED** [review]

**Review by metlos — COMMENTED** [review]
LGTM as such, but I wonder whether the signature of the `FileContentProvider#fetchContent` shouldn't be changed.

Firstly `String fetchContent(String filename) throws IOException` is too high level IMHO.

Secondly, the `filename` attribute doesn't have to be a filename at all, it is generally a path, and actually could be a URL (even though we have plans to introduce `url` attribute in #12733).

IMHO, the interface could look something like:

```java
Reader fetchContent(URI location) throws IOException;
```
at which point it could be used for both `local` and `url` without change. See also my changes in https://github.com/eclipse/che/pull/12800 that go in that direction as well.

**Review by mshaposhnik — APPROVED** [review]

**Comment by sleshchenko** [comment]
> Firstly `String fetchContent(String filename) throws IOException` is too high level IMHO.

If you mean that we should avoid `IOException` here - I agree with you.

> Secondly, the `filename` attribute doesn't have to be a filename at all, it is generally a path, and actually could be a URL (even though we have plans to introduce `url` attribute in #12733).

Makes sense in perspective but I think the current state is OK since we don't support referencing files with URL in devfile.

For me, it looks OK that FileContentProvider returns already fetched content without exposing low-level Reader, Stream, etc.

**Comment by metlos** [comment]
> For me, it looks OK that FileContentProvider returns already fetched content without exposing low-level Reader, Stream, etc.

If it had such IO-related signature, it'd avoid bugs like this one :)

**Review by metlos — APPROVED** [review]
I'm approving this PR as a bugfix to what we have. We can discuss the points I raised separately.

**Comment by sleshchenko** [comment]
Merged without `ci-test` because it was manually tested and affected functionality is not covered by selenium tests yet (see the corresponding issue https://github.com/eclipse/che/issues/12278)

**Pull request merged**
