### PR TITLE
CHE-12918 add checks for incompatible factories

### PR DESCRIPTION
**Pull request by olexii4**
Signed-off-by: Oleksii Orel <oorel@redhat.com>

### What does this PR do?
Show an error message in the case with incompatible CHE 6 factory. Reject incompatible factories resolving.

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/12918

Screenshot from 2019-05-30 10-40-46
Screenshot from 2019-05-30 10-38-52
Screenshot from 2019-05-30 10-38-09

Signed-off-by: Oleksii Orel <oorel@redhat.com>

### CODE REVIEW

**Comment by olexii4** [comment]
@slemeur WDYT?

**Comment by slemeur** [comment]
LGTM

**Review by slemeur — APPROVED** [review]

**Review by ashumilova — APPROVED** [review]

**Comment by olexii4** [comment]
ci-test

**Comment by skabashnyuk** [comment]
@olexii4 Does this pr make all persistent factories incompatible because they are not using devfile?

**Comment by olexii4** [comment]
@skabashnyuk No, it doesn't persistent all factories as incompatible. Only factories which include a CHE 6 workspace(with installers)

**Comment by olexii4** [comment]
@skabashnyuk Should I add devfile checks as a mandatory for both objects(workspace and factory)? Could you write an algorithm to check CHE 7 compatible workspaces and factories?

**Comment by skabashnyuk** [comment]
I think it should be a check of the existence of a devfile object in the workspace and factory objects.
At this moment we have it for workspaces https://github.com/eclipse/che/blob/master/wsmaster/che-core-api-workspace-shared/src/main/java/org/eclipse/che/api/workspace/shared/dto/WorkspaceDto.java#L32 but we don't have it for factories. We are planning to introduce it as part of  https://github.com/eclipse/che/issues/13423

**Comment by olexii4** [comment]
@slemeur WDYT?

**Comment by ashumilova** [comment]
This particular issue is about detecting "Che6" factories and notifying the user about them, as part of deprecation process. When devfile is introduced as part of the factory object, then we need to adjust following changes. But that fact doesn't block following PR to be merged. And for some period we will still be allowing to use workspaces with config.

**Review by akurinnoy — APPROVED** [review]

**Pull request merged**
