### PR TITLE
chore (CONTRIBUTING.md): update list of repos/components with links t…

### PR DESCRIPTION
**Pull request by sunix**
…o docs and devfiles

https://github.com/eclipse/che/issues/14126

### CODE REVIEW

**Review by benoitf — COMMENTED** [review]
should it be sorted by repo name after che one ?

**Comment by mmorhun** [comment]
I would like to avoid `---`, but put repository link instead.

**Comment by sunix** [comment]
> should it be sorted by repo name after che one ?

I have reordered a bit

**Review by benoitf — APPROVED** [review]

**Comment by sunix** [comment]
crw-ci-test

**Pull request merged**
