### PR TITLE
fix container cpu resource conversion

### LINKED ISSUE #18484: CPU request / limit in the plugin meta.yaml is not correctly translated on the k8s level
### Describe the bug
CPU request in the plugin meta.yaml is not correctly translated on the k8s level

e.g. `cpuRequest: "30m"` is translated to 30 cores (should be either 30m or 0.03):

### Che version
 - [ ] 7.22.0

### Steps to reproduce

devfile to reproduce:
```
metadata:
  name: test-cpulimit22qho
attributes:
  persistVolumes: 'false'
components:
  - type: cheEditor
    reference: >-
      https://gist.githubusercontent.com/sparkoo/cb5105fa1f01f29bf73eb238f6ae622f/raw/090062b9eca6a25ef5226d566ef9626d8a2ca012/theia_meta.yaml
    alias: che-theia
apiVersion: 1.0.0
```

Details in the 
- https://github.com/eclipse/che-plugin-registry/pull/716
- https://github.com/eclipse/che-plugin-registry/pull/716#issuecomment-735729772

### Expected behavior

`cpuRequest: "30m"` is transated to either `30m` or `0.03`

### Runtime
   - Openshift 4.6

### PR DESCRIPTION
**Pull request by sparkoo**
Signed-off-by: Michal Vala <mvala@redhat.com>

### What does this PR do?
Fix conversion of CPU resource into full cores for plugins.

### What issues does this PR fix or reference?

https://github.com/eclipse/che/issues/18484

### How to test this PR?

```
metadata:
  name: test-cpulimit22qho
attributes:
  persistVolumes: 'false'
components:
  - type: cheEditor
    reference: >-
      https://gist.githubusercontent.com/sparkoo/cb5105fa1f01f29bf73eb238f6ae622f/raw/090062b9eca6a25ef5226d566ef9626d8a2ca012/theia_meta.yaml
    alias: che-theia
apiVersion: 1.0.0
```
This devfile should now work and theia container should have 
```     
  cpuLimit: "1"
  cpuRequest: "0.03"
```

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by sparkoo** [comment]
[crw-ci-test --rebuild]

**Comment by sparkoo** [comment]
[ci-build]

**Review by amisevsk — APPROVED** [review]
LGTM

**Review by skabashnyuk — APPROVED** [review]

**Comment by sparkoo** [comment]
[crw-ci-test]

**Pull request merged**
