### PR TITLE
Minor typographical improvements to localization file.

### PR DESCRIPTION
**Pull request by zv-io**
### What does this PR do?

Fixes minor errors in grammar, spelling, and consistency within the localizations file.

### What issues does this PR fix or reference?

(n/a)

#### Release Notes

(n/a)

#### Docs PR

(n/a)

### CODE REVIEW

**Comment by riuvshin** [comment]
@vparfonov WDYT? 
@eclipse/eclipse-che-qa guys please consider these changes may affect tests

**Review by gorkem — APPROVED** [review]

**Review by slemeur — APPROVED** [review]

**Comment by skabashnyuk** [comment]
ci-test

**Comment by skabashnyuk** [comment]
@zv-io  you need to sign Eclipse CA https://www.eclipse.org/legal/ecafaq.php

**Comment by zv-io** [comment]
@skabashnyuk done.

**Comment by skabashnyuk** [comment]
@zv-io  your changes has compilation issues
```
http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd, jar:file:/home/codenvy/workspace/che-pullrequests-test-ocp/ide/che-core-ide-app/target/che-core-ide-app-6.7.0-SNAPSHOT.jar!/org/eclipse/che/ide/xml/xml.svg)
16:08:19 [INFO]    Computing all possible rebind results for 'org.eclipse.che.ide.CoreLocalizationConstant'
16:08:19 [INFO]       Rebinding org.eclipse.che.ide.CoreLocalizationConstant
16:08:19 [INFO]          Invoking generator com.google.gwt.i18n.rebind.LocalizableGenerator
16:08:19 [INFO]             Processing interface org.eclipse.che.ide.CoreLocalizationConstant
16:08:19 [INFO]                Generating method body for importProjectSshKeyUploadFailedText()
16:08:19 [INFO]                   [ERROR] Error parsing 'We are unable to clone your repository even though you've configured OAuth2 access. Some providers do not allow automatic upload of SSH keys. Please paste your SSH key manually in your provider account preferences.'
16:08:19 [INFO] java.text.ParseException: Unterminated single quote: We are unable to clone your repository even though you've configured OAuth2 access. Some providers do not allow automatic upload of SSH keys. Please paste your SSH key manually in your provider account preferences.
16:08:19 [INFO] 	at com.google.gwt.i18n.rebind.MessageFormatParser.parse(MessageFormatParser.java:467)
16:08:19 [INFO] 	at com.google.gwt.i18n.rebind.MessagesMethodCreator.createMethodFor(MessagesMethodCreator.java:1151)
16:08:19 [INFO] 	at com.google.gwt.i18n.rebind.AbstractLocalizableImplCreator.delegateToCreator(AbstractLocalizableImplCreator.java:490)
16:08:19 [INFO] 	at com.google.gwt.i18n.rebind.MessagesImplCreator.emitMethodBody(MessagesImplCreator.java:94)
16:08:19 [INFO] 	at com.google.gwt.user.rebind.AbstractGeneratorClassCreator.genMethod(AbstractGeneratorClassCreator.java:277)
16:08:19 [INFO] 	at com.google.gwt.user.rebind.AbstractGeneratorClassCreator.emitMethods(AbstractGeneratorClassCreator.java:239)
16:08:19 [INFO] 	at com.google.gwt.user.rebind.AbstractGeneratorClassCreator.emitClass(AbstractGeneratorClassCreator.java:118)
16:08:19 [INFO] 	at com.google.gwt.i18n.rebind.AbstractLocalizableImplCreator.generateConstantOrMessageClass(AbstractLocalizableImplCreator.j
```

**Comment by slemeur** [comment]
@skabashnyuk + @vkuznyetsov : Can you please help into getting the PR fixed and merged. The PR has been proposed long time ago and it was not reviewed since now...

**Review by vparfonov — APPROVED** [review]

**Comment by riuvshin** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test

**Pull request closed without merging**
