### PR TITLE
Fix the link to docs.

### PR DESCRIPTION
**Pull request by monaka**
### What does this PR do?

codenvy/che-doc to eclipse/che-doc.

### CODE REVIEW

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Review by gorkem — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Pull request merged**
