### PR TITLE
Contribute PatternFly starter template

### PR DESCRIPTION
**Pull request by dgutride**
### New behavior
Adds a PatternFly starter template for the Node.JS stack.  This uses on Angular 1 and makes use of PatternFly styles (www.patternfly.org) and bootstrap themes for building enterprise web applications.

### CODE REVIEW

**Comment by benoitf** [comment]
ci-build

**Comment by benoitf** [comment]
Hello @dgutride could you check you've a valid CLA
https://dev.eclipse.org/eclipse-webhook/services/status_details.php?id=581cbdd8f38ce

**Comment by dgutride** [comment]
@benoitf - Thanks for the quick feedback, I've filled out the necessary paperwork 👍

**Comment by TylerJewell** [comment]
Thanks for the contribution - it will show up in M7

**Pull request merged**
