### PR TITLE
Display configured project in project explorer after importing project

### PR DESCRIPTION
**Pull request by RomanNikitenko**
Signed-off-by: Roman Nikitenko rnikitenko@codenvy.com

We should fire CreateProjectEvent to display configured project in project explorer after importing project

### CODE REVIEW

**Comment by sleshchenko** [comment]
Commit message says about displaying smth but in the fact its changes sends event CreateProjectEvent after importing of project. Maybe it would better to fix commit message in accordance to changes

**Comment by RomanNikitenko** [comment]
What do you mean?
Change commit message to "sends event CreateProjectEvent after importing of project."?
But this commit will fix displaying configured project in project explorer and it does not matter which way.
Way how we reach it we can see in the changes...

**Comment by sleshchenko** [comment]
I mean that commit message should describe commit's changes. For now it is hard to understand that 'Display...' means adding missed firing of event that invoke some method with displaying new project in project tree. So you can change commit message to "Add sending of CreateProjectEvent after importing of project". And if you want to describe why you did these changes you can add number of issue in titile of commit message or use body of commit message.

**Comment by RomanNikitenko** [comment]
I think we can see in changes "Add sending of CreateProjectEvent after importing of project"
But why we do it?
I think my message is more informative for next developer...

**Comment by vparfonov** [comment]
ok

**Pull request merged**
