### PR TITLE
Autogenerated changes log.

### PR DESCRIPTION
**Pull request by skabashnyuk**
**_2 Upvotes**_ Output of https://github.com/skywinder/github-changelog-generator

### CODE REVIEW

**Comment by skabashnyuk** [comment]
yes

**Comment by garagatyi** [comment]
LGTM

**Comment by benoitf** [comment]
I think we need to add them just after the release (no changelog on master, only on tags)

**Comment by skabashnyuk** [comment]
Updated with 4.0.0-RC9  changes

**Comment by ghost** [comment]
+1 very helpful tool

**Comment by benoitf** [comment]
+1

**Comment by benoitf** [comment]
very good job

**Pull request merged**
