### PR TITLE
Use styled dialog instead of browser pop-up for goto line in compare widget

### PR DESCRIPTION
**Pull request by vparfonov**
Signed-off-by: Vitalii Parfonov <vparfonov@redhat.com>

### What does this PR do?
Use styled dialog instead of browser pop-up for goto file in compare widget

goto-compare-widget

### What issues does this PR fix or reference?
#2299 depends on https://github.com/eclipse/che-lib/pull/114

### CODE REVIEW

**Comment by vparfonov** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1077/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1077//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11738
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Review by azatsarynnyy — APPROVED** [review]

**Comment by vparfonov** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1080/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1080//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11738
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by vparfonov** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1082/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1082//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11738
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by RomanNikitenko** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1084/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1084//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11738
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by vparfonov** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1087/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1087//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11738
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by vparfonov** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1090/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1090//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11738
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by vparfonov** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1096/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1096//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11738
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Pull request merged**
