### PR TITLE
CHE-3438: Reuse shell interpreter passed to command line to start terminal

### PR DESCRIPTION
**Pull request by tolusha**
### What does this PR do?
Reuse shell interpreter passed to command line to start terminal

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/3438

### Previous behavior
`sh` was always used as shell interpreter to execute commands

### New behavior
Reuse shell interpreter passed to command line to start terminal

Please review [Che's Contributing Guide](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md) for best practices.

### CODE REVIEW

**Review by garagatyi — APPROVED** [review]

**Review by skabashnyuk — APPROVED** [review]

**Review by AndrienkoAleksandr — APPROVED** [review]

**Comment by TylerJewell** [comment]
@tolusha - when will we merge?

**Comment by tolusha** [comment]
When @evoevodin approve PR

**Comment by TylerJewell** [comment]
Lash him with some wet noodles, please.

**Review by voievodin — APPROVED** [review]
`go fmt` modified files

**Pull request merged**
