### PR TITLE
Follow up fixes after configuration property renaming

### PR DESCRIPTION
**Pull request by mkuznyetsov**
Fix issues related to problems with data mounting and properties/variables renaming

Related issue: https://github.com/eclipse/che/issues/2941

### CODE REVIEW

**Comment by mkuznyetsov** [comment]
@TylerJewell  your Windows SIGTERM issue related edits will be excluded from this PR, ok?

**Review by skabashnyuk — APPROVED** [review]

**Review by TylerJewell — CHANGES_REQUESTED** [review]
You cannot hard code a branch into the code.

**Review by TylerJewell — CHANGES_REQUESTED** [review]
Missing all of the fixes for the docker entry point that was merged into the cli-refactoring branch.

**Comment by TylerJewell** [comment]
Yes, please merge - lets get these changes rationalized quickly.  Ok to merge che-dockerfiles repository changes, too.

**Pull request merged**
