### PR TITLE
fixed minor "webscoket" typos

### PR DESCRIPTION
**Pull request by Patricol**
continued from #6790

### CODE REVIEW

**Comment by Patricol** [comment]
I can't change both files in one commit from just the website, and two pull requests would be insane to do.
I'll have to figure this out tomorrow.

**Review by garagatyi — APPROVED** [review]
Looks good. Thank you for your contribution!

**Comment by benoitf** [comment]
@Patricol did you find time to get ECA added as Signed-Off-By ?

**Comment by Patricol** [comment]
@benoitf 

It looks to me like both commits are signed off identically, and that only one failed the ip-validation check.
What exactly is the issue?

The incorrect(?) data in the ip-validation check's [details](https://dev.eclipse.org/eclipse-webhook/services/status_details.php?id=59e729a7cc7b5) (the users listed are noreply@github.com and web-flow) made me think the problem was no longer coming from my side, and I mistakenly interpreted my email notification of garagatyi's comment as indication that the PR was successful.

I'd assume that the error was caused by me using the github.com website to make the commits; (as it would make some sense for the committer to be "web-flow <noreply@github.com>", mismatching the "signed off by" line and causing the ip-validation check to fail,) but in that case I'd expect the ip-validation check to fail on both commits.

Thank you for your patience, by the way. 
As you may be able to tell from #6790's initial title; I prematurely submitted that PR by pressing enter while typing in its information; so I missed all of the notes about contribution guidelines.

**Comment by Patricol** [comment]
Nevermind; just noticed that only one of the two initial commits in this PR was tested; both would have failed.

So the issue was that you cannot have a compliant signed-off-by when committing from github.com's web-based editor.

Thank you for your time!

**Comment by benoitf** [comment]
@Patricol yes the github web editor is adding noreply@github.com and make ECA fails.

Thanks for your patience and the fix.

**Pull request merged**
