### PR TITLE
Devfile fixes

### PR DESCRIPTION
**Pull request by sleshchenko**
### What does this PR do?
This PR contains several fixes and improvements that are in separate commits:
1. Fix lazy initialization of collections in some POJOs. Previously they returned new collections implementation without saving it to field. As result invocation of `workspaceConfig.getAttibutes().put("something", "something")' does not modify `WorkspaceConfig`.

2. Move 'machineName' and 'plugin' attributes definition to Command class. It would prevent typos errors in other parts of code where this attribute is also set.

3. Fix configuring plugin reference for Devfile commands. 
Previously `pluginId` was used but actually Che Server respects only `plugin` attribute.

3. Fix Devfile commands converting
For some reasons, command name was used as `{DevfileCommand#getName}:{DevfileAction#getTool}`.
Not workspace config commands are named in the same was as Devfile declares.

4. Improve validation of `Devfile#Commands#Actions` list.
We don't support multiple actions in `Devfile#commands` because of current commands model on Workspace API level. `Exec/terminal` plugin is not able to handle multiple exec commands in different containers as one Task.
Later it can be implemented along with Commands model changing on Workspace API level.

5. Set empty HashMap for null Map fields in Devfile.
We used to expect from POJO to return empty collections(including Maps) instead of null. `jsonschema2pojo-maven-plugin` returns empty collections only for List, Set types but not for Map. This commit manually initialize Devfile Maps fields after Devfile parsing. 
Maybe later it can be handled on `jsonschema2pojo-maven-plugin`, the corresponding issues is created https://github.com/joelittlejohn/jsonschema2pojo/issues/955.

### What issues does this PR fix or reference?
It is needed for https://github.com/eclipse/che/issues/12479.

#### Release Notes
N/A

#### Docs PR
N/A

### CODE REVIEW

**Review by garagatyi — APPROVED** [review]

**Comment by mshaposhnik** [comment]
`We do not support multiple actions in Devfile#commands`
This is the doubtful statement  you introduced with this PR.
It goes against the approved Devfile format at https://github.com/redhat-developer/devfile/blob/master/Devfile.yaml
and devfile schema at https://github.com/eclipse/che/blob/master/wsmaster/che-core-api-devfile/src/main/resources/schema/devfile.json#L185
So if it's a permanent change, we need to change format & schema. If it's an temporary, i would like to state this more clearly somehow.

**Comment by sleshchenko** [comment]
> It goes against the approved Devfile format at https://github.com/redhat-developer/devfile/blob/master/Devfile.yaml

Well, `Devfile.yaml` just shows what we would like to have in devfile format. Neither `runType: sequential` command attribute nor dockerimage tool, not multiple tools which are not cheEditor/chePlugin are not supported yet.

>  If it's an temporary, i would like to state this more clearly somehow.

Makes sense. 
@mshaposhnik Do you have any proposal how to do it? 
Would you like me to revert my commit and create a separate issue to implement it
Or merge this commit and create a separate issue to describe differences bettwen what we would like to have `https://github.com/redhat-developer/devfile/blob/master/Devfile.yaml` and what we have now - Workspace API.

**Comment by mshaposhnik** [comment]
> Would you like me to revert my commit 
Nope. I propose to 
-  add an explanation why we did this into PR desc, and 
- also add comment in the validator why such validation is done manually instead of defining it in the schema and let be validated authomatically.

**Comment by sleshchenko** [comment]
@mshaposhnik I thought you were asking about this documenting limitation in JSON Spec. Will add a detailed explanation in PR/commit description and add a comment to the validator.

**Comment by mshaposhnik** [comment]
That would be double great if you put note about this into schema description of the Action list :-)

**Comment by sleshchenko** [comment]
ci-test

**Review by mshaposhnik — APPROVED** [review]

**Review by skabashnyuk — APPROVED** [review]

**Comment by artaleks9** [comment]
Selenium tests execution on Eclipse Che Multiuser on OCP (https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1501/) doesn't show any regression against this Pull Request.

**Pull request merged**
