### PR TITLE
CHE-2633: Fix leak of file descriptors

### PR DESCRIPTION
**Pull request by mmorhun**
### What does this PR do?

Fix leak of file descriptors
### What issues does this PR fix or reference?
#2633
### Previous behavior

After command execution descriptor to log file of command never release
### New behavior

After command execution all used descriptors are released

### CODE REVIEW

**Comment by mmorhun** [comment]
@AndrienkoAleksandr @tolusha take a look please

**Comment by tolusha** [comment]
Nice.

**Review by tolusha — APPROVED** [review]

**Comment by AndrienkoAleksandr** [comment]
Nice

**Review by garagatyi — APPROVED** [review]
Nice catch!

**Pull request merged**
