### PR TITLE
Add ability to provide additional build-info in Che

### PR DESCRIPTION
**Pull request by mkuznyetsov**
### What does this PR do?
Add ability to provide "build info" during the build of the project. "Build info" is a string that can contain additional information, such as revision, branch that was this project built on, version of upstream Che, etc.
This "build info" must be defined and passed with Maven command during build of Che as variable `-Dbuild.info=` , and it is supported for following modules: 
- build "assembly-wsmaster-war" to provide build info for Che Server side (so it would display on Dashboard.
- build "che-ide-gwt-app" to provide build info for GWT IDE in Help -> About section

Assembly-wsmaster-war would provide build.info into Che via properties. The `buildinfo.properties` file would be generated by Maven Antrun task. Note that property generation is required to be present for `assembly-wsmaster-war` and `assembly-wsagent-war`.

<details>
  <summary>generating buildinfo for wsmaster/wsagent</summary>

            </plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-antrun-plugin</artifactId>
                <executions>
                    <execution>
                        <id>buildinfo</id>
                        <phase>process-resources</phase>
                        <goals>
                            <goal>run</goal>
                        </goals>
                        <configuration>
                            <tasks>
                                <echo append="false" file="${project.build.outputDirectory}/che/buildinfo.properties">che.product.build_info = ${build.info}</echo>
                            </tasks>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
</details>

<details>
  <summary>preview of displaying buildinfo of WS Master (instead of version) on Dashboard</summary>

Screenshot from 2019-03-19 12-52-35

</details>

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/12871

### CODE REVIEW

**Comment by nickboldt** [comment]
This looks great. `-Dbuild.info=` is exactly the kind of easy override I was looking for.

Will this be backported to 6.19.x or will it only be in 7.0 for Theia?

**Comment by garagatyi** [comment]
@ibuziuk this ^ can help us setting commit ID in RhChe

**Comment by nickboldt** [comment]
If you're wondering how I generate the lengthy CRW/che/che-ls-jdt version string, here's the Jenkinsfile we use to build and shove that into the dashboard:

https://github.com/redhat-developer/codeready-workspaces/blob/master/Jenkinsfile#L165-L175

**Comment by ibuziuk** [comment]
>  can help us setting commit ID in RhChe

@garagatyi yeah, currently it is set correctly in about btw:

image

**Comment by mkuznyetsov** [comment]
@nickboldt yes, just to make sure, this PR only affects display of Che version on Dashboard and GWT IDE. 
Theia currently doesn't show information about Che, apart from Theia version, so atm adding build info for theia is not in the scope for this PR

**Review by skabashnyuk — APPROVED** [review]

**Comment by mkuznyetsov** [comment]
ci-test

**Comment by mkuznyetsov** [comment]
ci-test

**Comment by nickboldt** [comment]
"atm adding build info for theia is not in the scope for this PR"

Please make sure to cherry-pick this fix to the 6.19.x or 6.x branch then as we need it for 6.x (and 7.x might eventually remove the GWT IDE entirely.

**Review by ashumilova — APPROVED** [review]

**Pull request merged**
