### PR TITLE
Add Theia stack for Kubernetes

### PR DESCRIPTION
**Pull request by AndrienkoAleksandr**
Signed-off-by: Oleksandr Andriienko <oandriie@redhat.com>

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Comment by AndrienkoAleksandr** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1011/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1011//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11661
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by Ohrimenko1988** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1012/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1012//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11661
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1013/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1013//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11661
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by AndrienkoAleksandr** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1022/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1022//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11661
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by SkorikSergey** [comment]
Selenium tests execution on Eclipse Che Multiuser on OCP (https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1022//Selenium_20tests_20report/) doesn't show any regression against this Pull Request.

**Comment by SkorikSergey** [comment]
Selenium tests execution on Eclipse Che Multiuser on OCP (https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1022//Selenium_20tests_20report/) doesn't show any regression against this Pull Request.

**Comment by SkorikSergey** [comment]
Selenium tests execution on Eclipse Che Multiuser on OCP (https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1022//Selenium_20tests_20report/) doesn't show any regression against this Pull Request.

**Comment by SkorikSergey** [comment]
Selenium tests execution on Eclipse Che Multiuser on OCP (https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1022//Selenium_20tests_20report/) doesn't show any regression against this Pull Request.

**Pull request merged**
