### PR TITLE
Che 1076 Refactoring of che-core-api-infrastructure-local

### PR DESCRIPTION
**Pull request by skabashnyuk**
**_1 Upvote**_ -  Split che-core-api-infrastructure-local to  /assembly/wsagent-local /assembly/wsmaster-local
-  moved to /assembly/wsagent-local /assembly/wsmaster-local classes from wars
-  Removed unused or deprecated code

### CODE REVIEW

**Comment by benoitf** [comment]
it looks like strange to have many classes as part of an assembly module.
Assembly in maven is a result of taking dependencies, http://maven.apache.org/plugins/maven-assembly-plugin/ , not defining new modules

**Comment by skabashnyuk** [comment]
What do you propose?

**Comment by benoitf** [comment]
it may be use existing https://github.com/eclipse/che/tree/master/wsagent and https://github.com/eclipse/che/tree/master/wsmaster modules ?

**Comment by skabashnyuk** [comment]
ok

**Comment by benoitf** [comment]
+1 on my side

**Comment by vparfonov** [comment]
Ok

**Pull request merged**
