### PR TITLE
Update stable selenium tests suite

### PR DESCRIPTION
**Pull request by dmytro-ndp**
### What does this PR do?
It updates list of stable selenium tests in CheSuite.xml

### CODE REVIEW

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by skabashnyuk** [comment]
Need to have this changes in the ```che-multiuser``` branch. It's quite hard to merge such complex changes.

**Comment by skabashnyuk** [comment]
WDYT is the best way to do that?

**Comment by dmytro-ndp** [comment]
@skabashnyuk:
> It's quite hard to merge such complex changes.

where do you see complex changes? ;-)

Actually, this pull request be merged after we obtain ~100% test execution success on stable tests.

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by skabashnyuk** [comment]
@dmytro-ndp never mind.

**Comment by dmytro-ndp** [comment]
@musienko-maxim: please, review this request

**Comment by dmytro-ndp** [comment]
ci-test

**Review by musienko-maxim — APPROVED** [review]

**Comment by dmytro-ndp** [comment]
ci-test

**Pull request merged**
