### PR TITLE
Added "obj" folders to .gitignore

### PR DESCRIPTION
**Pull request by ghost**
### What does this PR do?
Add "obj" folders to .gitignore.

### What issues does this PR fix or reference?
#14784

### CODE REVIEW

**Comment by skabashnyuk** [comment]
ci-build

**Comment by skabashnyuk** [comment]
@swe-covis thanks for your contribution. To be able to merge it you need to sign https://www.eclipse.org/legal/ECA.php with the same email you push this change.

**Review by skabashnyuk — APPROVED** [review]

**Comment by swe-covis** [comment]
ECA has been signed

**Comment by skabashnyuk** [comment]
Ah. Forgot to mention about "Signed-off-by footer". That is the last thing to make eclipsefdn/eca  happy. Can you amend your commit?

**Comment by swe-covis** [comment]
Sorry for asking that but do you have a short instruction or link to docs how to and where to set that footer?

**Comment by swe-covis** [comment]
Got it: https://wiki.eclipse.org/Development_Resources/Contributing_via_Git

**Comment by skabashnyuk** [comment]
Something like `git commit --amend --signoff` 
See https://stackoverflow.com/a/15667644/318536

**Pull request closed without merging**
