### PR TITLE
Minor fixes to new Che workspace Grafana panels

### PR DESCRIPTION
**Pull request by mkuznyetsov**
### What does this PR do?
Miscellaneous fixes for `che-workspace` Grafana dashboard

### CODE REVIEW

**Review by skabashnyuk — APPROVED** [review]

**Comment by skabashnyuk** [comment]
ci-test

**Comment by mkuznyetsov** [comment]
ci-build

**Comment by mkuznyetsov** [comment]
ci-test

**Comment by mkuznyetsov** [comment]
crw-ci-test

**Comment by mkuznyetsov** [comment]
crw-ci-test

**Comment by mkuznyetsov** [comment]
ci-test

**Pull request merged**
