### PR TITLE
Removed WorkspaceConfig related REST API

### PR DESCRIPTION
**Pull request by skabashnyuk**
### What does this PR do?
FactoryService
 - saveFactory
 - getFactory
 - getFactoryByAttribute
 - updateFactory
 - removeFactory
 - getFactoryJson

WorkspaceService
 - create with WorkspaceConfigDto
 - startFromConfig with WorkspaceConfigDto
 - addCommand related to WorkspaceConfig's commands not Devfile's
 - updateCommand related to WorkspaceConfig's commands not Devfile's
 - deleteCommand related to WorkspaceConfig's commands not Devfile's
 - addEnvironment
 - updateEnvironment
 - deleteEnvironment
 - addProject related to WorkspaceConfig's projects not Devfile's
 - updateProject related to WorkspaceConfig's projects not Devfile's
 - deleteProject related to WorkspaceConfig's projects not Devfile's

Related permission staff.

### What issues does this PR fix or reference?

https://github.com/eclipse/che/issues/17390
Model objects I've decided to remove in another pr.

#### Release Notes
n/a

#### Docs PR
n/a

### CODE REVIEW

**Review by sparkoo — APPROVED** [review]
lgtm. I would wait to merge this after the release.

**Comment by sleshchenko** [comment]
@akurinnoy @olexii4 I assume [Che Workspace Client](https://github.com/eclipse/che-workspace-client) should be updated as well, could you check and create an issue if needed?

**Comment by dmytro-ndp** [comment]
[ci-test]

**Comment by dmytro-ndp** [comment]
[ci-test]

**Comment by skabashnyuk** [comment]
@dmytro-ndp FYI I'm planning to make the second pr after this. It will remove WorkspaceConfig related model object.

**Review by metlos — APPROVED** [review]

**Pull request merged**
