### PR TITLE
[Happy-Path] Update chromedriver to version 76.0.0

### PR DESCRIPTION
**Pull request by Ohrimenko1988**
Signed-off-by: Ihor Okhrimenko <iokhrime@redhat.com>

### What does this PR do?
Update chromedriver to version 76.0.0

### What issues does this PR fix or reference?
Issue: https://github.com/eclipse/che/issues/14143

### CODE REVIEW

**Comment by Ohrimenko1988** [comment]
CQ in pending status <https://dev.eclipse.org/ipzilla/show_bug.cgi?id=19665>

**Comment by Ohrimenko1988** [comment]
CQ has been approved, @dmytro-ndp @rhopp we have to update chrome browser version in the test image to "76" before merging

**Review by rhopp — DISMISSED** [review]

**Comment by rhopp** [comment]
@Ohrimenko1988 Cannot you do that as part of this issue?

**Comment by dmytro-ndp** [comment]
I have start Happy path tests from this PR on `eclipse/che-e2e:nightly` which has latest chrome driver inside https://codeready-workspaces-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/CHE-7-Maven-PR-build-checker-codenvy-slave9/56/

**Comment by Ohrimenko1988** [comment]
@dmytro-ndp thank you

**Review by artaleks9 — APPROVED** [review]

**Review by dmytro-ndp — APPROVED** [review]

**Review by SkorikSergey — APPROVED** [review]

**Pull request merged**
