### PR TITLE
Fix K8s Helm Chart

### PR DESCRIPTION
**Pull request by perspectivus1**
### What does this PR do?
Fix broken K8s Helm chart

### What issues does this PR fix or reference?
Helm chart cannot be packaged because of mismatch between directory name and chart name (in Chart.yaml). Cause is movement of deployment files (#9143).

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Review by riuvshin — APPROVED** [review]

**Review by sleshchenko — APPROVED** [review]

**Review by garagatyi — APPROVED** [review]
Sorry for breaking Helm installation. 
BTW I checked it using instruction in the readme before the merge. @perspectivus1 can you help me figuring out what I had to do to find out that something was broken?

**Comment by perspectivus1** [comment]
No problem @garagatyi.

The Helm installation still works, if performing it directly from the Git repo. However, the preferred method for installing a Helm chart is by referencing a Helm repository. The prerequisite for uploading a Helm chart to a Helm repo is packing it into a .tgz file using ```helm package```. This command will fail if the directory name is different from the chart's name.

We maintain an internal Jenkins job that run periodically, clones the eclipse/che git repo, packages the Helm chart, and then uploads it to a our own Helm repository. This job failed after the change.

**Comment by l0rd** [comment]
@perspectivus1 why `eclipse-che` and not `che` as the name of the chart? I think I saw some eclipse projects in the helm charts repository that are not prefixed with `eclispe`.

**Comment by perspectivus1** [comment]
@l0rd I named the chart ```eclipse-che``` so it would be easy to find when exploring a Helm repo.

Helm chart naming conventions are [here](https://github.com/kubernetes/helm/blob/master/docs/chart_best_practices/conventions.md#chart-names). There are no naming conventions for charts in Helm repos, other than uniqueness.

I can rename it to ```che``` if you think it's better.

**Comment by l0rd** [comment]
@perspectivus1 I understand you point. I personally prefer `che` to avoid confusions with the eclipse desktop IDE but I don't want to take this decision. 

@slemeur @gorkem how should we call Che in an kubernetes application catalog like [kubeapps](https://hub.kubeapps.com/charts): `che` or `eclipse-che`?

**Comment by perspectivus1** [comment]
@l0rd, I followed your advice and changed the chart name to ```che```.

**Comment by l0rd** [comment]
@perspectivus1 thank you. If you are ok I would merge this PR right away.

**Review by l0rd — APPROVED** [review]

**Comment by perspectivus1** [comment]
Thanks @l0rd. Go ahead with the merge.

**Pull request merged**
