### PR TITLE
3656 Port Languages Server Support to lsp4j

### LINKED ISSUE #3656: Port Language Server Support to LSP4J
As I understand it, Typefox has moved their LSP binding for Java to the LSP4J project at Eclipse (http://www.eclipse.org/lsp4j). I think it would make sense to port the langage server plugin to LSP4J in order to profit from ongoing work (bug fixes, etc.)

### PR DESCRIPTION
**Pull request by skabashnyuk**
Based on work https://github.com/eclipse/che/pull/4160
This PR updates the che language server support to use Eclipse LSP4J 0.1.2 instead of the obsolete Typefox library.

This PR fixes https://github.com/eclipse/che/issues/3656

The port uses normal che RPC support to communicate between IDE and workspace agent. Since the lsp4j API is based on dto classes instead of interfaces, a new code generator and maven plugin have been added to generate dto classes from the lsp4j API classes.
The lsp4j version used is a snapshot version because it includes fixes that have already been present in the latest typefox library, but were missing from lsp4j <= 0.1.1.

#### Changelog
Language Server Protocol support ported to Eclipse LSP4J.

#### Release Notes
We have updated the Che language server support to use Eclipse LSP4J 0.1.2 instead of the obsolete Typefox library.

The port uses the normal Che RPC support to communicate between the IDE and workspace agent. Since the LSP4J API is based on DTO classes instead of interfaces, a new code generator and maven plugin have been added to generate DTO classes from the LSP4J API classes.

#### Docs PR
n/a

### CODE REVIEW

**Review by riuvshin — APPROVED** [review]

**Review by evidolob — APPROVED** [review]

**Review by vparfonov — APPROVED** [review]

**Comment by skabashnyuk** [comment]
@tsmaeder can you fix merge conflicts plz. Looks like  you've edited the same files here https://github.com/eclipse/che/pull/4345

**Comment by benoitf** [comment]
The PR description is
```This PR updates the che language server support to use Eclipse LSP4J 0.2.0-SNAPSHOT instead of the obsolete Typefox library.```

while in che-dependencies the version is ```0.1.2```

https://github.com/eclipse/che-dependencies/blob/50ace460ea596c7db369782c7478fd75b5956da4/pom.xml#L67

so either PR description or PR in che-dependencies is incorrect

**Comment by skabashnyuk** [comment]
thx @benoitf , fixed

**Comment by skabashnyuk** [comment]
ci-build

**Review by bmicklea — APPROVED** [review]
Updated Release Notes based on the issue description.

**Pull request merged**
