### PR TITLE
Update nodejs-hello-world run command

### PR DESCRIPTION
**Pull request by jarifibrahim**
### What does this PR do?

This PR depends on https://github.com/che-samples/web-nodejs-sample/pull/1
This PR changes the run command for nodejs-hello-world sample project.

### What issues does this PR fix or reference?
See https://github.com/redhat-developer/rh-che/pull/1078#issuecomment-439561716

### CODE REVIEW

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by jarifibrahim** [comment]
@ibuziuk I think we can merge this PR.

**Review by l0rd — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Review by ibuziuk — APPROVED** [review]
+1 to merge. but we need to also apply https://github.com/che-samples/web-nodejs-sample/pull/1 
@l0rd @eivantsov who could approve and merge PR in samples ? I have no rights in the samples repo

**Comment by ibuziuk** [comment]
ci-build

**Comment by eivantsov** [comment]
ci-build

**Comment by ibuziuk** [comment]
ci-test

**Comment by ibuziuk** [comment]
@riuvshin it looks like build / tests checks are not triggered to this PR, any idea what is the reason ?

**Comment by ibuziuk** [comment]
ci-build

**Comment by ibuziuk** [comment]
ci-build

**Pull request merged**
