### PR TITLE
Upgrade Apache Commons Collections to v3.2.2

### PR DESCRIPTION
**Pull request by ProgramMax**
Signed-off-by: Chris Blume cblume@google.com

### CODE REVIEW

**Comment by benoitf** [comment]
New dependency needs to be approved by IP team first
we need to get a PB on https://dev.eclipse.org/ipzilla/show_bug.cgi?id=10385 first

**Comment by skabashnyuk** [comment]
We don't in this case. See more https://github.com/eclipse/che/pull/654#issuecomment-194307588

**Comment by benoitf** [comment]
Here is PB https://dev.eclipse.org/ipzilla/show_bug.cgi?id=11073

**Comment by riuvshin** [comment]
@benoitf it's resources, why we need CQ for that?

**Comment by benoitf** [comment]
@skabashnyuk @riuvshin you are right, we don't need CQ

**Comment by benoitf** [comment]
BTW we can still merge the update of the test example

**Pull request merged**
