### PR TITLE
[WIP] Add logging of machine toke signed requests

### PR DESCRIPTION
**Pull request by mshaposhnik**
### What does this PR do?
This PR created to pass CI tests with some  additional logging information and not intended to be merged.

### CODE REVIEW

**Comment by mshaposhnik** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/636/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/636//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10862)
docker image: eclipseche/che-server:10862
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by mshaposhnik** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/637/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/637//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10862)
docker image: eclipseche/che-server:10862
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by mshaposhnik** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/638/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/638//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10862)
docker image: eclipseche/che-server:10862
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Pull request closed without merging**
