### PR TITLE
Fix remaining files with licenses

### PR DESCRIPTION
**Pull request by mkuznyetsov**
### What does this PR do?
Fix old licenses for following groups of files
- Dockerfiles
- SH scripts
- JS and TS files 
- Various java plugins and modules

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/10465

### CODE REVIEW

**Comment by mkuznyetsov** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/598/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/598//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10746)
docker image: eclipseche/che-server:10746
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by mkuznyetsov** [comment]
ci-test

**Review by skabashnyuk — APPROVED** [review]
make sure tests are passing

**Comment by mkuznyetsov** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/612/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/612//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10746)
docker image: eclipseche/che-server:10746
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Review by musienko-maxim — APPROVED** [review]

**Comment by mkuznyetsov** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/633/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/633//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10746)
docker image: eclipseche/che-server:10746
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Pull request merged**
