### PR TITLE
Replace Crane with felixfbecker PHP Language Server

### PR DESCRIPTION
**Pull request by kaloyan-raev**
### What does this PR do?

Replaces [HvyIndustries/crane](https://github.com/HvyIndustries/crane) with [felixfbecker/php-language-server](https://github.com/felixfbecker/php-language-server) as the PHP language server.

[felixfbecker/php-language-server](https://github.com/felixfbecker/php-language-server) is implemented in pure PHP, utilizes existing PHP Tools (like PHP Parser, CodeSniffer and phpDocumentor) and already attracts a few PHP developers to contribute.

The below attachment must be uploaded to https://codenvy.com/update/repository/public/download/org.eclipse.che.ls.php.binaries
Attachment: [php-language-server.tar.gz](https://github.com/eclipse/che/files/539317/php-language-server.tar.gz)

The tarball includes the necessary PHP executable for running the PHP language server. No additional OS packages need to be installed.
### What issues does this PR fix or reference?
- PHP support #2590
### Previous behavior

The Crane PHP language server used so far provided only limited code completion and no other capabilities. It was implemented in TypeScript, so it can't reuse existing PHP tools and has much less potential to attract the PHP community for contributions.
### New behavior

In its current state the PHP language server comes with the following capabilities:
- Code completion
- Syntax validation
- Document formatting
- Document symbols
- Workspace symbols
- Go to definition
- Find references
- Hover support

Signed-off-by: Kaloyan Raev kaloyan.r@zend.com

### CODE REVIEW

**Comment by slemeur** [comment]
Very cool !

**Comment by kaloyan-raev** [comment]
@vparfonov Thanks for merging the PR. 

When do you plan to upload the attached binaries to https://codenvy.com/update/repository/public/download/org.eclipse.che.ls.php.binaries?

The PHP language server in M7 builds cannot initialize properly until the binaries are uploaded. But if you upload the binaries then it will break the PHP language server initialization older milestones, because the old Crane language server won't be available at that location.

Should we upload the new PHP language server to a newer location?

**Comment by tolusha** [comment]
@kaloyan-raev binaries updated

**Comment by kaloyan-raev** [comment]
@tolusha Thank you!

**Pull request merged**
