### PR TITLE
Optimize the list of stacks

### PR DESCRIPTION
**Pull request by ghost**
### What does this PR do?

This PR removes unused stacks and sample apps. Updated components versions. Tested most of sample commands.

### What issues does this PR fix or reference?

https://github.com/eclipse/che/issues/9899

#### Docs PR

https://github.com/eclipse/che-docs/pull/419

## PR to Dockerfiles repo:

https://github.com/eclipse/che-dockerfiles/pull/190

### CODE REVIEW

**Review by slemeur — APPROVED** [review]

**Comment by slemeur** [comment]
@vkuznyetsov : Could you please organize dedicated QA on this. 
All stacks should be tested:
- Language Servers associated with the stacks are working properly
- Each samples have a build, run and test commands that are working

**Comment by eivantsov** [comment]
@vkuznyetsov I suggest the following testing:

1. In UD, click All tab in Create a Workspace screen:

image

2. Test stacks + offered sample apps one by one.

3. In this issue, report which combination of stack+sample did not work, with details - logs, screenshots etc.

**Comment by SkorikSergey** [comment]
ci-test

**Comment by SkorikSergey** [comment]
ci-test-docker-single

**Pull request merged**
