### PR TITLE
Fix the get starting page title

### PR DESCRIPTION
**Pull request by olexii4**
Signed-off-by: Oleksii Orel <oorel@redhat.com>

### What does this PR do?
Fix the Get Started page title.

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/16135

### CODE REVIEW

**Comment by amisevsk** [comment]
cc: @nickboldt This is required for 7.9.1, right?

**Review by amisevsk — APPROVED** [review]

**Review by benoitf — APPROVED** [review]

**Review by nickboldt — APPROVED** [review]
seems simple enough.

**Review by sleshchenko — APPROVED** [review]

**Review by akurinnoy — APPROVED** [review]

**Comment by olexii4** [comment]
crw-ci-test

**Comment by olexii4** [comment]
ci-test

**Comment by SkorikSergey** [comment]
[ci-test]

**Comment by sleshchenko** [comment]
cc @nickboldt

**Comment by nickboldt** [comment]
Thanks for the fix!

In future, when you KNOW a fix is needed in the maintenance branch, can you ensure you cherry pick it across to the .x branch too?

That way I don't have to figure out what you did, where, and track down the commit SHA to copy it over to the .x branch. Thanks! 

Cherry picked in b52af9696c

**Pull request merged**
