### PR TITLE
Check file vcs status before reopen folder node

### PR DESCRIPTION
**Pull request by vzhukovs**
### What does this PR do?
This changes proposal fix problem with cached colored status for files which have different vcs status.

colored-tree

Signed-off-by: Vladyslav Zhukovskyi <vzhukovs@redhat.com>

### What issues does this PR fix or reference?
#10875

#### Release Notes

N/A

#### Docs PR

N/A

### CODE REVIEW

**Comment by vzhukovskii** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1135/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1135//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11836
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by vzhukovskii** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1142/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1142//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11836
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by vzhukovskii** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1145/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1145//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11836
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Review by musienko-maxim — APPROVED** [review]

**Review by dkulieshov — APPROVED** [review]

**Review by vinokurig — APPROVED** [review]

**Pull request merged**
