### PR TITLE
Detect tools containers on dashboard and disable action items for them

### PR DESCRIPTION
**Pull request by ashumilova**
Signed-off-by: Anna Shumilova <ashumilo@redhat.com>

### What does this PR do?
As far as user cannot modify environment variables, servers and volumes for tools containers, the PR contain changes, that differ the containers: tools and user defined ones, and disables "Add", "Edit" and "Delete" actions for runtime containers.

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/12337

### CODE REVIEW

**Review by benoitf — APPROVED** [review]

**Comment by ashumilova** [comment]
ci-test

**Review by olexii4 — APPROVED** [review]

**Review by akurinnoy — APPROVED** [review]

**Comment by ashumilova** [comment]
@eclipse/eclipse-che-qa please, validate the PR

**Comment by ashumilova** [comment]
ci-test

**Comment by ashumilova** [comment]
Success rate: 99.842% :)

**Comment by SkorikSergey** [comment]
Selenium tests execution on Eclipse Che Multiuser on OCP (https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1535//Selenium_20tests_20report/) doesn't show any regression against this Pull Request.

**Review by SkorikSergey — APPROVED** [review]

**Pull request merged**
