### PR TITLE
Apply Kohsuke Github library for reduce extra operation and increase stability GitPull test

### PR DESCRIPTION
**Pull request by musienko-maxim**
### What does this PR do?
* The test has many unnecessary steps and illogical operations for instance: we use 2 projects for checking pull feature. We perform Push, add to index, remove operation in first  project  from IDE. In second project we perform pull and check previews operations. This add unstable parts in the test and add many extra - steps. Also this make hard to understand what the test do.
* The kohsuke library for GitHub allows do many github features for test in 'background' mode and we do not need in unnecessary invocations from IDE. 
* Also the library allow add a test project on GitHub side from test. This can will get rid of us to do forks from master repository before a first test session.

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/7031

@vparfonov @tolusha

### CODE REVIEW

**Review by tolusha — APPROVED** [review]

**Review by vparfonov — APPROVED** [review]

**Comment by musienko-maxim** [comment]
ci-test

**Review by artaleks9 — APPROVED** [review]

**Comment by musienko-maxim** [comment]
The tests passed with regression. I should clarify reasons and will launch tests again.

**Comment by musienko-maxim** [comment]
ci-build

**Comment by musienko-maxim** [comment]
ci-build

**Comment by musienko-maxim** [comment]
ci-test

**Pull request merged**
