### PR TITLE
Enable to build the `che-dev` container.

### PR DESCRIPTION
**Pull request by monaka**
### What does this PR do?

Enable to build the `che-dev` container.

### What issues does this PR fix or reference?

#12340 #12341 

#### Docs PR

No.

### CODE REVIEW

**Comment by monaka** [comment]
I succeeded to build the `che` image with this patched `che-dev`.

**Review by benoitf — APPROVED** [review]

**Comment by benoitf** [comment]
ci-build

**Comment by benoitf** [comment]
ci-build

**Comment by monaka** [comment]
I read the result of CI-build. It seems the failure was caused by the build server side.

**Comment by skabashnyuk** [comment]
ci-build

**Pull request merged**
