### PR TITLE
add more stuff to skip when running the fast...

### PR DESCRIPTION
**Pull request by nickboldt**
add more stuff to skip when running the fast profile: no enforcement, no source validation, no integration tests, no javadocs, no gpg checks

Change-Id: I1d3c63a582ec64fffa41a935050e6269f7b1d550
Signed-off-by: nickboldt <nboldt@redhat.com>

### CODE REVIEW

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Review by benoitf — APPROVED** [review]

**Comment by benoitf** [comment]
ci-build

**Comment by benoitf** [comment]
@nickboldt need to check if it works (if we can toggle off some profiles within a profile with properties) as last time I checked it was not taken into account but it works now it would be a great improvement

**Comment by benoitf** [comment]
FYI @nickboldt build is failing with 
```
[INFO] Verifying file /home/codenvy/workspace/che-pullrequests-build/pom.xml
[ERROR] The xml element <gpg.skip> should be placed before <gwt.compiler.localWorkers>
[ERROR] The file /home/codenvy/workspace/che-pullrequests-build/pom.xml is not sorted
```

**Comment by benoitf** [comment]
ci-build

**Comment by benoitf** [comment]
@riuvshin as @nickboldt is an eclipse-che committer, could you add him to whitelist of checks ? so I don't have to manually use ci-build ? thx

**Comment by nickboldt** [comment]
This PR appears to do nothing. Seems these properties need to be set earlier than in a profile. Rejecting.

**Pull request closed without merging**
