### PR TITLE
Used non-blocking randomizer for Che master on OpenShift

### LINKED ISSUE #12553: Not able to deploy Che master in some cases
### Description
For some reason when I was deploying Che on minishift it was stuck at

```
2019-01-30 10:25:22,748[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Dcatalina.home=/home/user/eclipse-che//tomcat
2019-01-30 10:25:22,748[main]             [INFO ] [o.a.c.s.VersionLoggerListener 115]   - Command line argument: -Djava.io.tmpdir=/home/user/eclipse-che//tomcat/temp
2019-01-30 10:25:22,882[main]             [INFO ] [o.a.c.http11.Http11NioProtocol 560]  - Initializing ProtocolHandler ["http-nio-8080"]
2019-01-30 10:25:22,894[main]             [INFO ] [o.a.t.util.net.NioSelectorPool 67]   - Using a shared selector for servlet write/read
2019-01-30 10:25:22,920[main]             [INFO ] [o.a.catalina.startup.Catalina 649]   - Initialization processed in 684 ms
2019-01-30 10:25:22,950[main]             [INFO ] [c.m.JmxRemoteLifecycleListener 336]  - The JMX Remote Listener has configured the registry on port [32001] and the server on port [32101] for the [Platform] server
2019-01-30 10:25:22,951[main]             [INFO ] [o.a.c.core.StandardService 416]      - Starting service [Catalina]
2019-01-30 10:25:22,951[main]             [INFO ] [o.a.c.core.StandardEngine 259]       - Starting Servlet Engine: Apache Tomcat/8.5.35
```

```
"localhost-startStop-1" #18 daemon prio=5 os_prio=0 tid=0x000055928549d800 nid=0x42 runnable [0x00007f962ef36000]
   java.lang.Thread.State: RUNNABLE
        at java.io.FileInputStream.readBytes(Native Method)
        at java.io.FileInputStream.read(FileInputStream.java:255)
        at sun.security.provider.SeedGenerator$URLSeedGenerator.getSeedBytes(SeedGenerator.java:539)
        at sun.security.provider.SeedGenerator.generateSeed(SeedGenerator.java:144)
        at sun.security.provider.SecureRandom$SeederHolder.<clinit>(SecureRandom.java:203)
        at sun.security.provider.SecureRandom.engineNextBytes(SecureRandom.java:221)
        - locked <0x00000000f5ae0298> (a sun.security.provider.SecureRandom)
        at java.security.SecureRandom.nextBytes(SecureRandom.java:468)
        at java.security.SecureRandom.next(SecureRandom.java:491)
        at java.util.Random.nextInt(Random.java:329)
        at org.apache.catalina.util.SessionIdGeneratorBase.createSecureRandom(SessionIdGeneratorBase.java:269)
        at org.apache.catalina.util.SessionIdGeneratorBase.getRandomBytes(SessionIdGeneratorBase.java:203)
        at org.apache.catalina.util.StandardSessionIdGenerator.generateSessionId(StandardSessionIdGenerator.java:34)
        at org.apache.catalina.util.SessionIdGeneratorBase.generateSessionId(SessionIdGeneratorBase.java:195)
        at org.apache.catalina.util.SessionIdGeneratorBase.startInternal(SessionIdGeneratorBase.java:289)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        - locked <0x00000000f5adfee8> (a org.apache.catalina.util.StandardSessionIdGenerator)
        at org.apache.catalina.session.ManagerBase.startInternal(ManagerBase.java:599)
        at org.apache.catalina.session.StandardManager.startInternal(StandardManager.java:347)
        - locked <0x00000000f5749190> (a org.apache.catalina.session.StandardManager)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        - locked <0x00000000f5749190> (a org.apache.catalina.session.StandardManager)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5273)
        - locked <0x00000000e032e8c8> (a org.apache.catalina.core.StandardContext)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        - locked <0x00000000e032e8c8> (a org.apache.catalina.core.StandardContext)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1423)
```

The goal of this task is to add JAVA_OPTS ```-Djava.security.egd=file:/dev/./urandom``` for OpenShift as we are doing that for Docker

### PR DESCRIPTION
**Pull request by skabashnyuk**
### What does this PR do?
Used non-blocking randomizer for Che master on OpenShift
### What issues does this PR fix or reference?
Fixes https://github.com/eclipse/che/issues/12553

#### Release Notes
n/a

#### Docs PR
n/a

### CODE REVIEW

**Review by sleshchenko — APPROVED** [review]
I'm not very familiar with randomizer implementations.
Is it needed to do the same changes for Kubernetes deployment, Che Operator?

**Comment by skabashnyuk** [comment]
ci-test

**Comment by skabashnyuk** [comment]
>Is it needed to do the same changes for Kubernetes deployment, Che Operator? 

Don't know

**Comment by garagatyi** [comment]
@sleshchenko It is not always needed

**Review by garagatyi — APPROVED** [review]

**Pull request merged**
