### PR TITLE
Fix environment variables for CHE_DATA_FOLDER

### PR DESCRIPTION
**Pull request by TylerJewell**
### What does this PR do?

Changes the environment variables so that when CHE_DATA_FOLDER= is set with che-launcher image, that the right variables are passed to the che-server image.
### Previous Behavior

By fixing these variables, it is now possible for projects and storage to be saved across containers while using che-launcher.  This was failing before.
### Tests written?

No
### Docs requirements?

N/A

### CODE REVIEW

**Comment by TylerJewell** [comment]
@l0rd - please verify for mac / linux.

**Comment by l0rd** [comment]
I've checked with docker for mac and on linux. Here are my comments:
- Folders `storage`, `workspaces` are created correctly in `$CHE_DATA_FOLDER` but the workspaces folders are empty. The folders are empty even after stopping the workspace or stopping the che-server:
  image
- Inspecting a workspace container we can see that the ws volume is mounted on `/home/user/che/workspaces/<ws-id>`. I expected it to be in $CHE_DATA_FOLDER/workspaces/<ws-id> (with CHE_DATA_FOLDER=/Users/mloriedo/tmp/che)
  image
- On Linux I can sucessfully restore a snapshotted workspace. On Mac I get these errors:

```
chown: changing ownership of '/projects/console-java-simple/.git/objects/pack/pack-163a2f22e0a86c2d3f9fd736c98f9a799756644a.idx': Permission denied
chown: changing ownership of '/projects/console-java-simple/.git/objects/pack/pack-163a2f22e0a86c2d3f9fd736c98f9a799756644a.pack': Permission denied
```
- On both Linux and Mac, if I try to stop Che and restart it (using the launcher with CHE_DATA_FOLDER set), when I try to import an existing workspace I have the following screen:

image

**Comment by garagatyi** [comment]
Have you set property or env variable to disable creation of workspace folders by Che?

**Comment by l0rd** [comment]
image

**Comment by benoitf** [comment]
on my side with the env variables fix the folders are created and I am able to see workspaces content :

```
$ ls -la .che/workspaces/
total 0
drwxr--r--  4 benoitf  wheel  136 21 jul 11:52 .
drwxr--r--  4 benoitf  wheel  136 20 jul 15:20 ..
drwxr-xr-x@ 3 benoitf  wheel  102 21 jul 11:47 storage
drwxr-xr-x  3 benoitf  wheel  102 21 jul 11:52 workspaces
benoitf@MacBookFlorent:web-java-spring (master=)$ ls -la .che/workspaces/workspaces/florent3/ffffdsfsd/
total 8
drwxr-xr-x  5 benoitf  wheel  170 21 jul 11:54 .
drwxr-xr-x@ 3 benoitf  wheel  102 21 jul 11:54 ..
drwxr-xr-x  3 benoitf  wheel  102 21 jul 11:54 .codenvy
-rw-r--r--  1 benoitf  wheel  432 21 jul 11:54 pom.xml
drwxr-xr-x  4 benoitf  wheel  136 21 jul 11:54 src

```

docker inspect on agent container:

```
   {
                "Source": "/tmp/web-java-spring/.che/workspaces/workspaces/florent3",
                "Destination": "/projects",
                "Mode": "Z",
                "RW": true,
                "Propagation": "rprivate"
            }

```

and inspect on che-server

```
 "Env": [
                "CHE_WORKSPACE_STORAGE=/tmp/web-java-spring/.che/workspaces/workspaces",
                "CHE_WORKSPACE_STORAGE_CREATE_FOLDERS=false",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/bin",
                "LANG=C.UTF-8",
                "JAVA_HOME=/usr/lib/jvm/default-jvm/jre",
                "CHE_HOME=/home/user/che",
                "DOCKER_VERSION=1.6.0",
                "DOCKER_BUCKET=get.docker.com"
            ],
```

**Comment by benoitf** [comment]
@l0rd I notice two / in your env CHE_WORKSPACE_STORAGE /Users/mloredio/tmp/che**//**workspaces

(I've also used Workspace/stop in the IDE menu)

**Comment by l0rd** [comment]
Thank you @benoitf (and @garagatyi that spotted this too).

Indeed `-e CHE_WORKSPACE_STORAGE=/somefolder/` doesn't work, `-e CHE_WORKSPACE_STORAGE=/somefolder`works.

**==> To address that we could sanitize the folder paths in launcher.sh. wdyt?**

With that I solved the first 2 points but I still have permissions errors when restoring a snapshotted workspace. This may be related to the fact that, now with the che-launcher, the server is started as `root` (or with a specific user provided with the CHE_USER env variable) whereas the workspace containers are still started as `user`.

**==> To address that we could set the right permissions/owner when creating the folder or just running both che-server and ws-agents with the same user. I prefer the first option though. wdyt?**

After I `chmod 777` the workspace folder I could successfully stop/restart a workspace from the menu.  @benoitf have you been able to stop the workspace and restore it without manually `chmod`?

However I still can't re import an old workspaces when I stop and restart the Che server. But I'm not sure if that scenario should work.

**Comment by garagatyi** [comment]
+1 to perform additional checks to construct mount paths in a predictable way.

**Comment by TylerJewell** [comment]
+1 as well

**Comment by TylerJewell** [comment]
Merged in #1914 - closing this issue.

**Pull request closed without merging**
