### PR TITLE
Fix link for deploying multi-user che to kubernetes

### PR DESCRIPTION
**Pull request by ywskycn**
### What does this PR do?
Fix the link for deploying multi-user che to kubernetes

### CODE REVIEW

**Comment by sleshchenko** [comment]
@ywskycn Thanks for fixing this copy/paste error.

You need to add Signed-Off to your commit so we could merge it
Also, you need to sign Eclipse ECA https://www.eclipse.org/legal/ECA.php

**Comment by ywskycn** [comment]
> @ywskycn Thanks for fixing this copy/paste error.
> 
> You need to add Signed-Off to your commit so we could merge it
> Also, you need to sign Eclipse ECA https://www.eclipse.org/legal/ECA.php

Thanks for the reminder, @sleshchenko . Just signed the ECA. Not sure whether ip-validation check will automatically detect or I need to do sth here?
BTW, the "Signed-off-by footers" issue is due to the commit captures my global git config which uses my company email. Forgot to set project config... Do I also need to fix that, or you can do that when merging?

**Comment by l0rd** [comment]
@ywskycn you should `git commit -s --amend` to sign your commit and then push force on your branch.

**Review by sleshchenko — APPROVED** [review]

**Comment by sleshchenko** [comment]
ci-build

**Pull request merged**
