### PR TITLE
Adds update profile form template with validation of username to be k8s DNS compatible

### PR DESCRIPTION
**Pull request by tolusha**
### What does this PR do?
1. Adds update profile form template with validation of username to be k8s DNS compatible:

2. Adds a new theme `che-username-edit-disabled` based on che which put username filed to readonly. It doesn't allow to be accidentally autocompleted.

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/17265

### CODE REVIEW

**Review by skabashnyuk — APPROVED** [review]

**Comment by tolusha** [comment]
PR and description have been updated.

**Comment by sunix** [comment]
username-readonly ?

**Comment by l0rd** [comment]
@tolusha how can an admin configure Che to use the `che-username-edit-disabled` theme?

**Comment by tolusha** [comment]
@sunix 
the shorter -  the better ;)

@l0rd 
1. Login into keycloak admin console
2. Select `Themes
3. Select `che-username-edit-disabled` in the dropbox menu of the login theme.

**Comment by tolusha** [comment]
[crw-ci-test]

**Pull request merged**
