### PR TITLE
CHE-9418: Fix Git status message if the repository is checkouted to tag or commit.

### PR DESCRIPTION
**Pull request by vinokurig**
### What does this PR do?
Fix Git status message if the repository is checkouted to tag or commit.
Changed `getCurrentBranch` method in the Git API to `getCurrentReference` that returns `Reference` object that contains reference and type (branch, tag or commit).

### What issues does this PR fix or reference?
#9418

#### Release Notes

Fix Git status message if the repository is checkouted to tag or commit.

#### Docs PR

N/A

### CODE REVIEW

**Comment by vinokurig** [comment]
ci-test

**Review by vparfonov — APPROVED** [review]

**Comment by vinokurig** [comment]
ci-test

**Review by musienko-maxim — APPROVED** [review]

**Comment by vinokurig** [comment]
ci-build

**Comment by vinokurig** [comment]
ci-build

**Pull request merged**
