### PR TITLE
add information on how to use CI integration for PRs

### PR DESCRIPTION
**Pull request by riuvshin**
### What does this PR do?
add information on how to use CI integration for PRs

#### Changelog
add information on how to use CI integration for PRs

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Review by benoitf — COMMENTED** [review]
Maybe add ppl that are authorized to do the trigger

**Comment by riuvshin** [comment]
@benoitf updated, ty for the note

**Review by benoitf — APPROVED** [review]

**Review by TylerJewell — COMMENTED** [review]
-1 on adding this to pr template.  I think people will assume that they should add this comment in the pr summary which we do not want them to do.  Should we add this info into the wiki instead?

**Comment by riuvshin** [comment]
@TylerJewell Im ok with wiki, I just wanted to make sure that devs will easily figure how to use these commands because now they really often ask me directly.

**Pull request closed without merging**
