### PR TITLE
CHE-220: Improving 'removeContainer' API. Refactoring

### PR DESCRIPTION
**Pull request by ibuziuk**
cherry-picking https://github.com/eclipse/che/pull/5157

### CODE REVIEW

**Comment by sunix** [comment]
@ibuziuk this is not mergeable anymore :/ let us know if you can fix it

**Comment by ibuziuk** [comment]
@sunix could you please clarify why did not you merge it when it was ? The PR I provided was on top of the branch and it was merged in `openshift-connector`. Please, get me right - I'm ok to update the PR I just do not really into doing it again and again in order to avoid double / triple effort

**Comment by ibuziuk** [comment]
PR has been updated

**Comment by sunix** [comment]
sorry @ibuziuk  i missed this one. I didn't merge that one because there were already too many conflicts to deal with with the current `openshift-connector-rebased` and it as we are still waiting for the PR rebased to be merged ... let's wait for PR https://github.com/eclipse/che/pull/5052 to be merged and we will add that one on master if it works for you

**Comment by ibuziuk** [comment]
@sunix no problem ;-) let's wait https://github.com/eclipse/che/pull/5052 to be merged

**Comment by ibuziuk** [comment]
Not mergeable to master in the current state - https://github.com/redhat-developer/rh-che/issues/175

**Pull request closed without merging**
