### PR TITLE
Apache Camel Language LSP client compatible with Java files

### PR DESCRIPTION
**Pull request by apupier**
Signed-off-by: Aurélien Pupier <apupier@redhat.com>

### What does this PR do?

Triggering the Apache Camel Language Server on Java files

### What issues does this PR fix or reference?

#10262

### CODE REVIEW

**Comment by apupier** [comment]
to test it, Apache Camel Language Server "Installer"needs to be activated:
image


and this file with a .java extension can be used :
```
import org.apache.camel.builder.RouteBuilder;

/**
 * A Camel Java DSL Router
 */
public class MyRouteBuilder extends RouteBuilder {

    /**
     * Let's configure the Camel routing rules using Java code...
     */
    public void configure() {

        // here is a sample which processes the input files
        // (leaving them in place - see the 'noop' flag)
        // then performs content based routing on the message using XPath
        from("file:src/data?noop=true&antExclude=aa&antFilterCaseSensitive=true&runLoggingLevel=OFF")
            .choice()
                .when(xpath("/person/city = 'London'"))
                    .to("file:target/messages/uk")
                .otherwise()
                    .to("file:target/messages/others");
    }

import org.apache.camel.builder.RouteBuilder;

/**
 * A Camel Java DSL Router
 */
public class MyRouteBuilder extends RouteBuilder {

    /**
     * Let's configure the Camel routing rules using Java code...
     */
    public void configure() {

        // here is a sample which processes the input files
        // (leaving them in place - see the 'noop' flag)
        // then performs content based routing on the message using XPath
        from("file:src/data?noop=true&antExclude=aa&antFilterCaseSensitive=true&runLoggingLevel=OFF")
            .choice()
                .when(xpath("/person/city = 'London'"))
                    .to("file:target/messages/uk")
                .otherwise()
                    .to("file:target/messages/others");
    }

}
```

if you call the completion just after the quote from(" L.36 you should have several results including ahc-httpUri

**Comment by benoitf** [comment]
ci-test

**Comment by apupier** [comment]
there some test failures but they seem not related to my PR (as far I understand them)
They have always a success rate which is not 100%, does it mean that they are all flaky tests?

**Comment by tolusha** [comment]
@musienko-maxim 
Could you have a look at tests result?

**Comment by dkuleshov** [comment]
@apupier 

Hi, recently there were introduced several changes to regular expressions for language servers, they were called upon to give regexes more flexibility, and as of what I see probably by a mistake those changes were not applied to Camel language regexes, so I would recommend to replace 
```java
private static final String REGEX = ".*\\.(xml|java)";
```
with 
```java
private static final String REGEX = ".*\\.(xml|java)$";
```

**Comment by apupier** [comment]
@dkuleshov updated PR with your advice

**Review by dkulieshov — APPROVED** [review]

**Comment by skabashnyuk** [comment]
ci-test

**Comment by apupier** [comment]
with my PR it seems that the Java Language Server is not started at all:
image

i have no Java completion, neither Java Syntax coloring. Does it mean that 2 Language Server on the same file is not supported? Or that I misconfigured something?

**Comment by apupier** [comment]
I tend to say that several LSP on same file should work given this code:
https://github.com/eclipse/che/blob/89d6c1664aee6a25b117b2a63216e1804742d0da/wsagent/che-core-api-languageserver/src/main/java/org/eclipse/che/api/languageserver/TextDocumentService.java#L246-L247

I'm not able to have a working development environment so can't really investigate more unfortunately

**Comment by musienko-maxim** [comment]
After last selenium launching, was found that java files from maven project have wrong syntax highlighting. It may be depend on incorrect detecting of editor type. 
Steps to reproduce:
* Create a workspace based on java stack.
* Create for instance the spring project from wizard and open the GreetingController file
* More details on the screenshot:
selection_027

**Comment by vparfonov** [comment]
do not merge before @musienko-maxim approve it

**Comment by apupier** [comment]
this PR cannot be merged until jdt.ls has been integrated

**Comment by apupier** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1007/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1007//Selenium_20tests_20report/)
docker image: eclipseche/che-server:10264
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by apupier** [comment]
failure seems unrelated with the PR

```
08:49:06 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (run-tests) on project go-agents: An Ant BuildException has occured: exec returned: 1
08:49:06 [ERROR] around Ant part ...<exec failonerror="true" dir="/home/codenvy/workspace/che-pullrequests-test-ocp/agents/go-agents/target/go-workspace/src/github.com/eclipse/che/agents/go-agents" executable="go">... @ 4:181 in /home/codenvy/workspace/che-pullrequests-test-ocp/agents/go-agents/target/antrun/build-main.xml
```

**Comment by apupier** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1008/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1008//Selenium_20tests_20report/)
docker image: eclipseche/che-server:10264
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by apupier** [comment]
ci-build

**Comment by apupier** [comment]
ci-test

**Comment by apupier** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1020/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1020//Selenium_20tests_20report/)
docker image: eclipseche/che-server:10264
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by apupier** [comment]
The Camel Language server is not activated on the Java files :(

**Comment by apupier** [comment]
The Camel Language server is not activated on the Java files :(

**Comment by apupier** [comment]
wondering if mimetype is now preventing the activation of the Camel Language Server. it wasn't the case several months ago.
the problem with the mimetype is that it is accepting a single value https://github.com/eclipse/che/blob/07263f1e30089689d71b057f747a44a29283e3c4/wsagent/che-core-api-languageserver-shared/src/main/java/org/eclipse/che/api/languageserver/shared/model/LanguageDescription.java#L48 although we would need to work with xml fil and java file. Maybe a text/plain mime type would be better?

**Review by vparfonov — APPROVED** [review]

**Comment by apupier** [comment]
after investigation with @tsmaeder , we found that it is still not working correctly. Sometimes (depending on jvm internal loading order?), the syntax color is missing for Java files.
It is caused by the fact that it seems that there are mix between Language Server Id and Language Id on client side.
one thing to test is to remove the whole CamelLanguageDescriptionProvider class. Not sure that the Camel language server will still be started in this case but worth testing.

**Comment by apupier** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1071/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1071//Selenium_20tests_20report/)
docker image: eclipseche/che-server:10264
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by apupier** [comment]
the ci build error i smentioning missing theia stuff but this PR is not touching it.

**Comment by apupier** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1073/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1073//Selenium_20tests_20report/)
docker image: eclipseche/che-server:10264
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by dkuleshov** [comment]
@apupier Seems like at the moment for some reason CI tests fail during build, so not to waste your time I would recommend you to wait until the issue is resolved and then relaunch the tests. @musienko-maxim probably will tell you more.

**Comment by apupier** [comment]
ok, thanks for letting me know. Please ping me when it is fixed and if I need to rebase on master to get the fix too.

**Comment by apupier** [comment]
ci-test

**Comment by apupier** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1104/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1104//Selenium_20tests_20report/)
docker image: eclipseche/che-server:10264
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by apupier** [comment]
some tests seems due to this regression: https://github.com/eclipse/che/issues/11760

**Comment by apupier** [comment]
relaunching because it is working manually and the modifications should not have an impact to these failed tests

**Comment by apupier** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1111/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1111//Selenium_20tests_20report/)
docker image: eclipseche/che-server:10264
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by apupier** [comment]
without any changes, another set of tests has failed.
i'm not able to launch tests locally.
Testing the feature manually works well.

Can someone review this PR?

**Comment by dkuleshov** [comment]
@musienko-maxim can you please check test results?

**Comment by musienko-maxim** [comment]
So we had many failed tests - main reason problems on test infrastructure. After rerunning all problem tests - all tests passed properly. But we have just unexpected regression with `ApacheCamelFileEditingTest`. The logic of tests works as well. But we need some clarification.

**Comment by SkorikSergey** [comment]
@apupier **ApacheCamelFileEditingTest** selenium test failed due to missing expected "**Initialized language server 'org.eclipse.che.plugin.camel.server.languageserver**'' message in "**dev-machine**" console after opening "camel.xml" file. And there is an exception in "dev-machine" console.

org eclipse che selenium languageserver apachecamelfileeditingtest checklanguageserverinitialized_time-1540890573621-millis

**Comment by apupier** [comment]
stacktrace is similar to the one in https://github.com/eclipse/che/issues/11760
looks alike the JavaLanguageServerExtensionService is not robust enough when there are projects containing a single file

**Comment by SkorikSergey** [comment]
Selenium tests execution on Eclipse Che Multiuser on OCP (https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1111//Selenium_20tests_20report/) doesn't show any regression against this Pull Request.

**Review by SkorikSergey — APPROVED** [review]

**Comment by apupier** [comment]
Do I need to change something or to provide more information to have this PR merged?

**Comment by dmytro-ndp** [comment]
Looks like you have enough approvals to merge the PR into the master.

**Comment by apupier** [comment]
Just to be sure that it is clear, I don't have rights to merge myself.

**Pull request merged**
