### PR TITLE
New che/examples folder

### PR DESCRIPTION
**Pull request by stour**
- Introduce examples folder in Che root directory (list of example projects is not definitive)
- Add module in main pom.xml to build these examples as part of Che build
- Modify assembly to make these org.eclipse.che.examples projects available into Che instead of precedent org.eclipse.che.tutorials

### CODE REVIEW

**Comment by skabashnyuk** [comment]
I vote to squash this changes before commit.

**Comment by vparfonov** [comment]
ok for me, merge it with squash, please

**Comment by stour** [comment]
squash done

**Comment by benoitf** [comment]
Do you want that I merge Stephane's branch ? and also backport it in 4.0 ?

**Pull request merged**
