### PR TITLE
Add notifier about low disk space

### PR DESCRIPTION
**Pull request by vzhukovs**
### What does this PR do?
Add scheduler, that with desired time rate (1 minute) checks free disk space where project's folder mounted and if disk space is less than 200 megabytes, user is notified about that.

lowdiskspace

Upd:
eclipse che 2018-07-26 17-48-09

Signed-off-by: Vladyslav Zhukovskyi <vzhukovs@redhat.com>

### What issues does this PR fix or reference?
#9769 

#### Release Notes
N/A

#### Docs PR
N/A

### CODE REVIEW

**Comment by dkuleshov** [comment]
ci-test

**Review by dkulieshov — APPROVED** [review]

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/507/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/507//Selenium_tests_report)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10503)
docker image: eclipseche/che-server:10503
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by musienko-maxim** [comment]
Selenium tests execution on Eclipse Che Multiuser on OCP [results:](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/507 ) 
doesn't show any regression against this Pull Request.

**Review by musienko-maxim — APPROVED** [review]

**Comment by musienko-maxim** [comment]
We should cover this functionality with a test.

**Review by vparfonov — APPROVED** [review]

**Review by skabashnyuk — APPROVED** [review]

**Comment by vzhukovskii** [comment]
ci-build

**Pull request merged**
