### PR TITLE
CHE-1233: fix wrong behavior for ready-to-go-stacks selector

### PR DESCRIPTION
**Pull request by olexii4**
@ashumilova WDYT?

### CODE REVIEW

**Comment by benoitf** [comment]
@olexii4  for the fix-style commit , could you add screenshot ?

**Comment by olexii4** [comment]
selection_008
selection_006
selection_007

**Comment by olexii4** [comment]
It changes should be because style for che-input widget changed without che-select widget.

it was(and it still at https://nightly4.codenvy-stg.com):

selection_009

**Comment by ashumilova** [comment]
thx for sorting commit

**Pull request merged**
