### PR TITLE
Fields are declared at the top of the class

### PR DESCRIPTION
**Pull request by sachinaraballi**
According to Java Code Patterns : 
Fields should be declared at the top of the class, before any method declarations, constructors, initializers or inner classes.

### What does this PR do?
This is PR enhances code readability and uses Java code patterns.

### CODE REVIEW

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Review by tolusha — APPROVED** [review]

**Comment by tolusha** [comment]
ci-test

**Comment by benoitf** [comment]
hello @sachinaraballi, thanks for your contribution
In order to approve your contribution, ECA needs to be signed and you need to amend your commit with Signed-Off footer
https://www.eclipse.org/legal/ecafaq.php
https://accounts.eclipse.org/user/login?destination=user/eca

**Comment by sachinaraballi** [comment]
Hi @benoitf, I have signed ECA and Updated the commit with the signed-off footer. Thanks

**Comment by benoitf** [comment]
perfect @sachinaraballi

**Review by benoitf — APPROVED** [review]

**Comment by skabashnyuk** [comment]
ci-build

**Comment by benoitf** [comment]
@sachinaraballi FYI with your changes, it doesn't compile anymore:
https://ci.codenvycorp.com/job/che-pullrequests-build/4825/

```
16:53:50 [WARNING] Tests run: 1, Failures: 0, Errors: 0, Skipped: 1
16:53:50 [INFO] 
16:53:50 /home/codenvy/workspace/che-pullrequests-build/plugins/plugin-zend-debugger/che-plugin-zend-debugger-server/src/main/java/org/eclipse/che/plugin/zdb/server/connection/ZendDbgConnection.java:208: error: cannot find symbol
16:53:50             engineMessageHandler.handleNotification((IDbgEngineNotification) message);
16:53:50             ^
```

**Comment by sachinaraballi** [comment]
@benoitf  I am looking into this issue.

**Comment by sachinaraballi** [comment]
@skabashnyuk Can you trigger ci-build

**Comment by benoitf** [comment]
ci-build

**Comment by benoitf** [comment]
ci-build

**Comment by sachinaraballi** [comment]
Hi, @benoitf Build was successful.

**Pull request merged**
