### PR TITLE
[Selenium] Confirm workspace deletion, add project state java tests to UNDER_REPAIR group

### PR DESCRIPTION
**Pull request by SkorikSergey**
### What does this PR do?
Confirm workspace deletion in DeleteStoppingWorkspaceTest test, add project state java tests to UNDER_REPAIR group.

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/16563

P.S. Fix of #16579 has been added to PR.

### CODE REVIEW

**Comment by SkorikSergey** [comment]
[ci-test]

**Comment by SkorikSergey** [comment]
[crw-ci-test]

**Comment by SkorikSergey** [comment]
crw-ci-test

**Comment by SkorikSergey** [comment]
[ci-build]

**Comment by dmytro-ndp** [comment]
@SkorikSergey: could you, please:
- create an issue to fix ProjectStateAfterRefreshTest.java and ProjectStateAfterRenameWorkspaceTest.java tests, and then reference it in this PR;
- take a look at [DeleteOrganizationTest failure](http://artifacts.ci.centos.org/devtools/che/che-pullrequests-java-selenium-tests/207/report/site/failsafe-report.html#org.eclipse.che.selenium.dashboard.organization.DeleteOrganizationTest) to ensure that it was not related to the changes, and may fix it as well?

**Comment by SkorikSergey** [comment]
[ci-test]

**Comment by SkorikSergey** [comment]
> @SkorikSergey: could you, please:
> 
> * create an issue to fix ProjectStateAfterRefreshTest.java and ProjectStateAfterRenameWorkspaceTest.java tests, and then reference it in this PR;
> * take a look at [DeleteOrganizationTest failure](http://artifacts.ci.centos.org/devtools/che/che-pullrequests-java-selenium-tests/207/report/site/failsafe-report.html#org.eclipse.che.selenium.dashboard.organization.DeleteOrganizationTest) to ensure that it was not related to the changes, and may fix it as well?

Added https://github.com/eclipse/che/issues/16563 issue reference.

**Review by dmytro-ndp — APPROVED** [review]

**Pull request merged**
