### PR TITLE
Selenium: Add corrections to the 'ConfigureSomeSourceFoldersTest'

### PR DESCRIPTION
**Pull request by artaleks9**
### What does this PR do?
* Add corrections to the '_ConfigureSomeSourceFoldersTest_' to increase reliability when run on CI

### What issues does this PR fix or reference?
#12223

### CODE REVIEW

**Comment by artaleks9** [comment]
ci-test

**Review by SkorikSergey — APPROVED** [review]

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1338/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1338//Selenium_20tests_20report/)
docker image: eclipseche/che-server:12236
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by artaleks9** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1339/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1339//Selenium_20tests_20report/)
docker image: eclipseche/che-server:12236
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Pull request merged**
