### PR TITLE
Fix PR check Jenkinsfile to use 'che-e2e' image

### PR DESCRIPTION
**Pull request by dmytro-ndp**
### What does this PR do?
It fixes PR check Jenkinsfile to use `eclipse/che-e2e:nightly` image.

### What issues does this PR fix or reference?
#14346

### CODE REVIEW

**Comment by dmytro-ndp** [comment]
crw-ci-test

**Comment by dmytro-ndp** [comment]
crw-ci-test

**Comment by dmytro-ndp** [comment]
crw-ci-test

**Comment by dmytro-ndp** [comment]
crw-ci-test

**Comment by dmytro-ndp** [comment]
crw-ci-test

**Comment by dmytro-ndp** [comment]
crw-ci-test

**Comment by dmytro-ndp** [comment]
crw-ci-test

**Comment by dmytro-ndp** [comment]
ci-build

**Review by rhopp — APPROVED** [review]

**Review by Ohrimenko1988 — APPROVED** [review]

**Pull request merged**
