### PR TITLE
feat(e2e-memory): Reduce the amount of memory used by Happy Path tests 

### PR DESCRIPTION
**Pull request by benoitf**
### What does this PR do?
Reduce the overall memory to fit into 4GB of memory (instead of 8GB of memory)

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/18649

### How to test this PR?
Let happy path test be executed and see if it's green or not

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

Change-Id: I2cd0a302f6a02fe05ca51b1da1880c1aa1cac2ee
Signed-off-by: Florent Benoit <fbenoit@redhat.com>

### CODE REVIEW

**Comment by benoitf** [comment]
[crw-ci-test]

**Comment by benoitf** [comment]
Here is an example of run on Github actions
https://github.com/benoitf/start-che-gh/runs/1575593647?check_suite_focus=true

**Review by ScrewTSW — APPROVED** [review]
LTGM, great work!

**Comment by ScrewTSW** [comment]
[crw-ci-test]

**Comment by benoitf** [comment]
> + kubectl get ingress che --namespace=eclipse-che '-o=jsonpath={.spec.rules[0].host}'
> Error from server (NotFound): namespaces "eclipse-che" not found

Looks like there is a problem on happy path setup

**Comment by benoitf** [comment]
[crw-ci-test]

**Comment by benoitf** [comment]
[crw-ci-test --rebuild]

**Comment by benoitf** [comment]
[crw-ci-test]

**Comment by benoitf** [comment]
[crw-ci-test]

**Comment by benoitf** [comment]
[crw-ci-test]

**Comment by benoitf** [comment]
[crw-ci-test]

**Pull request merged**
