### PR TITLE
Patch custom-resource yaml when installing Che on ci.centos on E2E testing jobs

### PR DESCRIPTION
**Pull request by dmytro-ndp**
### What does this PR do?
1. Use `--che-operator-cr-patch-yaml` options for modifying checluster custom resourse yaml when installing _Eclipse Che_ using _chectl_ in tests on ci.centos.
2. Install testing _Eclipse Che_ with TLS support.
3. Cherry-pick release testing commit 4fa5aa2b87.
4. Get rid of unnecessarily setting up che namespace.
5. Fix Jenkinsfile path for release testing job.
6. Take into account that _chectl_ installs _Eclipse Che_ with **self-signed certificate** by default on _minishift_.
7. Fix storing of nightly devfile tests report on ci.centos.
8. Rename '**rc**' ci.centos jobs to '**release**' jobs.
9. Add _release-devfile-test_ ci.centos job script.

### What issues does this PR fix or reference?
#16905

### CODE REVIEW

**Comment by dmytro-ndp** [comment]
[ci-test]

**Review by SkorikSergey — APPROVED** [review]

**Comment by dmytro-ndp** [comment]
[ci-test]

**Comment by dmytro-ndp** [comment]
[ci-build]

**Comment by dmytro-ndp** [comment]
[ci-test]

**Comment by dmytro-ndp** [comment]
[ci-test]

**Comment by dmytro-ndp** [comment]
[ci-test]

**Comment by dmytro-ndp** [comment]
[ci-test]

**Comment by dmytro-ndp** [comment]
[ci-test]

**Comment by dmytro-ndp** [comment]
[ci-test]

**Comment by dmytro-ndp** [comment]
[ci-test]

**Comment by dmytro-ndp** [comment]
[ci-test]

**Comment by dmytro-ndp** [comment]
[ci-test]

**Comment by dmytro-ndp** [comment]
[ci-test]

**Comment by dmytro-ndp** [comment]
[ci-test]

**Comment by dmytro-ndp** [comment]
[ci-build]

**Comment by dmytro-ndp** [comment]
[ci-build]

**Comment by dmytro-ndp** [comment]
[ci-build]

**Comment by dmytro-ndp** [comment]
[ci-build]

**Pull request merged**
