### PR TITLE
CHE-10656: persist 'yarn.lock' with fixed dependency versions

### LINKED ISSUE #10656: Persist package-lock.json with fixed dependency versions
As far as we need to fix the npm dependency versions to avoid random build fails - there is need to : 
- [ ] have fixed package-lock.json
- [ ] remove package-lock.json from .gitignore
- [ ] avoid mvn clean task - remove the package-lock.json

It's actual both for dashboard and workspace-loader projects.

### PR DESCRIPTION
**Pull request by akurinnoy**
### What does this PR do?
This PR replaces `npm` with `yarn` in workspace loader image. This is done to not to depend on `npm` version in docker image and to use fixed versions of dependencies including transitive ones.

CQ https://dev.eclipse.org/ipzilla/show_bug.cgi?id=17113

### What issues does this PR fix or reference?
fix #10656 

Signed-off-by: Oleksii Kurinnyi <okurinny@redhat.com>

### CODE REVIEW

**Review by benoitf — APPROVED** [review]

**Comment by akurinnoy** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/563/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/563//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10694)
docker image: eclipseche/che-server:10694
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Review by vitaliy-guliy — APPROVED** [review]

**Comment by akurinnoy** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/564/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/564//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10694)
docker image: eclipseche/che-server:10694
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by SkorikSergey** [comment]
Selenium tests execution on Eclipse Che Multiuser on OCP (https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/564/) doesn't show any regression against this Pull Request.

**Review by ashumilova — APPROVED** [review]

**Pull request merged**
