### PR TITLE
cherry-pick: [UD] Avoid unnecessary redirection while checking if user is authorized

### PR DESCRIPTION
**Pull request by akurinnoy**
### What does this PR do?

PR in master branch: https://github.com/eclipse/che/pull/16319

### What issues does this PR fix or reference?

This PR should fix inability to login to CRW on Safari browser: https://issues.redhat.com/browse/CRW-376

### CODE REVIEW

**Comment by dmytro-ndp** [comment]
@akurinnoy: about [failed Happy path tests](https://github.com/eclipse/che/pull/16334#issuecomment-598157586): there are important changes in **master** branch which would be better to have in PR.

**Comment by akurinnoy** [comment]
@dmytro-ndp could you point to that commit in master branch? I'll add it to this PR.

**Comment by dmytro-ndp** [comment]
@akurinnoy: sorry, I didn't catch that it's PR into **7.9.x**, not into the **master** .
We are not providing PR check for such cases, because automated Happy path PR check tests are dedicated to master branch.

**Review by sleshchenko — COMMENTED** [review]
:+1: Can't wait to see it merged ;)

**Pull request merged**
