### PR TITLE
Fixing NPE in the 'KeycloakSettings'

### PR DESCRIPTION
**Pull request by ibuziuk**
### What does this PR do?

Fixing NPE in the 'KeycloakSettings'

```
Caused by: java.lang.NullPointerException: Both parameters are null
	at com.google.common.base.MoreObjects.firstNonNull(MoreObjects.java:61)
	at org.eclipse.che.multiuser.keycloak.server.KeycloakSettings.<init>(KeycloakSettings.java:88)
	at org.eclipse.che.multiuser.keycloak.server.KeycloakSettings$$FastClassByGuice$$e0d0786b.newInstance(<generated>)
	at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
	at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
	at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
	at 
```

Hosted Che related PR - https://github.com/redhat-developer/rh-che/pull/2019

### Screenshot/screencast of this PR
N/A

### What issues does this PR fix or reference?

Related to https://github.com/eclipse/che/commit/4100db305311cf499c3b828fcc784fe659573a92#diff-98040cc62368c248478c9fbd91b123bf43a150663b31fc997689ec469de691b9R88

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [ ] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [ ] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by skabashnyuk** [comment]
Can you write a test?

**Review by AndrienkoAleksandr — APPROVED** [review]

**Comment by AndrienkoAleksandr** [comment]
> Can you write a test?

+1

**Review by tolusha — APPROVED** [review]

**Comment by skabashnyuk** [comment]
I believe that the test is a `hard` requirement for this pr.

**Comment by ibuziuk** [comment]
added test

**Comment by ibuziuk** [comment]
[ci-build]

**Comment by ibuziuk** [comment]
[ci-build]

**Review by skabashnyuk — APPROVED** [review]

**Pull request merged**
