### PR TITLE
Copy MDC context in workspace runtime (start stop) related async tasks

### PR DESCRIPTION
**Pull request by sunix**
### What does this PR do?
When MDC is used in Che log configuration, we figured out that some information were not passed through workspace start and stop tasks. These tasks were executed asynchronously to different thread pools.
This PR is fixing the issue by copying the context. It uses kind of the same mechanism that has been used for thread local in the same portion of code.

### What issues does this PR fix or reference?
https://github.com/redhat-developer/rh-che/issues/495

### CODE REVIEW

**Comment by skabashnyuk** [comment]
I would say we need to solve this task a bit more general. My proposal is to create two classes
1. MDCContext analog of EnvironmentContext. Where MDC is stored in thread local variable  + static method to ``` ThreadLocalPropagateContext.addThreadLocal(currentMDC);```
2. MDCFilter to setup MDC in MDCContext. This filter can be configured for master and agent.

**Comment by sunix** [comment]
@skabashnyuk can you explain "more general" ? I don't see which improvements will bring your suggestions and feel like it is adding more complexity.

**Comment by skabashnyuk** [comment]
As far as I understand the problem that MDC context is lost when one thread delegates some work to another with help of  ThreadLocalPropagateContext. And you are fixed it in one particular place WorkspaceRuntimes.
My proposal was to solving this issue in any place we are using ThreadLocalPropagateContext not only in WorkspaceRuntimes with the build-in functionality of ThreadLocalPropagateContext.

**Comment by garagatyi** [comment]
+1 to use it in all the places ThreadLocalPropagateContext is used as @skabashnyuk suggested

**Comment by sunix** [comment]
@skabashnyuk OK thanks, understand works for me

**Comment by sunix** [comment]
@skabashnyuk @garagatyi I've updated the PR as requested, let me know if it works for you

**Review by skabashnyuk — COMMENTED** [review]
Hello.
Close but not exactly what I thought.
The idea was to consider ThreadLocalPropagateContext as a framework that is propagating thread-local variables to any child Threads. I was expecting to see
something very similar to EnvironmentContext(EnvironmentContextFilter). But in your case, you are modifying
framework itself by adding a direct dependency on slf4j. 

But I saw recommendation https://logback.qos.ch/manual/mdc.html#managedThreads and don't mind if you merge it as is.
BTW. I haven't seen in our filters a place where we reset MDC. Are you using MDCInsertingServletFilter in some place?

**Review by skabashnyuk — APPROVED** [review]

**Pull request merged**
