### PR TITLE
Fix override and skip root behaviors

### PR DESCRIPTION
**Pull request by vparfonov**
Signed-off-by: Vitalii Parfonov <vparfonov@redhat.com>

### What does this PR do?

Fix override existed and skip root behaviors

### What issues does this PR fix or reference?
#10484 
#10437

### CODE REVIEW

**Comment by vparfonov** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/690/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/690//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/11002)
docker image: eclipseche/che-server:11002
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by vparfonov** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/694/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/694//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/11002)
docker image: eclipseche/che-server:11002
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Review by musienko-maxim — APPROVED** [review]

**Pull request merged**
