### PR TITLE
Fix issue #6953 ...

### PR DESCRIPTION
**Pull request by davidfestal**
... by restoring the previous `WsAgentPingRequestFactory` behavior, and
providing a new custom server evaluation template strategy when both
internal *and* external addresses should be based on the custom
template. 

### What does this PR do?

This PR restores the previous `WsAgentPingRequestFactory` behavior, and
provides a new custom server evaluation template strategy when both
internal *and* external addresses should be based on the custom
template. 

### What issues does this PR fix or reference?

issue #6953

### CODE REVIEW

**Comment by davidfestal** [comment]
@riuvshin could you test this PR on Mac, as you had proposed ?

**Comment by benoitf** [comment]
ci-build

**Review by garagatyi — APPROVED** [review]

**Review by skabashnyuk — APPROVED** [review]

**Comment by riuvshin** [comment]
@davidfestal sure, will test it on Mac OS ASAP

**Comment by davidfestal** [comment]
@riuvshin Thanks !

**Review by benoitf — APPROVED** [review]

**Review by riuvshin — APPROVED** [review]

**Review by riuvshin — APPROVED** [review]
Tested on Mac - works OK!

**Pull request merged**
