### PR TITLE
Improve project type resolver

### PR DESCRIPTION
**Pull request by olexii4**
Signed-off-by: Oleksii Orel <oorel@codenvy.com>

### What does this PR do?
Move auto check project type logic into separate service.

### Release Note
- [x] Added to release note

### CODE REVIEW

**Comment by benoitf** [comment]
@olexii4 could you explain a little bit more the "Improve project type resolver"

why it was not good before, why now it's better
is it for example : move logic from controller to the API ?

**Comment by olexii4** [comment]
@benoitf 
I moved some of auto check type logic from controller to api as additional of project's update. Because we need it in several places. But the best way - move auto check type logic into separate service. WDYT?

**Review by benoitf — APPROVED** [review]
@olexii4 yes it makes sense

**Comment by olexii4** [comment]
done.

**Review by akurinnoy — APPROVED** [review]

**Review by ashumilova — APPROVED** [review]

**Comment by slemeur** [comment]
@riuvshin this fix must be included for 5.1.1

**Pull request merged**
