### PR TITLE
update justify library to 3.1.0

### PR DESCRIPTION
**Pull request by sparkoo**
Signed-off-by: Michal Vala <mvala@redhat.com>

### What does this PR do?
updates justify to latest 3.1.0. With this library we're validating the devfile schema and current version couldn't parse the devfile v2 schema.

CQ request for new justify version https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23030

### What issues does this PR fix or reference?

#18901 

### How to test this PR?

see this PR that actually does devfile validation on top of this and contain exact steps how to test https://github.com/eclipse/che/pull/19012

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Review by mshaposhnik — APPROVED** [review]
BTW is jakarta already CQ-ed?

**Comment by sparkoo** [comment]
> BTW is jakarta already CQ-ed?

it's eclipse project, so I assume yes

**Review by metlos — APPROVED** [review]

**Comment by sparkoo** [comment]
[crw-ci-test]

**Review by skabashnyuk — COMMENTED** [review]
ok to merge when cq https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23030 will be approved.

**Pull request merged**
