### PR TITLE
CHE-3953 - Starting workspace on openshift 1.4.1

### LINKED ISSUE #3953: Starting workspace on openshift 1.4.1
When starting a workspace on openshift 1.4.1 (minishift-1.0.0-beta3), che logs the following error:

```
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://192.168.0.26:8443/api/v1/namespaces/eclipse-che/services. Message: Service "che-ws-i4z9dgl4cpddw1bi" is invalid: [spec.ports[0].protocol: Unsupported value: "tcp": supported values: TCP, UDP, spec.ports[1].protocol: Unsupported value: "tcp": supported values: TCP, UDP, spec.ports[2].protocol: Unsupported value: "tcp": supported values: TCP, UDP, spec.ports[3].protocol: Unsupported value: "tcp": supported values: TCP, UDP, spec.ports[4].protocol: Unsupported value: "tcp": supported values: TCP, UDP, spec.ports[5].protocol: Unsupported value: "tcp": supported values: TCP, UDP, spec.ports[6].protocol: Unsupported value: "tcp": supported values: TCP, UDP]. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=spec.ports[0].protocol, message=Unsupported value: "tcp": supported values: TCP, UDP, reason=FieldValueNotSupported, additionalProperties={}), StatusCause(field=spec.ports[1].protocol, message=Unsupported value: "tcp": supported values: TCP, UDP, reason=FieldValueNotSupported, additionalProperties={}), StatusCause(field=spec.ports[2].protocol, message=Unsupported value: "tcp": supported values: TCP, UDP, reason=FieldValueNotSupported, additionalProperties={}), StatusCause(field=spec.ports[3].protocol, message=Unsupported value: "tcp": supported values: TCP, UDP, reason=FieldValueNotSupported, additionalProperties={}), StatusCause(field=spec.ports[4].protocol, message=Unsupported value: "tcp": supported values: TCP, UDP, reason=FieldValueNotSupported, additionalProperties={}), StatusCause(field=spec.ports[5].protocol, message=Unsupported value: "tcp": supported values: TCP, UDP, reason=FieldValueNotSupported, additionalProperties={}), StatusCause(field=spec.ports[6].protocol, message=Unsupported value: "tcp": supported values: TCP, UDP, reason=FieldValueNotSupported, additionalProperties={})], group=null, kind=Service, name=che-ws-i4z9dgl4cpddw1bi, retryAfterSeconds=nul
l, additionalProperties={}), kind=Status, message=Service "che-ws-i4z9dgl4cpddw1bi" is invalid: [spec.ports[0].protocol: Unsupported value: "tcp": supported values: TCP, UDP, spec.ports[1].protocol: Unsupported value: "tcp": supported values: TCP, UDP, spec.ports[2].protocol: Unsupported value: "tcp": supported values: TCP, UDP, spec.ports[3].protocol: Unsupported value: "tcp": supported values: TCP, UDP, spec.ports[4].protocol: Unsupported value: "tcp": supported values: TCP, UDP, spec.ports[5].protocol: Unsupported value: "tcp": supported values: TCP, UDP, spec.ports[6].protocol: Unsupported value: "tcp": supported values: TCP, UDP], metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:315) ~[kubernetes-client-1.4.31.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:268) ~[kubernetes-client-1.4.31.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:237) ~[kubernetes-client-1.4.31.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:230) ~[kubernetes-client-1.4.31.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:208) ~[kubernetes-client-1.4.31.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:644) ~[kubernetes-client-1.4.31.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:300) ~[kubernetes-client-1.4.31.jar:na]
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation$1.apply(BaseOperation.java:317) ~[kubernetes-client-1.4.31.jar:na]
	at io.fabric8.kubernetes.api.model.DoneableService.done(DoneableService.java:26) ~[kubernetes-model-1.0.65.jar:1.0.65]
	at org.eclipse.che.plugin.openshift.client.OpenShiftConnector.createOpenShiftService(OpenShiftConnector.java:480) ~[che-plugin-openshift-client-5.2.0-SNAPSHOT.jar:5.2.0-SNAPSHOT]
	at org.eclipse.che.plugin.openshift.client.OpenShiftConnector.createContainer(OpenShiftConnector.java:176) ~[che-plugin-openshift-client-5.2.0-SNAPSHOT.jar:5.2.0-SNAPSHOT]
	at org.eclipse.che.plugin.docker.machine.MachineProviderImpl.createContainer(MachineProviderImpl.java:529) ~[che-plugin-docker-machine-5.2.0-SNAPSHOT.jar:5.2.0-SNAPSHOT]
	at org.eclipse.che.plugin.docker.machine.MachineProviderImpl.startService(MachineProviderImpl.java:276) ~[che-plugin-docker-machine-5.2.0-SNAPSHOT.jar:5.2.0-SNAPSHOT]
... 13 common frames omitted
```
**OS and version:**    any, openshift 1.4.1
The issue is always reproducible.

### PR DESCRIPTION
**Pull request by snjeza**
Signed-off-by: Snjezana Peco <snjezana.peco@redhat.com>

### What does this PR do?

Fixes #3953 

### What issues does this PR fix or reference?

#3953 

#### Changelog
Bug fix for Starting workspace on openshift 1.4.1 `servicePort.setProtocol(protocol.toUpperCase());`

### CODE REVIEW

**Comment by l0rd** [comment]
@snjeza Have you tested if setting the protocol uppercase works with OpenShift 1.3.x?

**Comment by snjeza** [comment]
@l0rd 
Yes, I have tested with OpenShift 1.3.3. It works.

**Review by l0rd — APPROVED** [review]

**Comment by l0rd** [comment]
Thank you @snjeza

**Comment by riuvshin** [comment]
@snjeza @l0rd hey guys those changes break che build,
there are 2 failed tests https://ci.codenvycorp.com/job/che-ci-master/924/org.eclipse.che.plugin$che-plugin-openshift-client/testReport/

we should not merge changes that break build

**Comment by snjeza** [comment]
@riuvshin @l0rd 
I have created https://github.com/eclipse/che/pull/4065

**Comment by riuvshin** [comment]
@snjeza thanks for that reactivity!

**Pull request merged**
