### PR TITLE
Remove redundant <version> elements.

### PR DESCRIPTION
**Pull request by monaka**
### What does this PR do?

Remove redundant <version> elements in POM files.
They may be harmless. But some IDE like Eclipse reports them as an warning.

### What issues does this PR fix or reference?

None.

### CODE REVIEW

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by riuvshin** [comment]
Can one of the admins verify this patch?

**Comment by skabashnyuk** [comment]
ci-build

**Comment by skabashnyuk** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1218/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1218//Selenium_20tests_20report/)
docker image: eclipseche/che-server:12023
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by monaka** [comment]
ci-test

**Comment by monaka** [comment]
Referring to the build log, the build failure is not caused by my patch, right?
 
https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1218/org.eclipse.che$go-agents/console

**Comment by tolusha** [comment]
@monaka PR isn't the cause of failure.
```
     [exec] FAIL	github.com/eclipse/che/agents/go-agents/bootstrapper/booter [build failed]# runtime/cgo
     [exec] exec: "gcc": executable file not found in $PATH
     [exec] 
```

@riuvshin Is there any issue with Jenkins here?

**Comment by skabashnyuk** [comment]
ci-test

**Review by skabashnyuk — APPROVED** [review]

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1227/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1227//Selenium_20tests_20report/)
docker image: eclipseche/che-server:12023
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by skabashnyuk** [comment]
ci-build

**Pull request merged**
