### PR TITLE
Improve eclipse ssh agent on unknown Linux stacks

### PR DESCRIPTION
**Pull request by lehmanju**
### What does this PR do?
It improves the situation on custom docker images using a Linux OS which is not listed explicitly in the ssh server script file. (SSH server agent)

Originally I wanted to run a custom docker image with Arch Linux installed (in Codenvy). Currently this does not work because Arch Linux is not supported as docker container. However, the script basically checks whether sshd works or not. On supported systems the package is installed automatically, if it does not work. On unsupported systems the script currently exits regardless of a working sshd server.

This change at least **tries** whether it works or not. If not, you can still exit with an error code.

#### Changelog
Improve behavior of SSH installation script on unknown Linux stacks

### CODE REVIEW

**Comment by TylerJewell** [comment]
@lehmanju - thanks for the contribution.  A maintainer will take a look and consider the details.  Just to confirm, have you filled out the Eclipse CLA and signed your commit?  It looks like the IP validation test is failing so far.

**Comment by lehmanju** [comment]
@TylerJewell - I did sign the ECA on eclipse.org but the error still remains ... What do I have to do to fix that? Thx.

**Comment by TylerJewell** [comment]
Can you ammend the commit so that it contains the "Signed-off-by: Author Name <email@address.com>"?  If you do this, the automatic validation should pick it up.

**Comment by lehmanju** [comment]
**done**

**Review by TylerJewell — APPROVED** [review]

**Comment by TylerJewell** [comment]
Fixed - thanks for your contribution!

**Pull request merged**
