### PR TITLE
Document the basics of making the GWT libraries for the Che IDE GWT app

### PR DESCRIPTION
**Pull request by azatsarynnyy**
### What does this PR do?
Adds README.md for the IDE project with the basics of making the GWT libraries for the Che IDE GWT app.

### What issues does this PR fix or reference?
#7152

### CODE REVIEW

**Review by vparfonov — APPROVED** [review]

**Comment by benoitf** [comment]
should some stuff should go on che-docs /wiki as well ?
https://github.com/eclipse/che/wiki/Development-Workflow#gwt-super-dev-mode-for-eclipse
https://www.eclipse.org/che/docs/assemblies/plugin-lifecycle/

**Comment by vparfonov** [comment]
We want to put docs closer to the source

**Comment by slemeur** [comment]
@vparfonov : Having documentation as close to the source is nice - but don't forget to cross reference this page in the other documentation we have. 

We have:
https://github.com/eclipse/che/wiki/Development-Workflow#gwt-super-dev-mode-for-eclipse

And most of our documentation, including the ones related to the extensibility are on https://www.eclipse.org/che/docs/

Those documentations must be sync and not confuse/mislead the reader. Of course, multiplying the sources of information, multiply the risk for having places where information are not kept up-to-date

**Comment by slemeur** [comment]
@vparfonov : Having documentation as close to the source is nice - but don't forget to cross reference this page in the other documentation we have. 

We have:
https://github.com/eclipse/che/wiki/Development-Workflow#gwt-super-dev-mode-for-eclipse

And most of our documentation, including the ones related to the extensibility are on https://www.eclipse.org/che/docs/

Those documentations must be sync and not confuse/mislead the reader. Of course, multiplying the sources of information, multiply the risk for having places where information are not kept up-to-date

**Pull request merged**
