### PR TITLE
CHE-9937 Fix Composer project type

### PR DESCRIPTION
**Pull request by vinokurig**
### What does this PR do?
Fix error when updating or creating a project with Composer project type.

### What issues does this PR fix or reference?
#9937

#### Release Notes

N/A

#### Docs PR

N/A

### CODE REVIEW

**Review by vparfonov — APPROVED** [review]

**Comment by vinokurig** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/534/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/534//Selenium_tests_report)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10606)
docker image: eclipseche/che-server:10606
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by vinokurig** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/551/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/551//Selenium_tests_report)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/10606)
docker image: eclipseche/che-server:10606
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by vinokurig** [comment]
ci-build

**Pull request merged**
