### PR TITLE
Make ws agent-master interaction more consistent

### PR DESCRIPTION
**Pull request by gazarenkov**
### What does this PR do?
- avoid additional remote call of workspace API 
- make design more clean splitting interfaces for syncing projects and retrieving runtime
- remove unused methods

### CODE REVIEW

**Comment by vparfonov** [comment]
ci-test

**Review by dkulieshov — APPROVED** [review]

**Comment by vparfonov** [comment]
Basically ok for me, except name of class `WorkspaceProjectSynchronizer` now also will return workspace `Runtime`

**Review by vparfonov — APPROVED** [review]

**Comment by gazarenkov** [comment]
@vparfonov if you mean naming, well I tried to reduce confusing making it implement WorkspaceKeeper so it looks quite legitimate now. Otherwise - if you can see better than WorkspaceProjectSynchronizer name - go ahead.

**Comment by Tarrantella** [comment]
ci-test

**Comment by musienko-maxim** [comment]
ci-test

**Comment by musienko-maxim** [comment]
ci-test

**Review by musienko-maxim — APPROVED** [review]

**Pull request merged**
