### PR TITLE
[WIP]Add timeout after importing test project to be sure all file appeared in index

### PR DESCRIPTION
**Pull request by vparfonov**
Add timeout after importing test project to be sure all file appeared in index

Signed-off-by: Vitalii Parfonov <vparfonov@redhat.com>

### CODE REVIEW

**Comment by vparfonov** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/702/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/702//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/11016)
docker image: eclipseche/che-server:11016
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by vparfonov** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/707/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/707//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/11016)
docker image: eclipseche/che-server:11016
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by vparfonov** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/717/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/717//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/11016)
docker image: eclipseche/che-server:11016
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by riuvshin** [comment]
ci-test

**Comment by riuvshin** [comment]
ci-test build report:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/722/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/722//Selenium_20tests_20report/)
[selenium tests report data](http://tests.codenvycorp.com/selenium_test_report_data/11016)
docker image: eclipseche/che-server:11016
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Pull request closed without merging**
