### PR TITLE
Remove maven server

### PR DESCRIPTION
**Pull request by svor**
Signed-off-by: Valeriy Svydenko <vsvydenk@redhat.com>

### What does this PR do?
Remove Maven server and all related things

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/12164

### CODE REVIEW

**Comment by svor** [comment]
ci-test

**Review by benoitf — APPROVED** [review]

**Comment by svor** [comment]
ci-build

**Comment by svor** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1336/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1336//Selenium_20tests_20report/)
docker image: eclipseche/che-server:12235
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by svor** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1341/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/1341//Selenium_20tests_20report/)
docker image: eclipseche/che-server:12235
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Review by riuvshin — APPROVED** [review]

**Review by musienko-maxim — APPROVED** [review]

**Review by vparfonov — APPROVED** [review]

**Pull request merged**
