### PR TITLE
Add some files generated by m2e to .gitignore

### PR DESCRIPTION
**Pull request by kaloyan-raev**
### What does this PR do?

I have quite some `maven-eclipse.xml` and `Maven_Ant_Builder.launch` files listed as unstaged changes. These files are generated by the m2e Eclipse plugin and are not supposed to be committed to the Git repo.

This PR adds `maven-eclipse.xml` and `Maven_Ant_Builder.launch` to `.gitignore`.
### PR type
- [x] Minor change = no change to existing features or docs

Signed-off-by: Kaloyan Raev kaloyan.r@zend.com

### CODE REVIEW

**Review by benoitf — COMMENTED** [review]
Maybe use *.launch for matching all eclipse IDE commands

**Comment by kaloyan-raev** [comment]
Makes sense. Done.

**Comment by slemeur** [comment]
+1. This PR will help contributors who want to use Eclipse IDE.

**Review by slemeur — APPROVED** [review]

**Comment by TylerJewell** [comment]
Thanks for the contribution.

**Pull request merged**
