### PR TITLE
[Selenium] Remove java selenium tests and unused scripts for centos.ci

### PR DESCRIPTION
**Pull request by SkorikSergey**
### What does this PR do?
Remove java selenium tests and unused scripts for centos.ci

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/19190

### CODE REVIEW

**Comment by SkorikSergey** [comment]
[crw-ci-test]

**Comment by SkorikSergey** [comment]
[crw-ci-test]

**Comment by SkorikSergey** [comment]
[crw-csb-ci-test]

**Comment by dmytro-ndp** [comment]
@SkorikSergey: please, consider cleaning up of the next leftovers:
- java tests related functions in **tests/.infra/centos-ci/functional_tests_utils.sh** file, like `function seleniumTestsSetup() {` 
- java selenium tests scripts in **tests/.infra/centos-ci/release** directory
- `tests/legacy-e2e/**` in **.github/CODEOWNERS** file.

**Comment by dmytro-ndp** [comment]
[crw-ci-test --rebuild]

**Review by dmytro-ndp — APPROVED** [review]
Looks good.

**Review by sparkoo — APPROVED** [review]

**Pull request merged**
